package fr.legrain.stock.model;

// Generated 4 juin 2009 10:11:38 by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.Version;
import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

import fr.legrain.article.model.TaEntrepot;
import fr.legrain.article.model.TaFabrication;
import fr.legrain.article.model.TaLot;
import fr.legrain.validator.LgrHibernateValidated;

/**
 * TaStock generated by hbm2java
 */
@Entity
//@Cache(usage=CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "ta_mouvement_stock_prev")

/* - Dima - Début - */
@NamedQueries(value = { 
		@NamedQuery(name=TaMouvementStockPrev.QN.FIND_BY_MOUVEMENT_NO_DATE, query="select distinct a from TaMouvementStockPrev a"), // recherche globale
		@NamedQuery(name=TaMouvementStockPrev.QN.FIND_BY_CODE_MOUVEMENT_NO_DATE, query="select a from TaMouvementStockPrev a where a.idMouvementStock = :idMouvementStock"), // recherche avec ID sans Dates
		@NamedQuery(name=TaMouvementStockPrev.QN.FIND_BY_MOUVEMENT, query="select distinct a from TaMouvementStockPrev a where a.dateStock between :dateDebut and :dateFin"), // recherche avec les detes
		@NamedQuery(name=TaMouvementStockPrev.QN.FIND_BY_CODE_MOUVEMENT, query="select a from TaMouvementStockPrev a where a.idMouvementStock = :idMouvementStock and a.dateStock between :dateDebut and :dateFin"), // recherche avec ID et Dates
//		@NamedQuery(name=TaMouvementStockPrev.QN.FIND_ALL_LIGHT, query="select new fr.legrain.stock.dto.MouvementStocksDTO(a.idGrMouvStock,  a.codeGrMouvStock, a.dateStock,  a.libelleStock,  a.typeDoc) from TaMouvementStockPrev a order by a.codeGrMouvStock"),
//		@NamedQuery(name=TaMouvementStockPrev.QN.FIND_BY_CODE_LIGHT, query="select new fr.legrain.stock.dto.MouvementStocksDTO(a.idGrMouvStock,  a.codeGrMouvStock, a.dateStock,  a.libelleStock,  a.typeDoc) from TaMouvementStockPrev a  where a.codeGrMouvStock like ? order by a.codeGrMouvStock")
		
		
})
/* - Dima -  Fin  - */

public class TaMouvementStockPrev implements java.io.Serializable {


	private static final long serialVersionUID = 2391267493239779824L;
	
	/* - Dima - Début - */
	public static final String TYPE_DOC = "TaMouvementStockPrev";
	
	public static class QN {
		public static final String FIND_BY_MOUVEMENT_NO_DATE = "TaMouvementStockPrev.findMouvementStockNoDate";
		public static final String FIND_BY_CODE_MOUVEMENT_NO_DATE = "TaMouvementStockPrev.findCodeMouvementStockNoDate";
		public static final String FIND_BY_MOUVEMENT = "TaMouvementStockPrev.findMouvementStock";
		public static final String FIND_BY_CODE_MOUVEMENT = "TaMouvementStockPrev.findCodeMouvementStock";
//		public static final String FIND_ALL_LIGHT = "TaMouvementStockPrev.findAllLight";
//		public static final String FIND_BY_CODE_LIGHT = "TaMouvementStockPrev.findByCodeLight";
	}
	/* - Dima -  Fin  - */
	
	private int idMouvementStock;
	private TaGrMouvStockPrev taGrMouvStockPrev;
	private Date dateStock;
	private String libelleStock;
	private BigDecimal qte1Stock;
	private String un1Stock;
	private BigDecimal qte2Stock;
	private String un2Stock;	
	private TaEntrepot taEntrepot;
	private String emplacement;

	private TaLot taLot;
	
    @Transient
	private TaEntrepot taEntrepotDest;
    @Transient
    private String emplacementDest;

	private String lettrageDeplacement;
    
//	@Transient
//	private String numLot;


	private String description;
//	private String typeDoc;
//	private Integer idDocument;
	
	private String quiCree;
	private Date quandCree;
	private String quiModif;
	private Date quandModif;
	private String ipAcces;
	private Integer versionObj;
	private String version;
	
	 @Transient
	 private Boolean utilise=false;

	public TaMouvementStockPrev() {
	}

	public TaMouvementStockPrev(int idStock) {
		this.idMouvementStock = idStock;
	}


	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id_mouvement_stock", unique = true, nullable = false)
	@LgrHibernateValidated(champBd = "id_mouvement_stock",table = "ta_mouvement_stock", champEntite="idMouvementStock", clazz = TaMouvementStockPrev.class)
	public int getIdMouvementStock() {
		return this.idMouvementStock;
	}

	public void setIdMouvementStock(int idStock) {
		this.idMouvementStock = idStock;
	}

//	@Version
	@Column(name = "version", length = 20)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.EAGER, optional=false)
	@JoinColumn(name = "id_gr_mouv_stock" , referencedColumnName ="id_gr_mouv_stock", nullable=false)
	public TaGrMouvStockPrev getTaGrMouvStockPrev() {
		return taGrMouvStockPrev;
	}

	public void setTaGrMouvStockPrev(TaGrMouvStockPrev taGrMouvStockPrev) {
		this.taGrMouvStockPrev = taGrMouvStockPrev;
	}
	

	@Temporal(TemporalType.DATE)
	@Column(name = "date_stock", length = 19)
	@LgrHibernateValidated(champBd = "date_stock",table = "ta_mouvement_stock", champEntite="dateStock", clazz = TaMouvementStockPrev.class)
	public Date getDateStock() {
		return this.dateStock;
	}

	public void setDateStock(Date dateStock) {
		this.dateStock = dateStock;
	}

	@Column(name = "libelle_stock")
	@LgrHibernateValidated(champBd = "libelle_stock",table = "ta_mouvement_stock", champEntite="libelleStock", clazz = TaMouvementStockPrev.class)
	public String getLibelleStock() {
		return this.libelleStock;
	}

	public void setLibelleStock(String libelleStock) {
		this.libelleStock = libelleStock;
	}


	@Column(name = "qte1_stock", precision = 15)
	@LgrHibernateValidated(champBd = "qte1_stock",table = "ta_mouvement_stock", champEntite="qte1Stock", clazz = TaMouvementStockPrev.class)
	public BigDecimal getQte1Stock() {
		return this.qte1Stock;
	}

	public void setQte1Stock(BigDecimal qte1Stock) {
		this.qte1Stock = qte1Stock;
	}

	@Column(name = "un1_stock", length = 20)
	@LgrHibernateValidated(champBd = "un1_stock",table = "ta_mouvement_stock", champEntite="un1Stock", clazz = TaMouvementStockPrev.class)
	public String getUn1Stock() {
		return this.un1Stock;
	}

	public void setUn1Stock(String un1Stock) {
		this.un1Stock = un1Stock;
	}

	@Column(name = "qte2_stock", precision = 15)
	@LgrHibernateValidated(champBd = "qte2_stock",table = "ta_mouvement_stock", champEntite="qte2Stock", clazz = TaMouvementStockPrev.class)
	public BigDecimal getQte2Stock() {
		return this.qte2Stock;
	}

	public void setQte2Stock(BigDecimal qte2Stock) {
		this.qte2Stock = qte2Stock;
	}

	@Column(name = "un2_stock", length = 20)
	@LgrHibernateValidated(champBd = "un2_stock",table = "ta_mouvement_stock", champEntite="un2Stock", clazz = TaMouvementStockPrev.class)
	public String getUn2Stock() {
		return this.un2Stock;
	}

	public void setUn2Stock(String un2Stock) {
		this.un2Stock = un2Stock;
	}

	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_entrepot")
	@LgrHibernateValidated(champBd = "id_entrepot",table = "ta_entrepot", champEntite="taEntrepot.idEntrepot", clazz = TaEntrepot.class)
	public TaEntrepot getTaEntrepot() {
		return taEntrepot;
	}

	public void setTaEntrepot(TaEntrepot entrepotOrg) {
		this.taEntrepot = entrepotOrg;
	}

	
	@Column(name = "emplacement", length = 20)
	@LgrHibernateValidated(champBd = "emplacement",table = "ta_mouvement_stock", champEntite="emplacement", clazz = TaMouvementStockPrev.class)
	public String getEmplacement() {
		return emplacement;
	}

	public void setEmplacement(String emplacementOrg) {
		this.emplacement = emplacementOrg;
	}

	
	/* pour gérer les 2 lignes créées lors d'un déplacement d'un stock d'un entreport vers un autre*/
	@Transient
	public TaEntrepot getTaEntrepotDest() {
		return taEntrepotDest;
	}

	public void setTaEntrepotDest(TaEntrepot entrepotDest) {
		this.taEntrepotDest = entrepotDest;
	}
	
	@Transient
	public String getEmplacementDest() {
		return emplacementDest;
	}

	public void setEmplacementDest(String emplacementDest) {
		this.emplacementDest = emplacementDest;
	}


	
//	@Transient
	@NotNull(message="Le lot ne peut être nul")
	@ManyToOne(fetch = FetchType.EAGER, cascade = {CascadeType.REFRESH})
	@JoinColumn(name = "id_lot")
	@LgrHibernateValidated(champBd = "id_lot",table = "ta_lot", champEntite="taLot.idLot", clazz = TaLot.class)	
	@Valid
	public TaLot getTaLot() {
		return taLot;
	}

//	@Transient
	public void setTaLot(TaLot taLot) {
		this.taLot = taLot;
	}


//	@NotNull(message="Le lot doit être rempli")
//	@Size(min=1, max=50 , message="Le lot doit être rempli")
//	@Column(name = "num_lot", length = 50)
//	@LgrHibernateValidated(champBd = "num_lot",table = "ta_mouvement_stock", champEntite="numLot", clazz = TaMouvementStockPrev.class)
//	public String getNumLot() {
//		return numLot;
//	}
//
//	public void setNumLot(String numLot) {
//		this.numLot = numLot;
//	}

	@Column(name = "description", length = 20)
	@LgrHibernateValidated(champBd = "description",table = "ta_mouvement_stock_prev", champEntite="description", clazz = TaMouvementStockPrev.class)
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

//	@Column(name = "type_doc", length = 20)
//	@LgrHibernateValidated(champ = "type_doc",table = "ta_mouvement_stock", champEntite="typeDoc", clazz = TaMouvementStockPrev.class)
//	public String getTypeDoc() {
//		return typeDoc;
//	}
//
//	public void setTypeDoc(String type_doc) {
//		this.typeDoc = type_doc;
//	}
//
//	@Column(name = "id_document", length = 20)
//	@LgrHibernateValidated(champ = "id_document",table = "ta_mouvement_stock", champEntite="idDocument", clazz = TaMouvementStockPrev.class)
//	public Integer getIdDocument() {
//		return idDocument;
//	}
//
//	public void setIdDocument(Integer id_document) {
//		this.idDocument = id_document;
//	}
	
	@Column(name = "qui_cree", length = 50)
	public String getQuiCree() {
		return this.quiCree;
	}

	public void setQuiCree(String quiCreeStock) {
		this.quiCree = quiCreeStock;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "quand_cree", length = 19)
	public Date getQuandCree() {
		return this.quandCree;
	}

	public void setQuandCree(Date quandCreeStock) {
		this.quandCree = quandCreeStock;
	}

	@Column(name = "qui_modif", length = 50)
	public String getQuiModif() {
		return this.quiModif;
	}

	public void setQuiModif(String quiModifStock) {
		this.quiModif = quiModifStock;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "quand_modif", length = 19)
	public Date getQuandModif() {
		return this.quandModif;
	}

	public void setQuandModif(Date quandModifStock) {
		this.quandModif = quandModifStock;
	}

	@Column(name = "ip_acces", length = 50)
	public String getIpAcces() {
		return this.ipAcces;
	}

	public void setIpAcces(String ipAcces) {
		this.ipAcces = ipAcces;
	}
	@Version
	@Column(name = "version_obj")
	public Integer getVersionObj() {
		return this.versionObj;
	}

	public void setVersionObj(Integer versionObj) {
		this.versionObj = versionObj;
	}

	@Column(name = "lettrage_deplacement")
	public String getLettrageDeplacement() {
		return lettrageDeplacement;
	}

	public void setLettrageDeplacement(String lettrageDeplacement) {
		this.lettrageDeplacement = lettrageDeplacement;
	}

	@Transient
	public Boolean getUtilise() {
		return utilise;
	}

	public void setUtilise(Boolean utilise) {
		this.utilise = utilise;
	}


}
