
package fr.legrain.bdg.compteclient.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.10
 * 2018-06-14T14:51:43.171+02:00
 * Generated source version: 3.1.10
 */

@WebFault(name = "EJBException", targetNamespace = "http://service.bdg.legrain.fr/")
public class EJBException_Exception extends Exception {
    
    private fr.legrain.bdg.compteclient.ws.EJBException ejbException;

    public EJBException_Exception() {
        super();
    }
    
    public EJBException_Exception(String message) {
        super(message);
    }
    
    public EJBException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public EJBException_Exception(String message, fr.legrain.bdg.compteclient.ws.EJBException ejbException) {
        super(message);
        this.ejbException = ejbException;
    }

    public EJBException_Exception(String message, fr.legrain.bdg.compteclient.ws.EJBException ejbException, Throwable cause) {
        super(message, cause);
        this.ejbException = ejbException;
    }

    public fr.legrain.bdg.compteclient.ws.EJBException getFaultInfo() {
        return this.ejbException;
    }
}
