package fr.legrain.document.dto;

// Generated Mar 1, 2007 11:26:10 AM by Hibernate Tools 3.2.0.b9

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.math.BigDecimal;
import java.util.Date;

import fr.legrain.bdg.model.ModelObject;
import fr.legrain.document.model.TaAvisEcheance;
import fr.legrain.document.model.TaPrelevement;
import fr.legrain.validator.LgrHibernateValidated;

/**
 * SWTLFacture generated by hbm2java
 */
public class TaLPrelevementDTO extends ModelObject implements PropertyChangeListener, java.io.Serializable, ILigneDocumentDTO{


	/**
	 * 
	 */
	private static final long serialVersionUID = 4855675501458601291L;
	private Integer id;
	private Integer idDocument;
	private String codeTLigne;
	private Integer idArticle;
	private Integer numLigneLDocument;
	private String codeArticle;
	private String libLDocument;
	private BigDecimal qteLDocument;
	private BigDecimal qte2LDocument;
	private BigDecimal prixULDocument;
	private BigDecimal tauxTvaLDocument;
	private String codeTvaLDocument;
	private String codeTTvaLDocument;
	private BigDecimal mtHtLDocument;
	private BigDecimal remTxLDocument;
	private BigDecimal mtTtcLDocument;
	private BigDecimal remHtLDocument;
	private String ipAcces;
	private String u1LDocument;
	private String u2LDocument;
	private BigDecimal txRemHtDocument;
	private BigDecimal mtHtLApresRemiseGlobaleDocument;
	private BigDecimal mtTtcLApresRemiseGlobaleDocument;
	
	private String codeEntrepot;
	private String emplacement;
	private Date dluo;
	private String numLot;
	private String libelleLot;
	private String codeEtat;
	private Integer versionObj;
	
	private BigDecimal qteSaisieLDocument;
	private String uSaisieLDocument;
	
	public TaLPrelevementDTO() {
	}

	public TaLPrelevementDTO(Integer ID_L_Prelevement, Integer ID_Prelevement,
			String ID_T_LIGNE, Integer ID_ARTICLE,
			Integer NUM_LIGNE_L_Prelevement, String CODE_ARTICLE,
			String LIB_L_Prelevement, BigDecimal QTE_L_Prelevement,
			String U1_L_Prelevement, String U2_L_Prelevement,
			BigDecimal PRIX_U_L_Prelevement, BigDecimal TAUX_TVA_L_Prelevement,
			String CODE_TVA_L_Prelevement, String CODE_T_TVA_L_Prelevement,
			BigDecimal MT_HT_L_Prelevement, BigDecimal MT_TTC_L_Prelevement,
			BigDecimal REM_TX_L_Prelevement, BigDecimal REM_HT_L_Prelevement,
			String IP_ACCES) {
		this.id = ID_L_Prelevement;
		this.idDocument = ID_Prelevement;
		this.codeTLigne = ID_T_LIGNE;
		this.idArticle = ID_ARTICLE;
		this.numLigneLDocument = NUM_LIGNE_L_Prelevement;
		this.codeArticle = CODE_ARTICLE;
		this.libLDocument = LIB_L_Prelevement;
		this.qteLDocument = QTE_L_Prelevement;
		this.u1LDocument = U1_L_Prelevement;
		this.u2LDocument = U2_L_Prelevement;
		this.prixULDocument = PRIX_U_L_Prelevement;
		this.tauxTvaLDocument = TAUX_TVA_L_Prelevement;
		this.codeTvaLDocument = CODE_TVA_L_Prelevement;
		this.codeTTvaLDocument = CODE_T_TVA_L_Prelevement;
		this.mtHtLDocument = MT_HT_L_Prelevement;
		this.mtTtcLDocument = MT_TTC_L_Prelevement;
		this.remTxLDocument = REM_TX_L_Prelevement;
		this.remHtLDocument = REM_HT_L_Prelevement;
		this.ipAcces = IP_ACCES;
	}
	
	public void setIHMLPrelevement(TaLPrelevementDTO ihmLPrelevement) {
		setIdLDocument(ihmLPrelevement.id);
		setIdDocument(ihmLPrelevement.idDocument);
		setCodeTLigne(ihmLPrelevement.codeTLigne);
		setIdArticle(ihmLPrelevement.idArticle);
		setNumLigneLDocument(ihmLPrelevement.numLigneLDocument);
		setCodeArticle(ihmLPrelevement.codeArticle);
		setLibLDocument(ihmLPrelevement.libLDocument);
		setQteLDocument(ihmLPrelevement.qteLDocument);
		setU1LDocument(ihmLPrelevement.u1LDocument);
		setU2LDocument(ihmLPrelevement.u2LDocument);
		setPrixULDocument(ihmLPrelevement.prixULDocument);
		setTauxTvaLDocument(ihmLPrelevement.tauxTvaLDocument);
		setCodeTvaLDocument(ihmLPrelevement.codeTvaLDocument);
		setCodeTTvaLDocument(ihmLPrelevement.codeTTvaLDocument);
		setMtHtLDocument(ihmLPrelevement.mtHtLDocument);
		setMtTtcLDocument(ihmLPrelevement.mtTtcLDocument);
		setRemTxLDocument(ihmLPrelevement.remTxLDocument);
		setRemHtLDocument(ihmLPrelevement.remHtLDocument);
		setIpAcces(ihmLPrelevement.ipAcces);
	}
	
	static public TaLPrelevementDTO copy(TaLPrelevementDTO ihmLPrelevement) {
		TaLPrelevementDTO swtLPrelevementLoc = new TaLPrelevementDTO();
		swtLPrelevementLoc.setIdLDocument(ihmLPrelevement.id);
		swtLPrelevementLoc.setIdDocument(ihmLPrelevement.idDocument);
		swtLPrelevementLoc.setCodeTLigne(ihmLPrelevement.codeTLigne);
		swtLPrelevementLoc.setIdArticle(ihmLPrelevement.idArticle);
		swtLPrelevementLoc.setNumLigneLDocument(ihmLPrelevement.numLigneLDocument);
		swtLPrelevementLoc.setCodeArticle(ihmLPrelevement.codeArticle);
		swtLPrelevementLoc.setLibLDocument(ihmLPrelevement.libLDocument);
		swtLPrelevementLoc.setQteLDocument(ihmLPrelevement.qteLDocument);
		swtLPrelevementLoc.setQte2LDocument(ihmLPrelevement.qte2LDocument);
		swtLPrelevementLoc.setU1LDocument(ihmLPrelevement.u1LDocument);
		swtLPrelevementLoc.setU2LDocument(ihmLPrelevement.u2LDocument);
		swtLPrelevementLoc.setQte2LDocument(ihmLPrelevement.qte2LDocument);
		swtLPrelevementLoc.setPrixULDocument(ihmLPrelevement.prixULDocument);
		swtLPrelevementLoc.setTauxTvaLDocument(ihmLPrelevement.tauxTvaLDocument);
		swtLPrelevementLoc.setCodeTvaLDocument(ihmLPrelevement.codeTvaLDocument);
		swtLPrelevementLoc.setCodeTTvaLDocument(ihmLPrelevement.codeTTvaLDocument);
		swtLPrelevementLoc.setMtHtLDocument(ihmLPrelevement.mtHtLDocument);
		swtLPrelevementLoc.setMtTtcLDocument(ihmLPrelevement.mtTtcLDocument);
		swtLPrelevementLoc.setRemTxLDocument(ihmLPrelevement.remTxLDocument);
		swtLPrelevementLoc.setRemHtLDocument(ihmLPrelevement.remHtLDocument);
		swtLPrelevementLoc.setIpAcces(ihmLPrelevement.ipAcces);
		swtLPrelevementLoc.setVersionObj(ihmLPrelevement.versionObj);
		swtLPrelevementLoc.setQteSaisieLDocument(ihmLPrelevement.getQteSaisieLDocument());
		swtLPrelevementLoc.setUSaisieLDocument(ihmLPrelevement.uSaisieLDocument);
		return swtLPrelevementLoc;
	}

	public Integer getIdLDocument() {
		return this.id;
	}

	public void setIdLDocument(Integer ID_L_Prelevement) {
		firePropertyChange("idLDocument", this.id, this.id = ID_L_Prelevement);
	}

	public Integer getIdDocument() {
		return this.idDocument;
	}

	public void setIdDocument(Integer ID_Prelevement) {
		firePropertyChange("idDocument", this.idDocument, this.idDocument = ID_Prelevement);
	}

	public String getCodeTLigne() {
		return this.codeTLigne;
	}

	public void setCodeTLigne(String codeTLigne) {
		firePropertyChange("codeTLigne", this.codeTLigne, this.codeTLigne = codeTLigne);
	}


	public Integer getIdArticle() {
		return this.idArticle;
	}

	public void setIdArticle(Integer ID_ARTICLE) {
		firePropertyChange("ID_ARTICLE", this.idArticle, this.idArticle = ID_ARTICLE);
	}

	public Integer getNumLigneLDocument() {
		return this.numLigneLDocument;
	}

	public void setNumLigneLDocument(Integer NUM_LIGNE_L_Prelevement) {
		firePropertyChange("numLigneLDocument", this.numLigneLDocument, this.numLigneLDocument = NUM_LIGNE_L_Prelevement);
	}

	@LgrHibernateValidated(champBd = "code_article",table = "ta_article",champEntite="codeArticle",clazz = TaLPrelevementDTO.class)
	public String getCodeArticle() {
		return this.codeArticle;
	}

	public void setCodeArticle(String CODE_ARTICLE) {
		firePropertyChange("codeArticle", this.codeArticle, this.codeArticle = CODE_ARTICLE);
	}

	@LgrHibernateValidated(champBd = "lib_l_document",table = "ta_l_proforma",champEntite="libLDocument",clazz = TaLPrelevementDTO.class)
	public String getLibLDocument() {
		return this.libLDocument;
	}

	public void setLibLDocument(String LIB_L_Prelevement) {
		firePropertyChange("libLDocument", this.libLDocument, this.libLDocument = LIB_L_Prelevement);
	}

	@LgrHibernateValidated(champBd = "qte_l_document",table = "ta_l_proforma",champEntite="qteLDocument",clazz = TaLPrelevementDTO.class)
	public BigDecimal getQteLDocument() {
		return this.qteLDocument;
	}

	public void setQteLDocument(BigDecimal QTE_L_Prelevement) {
		firePropertyChange("qteLDocument", this.qteLDocument, this.qteLDocument = QTE_L_Prelevement);
	}

	@LgrHibernateValidated(champBd = "u1_l_document",table = "ta_l_proforma",champEntite="u1LDocument",clazz = TaLPrelevementDTO.class)
	public String getU1LDocument() {
		return this.u1LDocument;
	}

	public void setU1LDocument(String U1_L_Prelevement) {
		firePropertyChange("u1LDocument", this.u1LDocument, this.u1LDocument = U1_L_Prelevement);
	}

	@LgrHibernateValidated(champBd = "u2_l_document",table = "ta_l_proforma",champEntite="u2LDocument",clazz = TaLPrelevementDTO.class)
	public String getU2LDocument() {
		return this.u2LDocument;
	}

	public void setU2LDocument(String U2_L_Prelevement) {
		firePropertyChange("u2LDocument", this.u2LDocument, this.u2LDocument = U2_L_Prelevement);
	}

	@LgrHibernateValidated(champBd = "prix_u_l_document",table = "ta_l_proforma",champEntite="prixULDocument",clazz = TaLPrelevementDTO.class)
	public BigDecimal getPrixULDocument() {
		return this.prixULDocument;
	}

	public void setPrixULDocument(BigDecimal PRIX_U_L_Prelevement) {
		firePropertyChange("prixULDocument", this.prixULDocument, this.prixULDocument = PRIX_U_L_Prelevement);
	}

	@LgrHibernateValidated(champBd = "taux_tva_l_document",table = "ta_l_proforma",champEntite="tauxTvaLDocument",clazz = TaLPrelevementDTO.class)
	public BigDecimal getTauxTvaLDocument() {
		return this.tauxTvaLDocument;
	}

	public void setTauxTvaLDocument(BigDecimal TAUX_TVA_L_Prelevement) {
		firePropertyChange("tauxTvaLDocument", this.tauxTvaLDocument, this.tauxTvaLDocument = TAUX_TVA_L_Prelevement);
	}

	@LgrHibernateValidated(champBd = "code_tva_l_document",table = "ta_l_proforma",champEntite="codeTvaLDocument",clazz = TaLPrelevementDTO.class)
	public String getCodeTvaLDocument() {
		return this.codeTvaLDocument;
	}

	public void setCodeTvaLDocument(String CODE_TVA_L_Prelevement) {
		firePropertyChange("codeTvaLDocument", this.codeTvaLDocument, this.codeTvaLDocument = CODE_TVA_L_Prelevement);
	}

	@LgrHibernateValidated(champBd = "code_t_tva_l_document",table = "ta_l_proforma",champEntite="codeTTvaLDocument",clazz = TaLPrelevementDTO.class)
	public String getCodeTTvaLDocument() {
		return this.codeTTvaLDocument;
	}

	public void setCodeTTvaLDocument(String CODE_T_TVA_L_Prelevement) {
		firePropertyChange("codeTTvaLDocument", this.codeTTvaLDocument, this.codeTTvaLDocument = CODE_T_TVA_L_Prelevement);
	}

	@LgrHibernateValidated(champBd = "mt_ht_l_document",table = "ta_l_proforma",champEntite="mtHtLDocument",clazz = TaLPrelevementDTO.class)
	public BigDecimal getMtHtLDocument() {
		return this.mtHtLDocument;
	}

	public void setMtHtLDocument(BigDecimal MT_HT_L_Prelevement) {
		firePropertyChange("mtHtLDocument", this.mtHtLDocument, this.mtHtLDocument = MT_HT_L_Prelevement);
	}

	@LgrHibernateValidated(champBd = "mt_ttc_l_document",table = "ta_l_proforma",champEntite="mtTtcLDocument",clazz = TaLPrelevementDTO.class)
	public BigDecimal getMtTtcLDocument() {
		return this.mtTtcLDocument;
	}

	public void setMtTtcLDocument(BigDecimal MT_TTC_L_Prelevement) {
		firePropertyChange("mtTtcLDocument", this.mtTtcLDocument, this.mtTtcLDocument = MT_TTC_L_Prelevement);
	}

	@LgrHibernateValidated(champBd = "rem_tx_l_document",table = "ta_l_proforma",champEntite="remTxLDocument",clazz = TaLPrelevementDTO.class)
	public BigDecimal getRemTxLDocument() {
		return this.remTxLDocument;
	}

	public void setRemTxLDocument(BigDecimal REM_TX_L_Prelevement) {
		firePropertyChange("remTxLDocument", this.remTxLDocument, this.remTxLDocument = REM_TX_L_Prelevement);
	}

	@LgrHibernateValidated(champBd = "rem_ht_l_document",table = "ta_l_proforma",champEntite="remHtLDocument",clazz = TaLPrelevementDTO.class)
	public BigDecimal getRemHtLDocument() {
		return this.remHtLDocument;
	}

	public void setRemHtLDocument(BigDecimal REM_HT_L_Prelevement) {
		firePropertyChange("remHtLDocument", this.remHtLDocument, this.remHtLDocument = REM_HT_L_Prelevement);
	}

	public String getIpAcces() {
		return this.ipAcces;
	}

	public void setIpAcces(String IP_ACCES) {
		firePropertyChange("ipAcces", this.ipAcces, this.ipAcces = IP_ACCES);
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TaLPrelevementDTO))
			return false;
		TaLPrelevementDTO castOther = (TaLPrelevementDTO) other;

		return ((this.getIdLDocument() == castOther.getIdLDocument()) || (this
				.getIdLDocument() != null
				&& castOther.getIdLDocument() != null && this
				.getIdLDocument().equals(castOther.getIdLDocument())))
				&& ((this.getIdDocument() == castOther.getIdDocument()) || (this
						.getIdDocument() != null
						&& castOther.getIdDocument() != null && this
						.getIdDocument().equals(castOther.getIdDocument())))
				&& ((this.getCodeTLigne() == castOther.getCodeTLigne()) || (this
						.getCodeTLigne() != null
						&& castOther.getCodeTLigne() != null && this
						.getCodeTLigne().equals(castOther.getCodeTLigne())))
				&& ((this.getIdArticle() == castOther.getIdArticle()) || (this
						.getIdArticle() != null
						&& castOther.getIdArticle() != null && this
						.getIdArticle().equals(castOther.getIdArticle())))
				&& ((this.getNumLigneLDocument() == castOther
						.getNumLigneLDocument()) || (this
						.getNumLigneLDocument() != null
						&& castOther.getNumLigneLDocument() != null && this
						.getNumLigneLDocument().equals(
								castOther.getNumLigneLDocument())))
				&& ((this.getCodeArticle() == castOther.getCodeArticle()) || (this
						.getCodeArticle() != null
						&& castOther.getCodeArticle() != null && this
						.getCodeArticle().equals(castOther.getCodeArticle())))
				&& ((this.getLibLDocument() == castOther.getLibLDocument()) || (this
						.getLibLDocument() != null
						&& castOther.getLibLDocument() != null && this
						.getLibLDocument()
						.equals(castOther.getLibLDocument())))
				&& ((this.getQteLDocument() == castOther.getQteLDocument()) || (this
						.getQteLDocument() != null
						&& castOther.getQteLDocument() != null && this
						.getQteLDocument()
						.equals(castOther.getQteLDocument())))
				&& ((this.getU1LDocument() == castOther.getU1LDocument()) || (this
						.getU1LDocument() != null
						&& castOther.getU1LDocument() != null && this
						.getU1LDocument().equals(castOther.getU1LDocument())))
				&& ((this.getU2LDocument() == castOther.getU2LDocument()) || (this
						.getU2LDocument() != null
						&& castOther.getU2LDocument() != null && this
						.getU2LDocument().equals(castOther.getU2LDocument())))
				&& ((this.getPrixULDocument() == castOther
						.getPrixULDocument()) || (this.getPrixULDocument() != null
						&& castOther.getPrixULDocument() != null && this
						.getPrixULDocument().equals(
								castOther.getPrixULDocument())))
				&& ((this.getTauxTvaLDocument() == castOther
						.getTauxTvaLDocument()) || (this
						.getTauxTvaLDocument() != null
						&& castOther.getTauxTvaLDocument() != null && this
						.getTauxTvaLDocument().equals(
								castOther.getTauxTvaLDocument())))
				&& ((this.getCodeTvaLDocument() == castOther
						.getCodeTvaLDocument()) || (this
						.getCodeTvaLDocument() != null
						&& castOther.getCodeTvaLDocument() != null && this
						.getCodeTvaLDocument().equals(
								castOther.getCodeTvaLDocument())))
				&& ((this.getCodeTTvaLDocument() == castOther
						.getCodeTTvaLDocument()) || (this
						.getCodeTTvaLDocument() != null
						&& castOther.getCodeTTvaLDocument() != null && this
						.getCodeTTvaLDocument().equals(
								castOther.getCodeTTvaLDocument())))
				&& ((this.getMtHtLDocument() == castOther
						.getMtHtLDocument()) || (this.getMtHtLDocument() != null
						&& castOther.getMtHtLDocument() != null && this
						.getMtHtLDocument().equals(
								castOther.getMtHtLDocument())))
				&& ((this.getMtTtcLDocument() == castOther
						.getMtTtcLDocument()) || (this.getMtTtcLDocument() != null
						&& castOther.getMtTtcLDocument() != null && this
						.getMtTtcLDocument().equals(
								castOther.getMtTtcLDocument())))
				&& ((this.getRemTxLDocument() == castOther
						.getRemTxLDocument()) || (this.getRemTxLDocument() != null
						&& castOther.getRemTxLDocument() != null && this
						.getRemTxLDocument().equals(
								castOther.getRemTxLDocument())))
				&& ((this.getRemHtLDocument() == castOther
						.getRemHtLDocument()) || (this.getRemHtLDocument() != null
						&& castOther.getRemHtLDocument() != null && this
						.getRemHtLDocument().equals(
								castOther.getRemHtLDocument())))
				&& ((this.getIpAcces() == castOther.getIpAcces()) || (this
						.getIpAcces() != null
						&& castOther.getIpAcces() != null && this
						.getIpAcces().equals(castOther.getIpAcces())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getIdLDocument() == null ? 0 : this.getIdLDocument()
						.hashCode());
		result = 37
				* result
				+ (getIdDocument() == null ? 0 : this.getIdDocument()
						.hashCode());
		result = 37
				* result
				+ (getCodeTLigne() == null ? 0 : this.getCodeTLigne()
						.hashCode());
		result = 37
				* result
				+ (getIdArticle() == null ? 0 : this.getIdArticle()
						.hashCode());
		result = 37
				* result
				+ (getNumLigneLDocument() == null ? 0 : this
						.getNumLigneLDocument().hashCode());
		result = 37
				* result
				+ (getCodeArticle() == null ? 0 : this.getCodeArticle()
						.hashCode());
		result = 37
				* result
				+ (getLibLDocument() == null ? 0 : this.getLibLDocument()
						.hashCode());
		result = 37
				* result
				+ (getQteLDocument() == null ? 0 : this.getQteLDocument()
						.hashCode());
		result = 37
				* result
				+ (getU1LDocument() == null ? 0 : this.getU1LDocument()
						.hashCode());
		result = 37
				* result
				+ (getU2LDocument() == null ? 0 : this.getU2LDocument()
						.hashCode());
		result = 37
				* result
				+ (getPrixULDocument() == null ? 0 : this
						.getPrixULDocument().hashCode());
		result = 37
				* result
				+ (getTauxTvaLDocument() == null ? 0 : this
						.getTauxTvaLDocument().hashCode());
		result = 37
				* result
				+ (getCodeTvaLDocument() == null ? 0 : this
						.getCodeTvaLDocument().hashCode());
		result = 37
				* result
				+ (getCodeTTvaLDocument() == null ? 0 : this
						.getCodeTTvaLDocument().hashCode());
		result = 37
				* result
				+ (getMtHtLDocument() == null ? 0 : this.getMtHtLDocument()
						.hashCode());
		result = 37
				* result
				+ (getMtTtcLDocument() == null ? 0 : this
						.getMtTtcLDocument().hashCode());
		result = 37
				* result
				+ (getRemTxLDocument() == null ? 0 : this
						.getRemTxLDocument().hashCode());
		result = 37
				* result
				+ (getRemHtLDocument() == null ? 0 : this
						.getRemHtLDocument().hashCode());
		result = 37 * result
				+ (getIpAcces() == null ? 0 : this.getIpAcces().hashCode());
		return result;
	}

	public void propertyChange(PropertyChangeEvent evt) {
/*		
//		*/
//		if(evt.getPropertyName().equals("ID_L_Prelevement")){
//			this.setIdLPrelevement((Integer)evt.getNewValue());
//		}		
//		if(evt.getPropertyName().equals("ID_T_LIGNE")){
//			this.setCodeTLigne((Integer)evt.getNewValue());
//		}		
//		if(evt.getPropertyName().equals("ID_ARTICLE")){
//			this.setIdArticle((Integer)evt.getNewValue());
//		}		
//		if(evt.getPropertyName().equals("LIB_L_Prelevement")){
//			this.setLibLPrelevement((String)evt.getNewValue());
//		}		
//		if(evt.getPropertyName().equals("QTE_L_Prelevement")){
//			this.setQteLPrelevement((BigDecimal)evt.getNewValue());
//		}		
//		if(evt.getPropertyName().equals("U1_L_Prelevement")){
//			this.setU1LPrelevement((String)evt.getNewValue());
//		}		
//		if(evt.getPropertyName().equals("U2_L_Prelevement")){
//			this.setU2LPrelevement((String)evt.getNewValue());
//		}		
//		if(evt.getPropertyName().equals("PRIX_U_L_Prelevement")){
//			this.setPrixULPrelevement((BigDecimal)evt.getNewValue());
//		}		
//		if(evt.getPropertyName().equals("TAUX_TVA_L_Prelevement")){
//			this.setTauxTvaLPrelevement((BigDecimal)evt.getNewValue());
//		}		
//		if(evt.getPropertyName().equals("CODE_TVA_L_Prelevement")){
//			this.setCodeTvaLPrelevement((String)evt.getNewValue());
//		}		
//		if(evt.getPropertyName().equals("CODE_T_TVA_L_Prelevement")){
//			this.setCodeTTvaLPrelevement((String)evt.getNewValue());
//		}		
//		if(evt.getPropertyName().equals("MT_HT_L_Prelevement")){
//			this.setMtHtLPrelevement((BigDecimal)evt.getNewValue());
//		}		
//		if(evt.getPropertyName().equals("MT_TTC_L_Prelevement")){
//			this.setMtTtcLPrelevement((BigDecimal)evt.getNewValue());
//		}		
//		if(evt.getPropertyName().equals("REM_TX_L_Prelevement")){
//			this.setRemTxLPrelevement((BigDecimal)evt.getNewValue());
//		}		
//		if(evt.getPropertyName().equals("REM_HT_L_Prelevement")){
//			this.setRemHtLPrelevement((BigDecimal)evt.getNewValue());
//		}		
//		if(evt.getPropertyName().equals("CODE_ARTICLE")){
//			this.setCodeArticle((String)evt.getNewValue());
//		}		
	}

	public BigDecimal getTxRemHtDocument() {
		return txRemHtDocument;
	}

	public void setTxRemHtDocument(BigDecimal txRemHtPrelevement) {
		firePropertyChange("txRemHtDocument", this.txRemHtDocument, this.txRemHtDocument = txRemHtPrelevement);
	}

	@LgrHibernateValidated(champBd = "qte2_l_document",table = "ta_l_proforma",champEntite="qte2LDocument", clazz = TaLPrelevementDTO.class)
	public BigDecimal getQte2LDocument() {
		return qte2LDocument;
	}

	public void setQte2LDocument(BigDecimal qte2LPrelevement) {
		firePropertyChange("qte2LDocument", this.qte2LDocument, this.qte2LDocument = qte2LPrelevement);
	}

	@Override
	public BigDecimal getMtHtLApresRemiseGlobaleDocument() {
		return mtHtLApresRemiseGlobaleDocument;
	}

	@Override
	public void setMtHtLApresRemiseGlobaleDocument(BigDecimal mtHtLApresRemiseGlobaleDocument) {
		this.mtHtLApresRemiseGlobaleDocument = mtHtLApresRemiseGlobaleDocument;
	}

	@Override
	public BigDecimal getMtTtcLApresRemiseGlobaleDocument() {
		return mtTtcLApresRemiseGlobaleDocument;
	}

	@Override
	public void setMtTtcLApresRemiseGlobaleDocument(BigDecimal mtTtcLApresRemiseGlobaleDocument) {
		this.mtTtcLApresRemiseGlobaleDocument = mtTtcLApresRemiseGlobaleDocument;
	}
	
	public Integer getVersionObj() {
		return this.versionObj;
	}

	public void setVersionObj(Integer versionObj) {
		this.versionObj = versionObj;
	}
	
	public String getCodeEntrepot() {
		return codeEntrepot;
	}

	public void setCodeEntrepot(String codeEntrepot) {
		this.codeEntrepot = codeEntrepot;
	}

	public String getEmplacement() {
		return emplacement;
	}

	public void setEmplacement(String emplacement) {
		this.emplacement = emplacement;
	}

	public Date getDluo() {
		return dluo;
	}

	public void setDluo(Date dluo) {
		this.dluo = dluo;
	}

	public String getNumLot() {
		return numLot;
	}

	public void setNumLot(String numLot) {
		this.numLot = numLot;
	}

	public String getLibelleLot() {
		return libelleLot;
	}

	public void setLibelleLot(String libelleLot) {
		this.libelleLot = libelleLot;
	}
	
	@Override
	public String getTypeDocument() {
		// TODO Auto-generated method stub
		return TaPrelevement.TYPE_DOC;
	}

	public String getCodeEtat() {
		return codeEtat;
	}

	public void setCodeEtat(String codeEtat) {
		this.codeEtat = codeEtat;
	}



	public String getUSaisieLDocument() {
		return uSaisieLDocument;
	}

	public void setUSaisieLDocument(String uSaisieLDocument) {
		this.uSaisieLDocument = uSaisieLDocument;
	}

	public BigDecimal getQteSaisieLDocument() {
		return qteSaisieLDocument;
	}

	public void setQteSaisieLDocument(BigDecimal qteSaisieLDocument) {
		this.qteSaisieLDocument = qteSaisieLDocument;
	}


}
