package fr.legrain.document.dto;

// Generated Mar 1, 2007 11:26:10 AM by Hibernate Tools 3.2.0.b9

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.math.BigDecimal;
import java.util.Date;

import javax.validation.constraints.Size;

import fr.legrain.bdg.model.ModelObject;
import fr.legrain.document.model.TaAvisEcheance;
import fr.legrain.document.model.TaTicketDeCaisse;
import fr.legrain.validator.LgrHibernateValidated;


/**
 * SWTLFacture generated by hbm2java
 */
public class TaLTicketDeCaisseDTO extends ModelObject implements PropertyChangeListener, java.io.Serializable, ILigneDocumentDTO{

	private static final long serialVersionUID = -8786674923935823994L;
	
	private Integer id;
	private Integer idDocument;
	private String codeTLigne;
	private Integer idArticle;
	private Integer numLigneLDocument;
	private String codeArticle;
	private String libLDocument;
	private BigDecimal qteLDocument;
	private BigDecimal qte2LDocument;
	private BigDecimal prixULDocument;
	private BigDecimal tauxTvaLDocument;
	private String codeTvaLDocument;
	private String codeTTvaLDocument;
	private BigDecimal mtHtLDocument;
	private BigDecimal mtTtcLDocument;
	private BigDecimal mtHtLApresRemiseGlobaleDocument;
	private BigDecimal mtTtcLApresRemiseGlobaleDocument;	
	private BigDecimal remTxLDocument;
	private BigDecimal remHtLDocument;
	private String IP_ACCES;
	private String u1LDocument;
	private String u2LDocument;
	private BigDecimal txRemHtDocument;
	private String codeTitreTransport;
	private BigDecimal qteTitreTransport;
	
	private String codeEntrepot;
	private String emplacement;
	private Date dluo;
	private String numLot;
	private String libelleLot;
	private String codeEtat;
	private Integer versionObj;
	
	private BigDecimal qteSaisieLDocument;
	private String uSaisieLDocument;
	
	public TaLTicketDeCaisseDTO() {
	}

	public TaLTicketDeCaisseDTO(Integer ID_L_FACTURE, Integer ID_FACTURE,
			String ID_T_LIGNE, Integer ID_ARTICLE,
			Integer NUM_LIGNE_L_FACTURE, String CODE_ARTICLE,
			String LIB_L_FACTURE, BigDecimal QTE_L_FACTURE,
			String U1_L_FACTURE, String U2_L_FACTURE,
			BigDecimal PRIX_U_L_FACTURE, BigDecimal TAUX_TVA_L_FACTURE,
			String CODE_TVA_L_FACTURE, String CODE_T_TVA_L_FACTURE,
			BigDecimal MT_HT_L_FACTURE, BigDecimal MT_TTC_L_FACTURE,
			BigDecimal MT_HT_L_APRES_REMISE_GLOBALE_DOCUMENT, BigDecimal MT_TTC_L_APRES_REMISE_GLOBALE_DOCUMENT,
			BigDecimal REM_TX_L_FACTURE, BigDecimal REM_HT_L_FACTURE,
			String IP_ACCES) {
		this.id = ID_L_FACTURE;
		this.idDocument = ID_FACTURE;
		this.codeTLigne = ID_T_LIGNE;
		this.idArticle = ID_ARTICLE;
		this.numLigneLDocument = NUM_LIGNE_L_FACTURE;
		this.codeArticle = CODE_ARTICLE;
		this.libLDocument = LIB_L_FACTURE;
		this.qteLDocument = QTE_L_FACTURE;
		this.u1LDocument = U1_L_FACTURE;
		this.u2LDocument = U2_L_FACTURE;
		this.prixULDocument = PRIX_U_L_FACTURE;
		this.tauxTvaLDocument = TAUX_TVA_L_FACTURE;
		this.codeTvaLDocument = CODE_TVA_L_FACTURE;
		this.codeTTvaLDocument = CODE_T_TVA_L_FACTURE;
		this.mtHtLDocument = MT_HT_L_FACTURE;
		this.mtTtcLDocument = MT_TTC_L_FACTURE;
		this.mtHtLApresRemiseGlobaleDocument = MT_HT_L_APRES_REMISE_GLOBALE_DOCUMENT;
		this.mtTtcLApresRemiseGlobaleDocument = MT_TTC_L_APRES_REMISE_GLOBALE_DOCUMENT;		
		this.remTxLDocument = REM_TX_L_FACTURE;
		this.remHtLDocument = REM_HT_L_FACTURE;
		this.IP_ACCES = IP_ACCES;
	}
	
	public void setIHMLFacture(TaLTicketDeCaisseDTO ihmLFacture) {
		setIdLDocument(ihmLFacture.id);
		setIdDocument(ihmLFacture.idDocument);
		setCodeTLigne(ihmLFacture.codeTLigne);
		setIdArticle(ihmLFacture.idArticle);
		setNumLigneLDocument(ihmLFacture.numLigneLDocument);
		setCodeArticle(ihmLFacture.codeArticle);
		setLibLDocument(ihmLFacture.libLDocument);
		setQteLDocument(ihmLFacture.qteLDocument);
		setU1LDocument(ihmLFacture.u1LDocument);
		setU2LDocument(ihmLFacture.u2LDocument);
		setPrixULDocument(ihmLFacture.prixULDocument);
		setTauxTvaLDocument(ihmLFacture.tauxTvaLDocument);
		setCodeTvaLDocument(ihmLFacture.codeTvaLDocument);
		setCodeTTvaLDocument(ihmLFacture.codeTTvaLDocument);
		setMtHtLDocument(ihmLFacture.mtHtLDocument);
		setMtTtcLDocument(ihmLFacture.mtTtcLDocument);
		setRemTxLDocument(ihmLFacture.remTxLDocument);
		setRemHtLDocument(ihmLFacture.remHtLDocument);
		setMtHtLApresRemiseGlobaleDocument(mtHtLApresRemiseGlobaleDocument);
		setMtTtcLApresRemiseGlobaleDocument(mtTtcLApresRemiseGlobaleDocument);
		setCodeTitreTransport(codeTitreTransport);
		setQteTitreTransport(qteTitreTransport);
		setIP_ACCES(ihmLFacture.IP_ACCES);
	}
	
	static public TaLTicketDeCaisseDTO copy(TaLTicketDeCaisseDTO ihmLFacture) {
		TaLTicketDeCaisseDTO swtLFactureLoc = new TaLTicketDeCaisseDTO();
		swtLFactureLoc.setIdLDocument(ihmLFacture.id);
		swtLFactureLoc.setIdDocument(ihmLFacture.idDocument);
		swtLFactureLoc.setCodeTLigne(ihmLFacture.codeTLigne);
		swtLFactureLoc.setIdArticle(ihmLFacture.idArticle);
		swtLFactureLoc.setNumLigneLDocument(ihmLFacture.numLigneLDocument);
		swtLFactureLoc.setCodeArticle(ihmLFacture.codeArticle);
		swtLFactureLoc.setLibLDocument(ihmLFacture.libLDocument);
		swtLFactureLoc.setQteLDocument(ihmLFacture.qteLDocument);
		swtLFactureLoc.setQte2LDocument(ihmLFacture.qte2LDocument);
		swtLFactureLoc.setU1LDocument(ihmLFacture.u1LDocument);
		swtLFactureLoc.setU2LDocument(ihmLFacture.u2LDocument);
		swtLFactureLoc.setPrixULDocument(ihmLFacture.prixULDocument);
		swtLFactureLoc.setTauxTvaLDocument(ihmLFacture.tauxTvaLDocument);
		swtLFactureLoc.setCodeTvaLDocument(ihmLFacture.codeTvaLDocument);
		swtLFactureLoc.setCodeTTvaLDocument(ihmLFacture.codeTTvaLDocument);
		swtLFactureLoc.setMtHtLDocument(ihmLFacture.mtHtLDocument);
		swtLFactureLoc.setMtTtcLDocument(ihmLFacture.mtTtcLDocument);
		swtLFactureLoc.setMtHtLApresRemiseGlobaleDocument(ihmLFacture.mtHtLApresRemiseGlobaleDocument);
		swtLFactureLoc.setMtTtcLApresRemiseGlobaleDocument(ihmLFacture.mtTtcLApresRemiseGlobaleDocument);
		swtLFactureLoc.setRemTxLDocument(ihmLFacture.remTxLDocument);
		swtLFactureLoc.setRemHtLDocument(ihmLFacture.remHtLDocument);
		swtLFactureLoc.setIP_ACCES(ihmLFacture.IP_ACCES);
		swtLFactureLoc.setCodeTitreTransport(ihmLFacture.codeTitreTransport);
		swtLFactureLoc.setQteTitreTransport(ihmLFacture.qteTitreTransport);
		swtLFactureLoc.setVersionObj(ihmLFacture.versionObj);
		swtLFactureLoc.setQteSaisieLDocument(ihmLFacture.getQteSaisieLDocument());
		swtLFactureLoc.setUSaisieLDocument(ihmLFacture.uSaisieLDocument);
		return swtLFactureLoc;
	}

	public Integer getIdLDocument() {
		return this.id;
	}

	public void setIdLDocument(Integer ID_L_FACTURE) {
		firePropertyChange("idLDocument", this.id, this.id = ID_L_FACTURE);
	}

	public Integer getIdDocument() {
		return this.idDocument;
	}

	public void setIdDocument(Integer ID_FACTURE) {
		firePropertyChange("idDocument", this.idDocument, this.idDocument = ID_FACTURE);
	}

	public String getCodeTLigne() {
		return this.codeTLigne;
	}

	public void setCodeTLigne(String codeTLigne) {
		firePropertyChange("codeTLigne", this.codeTLigne, this.codeTLigne = codeTLigne);
	}

	public Integer getIdArticle() {
		return this.idArticle;
	}

	public void setIdArticle(Integer ID_ARTICLE) {
		firePropertyChange("idArticle", this.idArticle, this.idArticle = ID_ARTICLE);
	}

	public Integer getNumLigneLDocument() {
		return this.numLigneLDocument;
	}

	public void setNumLigneLDocument(Integer NUM_LIGNE_L_FACTURE) {
		firePropertyChange("numLigneLDocument", this.numLigneLDocument, this.numLigneLDocument = NUM_LIGNE_L_FACTURE);
	}

	@Size(min=0, max=20)
	@LgrHibernateValidated(champBd = "code_article",table = "ta_article",champEntite="codeArticle",clazz = TaLTicketDeCaisseDTO.class)
	public String getCodeArticle() {
		return this.codeArticle;
	}

	public void setCodeArticle(String CODE_ARTICLE) {
		firePropertyChange("codeArticle", this.codeArticle, this.codeArticle = CODE_ARTICLE);
	}

	@LgrHibernateValidated(champBd = "lib_l_document",table = "ta_l_facture",champEntite="libLDocument",clazz = TaLTicketDeCaisseDTO.class)
	public String getLibLDocument() {
		return this.libLDocument;
	}

	public void setLibLDocument(String LIB_L_FACTURE) {
		firePropertyChange("libLDocument", this.libLDocument, this.libLDocument = LIB_L_FACTURE);
	}

	@LgrHibernateValidated(champBd = "qte_l_document",table = "ta_l_facture",champEntite="qteLDocument",clazz = TaLTicketDeCaisseDTO.class)
	public BigDecimal getQteLDocument() {
		return this.qteLDocument;
	}

	public void setQteLDocument(BigDecimal QTE_L_FACTURE) {
		firePropertyChange("qteLDocument", this.qteLDocument, this.qteLDocument = QTE_L_FACTURE);
	}

	@LgrHibernateValidated(champBd = "u1_l_document",table = "ta_l_facture",champEntite="u1LDocument",clazz = TaLTicketDeCaisseDTO.class)
	public String getU1LDocument() {
		return this.u1LDocument;
	}

	public void setU1LDocument(String U1_L_FACTURE) {
		firePropertyChange("u1LDocument", this.u1LDocument, this.u1LDocument = U1_L_FACTURE);
	}

	@LgrHibernateValidated(champBd = "u2_l_document",table = "ta_l_facture",champEntite="u2LDocument",clazz = TaLTicketDeCaisseDTO.class)
	public String getU2LDocument() {
		return this.u2LDocument;
	}

	public void setU2LDocument(String U2_L_FACTURE) {
		firePropertyChange("u2LDocument", this.u2LDocument, this.u2LDocument = U2_L_FACTURE);
	}

	@LgrHibernateValidated(champBd = "prix_u_l_document",table = "ta_l_facture",champEntite="prixULDocument",clazz = TaLTicketDeCaisseDTO.class)
	public BigDecimal getPrixULDocument() {
		return this.prixULDocument;
	}

	public void setPrixULDocument(BigDecimal PRIX_U_L_FACTURE) {
		firePropertyChange("prixULDocument", this.prixULDocument, this.prixULDocument = PRIX_U_L_FACTURE);
	}

	@LgrHibernateValidated(champBd = "taux_tva_l_document",table = "ta_l_facture",champEntite="tauxTvaLDocument",clazz = TaLTicketDeCaisseDTO.class)
	public BigDecimal getTauxTvaLDocument() {
		return this.tauxTvaLDocument;
	}

	public void setTauxTvaLDocument(BigDecimal TAUX_TVA_L_FACTURE) {
		firePropertyChange("tauxTvaLDocument", this.tauxTvaLDocument, this.tauxTvaLDocument = TAUX_TVA_L_FACTURE);
	}

	@Size(min=0, max=20)
	@LgrHibernateValidated(champBd = "code_tva_l_document",table = "ta_l_facture",champEntite="codeTvaLDocument",clazz = TaLTicketDeCaisseDTO.class)
	public String getCodeTvaLDocument() {
		return this.codeTvaLDocument;
	}

	public void setCodeTvaLDocument(String CODE_TVA_L_FACTURE) {
		firePropertyChange("codeTvaLDocument", this.codeTvaLDocument, this.codeTvaLDocument = CODE_TVA_L_FACTURE);
	}

	@Size(min=0, max=20)
	@LgrHibernateValidated(champBd = "code_t_tva_l_document",table = "ta_l_facture",champEntite="codeTTvaLDocument",clazz = TaLTicketDeCaisseDTO.class)
	public String getCodeTTvaLDocument() {
		return this.codeTTvaLDocument;
	}

	public void setCodeTTvaLDocument(String CODE_T_TVA_L_FACTURE) {
		firePropertyChange("codeTTvaLDocument", this.codeTTvaLDocument, this.codeTTvaLDocument = CODE_T_TVA_L_FACTURE);
	}

	@LgrHibernateValidated(champBd = "mt_ht_l_document",table = "ta_l_facture",champEntite="mtHtLDocument",clazz = TaLTicketDeCaisseDTO.class)
	public BigDecimal getMtHtLDocument() {
		return this.mtHtLDocument;
	}

	public void setMtHtLDocument(BigDecimal MT_HT_L_FACTURE) {
		firePropertyChange("mtHtLDocument", this.mtHtLDocument, this.mtHtLDocument = MT_HT_L_FACTURE);
	}

	@LgrHibernateValidated(champBd = "mt_ttc_l_document",table = "ta_l_facture",champEntite="mtTtcLDocument",clazz = TaLTicketDeCaisseDTO.class)
	public BigDecimal getMtTtcLDocument() {
		return this.mtTtcLDocument;
	}

	public void setMtTtcLDocument(BigDecimal MT_TTC_L_FACTURE) {
		firePropertyChange("mtTtcLDocument", this.mtTtcLDocument, this.mtTtcLDocument = MT_TTC_L_FACTURE);
	}

	@LgrHibernateValidated(champBd = "rem_tx_l_document",table = "ta_l_facture",champEntite="remTxLDocument",clazz = TaLTicketDeCaisseDTO.class)
	public BigDecimal getRemTxLDocument() {
		return this.remTxLDocument;
	}

	public void setRemTxLDocument(BigDecimal REM_TX_L_FACTURE) {
		firePropertyChange("remTxLDocument", this.remTxLDocument, this.remTxLDocument = REM_TX_L_FACTURE);
	}

	@LgrHibernateValidated(champBd = "rem_ht_l_document",table = "ta_l_facture",champEntite="remHtLDocument",clazz = TaLTicketDeCaisseDTO.class)
	public BigDecimal getRemHtLDocument() {
		return this.remHtLDocument;
	}

	public void setRemHtLDocument(BigDecimal REM_HT_L_FACTURE) {
		firePropertyChange("remHtLDocument", this.remHtLDocument, this.remHtLDocument = REM_HT_L_FACTURE);
	}

	public String getIP_ACCES() {
		return this.IP_ACCES;
	}

	public void setIP_ACCES(String IP_ACCES) {
		firePropertyChange("IP_ACCES", this.IP_ACCES, this.IP_ACCES = IP_ACCES);
	}
	
	@Size(min=0, max=20)
	@LgrHibernateValidated(champBd = "titre_transport_l_document",table = "ta_l_facture",champEntite="codeTitreTransport",clazz = TaLTicketDeCaisseDTO.class)
	public String getCodeTitreTransport() {
		return this.codeTitreTransport;
	}

	public void setCodeTitreTransport(String codeTitreTransport) {
		firePropertyChange("codeTitreTransport", this.codeTitreTransport, this.codeTitreTransport = codeTitreTransport);
	}
	
	@LgrHibernateValidated(champBd = "qte_titre_transport_l_document",table = "ta_l_facture",champEntite="qteTitreTransport",clazz = TaLTicketDeCaisseDTO.class)
	public BigDecimal getQteTitreTransport() {
		return this.qteTitreTransport;
	}

	public void setQteTitreTransport(BigDecimal qteTitreTransport) {
		firePropertyChange("qteTitreTransport", this.qteTitreTransport, this.qteTitreTransport = qteTitreTransport);
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TaLTicketDeCaisseDTO))
			return false;
		TaLTicketDeCaisseDTO castOther = (TaLTicketDeCaisseDTO) other;

		return ((this.getIdLDocument() == castOther.getIdLDocument()) || (this
				.getIdLDocument() != null
				&& castOther.getIdLDocument() != null && this
				.getIdLDocument().equals(castOther.getIdLDocument())))
				&& ((this.getIdDocument() == castOther.getIdDocument()) || (this
						.getIdDocument() != null
						&& castOther.getIdDocument() != null && this
						.getIdDocument().equals(castOther.getIdDocument())))
				&& ((this.getCodeTLigne() == castOther.getCodeTLigne()) || (this
						.getCodeTLigne() != null
						&& castOther.getCodeTLigne() != null && this
						.getCodeTLigne().equals(castOther.getCodeTLigne())))
				&& ((this.getIdArticle() == castOther.getIdArticle()) || (this
						.getIdArticle() != null
						&& castOther.getIdArticle() != null && this
						.getIdArticle().equals(castOther.getIdArticle())))
				&& ((this.getNumLigneLDocument() == castOther
						.getNumLigneLDocument()) || (this
						.getNumLigneLDocument() != null
						&& castOther.getNumLigneLDocument() != null && this
						.getNumLigneLDocument().equals(
								castOther.getNumLigneLDocument())))
				&& ((this.getCodeArticle() == castOther.getCodeArticle()) || (this
						.getCodeArticle() != null
						&& castOther.getCodeArticle() != null && this
						.getCodeArticle().equals(castOther.getCodeArticle())))
				&& ((this.getLibLDocument() == castOther.getLibLDocument()) || (this
						.getLibLDocument() != null
						&& castOther.getLibLDocument() != null && this
						.getLibLDocument()
						.equals(castOther.getLibLDocument())))
				&& ((this.getQteLDocument() == castOther.getQteLDocument()) || (this
						.getQteLDocument() != null
						&& castOther.getQteLDocument() != null && this
						.getQteLDocument()
						.equals(castOther.getQteLDocument())))
				&& ((this.getU1LDocument() == castOther.getU1LDocument()) || (this
						.getU1LDocument() != null
						&& castOther.getU1LDocument() != null && this
						.getU1LDocument().equals(castOther.getU1LDocument())))
				&& ((this.getU2LDocument() == castOther.getU2LDocument()) || (this
						.getU2LDocument() != null
						&& castOther.getU2LDocument() != null && this
						.getU2LDocument().equals(castOther.getU2LDocument())))
				&& ((this.getPrixULDocument() == castOther
						.getPrixULDocument()) || (this.getPrixULDocument() != null
						&& castOther.getPrixULDocument() != null && this
						.getPrixULDocument().equals(
								castOther.getPrixULDocument())))
				&& ((this.getTauxTvaLDocument() == castOther
						.getTauxTvaLDocument()) || (this
						.getTauxTvaLDocument() != null
						&& castOther.getTauxTvaLDocument() != null && this
						.getTauxTvaLDocument().equals(
								castOther.getTauxTvaLDocument())))
				&& ((this.getCodeTvaLDocument() == castOther
						.getCodeTvaLDocument()) || (this
						.getCodeTvaLDocument() != null
						&& castOther.getCodeTvaLDocument() != null && this
						.getCodeTvaLDocument().equals(
								castOther.getCodeTvaLDocument())))
				&& ((this.getCodeTTvaLDocument() == castOther
						.getCodeTTvaLDocument()) || (this
						.getCodeTTvaLDocument() != null
						&& castOther.getCodeTTvaLDocument() != null && this
						.getCodeTTvaLDocument().equals(
								castOther.getCodeTTvaLDocument())))
				&& ((this.getMtHtLDocument() == castOther
						.getMtHtLDocument()) || (this.getMtHtLDocument() != null
						&& castOther.getMtHtLDocument() != null && this
						.getMtHtLDocument().equals(
								castOther.getMtHtLDocument())))
				&& ((this.getMtTtcLDocument() == castOther
						.getMtTtcLDocument()) || (this.getMtTtcLDocument() != null
						&& castOther.getMtTtcLDocument() != null && this
						.getMtTtcLDocument().equals(
								castOther.getMtTtcLDocument())))
				&& ((this.getRemTxLDocument() == castOther
						.getRemTxLDocument()) || (this.getRemTxLDocument() != null
						&& castOther.getRemTxLDocument() != null && this
						.getRemTxLDocument().equals(
								castOther.getRemTxLDocument())))
				&& ((this.getRemHtLDocument() == castOther
						.getRemHtLDocument()) || (this.getRemHtLDocument() != null
						&& castOther.getRemHtLDocument() != null && this
						.getRemHtLDocument().equals(
								castOther.getRemHtLDocument())))
				&& ((this.getIP_ACCES() == castOther.getIP_ACCES()) || (this
						.getIP_ACCES() != null
						&& castOther.getIP_ACCES() != null && this
						.getIP_ACCES().equals(castOther.getIP_ACCES())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getIdLDocument() == null ? 0 : this.getIdLDocument()
						.hashCode());
		result = 37
				* result
				+ (getIdDocument() == null ? 0 : this.getIdDocument()
						.hashCode());
		result = 37
				* result
				+ (getCodeTLigne() == null ? 0 : this.getCodeTLigne()
						.hashCode());
		result = 37
				* result
				+ (getIdArticle() == null ? 0 : this.getIdArticle()
						.hashCode());
		result = 37
				* result
				+ (getNumLigneLDocument() == null ? 0 : this
						.getNumLigneLDocument().hashCode());
		result = 37
				* result
				+ (getCodeArticle() == null ? 0 : this.getCodeArticle()
						.hashCode());
		result = 37
				* result
				+ (getLibLDocument() == null ? 0 : this.getLibLDocument()
						.hashCode());
		result = 37
				* result
				+ (getQteLDocument() == null ? 0 : this.getQteLDocument()
						.hashCode());
		result = 37
				* result
				+ (getU1LDocument() == null ? 0 : this.getU1LDocument()
						.hashCode());
		result = 37
				* result
				+ (getU2LDocument() == null ? 0 : this.getU2LDocument()
						.hashCode());
		result = 37
				* result
				+ (getPrixULDocument() == null ? 0 : this
						.getPrixULDocument().hashCode());
		result = 37
				* result
				+ (getTauxTvaLDocument() == null ? 0 : this
						.getTauxTvaLDocument().hashCode());
		result = 37
				* result
				+ (getCodeTvaLDocument() == null ? 0 : this
						.getCodeTvaLDocument().hashCode());
		result = 37
				* result
				+ (getCodeTTvaLDocument() == null ? 0 : this
						.getCodeTTvaLDocument().hashCode());
		result = 37
				* result
				+ (getMtHtLDocument() == null ? 0 : this.getMtHtLDocument()
						.hashCode());
		result = 37
				* result
				+ (getMtTtcLDocument() == null ? 0 : this
						.getMtTtcLDocument().hashCode());
		result = 37
				* result
				+ (getRemTxLDocument() == null ? 0 : this
						.getRemTxLDocument().hashCode());
		result = 37
				* result
				+ (getRemHtLDocument() == null ? 0 : this
						.getRemHtLDocument().hashCode());
		result = 37 * result
				+ (getIP_ACCES() == null ? 0 : this.getIP_ACCES().hashCode());
		return result;
	}

	public void propertyChange(PropertyChangeEvent evt) {

//		if(evt.getPropertyName().equals("ID_L_FACTURE")){
//			this.setIdLFacture((Integer)evt.getNewValue());
//		}		
//		if(evt.getPropertyName().equals("ID_T_LIGNE")){
//			this.setCodeTLigne((String)evt.getNewValue());
//		}		
//		if(evt.getPropertyName().equals("ID_ARTICLE")){
//			this.setIdArticle((Integer)evt.getNewValue());
//		}		
//		if(evt.getPropertyName().equals("LIB_L_FACTURE")){
//			this.setLibLFacture((String)evt.getNewValue());
//		}		
//		if(evt.getPropertyName().equals("QTE_L_FACTURE")){
//			this.setQteLFacture((BigDecimal)evt.getNewValue());
//		}		
//		if(evt.getPropertyName().equals("U1_L_FACTURE")){
//			this.setU1LFacture((String)evt.getNewValue());
//		}		
//		if(evt.getPropertyName().equals("U2_L_FACTURE")){
//			this.setU2LFacture((String)evt.getNewValue());
//		}		
//		if(evt.getPropertyName().equals("PRIX_U_L_FACTURE")){
//			this.setPrixULFacture((BigDecimal)evt.getNewValue());
//		}		
//		if(evt.getPropertyName().equals("TAUX_TVA_L_FACTURE")){
//			this.setTauxTvaLFacture((BigDecimal)evt.getNewValue());
//		}		
//		if(evt.getPropertyName().equals("CODE_TVA_L_FACTURE")){
//			this.setCodeTvaLFacture((String)evt.getNewValue());
//		}		
//		if(evt.getPropertyName().equals("CODE_T_TVA_L_FACTURE")){
//			this.setCodeTTvaLFacture((String)evt.getNewValue());
//		}		
//		if(evt.getPropertyName().equals("MT_HT_L_FACTURE")){
//			this.setMtHtLFacture((BigDecimal)evt.getNewValue());
//		}		
//		if(evt.getPropertyName().equals("MT_TTC_L_FACTURE")){
//			this.setMtTtcLFacture((BigDecimal)evt.getNewValue());
//		}		
//		if(evt.getPropertyName().equals("REM_TX_L_FACTURE")){
//			this.setRemTxLFacture((BigDecimal)evt.getNewValue());
//		}		
//		if(evt.getPropertyName().equals("REM_HT_L_FACTURE")){
//			this.setRemHtLFacture((BigDecimal)evt.getNewValue());
//		}		
//		if(evt.getPropertyName().equals("CODE_ARTICLE")){
//			this.setCodeArticle((String)evt.getNewValue());
//		}		
	}

	@LgrHibernateValidated(champBd = "qte2_l_document",table = "ta_l_facture",champEntite="qte2LDocument",clazz = TaLTicketDeCaisseDTO.class)
	public BigDecimal getQte2LDocument() {
		return qte2LDocument;
	}

	public void setQte2LDocument(BigDecimal qte2LFacture) {
		firePropertyChange("qte2LDocument", this.qte2LDocument, this.qte2LDocument = qte2LFacture);

	}

	public BigDecimal getTxRemHtDocument() {
		return txRemHtDocument;
	}

	public void setTxRemHtDocument(BigDecimal txRemHtFacture) {
		firePropertyChange("txRemHtDocument", this.txRemHtDocument, this.txRemHtDocument = txRemHtFacture);
	}

	@LgrHibernateValidated(champBd = "mt_apr_rem_globale",table = "ta_l_facture",champEntite="mtHtLApresRemiseGlobaleDocument",clazz = TaLTicketDeCaisseDTO.class)
	public BigDecimal getMtHtLApresRemiseGlobaleDocument() {
		return mtHtLApresRemiseGlobaleDocument;
	}

	public void setMtHtLApresRemiseGlobaleDocument(
			BigDecimal mtHtLApresRemiseGlobaleDocument) {
		firePropertyChange("mtHtLApresRemiseGlobaleDocument", this.mtHtLApresRemiseGlobaleDocument, 
				this.mtHtLApresRemiseGlobaleDocument = mtHtLApresRemiseGlobaleDocument);
	}

	@LgrHibernateValidated(champBd = "mt_ttc_apr_rem_globale",table = "ta_l_facture",champEntite="mtTtcLApresRemiseGlobaleDocument", clazz = TaLTicketDeCaisseDTO.class)
	public BigDecimal getMtTtcLApresRemiseGlobaleDocument() {
		return mtTtcLApresRemiseGlobaleDocument;
	}

	public void setMtTtcLApresRemiseGlobaleDocument(
			BigDecimal mtTtcLApresRemiseGlobaleDocument) {
		firePropertyChange("mtTtcLApresRemiseGlobaleDocument", this.mtTtcLApresRemiseGlobaleDocument, 
				this.mtTtcLApresRemiseGlobaleDocument = mtTtcLApresRemiseGlobaleDocument);
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getVersionObj() {
		return versionObj;
	}

	public void setVersionObj(Integer versionObj) {
		this.versionObj = versionObj;
	}

	public String getCodeEntrepot() {
		return codeEntrepot;
	}

	public void setCodeEntrepot(String codeEntrepot) {
		this.codeEntrepot = codeEntrepot;
	}

	public String getEmplacement() {
		return emplacement;
	}

	public void setEmplacement(String emplacement) {
		this.emplacement = emplacement;
	}

	public Date getDluo() {
		return dluo;
	}

	public void setDluo(Date dluo) {
		this.dluo = dluo;
	}

	public String getNumLot() {
		return numLot;
	}

	public void setNumLot(String numLot) {
		this.numLot = numLot;
	}

	public String getLibelleLot() {
		return libelleLot;
	}

	public void setLibelleLot(String libelleLot) {
		this.libelleLot = libelleLot;
	}
	
	@Override
	public String getTypeDocument() {
		// TODO Auto-generated method stub
		return TaTicketDeCaisse.TYPE_DOC;
	}

	public String getCodeEtat() {
		return codeEtat;
	}

	public void setCodeEtat(String codeEtat) {
		this.codeEtat = codeEtat;
	}



	public String getUSaisieLDocument() {
		return uSaisieLDocument;
	}

	public void setUSaisieLDocument(String uSaisieLDocument) {
		this.uSaisieLDocument = uSaisieLDocument;
	}

	public BigDecimal getQteSaisieLDocument() {
		return qteSaisieLDocument;
	}

	public void setQteSaisieLDocument(BigDecimal qteSaisieLDocument) {
		this.qteSaisieLDocument = qteSaisieLDocument;
	}


}
