package fr.legrain.article.titretransport.model;

// Generated 4 juin 2009 10:11:38 by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.math.MathContext;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.Version;

import fr.legrain.article.model.TaArticle;
import fr.legrain.lib.data.LibConversion;
import fr.legrain.validator.LgrHibernateValidated;

/**
 * TaStock generated by hbm2java
 */
@Entity
//@Cache(usage=CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "ta_stock_capsules")
//@SequenceGenerator(name = "gen_stock_capsules", sequenceName = "num_id_stock_capsules", allocationSize = 1)
public class TaStockCapsules implements java.io.Serializable {


	private static final long serialVersionUID = 3345094752260248538L;
	
	private int idStock;
	private String version;
	private TaTitreTransport taTitreTransport;
	private String mouvStock;
	private Date dateStock;
	private String libelleStock;
	private BigDecimal qte1Stock;
	private String un1Stock;
	private BigDecimal qte2Stock;
	private String un2Stock;
	private String quiCree;
	private Date quandCree;
	private String quiModif;
	private Date quandModif;
	private String ipAcces;
	private Integer versionObj;

	public TaStockCapsules() {
	}

	public TaStockCapsules(int idStock) {
		this.idStock = idStock;
	}

	public TaStockCapsules(int idStock, TaTitreTransport taTitreTransport, String mouvStock,
			Date dateStock, String libelleStock, BigDecimal qte1Stock,
			String un1Stock, BigDecimal qte2Stock, String un2Stock,
			String quiCreeStock, Date quandCreeStock, String quiModifStock,
			Date quandModifStock, String ipAcces, Integer versionObj) {
		this.idStock = idStock;
		this.taTitreTransport = taTitreTransport;
		this.mouvStock = mouvStock;
		this.dateStock = dateStock;
		this.libelleStock = libelleStock;
		this.qte1Stock = qte1Stock;
		this.un1Stock = un1Stock;
		this.qte2Stock = qte2Stock;
		this.un2Stock = un2Stock;
		this.quiCree = quiCreeStock;
		this.quandCree = quandCreeStock;
		this.quiModif = quiModifStock;
		this.quandModif = quandModifStock;
		this.ipAcces = ipAcces;
		this.versionObj = versionObj;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id_stock_capsules", unique = true, nullable = false)
	@LgrHibernateValidated(champBd = "id_stock_capsules",table = "ta_stock_capsules", champEntite="idStock", clazz = TaStockCapsules.class)
	public int getIdStock() {
		return this.idStock;
	}

	public void setIdStock(int idStock) {
		this.idStock = idStock;
	}

//	@Version
	@Column(name = "version", length = 20)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_titre_transport")
	@LgrHibernateValidated(champBd = "id_titre_transport",table = "ta_titre_transport", champEntite="taTitreTransport.idTitreTransport", clazz = TaTitreTransport.class)
	public TaTitreTransport getTaTitreTransport() {
		return this.taTitreTransport;
	}

	public void setTaTitreTransport(TaTitreTransport taTitreTransport) {
		this.taTitreTransport = taTitreTransport;
	}
	
	@Column(name = "mouv_stock", length = 1)
	@LgrHibernateValidated(champBd = "mouv_stock",table = "ta_stock_capsules", champEntite="mouvStock", clazz = TaStockCapsules.class)
	public String getMouvStock() {
		return this.mouvStock;
	}

	public void setMouvStock(String mouvStock) {
		this.mouvStock = mouvStock;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_stock", length = 19)
	@LgrHibernateValidated(champBd = "date_stock",table = "ta_stock_capsules", champEntite="dateStock", clazz = TaStockCapsules.class)
	public Date getDateStock() {
		return this.dateStock;
	}

	public void setDateStock(Date dateStock) {
		this.dateStock = dateStock;
	}

	@Column(name = "libelle_stock")
	@LgrHibernateValidated(champBd = "libelle_stock",table = "ta_stock_capsules", champEntite="libelleStock", clazz = TaStockCapsules.class)
	public String getLibelleStock() {
		return this.libelleStock;
	}

	public void setLibelleStock(String libelleStock) {
		this.libelleStock = libelleStock;
	}

	@Column(name = "qte1_stock", precision = 15)
	@LgrHibernateValidated(champBd = "qte1_stock",table = "ta_stock_capsules", champEntite="qte1Stock", clazz = TaStockCapsules.class)
	public BigDecimal getQte1Stock() {
		return this.qte1Stock;
	}

	public void setQte1Stock(BigDecimal qte1Stock) {
		this.qte1Stock = qte1Stock;
	}

	@Column(name = "un1_stock", length = 20)
	@LgrHibernateValidated(champBd = "un1_stock",table = "ta_stock_capsules", champEntite="un1Stock", clazz = TaStockCapsules.class)
	public String getUn1Stock() {
		return this.un1Stock;
	}

	public void setUn1Stock(String un1Stock) {
		this.un1Stock = un1Stock;
	}

	@Column(name = "qte2_stock", precision = 15)
	@LgrHibernateValidated(champBd = "qte2_stock",table = "ta_stock_capsules", champEntite="qte2Stock", clazz = TaStockCapsules.class)
	public BigDecimal getQte2Stock() {
		return this.qte2Stock;
	}

	public void setQte2Stock(BigDecimal qte2Stock) {
		this.qte2Stock = qte2Stock;
	}

	@Column(name = "un2_stock", length = 20)
	@LgrHibernateValidated(champBd = "un2_stock",table = "ta_stock_capsules", champEntite="un2Stock", clazz = TaStockCapsules.class)
	public String getUn2Stock() {
		return this.un2Stock;
	}

	public void setUn2Stock(String un2Stock) {
		this.un2Stock = un2Stock;
	}

	@Column(name = "qui_cree", length = 50)
	public String getQuiCree() {
		return this.quiCree;
	}

	public void setQuiCree(String quiCreeStock) {
		this.quiCree = quiCreeStock;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "quand_cree", length = 19)
	public Date getQuandCree() {
		return this.quandCree;
	}

	public void setQuandCree(Date quandCreeStock) {
		this.quandCree = quandCreeStock;
	}

	@Column(name = "qui_modif", length = 50)
	public String getQuiModif() {
		return this.quiModif;
	}

	public void setQuiModif(String quiModifStock) {
		this.quiModif = quiModifStock;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "quand_modif", length = 19)
	public Date getQuandModif() {
		return this.quandModif;
	}

	public void setQuandModif(Date quandModifStock) {
		this.quandModif = quandModifStock;
	}

	@Column(name = "ip_acces", length = 50)
	public String getIpAcces() {
		return this.ipAcces;
	}

	public void setIpAcces(String ipAcces) {
		this.ipAcces = ipAcces;
	}
	@Version
	@Column(name = "version_obj")
	public Integer getVersionObj() {
		return this.versionObj;
	}

	public void setVersionObj(Integer versionObj) {
		this.versionObj = versionObj;
	}

	@Transient
	public void initQte2(TaArticle article){
		if(article.getTaRapportUnite()!=null && article.getTaRapportUnite().getTaUnite1()!=null && article.getTaRapportUnite().getTaUnite2()!=null
				&& article.getTaRapportUnite().getTaUnite1().getCodeUnite().equals(getUn1Stock())){
			int nbDecimal =article.getTaRapportUnite().getNbDecimal(); 
			setUn2Stock(article.getTaRapportUnite().getTaUnite2().getCodeUnite());
			BigDecimal Qte2 = new BigDecimal(0);
			if(getQte1Stock()!=null) {
				boolean sens = LibConversion.intToBoolean(article.getTaRapportUnite().getSens());
				if(sens) {
					if(getQte1Stock().compareTo(new BigDecimal(0))!=0)
						//Qte2 = LibCalcul.arrondi(getQte1Stock().divide(article.getTaRapportUnite().getRapport()),nbDecimal);
						Qte2 = getQte1Stock().divide(article.getTaRapportUnite().getRapport(),MathContext.DECIMAL128).setScale(nbDecimal,BigDecimal.ROUND_HALF_UP);
				} else {
					Qte2 = getQte1Stock().multiply(article.getTaRapportUnite().getRapport(),MathContext.DECIMAL128).setScale(nbDecimal,BigDecimal.ROUND_HALF_UP);
				}
			}

				setQte2Stock(Qte2);
		}
//				else
//		{
//			setUn2Stock("");
//			setQte2Stock(BigDecimal.ZERO);
//		}
	}

}
