package fr.legrain.article.model;

// Generated Sep 1, 2008 3:06:27 PM by Hibernate Tools 3.2.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import fr.legrain.general.model.TaObjetLgr;
import fr.legrain.validator.LgrHibernateValidated;

/**
 * TaTTva generated by hbm2java
 */
@Entity
//@Cache(usage=CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "ta_t_conditionnement")
//@SequenceGenerator(name = "gen_t_conditionnement", sequenceName = "num_id_t_conditionnement", allocationSize = 1)
public class TaTConditionnement extends TaObjetLgr   implements java.io.Serializable {

	private static final long serialVersionUID = 556413473118411765L;
	
	private int id;
//	private String version;
	private String codeType;
	private String libelle;
	private BigDecimal hauteur;
	private BigDecimal longueur;
	private BigDecimal largeur;
	private BigDecimal poids;
//	private String quiCree;
//	private Date quandCree;
//	private String quiModif;
//	private Date quandModif;
//	private String ipAcces;
	private Integer versionObj;

	public TaTConditionnement() {
	}

	public TaTConditionnement(int id) {
		this.id = id;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	@LgrHibernateValidated(champBd = "id",table = "ta_t_conditionnement", champEntite="id", clazz = TaTConditionnement.class)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

//	//@Version
//	@Column(name = "version", length = 20)
//	public String getVersion() {
//		return this.version;
//	}
//
//	public void setVersion(String version) {
//		this.version = version;
//	}
	
	@Version
	@Column(name = "version_obj", precision = 15)
	public Integer getVersionObj() {
		return this.versionObj;
	}

	public void setVersionObj(Integer versionObj) {
		this.versionObj = versionObj;
	}

	@Column(name = "code_t_conditionnement", length = 1)
	@LgrHibernateValidated(champBd = "code_t_conditionnement",table = "ta_t_conditionnement", champEntite="codeType", clazz = TaTConditionnement.class)
	public String getCodeType() {
		return this.codeType;
	}

	public void setCodeType(String code) {
		this.codeType = code;
	}

	@Column(name = "libelle_t_conditionnement")
	@LgrHibernateValidated(champBd = "libelle_t_conditionnement",table = "ta_t_conditionnement", champEntite="libelle", clazz = TaTConditionnement.class)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	@Column(name = "hauteur_t_conditionnement")
	@LgrHibernateValidated(champBd = "hauteur_t_conditionnement",table = "ta_t_conditionnement", champEntite="hauteur", clazz = TaTConditionnement.class)
	public BigDecimal getHauteur() {
		return hauteur;
	}

	public void setHauteur(BigDecimal hauteur) {
		this.hauteur = hauteur;
	}

	@Column(name = "longueur_t_conditionnement")
	@LgrHibernateValidated(champBd = "longueur_t_conditionnement",table = "ta_t_conditionnement", champEntite="longueur", clazz = TaTConditionnement.class)
	public BigDecimal getLongueur() {
		return longueur;
	}

	public void setLongueur(BigDecimal longueur) {
		this.longueur = longueur;
	}

	@Column(name = "largeur_t_conditionnement")
	@LgrHibernateValidated(champBd = "largeur_t_conditionnement",table = "ta_t_conditionnement", champEntite="largeur", clazz = TaTConditionnement.class)
	public BigDecimal getLargeur() {
		return largeur;
	}

	public void setLargeur(BigDecimal largeur) {
		this.largeur = largeur;
	}

	@Column(name = "poids")
	@LgrHibernateValidated(champBd = "poids",table = "ta_t_conditionnement", champEntite="poids", clazz = TaTConditionnement.class)
	public BigDecimal getPoids() {
		return poids;
	}

	public void setPoids(BigDecimal poids) {
		this.poids = poids;
	}

//	@Column(name = "qui_cree", length = 50)
//	public String getQuiCree() {
//		return this.quiCree;
//	}
//
//	public void setQuiCree(String quiCree) {
//		this.quiCree = quiCree;
//	}
//
//	@Temporal(TemporalType.TIMESTAMP)
//	@Column(name = "quand_cree", length = 19)
//	public Date getQuandCree() {
//		return this.quandCree;
//	}
//
//	public void setQuandCree(Date quandCree) {
//		this.quandCree = quandCree;
//	}
//
//	@Column(name = "qui_modif", length = 50)
//	public String getQuiModif() {
//		return this.quiModif;
//	}
//
//	public void setQuiModif(String quiModif) {
//		this.quiModif = quiModif;
//	}
//
//	@Temporal(TemporalType.TIMESTAMP)
//	@Column(name = "quand_modif", length = 19)
//	public Date getQuandModif() {
//		return this.quandModif;
//	}
//
//	public void setQuandModif(Date quandModif) {
//		this.quandModif = quandModif;
//	}
//
//	@Column(name = "ip_acces", length = 50)
//	public String getIpAcces() {
//		return this.ipAcces;
//	}
//
//	public void setIpAcces(String ipAcces) {
//		this.ipAcces = ipAcces;
//	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((hauteur == null) ? 0 : hauteur.hashCode());
		return result;
	}


}
