package fr.legrain.article.model;

// Generated Mar 24, 2009 4:44:04 PM by Hibernate Tools 3.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import fr.legrain.general.model.TaObjetLgr;
import fr.legrain.validator.LgrHibernateValidated;

/**
 * TaTNote generated by hbm2java
 */
@Entity
//@Cache(usage=CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "ta_t_note_article")
//@SequenceGenerator(name = "gen_t_note_article", sequenceName = "num_id_t_note_article", allocationSize = 1)
public class TaTNoteArticle extends TaObjetLgr   implements java.io.Serializable {

	private static final long serialVersionUID = -1753643247209813810L;
	
	private int idTNoteArticle;
//	private String version;
	private String codeTNoteArticle;
	private String liblTNoteArticle;
//	private String quiCree;
//	private Date quandCree;
//	private String quiModif;
//	private Date quandModif;
//	private String ipAcces;
	private Integer versionObj;
//	private Set<TaNoteArticle> taNotesArticle = new HashSet<TaNoteArticle>(0);

	public TaTNoteArticle() {
	}

	public TaTNoteArticle(int idTNote) {
		this.idTNoteArticle = idTNote;
	}

	public TaTNoteArticle(int idTNoteArticle, String codeTNoteArticle, String liblTNoteArticle,
			String quiCreeTNote, Date quandCreeTNote, String quiModifTNote,
			Date quandModifTNote, String ipAcces, Integer versionObj,
			Set<TaNoteArticle> taNotesArticle) {
		this.idTNoteArticle = idTNoteArticle;
		this.codeTNoteArticle = codeTNoteArticle;
		this.liblTNoteArticle = liblTNoteArticle;
		this.quiCree = quiCreeTNote;
		this.quandCree = quandCreeTNote;
		this.quiModif = quiModifTNote;
		this.quandModif = quandModifTNote;
		this.ipAcces = ipAcces;
		this.versionObj = versionObj;
//		this.taNotesArticle = taNotesArticle;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id_t_note_article", unique = true, nullable = false)
	@LgrHibernateValidated(champBd = "id_t_note_article",table = "ta_t_note_article", champEntite="idTNoteArticle", clazz = TaTNoteArticle.class)
	public int getIdTNoteArticle() {
		return this.idTNoteArticle;
	}

	public void setIdTNoteArticle(int idTNote) {
		this.idTNoteArticle = idTNote;
	}

//	@Column(name = "version", length = 20)
//	public String getVersion() {
//		return this.version;
//	}
//
//	public void setVersion(String version) {
//		this.version = version;
//	}

	@Column(name = "code_t_note_article", length = 20)
	@LgrHibernateValidated(champBd = "code_t_note_article",table = "ta_t_note_article", champEntite="codeTNoteArticle", clazz = TaTNoteArticle.class)
	public String getCodeTNoteArticle() {
		return this.codeTNoteArticle;
	}

	public void setCodeTNoteArticle(String codeTNoteArticle) {
		this.codeTNoteArticle = codeTNoteArticle;
	}

	@Column(name = "libl_t_note_article", length = 100)
	@LgrHibernateValidated(champBd = "libl_t_note_article",table = "ta_t_note_article", champEntite="liblTNoteArticle", clazz = TaTNoteArticle.class)
	public String getLiblTNoteArticle() {
		return this.liblTNoteArticle;
	}

	public void setLiblTNoteArticle(String liblTNoteArticle) {
		this.liblTNoteArticle = liblTNoteArticle;
	}

//	@Column(name = "qui_cree", length = 50)
//	public String getQuiCree() {
//		return this.quiCree;
//	}
//
//	public void setQuiCree(String quiCreeTNote) {
//		this.quiCree = quiCreeTNote;
//	}
//
//	@Temporal(TemporalType.TIMESTAMP)
//	@Column(name = "quand_cree", length = 19)
//	public Date getQuandCree() {
//		return this.quandCree;
//	}
//
//	public void setQuandCree(Date quandCreeTNote) {
//		this.quandCree = quandCreeTNote;
//	}
//
//	@Column(name = "qui_modif", length = 50)
//	public String getQuiModif() {
//		return this.quiModif;
//	}
//
//	public void setQuiModif(String quiModifTNote) {
//		this.quiModif = quiModifTNote;
//	}
//
//	@Temporal(TemporalType.TIMESTAMP)
//	@Column(name = "quand_modif", length = 19)
//	public Date getQuandModif() {
//		return this.quandModif;
//	}
//
//	public void setQuandModif(Date quandModifTNote) {
//		this.quandModif = quandModifTNote;
//	}
//
//	@Column(name = "ip_acces", length = 50)
//	public String getIpAcces() {
//		return this.ipAcces;
//	}
//
//	public void setIpAcces(String ipAcces) {
//		this.ipAcces = ipAcces;
//	}

	@Version
	@Column(name = "version_obj")
	public Integer getVersionObj() {
		return this.versionObj;
	}

	public void setVersionObj(Integer versionObj) {
		this.versionObj = versionObj;
	}

//	@OneToMany(cascade = {CascadeType.PERSIST, CascadeType.MERGE}, fetch = FetchType.LAZY, mappedBy = "taTNoteArticle")
//	public Set<TaNoteArticle> getTaNotesArticle() {
//		return this.taNotesArticle;
//	}
//
//	public void setTaNotesArticle(Set<TaNoteArticle> taNotes) {
//		this.taNotesArticle = taNotes;
//	}

	
//	@PrePersist
//	@PreUpdate
	public void beforePost ()throws Exception{
		this.setCodeTNoteArticle(codeTNoteArticle.toUpperCase());
	}
}
