package fr.legrain.licenceSara.model;

// Generated 11 août 2009 15:52:23 by Hibernate Tools 3.2.4.GA

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import fr.legrain.supportAbonLegrain.model.TaUtilisateur;
import fr.legrain.supportAbonnement.model.TaLicenceLogiciel;
import fr.legrain.tiers.model.TaFamilleTiers;
import fr.legrain.validator.LgrHibernateValidated;


/**
 * TaWlgr generated by hbm2java
 */
@Entity
@Table(name = "ta_licence_sara")
public  class TaLicenceSara extends TaLicenceLogiciel implements java.io.Serializable {

   
	/**
	 * 
	 */
	private static final long serialVersionUID = 3641229102134450810L;
	private TaUtilisateur taUtilisateur;
    private TaFamilleTiers groupe;
	private Integer telechargement=0;
//	private Integer versionObj;
	
	public TaLicenceSara() {
	}

	
public TaLicenceSara(TaUtilisateur taUtilisateur) {
	super();
	this.setClassName(this.getClass().getName());
	this.taUtilisateur = taUtilisateur;
}

	
	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinColumn(name = "id_utilisateur")
	@LgrHibernateValidated(champBd = "id_utilisateur",table = "ta_utilisateur", champEntite="taUtilisateur.idUtilisateur",clazz = TaUtilisateur.class)
	public TaUtilisateur getTaUtilisateur() {
		return taUtilisateur;
	}

	public void setTaUtilisateur(TaUtilisateur taUtilisateur) {
		this.taUtilisateur = taUtilisateur;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.REFRESH)
	@JoinColumn(name = "groupe")
	@LgrHibernateValidated(champBd = "id_famille",table = "ta_famille_tiers", champEntite="groupe.idFamille",clazz = TaFamilleTiers.class)
	public TaFamilleTiers getGroupe() {
		return groupe;
	}

	public void setGroupe(TaFamilleTiers groupe) {
		this.groupe = groupe;
	}
	
	@Column(name = "telechargement")
	@LgrHibernateValidated(champBd = "telechargement",table = "ta_licence_sara", champEntite="telechargement", clazz = TaLicenceSara.class)
	public Integer getTelechargement() {
		return telechargement;
	}


	public void setTelechargement(Integer telechargement) {
		this.telechargement = telechargement;
	}	

//	@Version
//	@Column(name = "VERSION_OBJ", precision = 15)
//	public Integer getVersionObj() {
//		return this.versionObj;
//	}
//
//	public void setVersionObj(Integer versionObj) {
//		this.versionObj = versionObj;
//	}
}
