package fr.legrain.gestCom.Module_Articles;

// Generated Mar 1, 2007 11:26:10 AM by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import java.util.ArrayList;

import fr.legrain.lib.data.ModelObject;

/**
 * SWTArticle generated by hbm2java
 */
public class SWTArticle extends ModelObject {

	private Integer idArticle;
	private String codeArticle;
	private String libellecArticle;
	private String libellelArticle;
	private String numcptArticle;
	private String diversArticle;
	private Integer idTTva;
	private BigDecimal stockMinArticle;
	private Integer idFamille;
	private Integer idPrix;
	private BigDecimal prixPrix;
	private BigDecimal prixttcPrix;
	private BigDecimal longueur;
	private BigDecimal largeur;
	private BigDecimal hauteur;
	private BigDecimal poids;
	private Integer idUnite;
	private String codeUnite;
	private String codeFamille;
	private String libcFamille;
	private Integer idTva;
	private String codeTva;
	private BigDecimal tauxTva;
	private String numcptTva;
	private String codeTTva;
	private String libTTva;
	private Integer idRapportUnite;
	private Integer idUnite2;
	private String codeUnite2;
	private BigDecimal rapport;
	private Integer nbDecimal;
	private Boolean actif;
	private Boolean sens;
	private String codeTitreTransport;
	private BigDecimal qteTitreTransport;
	private String commentaireArticle;
	
	
	private SWTUnite swtUnite = new SWTUnite();
	private SWTPrix swtPrix = new SWTPrix();
	private SWTRefPrix swtRefPrix = new SWTRefPrix();
	private SWTRapportUnite swtRapportUnite = new SWTRapportUnite();
	private ArrayList<SWTPrix> listePrix = new ArrayList<SWTPrix>();
	private ArrayList<SWTRapportUnite> listeRapportUnite = new ArrayList<SWTRapportUnite>();
	
	public SWTArticle() {
	}
	
	public SWTArticle(Integer ID_ARTICLE, String CODE_ARTICLE,
			String LIBELLEC_ARTICLE, String LIBELLEL_ARTICLE,
			String NUMCPT_ARTICLE, String DIVERS_ARTICLE,
			String COMMENTAIRE_ARTICLE, Integer ID_T_TVA,
			BigDecimal STOCK_MIN_ARTICLE, Integer ID_FAMILLE, Integer ID_PRIX,
			BigDecimal PRIX_PRIX,BigDecimal PRIXTTC_PRIX, Integer ID_UNITE, String CODE_UNITE,
			String CODE_FAMILLE, String LIBC_FAMILLE, Integer ID_TVA,
			String CODE_TVA, BigDecimal TAUX_TVA, String NUMCPT_TVA,
			String CODE_T_TVA, String LIB_T_TVA,SWTUnite swtUnite,SWTPrix swtPrix,
			SWTRefPrix swtRefPrix,ArrayList<SWTPrix> listePrix,
			ArrayList<SWTRapportUnite> listeRapportUnite,Integer idRapportUnite,
			Integer idUnite2,BigDecimal Rapport,Integer nbDecimal, Boolean actif) {
		this.idArticle = ID_ARTICLE;
		this.codeArticle = CODE_ARTICLE;
		this.libellecArticle = LIBELLEC_ARTICLE;
		this.libellelArticle = LIBELLEL_ARTICLE;
		this.numcptArticle = NUMCPT_ARTICLE;
		this.diversArticle = DIVERS_ARTICLE;
//		this.commentaireArticle = COMMENTAIRE_ARTICLE;
		this.idTTva = ID_T_TVA;
		this.stockMinArticle = STOCK_MIN_ARTICLE;
		this.idFamille = ID_FAMILLE;
		this.idPrix = ID_PRIX;
		this.prixPrix = PRIX_PRIX;
		this.prixttcPrix = PRIXTTC_PRIX;
		this.idUnite = ID_UNITE;
		this.codeUnite = CODE_UNITE;
		this.codeFamille = CODE_FAMILLE;
		this.libcFamille = LIBC_FAMILLE;
		this.idTva = ID_TVA;
		this.codeTva = CODE_TVA;
		this.tauxTva = TAUX_TVA;
		this.numcptTva = NUMCPT_TVA;
		this.codeTTva = CODE_T_TVA;
		this.libTTva = LIB_T_TVA;
		this.swtUnite = swtUnite;
		this.swtPrix = swtPrix;
		this.swtRefPrix = swtRefPrix;
		this.listePrix = listePrix;
		this.listeRapportUnite = listeRapportUnite;
		this.idRapportUnite =idRapportUnite;
		this.idUnite2=idUnite2;
		this.rapport = Rapport;
		this.nbDecimal = nbDecimal;
		this.actif = actif;
	}



	public Integer getIdArticle() {
		return this.idArticle;
	}

	public void setIdArticle(Integer ID_ARTICLE) {
		firePropertyChange("idArticle", this.idArticle, this.idArticle = ID_ARTICLE);
	}

	public String getCodeArticle() {
		return this.codeArticle;
	}

	public void setCodeArticle(String CODE_ARTICLE) {
		firePropertyChange("codeArticle", this.codeArticle, this.codeArticle = CODE_ARTICLE);
	}

	public String getLibellecArticle() {
		return this.libellecArticle;
	}

	public void setLibellecArticle(String LIBELLEC_ARTICLE) {
		firePropertyChange("libellecArticle", this.libellecArticle, this.libellecArticle = LIBELLEC_ARTICLE);
	}

	public String getLibellelArticle() {
		return this.libellelArticle;
	}

	public void setLibellelArticle(String LIBELLEL_ARTICLE) {
		firePropertyChange("libellelArticle", this.libellelArticle, this.libellelArticle = LIBELLEL_ARTICLE);
	}

	public String getNumcptArticle() {
		return this.numcptArticle;
	}

	public void setNumcptArticle(String NUMCPT_ARTICLE) {
		firePropertyChange("numcptArticle", this.numcptArticle, this.numcptArticle = NUMCPT_ARTICLE);
	}

	public String getDiversArticle() {
		return this.diversArticle;
	}

	public void setDiversArticle(String DIVERS_ARTICLE) {
		firePropertyChange("diversArticle", this.diversArticle, this.diversArticle = DIVERS_ARTICLE);
	}

//	public String getCommentaireArticle() {
//		return this.commentaireArticle;
//	}
//
//	public void setCommentaireArticle(String COMMENTAIRE_ARTICLE) {
//		firePropertyChange("commentaireArticle", this.commentaireArticle, this.commentaireArticle = COMMENTAIRE_ARTICLE);
//	}

	public Integer getIdTTva() {
		return this.idTTva;
	}

	public void setIdTTva(Integer ID_T_TVA) {
		firePropertyChange("idTTva", this.idTTva, this.idTTva = ID_T_TVA);
	}

	public BigDecimal getStockMinArticle() {
		return this.stockMinArticle;
	}

	public void setStockMinArticle(BigDecimal STOCK_MIN_ARTICLE) {
		firePropertyChange("stockMinArticle", this.stockMinArticle, this.stockMinArticle = STOCK_MIN_ARTICLE);
	}

	public Integer getIdFamille() {
		return this.idFamille;
	}

	public void setIdFamille(Integer ID_FAMILLE) {
		firePropertyChange("idFamille", this.idFamille, this.idFamille = ID_FAMILLE);
	}

	public Integer getIdPrix() {
		return this.idPrix;
	}

	public void setIdPrix(Integer ID_PRIX) {
		firePropertyChange("idPrix", this.idPrix, this.idPrix = ID_PRIX);
	}

	public BigDecimal getPrixPrix() {
		return this.prixPrix;
	}

	public void setPrixPrix(BigDecimal PRIX_PRIX) {
		firePropertyChange("prixPrix", this.prixPrix, this.prixPrix = PRIX_PRIX);
	}

	public Integer getIdUnite() {
		return this.idUnite;
	}

	public void setIdUnite(Integer ID_UNITE) {
		firePropertyChange("idUnite", this.idUnite, this.idUnite = ID_UNITE);
	}

	public String getCodeUnite() {
		return this.codeUnite;
	}

	public void setCodeUnite(String CODE_UNITE) {
		firePropertyChange("codeUnite", this.codeUnite, this.codeUnite = CODE_UNITE);
	}

	public String getCodeFamille() {
		return this.codeFamille;
	}

	public void setCodeFamille(String CODE_FAMILLE) {
		firePropertyChange("codeFamille", this.codeFamille, this.codeFamille = CODE_FAMILLE);
	}

	public String getLibcFamille() {
		return this.libcFamille;
	}

	public void setLibcFamille(String LIBC_FAMILLE) {
		firePropertyChange("libcFamille", this.libcFamille, this.libcFamille = LIBC_FAMILLE);
	}

	public Integer getIdTva() {
		return this.idTva;
	}

	public void setIdTva(Integer ID_TVA) {
		firePropertyChange("idTva", this.idTva, this.idTva = ID_TVA);
	}

	public String getCodeTva() {
		return this.codeTva;
	}

	public void setCodeTva(String CODE_TVA) {
		firePropertyChange("codeTva", this.codeTva, this.codeTva = CODE_TVA);
	}

	public BigDecimal getTauxTva() {
		return this.tauxTva;
	}

	public void setTauxTva(BigDecimal TAUX_TVA) {
		firePropertyChange("tauxTva", this.tauxTva, this.tauxTva = TAUX_TVA);
	}

	public String getNumcptTva() {
		return this.numcptTva;
	}

	public void setNumcptTva(String NUMCPT_TVA) {
		firePropertyChange("numcptTva", this.numcptTva, this.numcptTva = NUMCPT_TVA);
	}

	public String getCodeTTva() {
		return this.codeTTva;
	}

	public void setCodeTTva(String CODE_T_TVA) {
		firePropertyChange("codeTTva", this.codeTTva, this.codeTTva = CODE_T_TVA);
	}

	public String getLibTTva() {
		return this.libTTva;
	}

	public void setLibTTva(String LIB_T_TVA) {
		firePropertyChange("libTTva", this.libTTva, this.libTTva = LIB_T_TVA);
	}
	
	public String getCodeTitreTransport() {
		return this.codeTitreTransport;
	}

	public void setCodeTitreTransport(String titreTransport) {
		firePropertyChange("titreTransport", this.codeTitreTransport, this.codeTitreTransport = titreTransport);
	}
	
	public BigDecimal getQteTitreTransport() {
		return this.qteTitreTransport;
	}

	public void setQteTitreTransport(BigDecimal qteTitreTransport) {
		firePropertyChange("qteTitreTransport", this.qteTitreTransport, this.qteTitreTransport = qteTitreTransport);
	}

	
	public static SWTArticle copy(SWTArticle swtArticle){
		return copy(swtArticle, null);
	}
	
	public static SWTArticle copy(SWTArticle swtArticle, SWTArticle articleDest){
		SWTArticle swtArticleLoc = null;
		if(articleDest==null)
			swtArticleLoc = new SWTArticle();
		else
			swtArticleLoc = articleDest;
		swtArticleLoc.setCodeArticle(swtArticle.codeArticle);
		swtArticleLoc.setCodeFamille(swtArticle.codeFamille);
		swtArticleLoc.setCodeTTva(swtArticle.codeTTva);
		swtArticleLoc.setCodeTva(swtArticle.codeTva);
		swtArticleLoc.setCodeUnite(swtArticle.codeUnite);
//		swtArticleLoc.setCommentaireArticle(swtArticle.commentaireArticle);
		swtArticleLoc.setDiversArticle(swtArticle.diversArticle);
		swtArticleLoc.setIdArticle(swtArticle.idArticle);
		swtArticleLoc.setIdFamille(swtArticle.idFamille);
		swtArticleLoc.setIdPrix(swtArticle.idPrix);
		swtArticleLoc.setIdTTva(swtArticle.idTTva);
		swtArticleLoc.setIdTva(swtArticle.idTva);
		swtArticleLoc.setIdUnite(swtArticle.idUnite);
		swtArticleLoc.setLibTTva(swtArticle.libTTva);
		swtArticleLoc.setLibcFamille(swtArticle.libcFamille);
		swtArticleLoc.setLibellecArticle(swtArticle.libellecArticle);
		swtArticleLoc.setLibellelArticle(swtArticle.libellelArticle);
		swtArticleLoc.setNumcptArticle(swtArticle.numcptArticle);
		swtArticleLoc.setNumcptTva(swtArticle.numcptTva);
		swtArticleLoc.setPrixPrix(swtArticle.prixPrix);
		swtArticleLoc.setPrixttcPrix(swtArticle.prixttcPrix);
		swtArticleLoc.setStockMinArticle(swtArticle.stockMinArticle);
		swtArticleLoc.setTauxTva(swtArticle.tauxTva);
		swtArticleLoc.setSwtPrix(swtArticle.swtPrix);
		swtArticleLoc.setSwtRefPrix(swtArticle.swtRefPrix);
		swtArticleLoc.setSwtUnite(swtArticle.swtUnite);
		swtArticleLoc.setListePrix(swtArticle.listePrix);
		swtArticleLoc.setListeRapportUnite(swtArticle.listeRapportUnite);
		swtArticleLoc.setSwtRapportUnite(swtArticle.swtRapportUnite);
		swtArticleLoc.setIdRapportUnite(swtArticle.idRapportUnite);
		swtArticleLoc.setCodeUnite2(swtArticle.codeUnite2);
		swtArticleLoc.setIdUnite2(swtArticle.idUnite2);
		swtArticleLoc.setRapport(swtArticle.rapport);
		swtArticleLoc.setNbDecimal(swtArticle.nbDecimal);
		swtArticleLoc.setActif(swtArticle.actif);
		swtArticleLoc.setSens(swtArticle.sens);
		swtArticleLoc.setCodeTitreTransport(swtArticle.codeTitreTransport);
		swtArticleLoc.setQteTitreTransport(swtArticle.qteTitreTransport);
		swtArticleLoc.setCommentaireArticle(swtArticle.commentaireArticle);
		return swtArticleLoc;
	}

	public SWTPrix getSwtPrix() {
		return swtPrix;
	}

	public void setSwtPrix(SWTPrix swtPrix) {
		this.swtPrix = swtPrix;
	}

	public SWTRefPrix getSwtRefPrix() {
		return swtRefPrix;
	}

	public void setSwtRefPrix(SWTRefPrix swtRefPrix) {
		this.swtRefPrix = swtRefPrix;
	}

	public SWTUnite getSwtUnite() {
		return swtUnite;
	}

	public void setSwtUnite(SWTUnite swtUnite) {
		this.swtUnite = swtUnite;
	}

	public ArrayList<SWTPrix> getListePrix() {
		return listePrix;
	}

	public void setListePrix(ArrayList<SWTPrix> listePrix) {
		this.listePrix = listePrix;
	}

	public BigDecimal getPrixttcPrix() {
		return prixttcPrix;
	}

	public void setPrixttcPrix(BigDecimal prixttcPrix) {
		firePropertyChange("prixttcPrix", this.prixttcPrix, this.prixttcPrix = prixttcPrix);
	}

	public Integer getIdRapportUnite() {
		return idRapportUnite;
	}

	public void setIdRapportUnite(Integer idRapportUnite) {
		firePropertyChange("idRapportUnite", this.idRapportUnite, this.idRapportUnite = idRapportUnite);
	}

	public Integer getIdUnite2() {
		return idUnite2;
	}

	public void setIdUnite2(Integer idUnite2) {
		firePropertyChange("idUnite2", this.idUnite2, this.idUnite2 = idUnite2);
	}

	public BigDecimal getRapport() {
		return rapport;
	}

	public void setRapport(BigDecimal rapport) {
		firePropertyChange("Rapport", this.rapport, this.rapport = rapport);
	}

	public Integer getNbDecimal() {
		return nbDecimal;
	}

	public void setNbDecimal(Integer nbDecimal) {
		firePropertyChange("nbDecimal", this.nbDecimal, this.nbDecimal = nbDecimal);
	}

	public String getCodeUnite2() {
		return codeUnite2;
	}

	public void setCodeUnite2(String codeUnite2) {
		firePropertyChange("codeUnite2", this.codeUnite2, this.codeUnite2 = codeUnite2);
	}

	
	public SWTRapportUnite getSwtRapportUnite() {
		return swtRapportUnite;
	}

	public void setSwtRapportUnite(SWTRapportUnite swtRapportUnite) {
		this.swtRapportUnite = swtRapportUnite;
	}

	public ArrayList<SWTRapportUnite> getListeRapportUnite() {
		return listeRapportUnite;
	}

	public void setListeRapportUnite(ArrayList<SWTRapportUnite> listeRapportUnite) {
		this.listeRapportUnite = listeRapportUnite;
	}

	public Boolean getActif() {
		return actif;
	}

	public void setActif(Boolean actif) {
		firePropertyChange("actif", this.actif, this.actif = actif);
	}

	public Boolean getSens() {
		return sens;
	}

	public void setSens(Boolean sens) {
		firePropertyChange("sens", this.sens, this.sens = sens);
	}

	public BigDecimal getLongueur() {
		return longueur;
	}

	public void setLongueur(BigDecimal longueur) {
		firePropertyChange("longueur", this.longueur, this.longueur = longueur);
	}

	public BigDecimal getLargeur() {
		return largeur;
	}

	public void setLargeur(BigDecimal largeur) {
		firePropertyChange("largeur", this.largeur, this.largeur = largeur);
	}

	public BigDecimal getHauteur() {
		return hauteur;
	}

	public void setHauteur(BigDecimal hauteur) {
		firePropertyChange("hauteur", this.hauteur, this.hauteur = hauteur);
	}

	public BigDecimal getPoids() {
		return poids;
	}

	public void setPoids(BigDecimal poids) {
		firePropertyChange("poids", this.poids, this.poids = poids);
	}

	public String getCommentaireArticle() {
		return commentaireArticle;
	}

	public void setCommentaireArticle(String commentaireArticle) {
		firePropertyChange("commentaireArticle", this.commentaireArticle, this.commentaireArticle = commentaireArticle);
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((actif == null) ? 0 : actif.hashCode());
		result = prime * result
				+ ((codeArticle == null) ? 0 : codeArticle.hashCode());
		result = prime * result
				+ ((codeFamille == null) ? 0 : codeFamille.hashCode());
		result = prime * result
				+ ((codeTTva == null) ? 0 : codeTTva.hashCode());
		result = prime
				* result
				+ ((codeTitreTransport == null) ? 0 : codeTitreTransport
						.hashCode());
		result = prime * result + ((codeTva == null) ? 0 : codeTva.hashCode());
		result = prime * result
				+ ((codeUnite == null) ? 0 : codeUnite.hashCode());
		result = prime * result
				+ ((codeUnite2 == null) ? 0 : codeUnite2.hashCode());
		result = prime
				* result
				+ ((commentaireArticle == null) ? 0 : commentaireArticle
						.hashCode());
		result = prime * result
				+ ((diversArticle == null) ? 0 : diversArticle.hashCode());
		result = prime * result + ((hauteur == null) ? 0 : hauteur.hashCode());
		result = prime * result
				+ ((idArticle == null) ? 0 : idArticle.hashCode());
		result = prime * result
				+ ((idFamille == null) ? 0 : idFamille.hashCode());
		result = prime * result + ((idPrix == null) ? 0 : idPrix.hashCode());
		result = prime * result
				+ ((idRapportUnite == null) ? 0 : idRapportUnite.hashCode());
		result = prime * result + ((idTTva == null) ? 0 : idTTva.hashCode());
		result = prime * result + ((idTva == null) ? 0 : idTva.hashCode());
		result = prime * result + ((idUnite == null) ? 0 : idUnite.hashCode());
		result = prime * result
				+ ((idUnite2 == null) ? 0 : idUnite2.hashCode());
		result = prime * result + ((largeur == null) ? 0 : largeur.hashCode());
		result = prime * result + ((libTTva == null) ? 0 : libTTva.hashCode());
		result = prime * result
				+ ((libcFamille == null) ? 0 : libcFamille.hashCode());
		result = prime * result
				+ ((libellecArticle == null) ? 0 : libellecArticle.hashCode());
		result = prime * result
				+ ((libellelArticle == null) ? 0 : libellelArticle.hashCode());
		result = prime * result
				+ ((listePrix == null) ? 0 : listePrix.hashCode());
		result = prime
				* result
				+ ((listeRapportUnite == null) ? 0 : listeRapportUnite
						.hashCode());
		result = prime * result
				+ ((longueur == null) ? 0 : longueur.hashCode());
		result = prime * result
				+ ((nbDecimal == null) ? 0 : nbDecimal.hashCode());
		result = prime * result
				+ ((numcptArticle == null) ? 0 : numcptArticle.hashCode());
		result = prime * result
				+ ((numcptTva == null) ? 0 : numcptTva.hashCode());
		result = prime * result + ((poids == null) ? 0 : poids.hashCode());
		result = prime * result
				+ ((prixPrix == null) ? 0 : prixPrix.hashCode());
		result = prime * result
				+ ((prixttcPrix == null) ? 0 : prixttcPrix.hashCode());
		result = prime
				* result
				+ ((qteTitreTransport == null) ? 0 : qteTitreTransport
						.hashCode());
		result = prime * result + ((rapport == null) ? 0 : rapport.hashCode());
		result = prime * result + ((sens == null) ? 0 : sens.hashCode());
		result = prime * result
				+ ((stockMinArticle == null) ? 0 : stockMinArticle.hashCode());
		result = prime * result + ((swtPrix == null) ? 0 : swtPrix.hashCode());
		result = prime * result
				+ ((swtRapportUnite == null) ? 0 : swtRapportUnite.hashCode());
		result = prime * result
				+ ((swtRefPrix == null) ? 0 : swtRefPrix.hashCode());
		result = prime * result
				+ ((swtUnite == null) ? 0 : swtUnite.hashCode());
		result = prime * result + ((tauxTva == null) ? 0 : tauxTva.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		SWTArticle other = (SWTArticle) obj;
		if (actif == null) {
			if (other.actif != null)
				return false;
		} else if (!actif.equals(other.actif))
			return false;
		if (codeArticle == null) {
			if (other.codeArticle != null)
				return false;
		} else if (!codeArticle.equals(other.codeArticle))
			return false;
		if (codeFamille == null) {
			if (other.codeFamille != null)
				return false;
		} else if (!codeFamille.equals(other.codeFamille))
			return false;
		if (codeTTva == null) {
			if (other.codeTTva != null)
				return false;
		} else if (!codeTTva.equals(other.codeTTva))
			return false;
		if (codeTitreTransport == null) {
			if (other.codeTitreTransport != null)
				return false;
		} else if (!codeTitreTransport.equals(other.codeTitreTransport))
			return false;
		if (codeTva == null) {
			if (other.codeTva != null)
				return false;
		} else if (!codeTva.equals(other.codeTva))
			return false;
		if (codeUnite == null) {
			if (other.codeUnite != null)
				return false;
		} else if (!codeUnite.equals(other.codeUnite))
			return false;
		if (codeUnite2 == null) {
			if (other.codeUnite2 != null)
				return false;
		} else if (!codeUnite2.equals(other.codeUnite2))
			return false;
		if (commentaireArticle == null) {
			if (other.commentaireArticle != null)
				return false;
		} else if (!commentaireArticle.equals(other.commentaireArticle))
			return false;
		if (diversArticle == null) {
			if (other.diversArticle != null)
				return false;
		} else if (!diversArticle.equals(other.diversArticle))
			return false;
		if (hauteur == null) {
			if (other.hauteur != null)
				return false;
		} else if (!hauteur.equals(other.hauteur))
			return false;
		if (idArticle == null) {
			if (other.idArticle != null)
				return false;
		} else if (!idArticle.equals(other.idArticle))
			return false;
		if (idFamille == null) {
			if (other.idFamille != null)
				return false;
		} else if (!idFamille.equals(other.idFamille))
			return false;
		if (idPrix == null) {
			if (other.idPrix != null)
				return false;
		} else if (!idPrix.equals(other.idPrix))
			return false;
		if (idRapportUnite == null) {
			if (other.idRapportUnite != null)
				return false;
		} else if (!idRapportUnite.equals(other.idRapportUnite))
			return false;
		if (idTTva == null) {
			if (other.idTTva != null)
				return false;
		} else if (!idTTva.equals(other.idTTva))
			return false;
		if (idTva == null) {
			if (other.idTva != null)
				return false;
		} else if (!idTva.equals(other.idTva))
			return false;
		if (idUnite == null) {
			if (other.idUnite != null)
				return false;
		} else if (!idUnite.equals(other.idUnite))
			return false;
		if (idUnite2 == null) {
			if (other.idUnite2 != null)
				return false;
		} else if (!idUnite2.equals(other.idUnite2))
			return false;
		if (largeur == null) {
			if (other.largeur != null)
				return false;
		} else if (!largeur.equals(other.largeur))
			return false;
		if (libTTva == null) {
			if (other.libTTva != null)
				return false;
		} else if (!libTTva.equals(other.libTTva))
			return false;
		if (libcFamille == null) {
			if (other.libcFamille != null)
				return false;
		} else if (!libcFamille.equals(other.libcFamille))
			return false;
		if (libellecArticle == null) {
			if (other.libellecArticle != null)
				return false;
		} else if (!libellecArticle.equals(other.libellecArticle))
			return false;
		if (libellelArticle == null) {
			if (other.libellelArticle != null)
				return false;
		} else if (!libellelArticle.equals(other.libellelArticle))
			return false;
		if (listePrix == null) {
			if (other.listePrix != null)
				return false;
		} else if (!listePrix.equals(other.listePrix))
			return false;
		if (listeRapportUnite == null) {
			if (other.listeRapportUnite != null)
				return false;
		} else if (!listeRapportUnite.equals(other.listeRapportUnite))
			return false;
		if (longueur == null) {
			if (other.longueur != null)
				return false;
		} else if (!longueur.equals(other.longueur))
			return false;
		if (nbDecimal == null) {
			if (other.nbDecimal != null)
				return false;
		} else if (!nbDecimal.equals(other.nbDecimal))
			return false;
		if (numcptArticle == null) {
			if (other.numcptArticle != null)
				return false;
		} else if (!numcptArticle.equals(other.numcptArticle))
			return false;
		if (numcptTva == null) {
			if (other.numcptTva != null)
				return false;
		} else if (!numcptTva.equals(other.numcptTva))
			return false;
		if (poids == null) {
			if (other.poids != null)
				return false;
		} else if (!poids.equals(other.poids))
			return false;
		if (prixPrix == null) {
			if (other.prixPrix != null)
				return false;
		} else if (!prixPrix.equals(other.prixPrix))
			return false;
		if (prixttcPrix == null) {
			if (other.prixttcPrix != null)
				return false;
		} else if (!prixttcPrix.equals(other.prixttcPrix))
			return false;
		if (qteTitreTransport == null) {
			if (other.qteTitreTransport != null)
				return false;
		} else if (!qteTitreTransport.equals(other.qteTitreTransport))
			return false;
		if (rapport == null) {
			if (other.rapport != null)
				return false;
		} else if (!rapport.equals(other.rapport))
			return false;
		if (sens == null) {
			if (other.sens != null)
				return false;
		} else if (!sens.equals(other.sens))
			return false;
		if (stockMinArticle == null) {
			if (other.stockMinArticle != null)
				return false;
		} else if (!stockMinArticle.equals(other.stockMinArticle))
			return false;
		if (swtPrix == null) {
			if (other.swtPrix != null)
				return false;
		} else if (!swtPrix.equals(other.swtPrix))
			return false;
		if (swtRapportUnite == null) {
			if (other.swtRapportUnite != null)
				return false;
		} else if (!swtRapportUnite.equals(other.swtRapportUnite))
			return false;
		if (swtRefPrix == null) {
			if (other.swtRefPrix != null)
				return false;
		} else if (!swtRefPrix.equals(other.swtRefPrix))
			return false;
		if (swtUnite == null) {
			if (other.swtUnite != null)
				return false;
		} else if (!swtUnite.equals(other.swtUnite))
			return false;
		if (tauxTva == null) {
			if (other.tauxTva != null)
				return false;
		} else if (!tauxTva.equals(other.tauxTva))
			return false;
		return true;
	}


}
