package fr.legrain.gestCom.Module_Articles;

// Generated Mar 1, 2007 11:26:10 AM by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;

import fr.legrain.lib.data.ModelObject;

/**
 * SWTRefPrix generated by hbm2java
 */
public class SWTRefPrix extends ModelObject {

	private Integer idRefPrix;
	private Integer idArticle;
	private Integer idPrix;
	private String codeArticle;
	private BigDecimal prixPrix;
	private BigDecimal prixttcPrix;

	public SWTRefPrix() {
	}

	public SWTRefPrix(Integer ID_REF_PRIX, Integer ID_ARTICLE,
			Integer ID_PRIX, String CODE_ARTICLE, BigDecimal PRIX_PRIX,
			BigDecimal PRIXTTC_PRIX) {
		this.idRefPrix = ID_REF_PRIX;
		this.idArticle = ID_ARTICLE;
		this.idPrix = ID_PRIX;
		this.codeArticle = CODE_ARTICLE;
		this.prixPrix = PRIX_PRIX;
		this.prixttcPrix = PRIXTTC_PRIX;
	}
	
	public void setSWTRefPrix(SWTRefPrix swtRefPrix) {
		this.idRefPrix = swtRefPrix.idRefPrix;
		this.idArticle = swtRefPrix.idArticle;
		this.idPrix = swtRefPrix.idPrix;
		this.codeArticle = swtRefPrix.codeArticle;
		this.prixPrix = swtRefPrix.prixPrix;
		this.prixttcPrix = swtRefPrix.prixttcPrix;
	}
	
	public static SWTRefPrix copy(SWTRefPrix swtRefPrix){
		SWTRefPrix swtRefPrixLoc = new SWTRefPrix();
		swtRefPrixLoc.setIdRefPrix(swtRefPrix.idRefPrix);
		swtRefPrixLoc.setIdArticle(swtRefPrix.idArticle);
		swtRefPrixLoc.setIdPrix(swtRefPrix.idPrix);
		swtRefPrixLoc.setCodeArticle(swtRefPrix.codeArticle);
		swtRefPrixLoc.setPrixPrix(swtRefPrix.prixPrix);
		swtRefPrixLoc.setPrixttcPrix(swtRefPrix.prixttcPrix);
		return swtRefPrixLoc;
	}

	public Integer getIdRefPrix() {
		return this.idRefPrix;
	}

	public void setIdRefPrix(Integer ID_REF_PRIX) {
		firePropertyChange("idRefPrix", this.idRefPrix, this.idRefPrix = ID_REF_PRIX);
	}

	public Integer getIdArticle() {
		return this.idArticle;
	}

	public void setIdArticle(Integer ID_ARTICLE) {
		firePropertyChange("idArticle", this.idArticle, this.idArticle = ID_ARTICLE);
	}

	public Integer getIdPrix() {
		return this.idPrix;
	}

	public void setIdPrix(Integer ID_PRIX) {
		firePropertyChange("idPrix", this.idPrix, this.idPrix = ID_PRIX);
	}

	public String getCodeArticle() {
		return this.codeArticle;
	}

	public void setCodeArticle(String CODE_ARTICLE) {
		firePropertyChange("codeArticle", this.codeArticle, this.codeArticle = CODE_ARTICLE);
	}

	public BigDecimal getPrixPrix() {
		return this.prixPrix;
	}

	public void setPrixPrix(BigDecimal PRIX_PRIX) {
		firePropertyChange("prixPrix", this.prixPrix, this.prixPrix = PRIX_PRIX);
	}

	public BigDecimal getPrixttcPrix() {
		return this.prixttcPrix;
	}

	public void setPrixttcPrix(BigDecimal PRIXTTC_PRIX) {
		firePropertyChange("prixttcPrix", this.prixttcPrix, this.prixttcPrix = PRIXTTC_PRIX);
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SWTRefPrix))
			return false;
		SWTRefPrix castOther = (SWTRefPrix) other;

		return ((this.getIdRefPrix() == castOther.getIdRefPrix()) || (this
				.getIdRefPrix() != null
				&& castOther.getIdRefPrix() != null && this.getIdRefPrix()
				.equals(castOther.getIdRefPrix())))
				&& ((this.getIdArticle() == castOther.getIdArticle()) || (this
						.getIdArticle() != null
						&& castOther.getIdArticle() != null && this
						.getIdArticle().equals(castOther.getIdArticle())))
				&& ((this.getIdPrix() == castOther.getIdPrix()) || (this
						.getIdPrix() != null
						&& castOther.getIdPrix() != null && this.getIdPrix()
						.equals(castOther.getIdPrix())))
				&& ((this.getCodeArticle() == castOther.getCodeArticle()) || (this
						.getCodeArticle() != null
						&& castOther.getCodeArticle() != null && this
						.getCodeArticle().equals(castOther.getCodeArticle())))
				&& ((this.getPrixPrix() == castOther.getPrixPrix()) || (this
						.getPrixPrix() != null
						&& castOther.getPrixPrix() != null && this
						.getPrixPrix().equals(castOther.getPrixPrix())))
				&& ((this.getPrixttcPrix() == castOther.getPrixttcPrix()) || (this
						.getPrixttcPrix() != null
						&& castOther.getPrixttcPrix() != null && this
						.getPrixttcPrix().equals(castOther.getPrixttcPrix())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getIdRefPrix() == null ? 0 : this.getIdRefPrix()
						.hashCode());
		result = 37
				* result
				+ (getIdArticle() == null ? 0 : this.getIdArticle()
						.hashCode());
		result = 37 * result
				+ (getIdPrix() == null ? 0 : this.getIdPrix().hashCode());
		result = 37
				* result
				+ (getCodeArticle() == null ? 0 : this.getCodeArticle()
						.hashCode());
		result = 37 * result
				+ (getPrixPrix() == null ? 0 : this.getPrixPrix().hashCode());
		result = 37
				* result
				+ (getPrixttcPrix() == null ? 0 : this.getPrixttcPrix()
						.hashCode());
		return result;
	}

}
