package fr.legrain.supportAbonnement.model;

// Generated 11 août 2009 15:52:23 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.OrderBy;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.Version;

import fr.legrain.abonnement.model.TaAbonnementOld;
import fr.legrain.article.model.TaArticle;
import fr.legrain.article.model.TaTSupport;
import fr.legrain.document.model.TaLFacture;
import fr.legrain.tiers.model.TaTiers;
import fr.legrain.validator.LgrHibernateValidated;


/**
 * TaWlgr generated by hbm2java
 */
@Entity
@Inheritance(strategy=InheritanceType.JOINED)
//@DiscriminatorColumn(name="type_support_abon")
@Table(name = "ta_support_abon")
//@SequenceGenerator(name = "gen_support_abon", sequenceName = "num_id_support_abon", allocationSize = 1)

public  class TaSupportAbon implements java.io.Serializable {

	private static final long serialVersionUID = -2121115265050158358L;

	public static final String TYPE_DOC = "fr.legrain.licence";

	private Integer idSupportAbon;
	private String codeSupportAbon;
    private Date dateAcquisition;
    private TaArticle taArticle;
    private TaTiers taTiers;
    private String commentaire;
    private String libelle;
    private TaTiers commercial;
    private TaLFacture taLDocument;
    private TaTSupport taTSupport;
    private Integer inactif=0;
	private Integer versionObj;
    @Transient
    private String className;
    
    private Set<TaROptionAbon> taROptionAbons = new HashSet<TaROptionAbon>(0);
    private Set<TaAbonnementOld> taAbonnements = new HashSet<TaAbonnementOld>(0);

	
	public TaSupportAbon() {
		
	}

	public TaSupportAbon(Integer idSupportAbon) {
		this.idSupportAbon = idSupportAbon;
	}


	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id_support_abon", unique = true)
	public Integer getIdSupportAbon() {
		return this.idSupportAbon;
	}

	public void setIdSupportAbon(Integer idSupportAbon) {
		this.idSupportAbon = idSupportAbon;
	}

	@Column(name = "code_support_abon")
	@LgrHibernateValidated(champBd = "code_support_abon",table = "ta_support_abon", champEntite="codeSupportAbon", clazz = TaSupportAbon.class)
	public String getCodeSupportAbon() {
		return this.codeSupportAbon;
	}

	public void setCodeSupportAbon(String codeSupportAbon) {
		this.codeSupportAbon = codeSupportAbon;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_acquisition", length = 10)
	public Date getDateAcquisition() {
		return dateAcquisition;
	}


	public void setDateAcquisition(Date dateAcquisition) {
		this.dateAcquisition = dateAcquisition;
	}
	
	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.REFRESH)
	@JoinColumn(name = "id_article")
	@LgrHibernateValidated(champBd = "id_article",table = "ta_article", champEntite="taArticle.idArticle", clazz = TaArticle.class)
	public TaArticle getTaArticle() {
		return taArticle;
	}

	public void setTaArticle(TaArticle taArticle) {
		this.taArticle = taArticle;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.REFRESH)
	@JoinColumn(name = "id_tiers")
	@LgrHibernateValidated(champBd = "id_tiers",table = "ta_tiers", champEntite="taTiers.idTiers", clazz = TaTiers.class)
	public TaTiers getTaTiers() {
		return taTiers;
	}

	public void setTaTiers(TaTiers taTiers) {
		this.taTiers = taTiers;
	}

	@Column(name = "commentaire")
	@LgrHibernateValidated(champBd = "commentaire",table = "ta_support_abon",champEntite="commentaire", clazz = TaSupportAbon.class)
	public String getCommentaire() {
		return commentaire;
	}

	public void setCommentaire(String commentaire) {
		this.commentaire = commentaire;
	}

	@Column(name = "libelle")
	@LgrHibernateValidated(champBd = "libelle",table = "ta_support_abon",champEntite="libelle", clazz = TaSupportAbon.class)
	public String getLibelle() {
		return libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.REFRESH)
	@JoinColumn(name = "commercial")
	@LgrHibernateValidated(champBd = "id_tiers",table = "ta_tiers", champEntite="taTiers.idTiers", clazz = TaTiers.class)
	public TaTiers getCommercial() {
		return commercial;
	}

	public void setCommercial(TaTiers commercial) {
		this.commercial = commercial;
	}


	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_l_document")
	@LgrHibernateValidated(champBd = "id_l_document",table = "ta_l_facture", champEntite="taLDocument.idLDocument", clazz = TaLFacture.class)
	public TaLFacture getTaLDocument() {
		return this.taLDocument;
	}

	public void setTaLDocument(TaLFacture taLDocument) {
		this.taLDocument = taLDocument;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "taSupportAbon")
	@OrderBy(value = "dateDebut ASC")
	public Set<TaAbonnementOld> getTaAbonnements() {
		return this.taAbonnements;
	}

	public void setTaAbonnements(Set<TaAbonnementOld> taAbonnements) {
		this.taAbonnements = taAbonnements;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "taSupportAbon")
	public Set<TaROptionAbon> getTaROptionAbons() {
		return this.taROptionAbons;
	}

	public void setTaROptionAbons(Set<TaROptionAbon> taROptionAbons) {
		this.taROptionAbons = taROptionAbons;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_t_support")
	@LgrHibernateValidated(champBd = "id_t_support",table = "ta_t_support", champEntite="taTSupport.idTSupport", clazz = TaTSupport.class)
	public TaTSupport getTaTSupport() {
		return taTSupport;
	}

	public void setTaTSupport(TaTSupport taTSupport) {
		this.taTSupport = taTSupport;
	}

	@Column(name = "inactif")
	@LgrHibernateValidated(champBd = "inactif",table = "ta_support_abon", champEntite="inactif", clazz = TaSupportAbon.class)
	public Integer getInactif() {
		return inactif;
	}

	public void setInactif(Integer inactif) {
		this.inactif = inactif;
	}

	@Transient
	public String getClassName() {
		return className;
	}
	
	@Transient
	public void setClassName(String className) {
		this.className = className;
	}
	
	@Version
	@Column(name = "version_obj", precision = 15)
	public Integer getVersionObj() {
		return this.versionObj;
	}

	public void setVersionObj(Integer versionObj) {
		this.versionObj = versionObj;
	}
}
