package fr.legrain.articles.dao;

// Generated Sep 1, 2008 3:06:27 PM by Hibernate Tools 3.2.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import fr.legrain.validator.LgrHibernateValidated;

/**
 * TaPrix generated by hbm2java
 */
@Entity
//@Cache(usage=CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "TA_CATEGORIE_ARTICLE")
@SequenceGenerator(name = "GEN_CATEGORIE_ARTICLE", sequenceName = "NUM_ID_CATEGORIE_ARTICLE", allocationSize = 1)
@NamedQueries(value = { 
		@NamedQuery(name=TaCategorieArticle.QN.FIND_BY_PARENT, query="select a from TaCategorieArticle a where a.categorieMereArticle.codeCategorieArticle = ?"),
		@NamedQuery(name=TaCategorieArticle.QN.FIND_CATEGORIE_MERE, query="select a from TaCategorieArticle a where a.categorieMereArticle is null"),
		@NamedQuery(name=TaCategorieArticle.QN.FIND_BY_NEW_OR_UPDATED_AFTER, query="select a from TaCategorieArticle a where a.quandCree >= ? or a.quandModif >= ?")
		})
public class TaCategorieArticle implements java.io.Serializable {
	
	public static class QN {
		public static final String FIND_BY_PARENT = "TaCategorieArticle.findByParent";
		public static final String FIND_CATEGORIE_MERE = "TaCategorieArticle.findCategorieMere";
		public static final String FIND_BY_NEW_OR_UPDATED_AFTER = "TaCategorieArticle.findByNewOrUpdatedAfter";
	}

	private int idCategorieArticle;
	private String version;
	private TaCategorieArticle categorieMereArticle;
	private String codeCategorieArticle;
	private String libelleCategorieArticle;
	private String desciptionCategorieArticle;
	private String urlRewritingCategorieArticle;
	private String cheminImageCategorieArticle;
	private String nomImageCategorieArticle;
	private String quiCreeCategorieArticle;
	private Date quandCreeCategorieArticle;
	private String quiModifCategorieArticle;
	private Date quandModifCategorieArticle;
	private String ipAcces;
	private Integer versionObj;
	

	public TaCategorieArticle() {
	}

	public TaCategorieArticle(int idCategorieArticle) {
		this.idCategorieArticle = idCategorieArticle;
	}

	public TaCategorieArticle(int idCategorieArticle, String version,
			TaCategorieArticle categorieMereArticle, String codeCategorieArticle,
			String libelleCategorieArticle, String desciptionCategorieArticle,
			String urlRewritingCategorieArticle,String cheminImageArticle, String nomImageArticle,
			String quiCreeImageArticle, Date quandCreeImageArticle,
			String quiModifImageArticle, Date quandModifImageArticle,
			String ipAcces, Integer versionObj) {
		super();
		this.idCategorieArticle = idCategorieArticle;
		this.version = version;
		this.categorieMereArticle = categorieMereArticle;
		this.codeCategorieArticle = codeCategorieArticle;
		this.libelleCategorieArticle = libelleCategorieArticle;
		this.desciptionCategorieArticle = desciptionCategorieArticle;
		this.urlRewritingCategorieArticle = urlRewritingCategorieArticle;
		this.cheminImageCategorieArticle = cheminImageArticle;
		this.nomImageCategorieArticle = nomImageArticle;
		this.quiCreeCategorieArticle = quiCreeImageArticle;
		this.quandCreeCategorieArticle = quandCreeImageArticle;
		this.quiModifCategorieArticle = quiModifImageArticle;
		this.quandModifCategorieArticle = quandModifImageArticle;
		this.ipAcces = ipAcces;
		this.versionObj = versionObj;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "GEN_CATEGORIE_ARTICLE")
	@Column(name = "ID_CATEGORIE_ARTICLE", unique = true, nullable = false)
	@LgrHibernateValidated(champEntite = "", champBd = "ID_CATEGORIE_ARTICLE",table = "TA_CATEGORIE_ARTICLE",clazz = TaCategorieArticle.class)
	public int getIdCategorieArticle() {
		return this.idCategorieArticle;
	}

	public void setIdCategorieArticle(int idCategorieArticle) {
		this.idCategorieArticle = idCategorieArticle;
	}

	@Column(name = "VERSION", length = 20)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}
	
	@Version
	@Column(name = "VERSION_OBJ", precision = 15)
	public Integer getVersionObj() {
		return this.versionObj;
	}

	public void setVersionObj(Integer versionObj) {
		this.versionObj = versionObj;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PARENT_CATEGORIE_ARTICLE")
	@LgrHibernateValidated(champEntite = "", champBd = "ID_PARENT_CATEGORIE_ARTICLE",table = "TA_CATEGORIE_ARTICLE",clazz = TaCategorieArticle.class)
	public TaCategorieArticle getCategorieMereArticle() {
		return this.categorieMereArticle;
	}

	public void setCategorieMereArticle(TaCategorieArticle taCategorieArticle) {
		this.categorieMereArticle = taCategorieArticle;
	}

	@Column(name = "CODE_CATEGORIE_ARTICLE", precision = 15)
	@LgrHibernateValidated(champEntite = "", champBd = "CODE_CATEGORIE_ARTICLE",table = "TA_CATEGORIE_ARTICLE",clazz = TaCategorieArticle.class)
	public String getCodeCategorieArticle() {
		return this.codeCategorieArticle;
	}

	public void setCodeCategorieArticle(String codeCategorieArticle) {
		this.codeCategorieArticle = codeCategorieArticle;
	}
	
	@Column(name = "LIBELLE_CATEGORIE_ARTICLE", precision = 15)
	@LgrHibernateValidated(champEntite = "", champBd = "LIBELLE_CATEGORIE_ARTICLE",table = "TA_CATEGORIE_ARTICLE",clazz = TaCategorieArticle.class)
	public String getLibelleCategorieArticle() {
		return this.libelleCategorieArticle;
	}

	public void setLibelleCategorieArticle(String libelleCategorieArticle) {
		this.libelleCategorieArticle = libelleCategorieArticle;
	}
	
	@Column(name = "DESCRIPTION_CATEGORIE_ARTICLE", precision = 15)
	@LgrHibernateValidated(champEntite = "", champBd = "DESCRIPTION_CATEGORIE_ARTICLE",table = "TA_CATEGORIE_ARTICLE",clazz = TaCategorieArticle.class)
	public String getDesciptionCategorieArticle() {
		return this.desciptionCategorieArticle;
	}

	public void setDesciptionCategorieArticle(String desciptionCategorieArticle) {
		this.desciptionCategorieArticle = desciptionCategorieArticle;
	}
	
	@Column(name = "URL_REWRITING_CATEGORIE_ARTICLE", precision = 15)
	@LgrHibernateValidated(champEntite = "", champBd = "URL_REWRITING_CATEGORIE_ARTICLE",table = "TA_CATEGORIE_ARTICLE",clazz = TaCategorieArticle.class)
	public String getUrlRewritingCategorieArticle() {
		return this.urlRewritingCategorieArticle;
	}

	public void setUrlRewritingCategorieArticle(String urlRewritingCategorieArticle) {
		this.urlRewritingCategorieArticle = urlRewritingCategorieArticle;
	}

	@Column(name = "CHEMIN_IMAGE_CATEGORIE_ARTICLE", precision = 15)
	@LgrHibernateValidated(champEntite = "", champBd = "CHEMIN_IMAGE_CATEGORIE_ARTICLE",table = "TA_CATEGORIE_ARTICLE",clazz = TaCategorieArticle.class)
	public String getCheminImageCategorieArticle() {
		return cheminImageCategorieArticle;
	}

	public void setCheminImageCategorieArticle(String cheminImageArticle) {
		this.cheminImageCategorieArticle = cheminImageArticle;
	}

	@Column(name = "NOM_IMAGE_CATEGORIE_ARTICLE", precision = 15)
	@LgrHibernateValidated(champEntite = "", champBd = "NOM_IMAGE_CATEGORIE_ARTICLE",table = "TA_CATEGORIE_ARTICLE",clazz = TaCategorieArticle.class)
	public String getNomImageCategorieArticle() {
		return nomImageCategorieArticle;
	}

	public void setNomImageCategorieArticle(String nomImageArticle) {
		this.nomImageCategorieArticle = nomImageArticle;
	}

	@Column(name = "QUI_CREE_CATEGORIE_ARTICLE", length = 50)
	public String getQuiCreeCategorieArticle() {
		return this.quiCreeCategorieArticle;
	}

	public void setQuiCreeCategorieArticle(String quiCreeCategorieArticle) {
		this.quiCreeCategorieArticle = quiCreeCategorieArticle;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "QUAND_CREE_CATEGORIE_ARTICLE", length = 19)
	public Date getQuandCreeCategorieArticle() {
		return this.quandCreeCategorieArticle;
	}

	public void setQuandCreeCategorieArticle(Date quandCreeCategorieArticle) {
		this.quandCreeCategorieArticle = quandCreeCategorieArticle;
	}

	@Column(name = "QUI_MODIF_CATEGORIE_ARTICLE", length = 50)
	public String getQuiModifCategorieArticle() {
		return this.quiModifCategorieArticle;
	}

	public void setQuiModifCategorieArticle(String quiModifCategorieArticle) {
		this.quiModifCategorieArticle = quiModifCategorieArticle;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "QUAND_MODIF_CATEGORIE_ARTICLE", length = 19)
	public Date getQuandModifCategorieArticle() {
		return this.quandModifCategorieArticle;
	}

	public void setQuandModifCategorieArticle(Date quandModifCategorieArticle) {
		this.quandModifCategorieArticle = quandModifCategorieArticle;
	}

	@Column(name = "IP_ACCES", length = 50)
	public String getIpAcces() {
		return this.ipAcces;
	}

	public void setIpAcces(String ipAcces) {
		this.ipAcces = ipAcces;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + idCategorieArticle;
		result = prime * result
				+ ((codeCategorieArticle == null) ? 0 : codeCategorieArticle.hashCode());
		result = prime * result
				+ ((libelleCategorieArticle == null) ? 0 : libelleCategorieArticle.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final TaCategorieArticle other = (TaCategorieArticle) obj;
		if (idCategorieArticle != other.idCategorieArticle)
			return false;
		if (codeCategorieArticle == null) {
			if (other.codeCategorieArticle != null)
				return false;
		} else if (!codeCategorieArticle.equals(other.codeCategorieArticle))
			return false;
		if (ipAcces == null) {
			if (other.ipAcces != null)
				return false;
		} else if (!ipAcces.equals(other.ipAcces))
			return false;
		if (libelleCategorieArticle == null) {
			if (other.libelleCategorieArticle != null)
				return false;
		} else if (!libelleCategorieArticle.equals(other.libelleCategorieArticle))
			return false;
		return true;
	}

}
