package fr.legrain.articles.dao;

// Generated 11 août 2009 15:52:23 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import fr.legrain.articles.dao.TaArticle;
import fr.legrain.documents.dao.TaFacture;
import fr.legrain.documents.dao.TaLFacture;
import fr.legrain.validator.LgrHibernateValidated;
import fr.legrain.tiers.dao.TaTiers;


/**
 * TaWlgr generated by hbm2java
 */
@Entity
//@Cache(usage=CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "TA_R_T_SUPPORT")
@SequenceGenerator(name = "GEN_R_T_SUPPORT", sequenceName = "NUM_ID_R_T_SUPPORT", allocationSize = 1)

public class TaRTSupport implements java.io.Serializable {  
	private Integer idRTSupport;
    private TaArticle taArticle;
    private TaTSupport taTSupport;
    private TaTAbonnement taTAbonnement;
    private TaArticle taArticleAbonnement;


	
	public TaRTSupport() {
	}

	public TaRTSupport(Integer idRTArticle) {
		this.idRTSupport = idRTArticle;
	}


	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "GEN_R_T_SUPPORT")
	@Column(name = "ID_R_T_SUPPORT", unique = true)
	public Integer getIdRTSupport() {
		return this.idRTSupport;
	}

	public void setIdRTSupport(Integer idRTArticle) {
		this.idRTSupport = idRTArticle;
	}

		
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ARTICLE")
	@LgrHibernateValidated(champEntite = "", champBd = "ID_ARTICLE",table = "TA_ARTICLE",clazz = TaArticle.class)
	public TaArticle getTaArticle() {
		return this.taArticle;
	}

	public void setTaArticle(TaArticle taArticle) {
		this.taArticle = taArticle;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_T_SUPPORT")
	@LgrHibernateValidated(champEntite = "", champBd = "ID_T_SUPPORT",table = "TA_T_SUPPORT",clazz = TaTSupport.class)
	public TaTSupport getTaTSupport() {
		return this.taTSupport;
	}

	public void setTaTSupport(TaTSupport taTArticle) {
		this.taTSupport = taTArticle;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_T_ABONNEMENT")
	@LgrHibernateValidated(champEntite = "", champBd = "ID_T_ABONNEMENT",table = "TA_T_ABONNEMENT",clazz = TaTAbonnement.class)
	public TaTAbonnement getTaTAbonnement() {
		return taTAbonnement;
	}

	public void setTaTAbonnement(TaTAbonnement taTAbonnement) {
		this.taTAbonnement = taTAbonnement;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ARTICLE_ABONNEMENT")
	@LgrHibernateValidated(champEntite = "", champBd = "ID_ARTICLE",table = "TA_ARTICLE",clazz = TaArticle.class)
	public TaArticle getTaArticleAbonnement() {
		return taArticleAbonnement;
	}

	public void setTaArticleAbonnement(TaArticle taArticleAbonnement) {
		this.taArticleAbonnement = taArticleAbonnement;
	}
}
