package fr.legrain.articles.dao;

// Generated Mar 24, 2009 4:44:04 PM by Hibernate Tools 3.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import fr.legrain.validator.LgrHibernateValidated;

/**
 * TaTNote generated by hbm2java
 */
@Entity
//@Cache(usage=CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "TA_T_ABONNEMENT")
@SequenceGenerator(name = "GEN_T_ABONNEMENT", sequenceName = "NUM_ID_T_ABONNEMENT", allocationSize = 1)
public class TaTAbonnement implements java.io.Serializable {

	private int idTAbonnement;
	private String codeTAbonnement;
	private String types;
	private Integer duree;
	private String libelleType;
//	private Set<TaRTArticle> taRTArticles = new HashSet<TaRTArticle>(0);
	private Set<TaArticle> taArticles = new HashSet<TaArticle>(0);
	
	public TaTAbonnement() {
	}

	public TaTAbonnement(int idTArticle) {
		this.idTAbonnement = idTArticle;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "GEN_T_ABONNEMENT")
	@Column(name = "ID_T_ABONNEMENT", unique = true, nullable = false)
	@LgrHibernateValidated(champEntite = "", champBd = "ID_T_ABONNEMENT",table = "TA_T_ABONNEMENT",clazz = TaTAbonnement.class)
	public int getIdTAbonnement() {
		return this.idTAbonnement;
	}

	public void setIdTAbonnement(int idTArticle) {
		this.idTAbonnement = idTArticle;
	}


	@Column(name = "CODE_T_ABONNEMENT", length = 20)
	@LgrHibernateValidated(champEntite = "", champBd = "CODE_T_ABONNEMENT",table = "TA_T_ABONNEMENT",clazz = TaTAbonnement.class)
	public String getCodeTAbonnement() {
		return this.codeTAbonnement;
	}

	public void setCodeTAbonnement(String codeTSupport) {
		this.codeTAbonnement = codeTSupport;
	}

//	@ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "taTArticle")
//	public Set<TaRTArticle> getTaRTArticles() {
//		return this.taRTArticles;
//	}
//
//	public void setTaRTArticles(Set<TaRTArticle> taRTArticles) {
//		this.taRTArticles = taRTArticles;
//	}
	
	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "TA_R_T_ABONNEMENT",
			joinColumns = {@JoinColumn(name = "ID_T_ABONNEMENT")},inverseJoinColumns = {@JoinColumn(name = "ID_ARTICLE")})
	public Set<TaArticle> getTaArticles(){
		return this.taArticles;
	}

	public void setTaArticles(Set<TaArticle> taArticles) {
		this.taArticles = taArticles;
	}
	
	@Column(name = "TYPES", length = 1)
	@LgrHibernateValidated(champEntite = "", champBd = "TYPES",table = "TA_T_ABONNEMENT",clazz = TaTAbonnement.class)
	public String getTypes() {
		return types;
	}

	public void setTypes(String types) {
		this.types = types;
	}

	@Column(name = "DUREE")
	@LgrHibernateValidated(champEntite = "", champBd = "DUREE",table = "TA_T_ABONNEMENT",clazz = TaTAbonnement.class)
	public Integer getDuree() {
		return duree;
	}

	public void setDuree(Integer duree) {
		this.duree = duree;
	}

	@Column(name = "LIBELLE_TYPE", length = 100)
	@LgrHibernateValidated(champEntite = "", champBd = "LIBELLE_TYPE",table = "TA_T_ABONNEMENT",clazz = TaTAbonnement.class)
	public String getLibelleType() {
		return libelleType;
	}

	public void setLibelleType(String libelleType) {
		this.libelleType = libelleType;
	}
	
}
