package fr.legrain.tiers.dao;

// Generated Mar 24, 2009 4:44:04 PM by Hibernate Tools 3.2.0.CR1

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import fr.legrain.validator.LgrHibernateValidated;

/**
 * TaNote generated by hbm2java
 */
@Entity
//@Cache(usage=CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "TA_NOTE_TIERS")
@SequenceGenerator(name = "GEN_NOTE_TIERS", sequenceName = "NUM_ID_NOTE_TIERS", allocationSize = 1)
public class TaNoteTiers implements java.io.Serializable {

	private int idNoteTiers;
	private String version;
	private TaTNoteTiers taTNoteTiers;
	private TaTiers taTiers;
	private String noteTiers;
	private Date dateNoteTiers;
	private String quiCreeNote;
	private Date quandCreeNote;
	private String quiModifNote;
	private Date quandModifNote;
	private String ipAcces;
	private Integer versionObj;

	public TaNoteTiers() {
	}

	public TaNoteTiers(int idNote) {
		this.idNoteTiers = idNote;
	}

	public TaNoteTiers(int idNoteTiers, TaTNoteTiers taTNoteTiers, TaTiers taTiers, String noteTiers, Date dateNoteTiers,
			String quiCreeNote, Date quandCreeNote, String quiModifNote,
			Date quandModifNote, String ipAcces, Integer versionObj) {
		this.idNoteTiers = idNoteTiers;
		this.taTNoteTiers = taTNoteTiers;
		this.taTiers = taTiers;
		this.noteTiers = noteTiers;
		this.dateNoteTiers = dateNoteTiers;
		this.quiCreeNote = quiCreeNote;
		this.quandCreeNote = quandCreeNote;
		this.quiModifNote = quiModifNote;
		this.quandModifNote = quandModifNote;
		this.ipAcces = ipAcces;
		this.versionObj = versionObj;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "GEN_NOTE_TIERS")
	@Column(name = "ID_NOTE_TIERS", unique = true, nullable = false)
	@LgrHibernateValidated(champEntite = "", champBd = "ID_NOTE_TIERS",table = "TA_NOTE_TIERS",clazz = TaNoteTiers.class)
	public int getIdNoteTiers() {
		return this.idNoteTiers;
	}

	public void setIdNoteTiers(int idNoteTiers) {
		this.idNoteTiers = idNoteTiers;
	}

	@Column(name = "VERSION", length = 20)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = {CascadeType.PERSIST, CascadeType.MERGE, CascadeType.REFRESH})
	@JoinColumn(name = "ID_T_NOTE_TIERS")
	@LgrHibernateValidated(champEntite = "", champBd = "ID_T_NOTE_TIERS",table = "TA_T_NOTE_TIERS",clazz = TaTNoteTiers.class)
	public TaTNoteTiers getTaTNoteTiers() {
		return this.taTNoteTiers;
	}

	public void setTaTNoteTiers(TaTNoteTiers taTNoteTiers) {
		this.taTNoteTiers = taTNoteTiers;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = {CascadeType.PERSIST, CascadeType.MERGE})
	@JoinColumn(name = "ID_TIERS")
	@LgrHibernateValidated(champEntite = "", champBd = "ID_TIERS",table = "TA_TIERS",clazz = TaTiers.class)
	public TaTiers getTaTiers() {
		return this.taTiers;
	}

	public void setTaTiers(TaTiers taTiers) {
		this.taTiers = taTiers;
	}

	@Column(name = "NOTE_TIERS")
	@LgrHibernateValidated(champEntite = "", champBd = "NOTE_TIERS",table = "TA_NOTE_TIERS",clazz = TaNoteTiers.class)
	public String getNoteTiers() {
		return this.noteTiers;
	}

	public void setNoteTiers(String noteTiers) {
		this.noteTiers = noteTiers;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_NOTE_TIERS", length = 19)
	@LgrHibernateValidated(champEntite = "", champBd = "DATE_NOTE_TIERS",table = "TA_NOTE_TIERS",clazz = TaNoteTiers.class)
	public Date getDateNoteTiers() {
		return this.dateNoteTiers;
	}

	public void setDateNoteTiers(Date dateNoteTiers) {
		this.dateNoteTiers = dateNoteTiers;
	}

	@Column(name = "QUI_CREE_NOTE", length = 50)
	public String getQuiCreeNote() {
		return this.quiCreeNote;
	}

	public void setQuiCreeNote(String quiCreeNote) {
		this.quiCreeNote = quiCreeNote;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "QUAND_CREE_NOTE", length = 19)
	public Date getQuandCreeNote() {
		return this.quandCreeNote;
	}

	public void setQuandCreeNote(Date quandCreeNote) {
		this.quandCreeNote = quandCreeNote;
	}

	@Column(name = "QUI_MODIF_NOTE", length = 50)
	public String getQuiModifNote() {
		return this.quiModifNote;
	}

	public void setQuiModifNote(String quiModifNote) {
		this.quiModifNote = quiModifNote;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "QUAND_MODIF_NOTE", length = 19)
	public Date getQuandModifNote() {
		return this.quandModifNote;
	}

	public void setQuandModifNote(Date quandModifNote) {
		this.quandModifNote = quandModifNote;
	}

	@Column(name = "IP_ACCES", length = 50)
	public String getIpAcces() {
		return this.ipAcces;
	}

	public void setIpAcces(String ipAcces) {
		this.ipAcces = ipAcces;
	}

	@Version
	@Column(name = "VERSION_OBJ")
	public Integer getVersionObj() {
		return this.versionObj;
	}

	public void setVersionObj(Integer versionObj) {
		this.versionObj = versionObj;
	}

}
