package fr.legrain.tiers.dao;

// Generated Mar 24, 2009 4:44:04 PM by Hibernate Tools 3.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import fr.legrain.validator.LgrHibernateValidated;

/**
 * TaTCivilite generated by hbm2java
 */
@Entity
//@Cache(usage=CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "TA_T_CIVILITE")
@SequenceGenerator(name = "GEN_T_CIVILITE", sequenceName = "NUM_ID_T_CIVILITE", allocationSize = 1)
public class TaTCivilite implements java.io.Serializable {

	private int idTCivilite;
	private String version;
	private String codeTCivilite;
	private String quiCreeTCivilite;
	private Date quandCreeTCivilite;
	private String quiModifTCivilite;
	private Date quandModifTCivilite;
	private String ipAcces;
	private Integer versionObj;
	private Set<TaTiers> taTierses = new HashSet<TaTiers>(0);

	public TaTCivilite() {
	}

	public TaTCivilite(int idTCivilite) {
		this.idTCivilite = idTCivilite;
	}

	public TaTCivilite(int idTCivilite, String codeTCivilite,
			String quiCreeTCivilite, Date quandCreeTCivilite,
			String quiModifTCivilite, Date quandModifTCivilite, String ipAcces,
			Integer versionObj, Set<TaTiers> taTierses) {
		this.idTCivilite = idTCivilite;
		this.codeTCivilite = codeTCivilite;
		this.quiCreeTCivilite = quiCreeTCivilite;
		this.quandCreeTCivilite = quandCreeTCivilite;
		this.quiModifTCivilite = quiModifTCivilite;
		this.quandModifTCivilite = quandModifTCivilite;
		this.ipAcces = ipAcces;
		this.versionObj = versionObj;
		this.taTierses = taTierses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "GEN_T_CIVILITE")
	@Column(name = "ID_T_CIVILITE", unique = true, nullable = false)
	@LgrHibernateValidated(champEntite = "", champBd = "ID_T_CIVILITE",table = "TA_T_CIVILITE",clazz = TaTCivilite.class)
	public int getIdTCivilite() {
		return this.idTCivilite;
	}

	public void setIdTCivilite(int idTCivilite) {
		this.idTCivilite = idTCivilite;
	}

	
	@Column(name = "VERSION", length = 20)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@Column(name = "CODE_T_CIVILITE", length = 20)
	@LgrHibernateValidated(champEntite = "", champBd = "CODE_T_CIVILITE",table = "TA_T_CIVILITE",clazz = TaTCivilite.class)
	public String getCodeTCivilite() {
		return this.codeTCivilite;
	}

	public void setCodeTCivilite(String codeTCivilite) {
		this.codeTCivilite = codeTCivilite;
	}

	@Column(name = "QUI_CREE_T_CIVILITE", length = 50)
	public String getQuiCreeTCivilite() {
		return this.quiCreeTCivilite;
	}

	public void setQuiCreeTCivilite(String quiCreeTCivilite) {
		this.quiCreeTCivilite = quiCreeTCivilite;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "QUAND_CREE_T_CIVILITE", length = 19)
	public Date getQuandCreeTCivilite() {
		return this.quandCreeTCivilite;
	}

	public void setQuandCreeTCivilite(Date quandCreeTCivilite) {
		this.quandCreeTCivilite = quandCreeTCivilite;
	}

	@Column(name = "QUI_MODIF_T_CIVILITE", length = 50)
	public String getQuiModifTCivilite() {
		return this.quiModifTCivilite;
	}

	public void setQuiModifTCivilite(String quiModifTCivilite) {
		this.quiModifTCivilite = quiModifTCivilite;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "QUAND_MODIF_T_CIVILITE", length = 19)
	public Date getQuandModifTCivilite() {
		return this.quandModifTCivilite;
	}

	public void setQuandModifTCivilite(Date quandModifTCivilite) {
		this.quandModifTCivilite = quandModifTCivilite;
	}

	@Column(name = "IP_ACCES", length = 50)
	public String getIpAcces() {
		return this.ipAcces;
	}

	public void setIpAcces(String ipAcces) {
		this.ipAcces = ipAcces;
	}

	@Version
	@Column(name = "VERSION_OBJ")
	public Integer getVersionObj() {
		return this.versionObj;
	}

	public void setVersionObj(Integer versionObj) {
		this.versionObj = versionObj;
	}

	@OneToMany(cascade = {CascadeType.PERSIST, CascadeType.MERGE}, fetch = FetchType.LAZY, mappedBy = "taTCivilite")
	public Set<TaTiers> getTaTierses() {
		return this.taTierses;
	}

	public void setTaTierses(Set<TaTiers> taTierses) {
		this.taTierses = taTierses;
	}

}
