package fr.legrain.tiers.dao;

// Generated Mar 24, 2009 4:44:04 PM by Hibernate Tools 3.2.0.CR1

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import fr.legrain.documents.dao.TaAcompte;
import fr.legrain.documents.dao.TaApporteur;
import fr.legrain.documents.dao.TaAvisEcheance;
import fr.legrain.documents.dao.TaAvoir;
import fr.legrain.documents.dao.TaBoncde;
import fr.legrain.documents.dao.TaBonliv;
import fr.legrain.documents.dao.TaDevis;
import fr.legrain.documents.dao.TaFacture;
import fr.legrain.documents.dao.TaPrelevement;
import fr.legrain.documents.dao.TaProforma;
import fr.legrain.validator.LgrHibernateValidated;

/**
 * TaTTel generated by hbm2java
 */
@Entity
//@Cache(usage=CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "TA_T_C_PAIEMENT")
@SequenceGenerator(name = "GEN_T_C_PAIEMENT", sequenceName = "NUM_ID_T_C_PAIEMENT", allocationSize = 1)
public class TaTCPaiement implements java.io.Serializable {
	
	/*
	 * Table dont le contenu est géré manuellement, pas d'interface
	 * Les constantes suivantes doivent correspondrent au champ "CODE" de la table
	 */
	public static final String C_CODE_TYPE_TIERS 	= TaTiers.TYPE_DOC;//"T";
	public static final String C_CODE_TYPE_FACTURE 	= TaFacture.TYPE_DOC;//"F";
	public static final String C_CODE_TYPE_DEVIS 	= TaDevis.TYPE_DOC;//"D";
	public static final String C_CODE_TYPE_BON_COMMANDE = TaBoncde.TYPE_DOC;//"BC";
	public static final String C_CODE_TYPE_AVOIR = TaAvoir.TYPE_DOC;//"A";
	public static final String C_CODE_TYPE_APORTEUR = TaApporteur.TYPE_DOC;//"AP";
	public static final String C_CODE_TYPE_ACOMPTE = TaAcompte.TYPE_DOC;//"AC";
	public static final String C_CODE_TYPE_PROFORMA = TaProforma.TYPE_DOC;//"P";
	public static final String C_CODE_TYPE_PRELEVEMENT = TaPrelevement.TYPE_DOC;//"PR";
	public static final String C_CODE_TYPE_BON_LIVRAISON = TaBonliv.TYPE_DOC;//"BL";
	public static final String C_CODE_TYPE_AVIS_ECHEANCE = TaAvisEcheance.TYPE_DOC;//"BL";

	private int idTCPaiement;
	private String version;
	private String codeTCPaiement;
	private String liblTCPaiement;
	private TaCPaiement taCPaiement;
	private String quiCreeTCPaiement;
	private Date quandCreeTCPaiement;
	private String quiModifTCPaiement;
	private Date quandModifTCPaiement;
	private String ipAcces;
	private Integer versionObj;

	public TaTCPaiement() {
	}

	public TaTCPaiement(int idTCPaiement) {
		this.idTCPaiement = idTCPaiement;
	}

	public TaTCPaiement(int idTCPaiement, String codeTCPaiement, String liblTCPaiement,
			TaCPaiement taCPaiement,
			String quiCreeTCPaiement, Date quandCreeTCPaiement, String quiModifTTel,
			Date quandModifTTel, String ipAcces, Integer versionObj) {
		this.idTCPaiement = idTCPaiement;
		this.codeTCPaiement = codeTCPaiement;
		this.liblTCPaiement = liblTCPaiement;
		this.taCPaiement = taCPaiement;
		this.quiCreeTCPaiement = quiCreeTCPaiement;
		this.quandCreeTCPaiement = quandCreeTCPaiement;
		this.ipAcces = ipAcces;
		this.versionObj = versionObj;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "GEN_T_C_PAIEMENT")
	@Column(name = "ID_T_C_PAIEMENT", unique = true, nullable = false)
	@LgrHibernateValidated(champEntite = "", champBd = "ID_T_C_PAIEMENT",table = "TA_T_C_PAIEMENT",clazz = TaTCPaiement.class)
	public int getIdTCPaiement() {
		return this.idTCPaiement;
	}

	public void setIdTCPaiement(int idTCPaiement) {
		this.idTCPaiement = idTCPaiement;
	}

	@Column(name = "VERSION", length = 20)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@Column(name = "CODE_T_C_PAIEMENT", unique = true, length = 20)
	@LgrHibernateValidated(champEntite = "", champBd = "CODE_T_C_PAIEMENT",table = "TA_T_C_PAIEMENT",clazz = TaTCPaiement.class)
	public String getCodeTCPaiement() {
		return this.codeTCPaiement;
	}

	public void setCodeTCPaiement(String codeTCPaiement) {
		this.codeTCPaiement = codeTCPaiement;
	}

	@Column(name = "LIBL_T_C_PAIEMENT", length = 100)
	@LgrHibernateValidated(champEntite = "", champBd = "LIBL_T_C_PAIEMENT",table = "TA_T_C_PAIEMENT",clazz = TaTCPaiement.class)
	public String getLiblTCPaiement() {
		return this.liblTCPaiement;
	}

	public void setLiblTCPaiement(String liblTCPaiement) {
		this.liblTCPaiement = liblTCPaiement;
	}
	
	@ManyToOne(fetch = FetchType.LAZY, cascade = {/*CascadeType.PERSIST, CascadeType.MERGE,*/ CascadeType.REFRESH})
	@JoinColumn(name = "ID_C_PAIEMENT")
	@LgrHibernateValidated(champEntite = "", champBd = "ID_C_PAIEMENT",table = "TA_C_PAIEMENT",clazz = TaCPaiement.class)
	public TaCPaiement getTaCPaiement() {
		return this.taCPaiement;
	}

	public void setTaCPaiement(TaCPaiement taCPaiement) {
		this.taCPaiement = taCPaiement;
	}

	@Column(name = "QUI_CREE_T_C_PAIEMENT", length = 50)
	public String getQuiCreeTCPaiement() {
		return this.quiCreeTCPaiement;
	}

	public void setQuiCreeTCPaiement(String quiCreeTCPaiement) {
		this.quiCreeTCPaiement = quiCreeTCPaiement;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "QUAND_CREE_T_C_PAIEMENT", length = 19)
	public Date getQuandCreeTCPaiement() {
		return this.quandCreeTCPaiement;
	}

	public void setQuandCreeTCPaiement(Date quandCreeTCPaiement) {
		this.quandCreeTCPaiement = quandCreeTCPaiement;
	}

	@Column(name = "QUI_MODIF_T_C_PAIEMENT", length = 50)
	public String getQuiModifTCPaiement() {
		return this.quiModifTCPaiement;
	}

	public void setQuiModifTCPaiement(String quiModifTCPaiement) {
		this.quiModifTCPaiement = quiModifTCPaiement;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "QUAND_MODIF_T_C_PAIEMENT", length = 19)
	public Date getQuandModifTCPaiement() {
		return this.quandModifTCPaiement;
	}

	public void setQuandModifTCPaiement(Date quandModifTCPaiement) {
		this.quandModifTCPaiement = quandModifTCPaiement;
	}

	@Column(name = "IP_ACCES", length = 50)
	public String getIpAcces() {
		return this.ipAcces;
	}

	public void setIpAcces(String ipAcces) {
		this.ipAcces = ipAcces;
	}

	@Version
	@Column(name = "VERSION_OBJ")
	public Integer getVersionObj() {
		return this.versionObj;
	}

	public void setVersionObj(Integer versionObj) {
		this.versionObj = versionObj;
	}

//	@OneToMany(cascade = {CascadeType.PERSIST, CascadeType.MERGE}, fetch = FetchType.LAZY, mappedBy = "taTTel")
//	public Set<TaTelephone> getTaTelephones() {
//		return this.taTelephones;
//	}
//
//	public void setTaTelephones(Set<TaTelephone> taTelephones) {
//		this.taTelephones = taTelephones;
//	}

}
