package fr.legrain.tiers.dao;

// Generated Mar 24, 2009 4:44:04 PM by Hibernate Tools 3.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import fr.legrain.validator.LgrHibernateValidated;

/**
 * TaTLiens generated by hbm2java
 */
@Entity
//@Cache(usage=CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "TA_T_LIENS")
@SequenceGenerator(name = "GEN_T_LIENS", sequenceName = "NUM_ID_T_LIENS", allocationSize = 1)
public class TaTLiens implements java.io.Serializable {

	private int idTLiens;
	private String version;
	private String codeTLiens;
	private String liblTLiens;
	private String quiCreeTLiens;
	private Date quandCreeTLiens;
	private String quiModifTLiens;
	private Date quandModifTLiens;
	private String ipAcces;
	private Integer versionObj;
	private Set<TaLiens> taLienses = new HashSet<TaLiens>(0);

	public TaTLiens() {
	}

	public TaTLiens(int idTLiens) {
		this.idTLiens = idTLiens;
	}

	public TaTLiens(int idTLiens, String codeTLiens, String liblTLiens,
			String quiCreeTLiens, Date quandCreeTLiens, String quiModifTLiens,
			Date quandModifTLiens, String ipAcces, Integer versionObj,
			Set<TaLiens> taLienses) {
		this.idTLiens = idTLiens;
		this.codeTLiens = codeTLiens;
		this.liblTLiens = liblTLiens;
		this.quiCreeTLiens = quiCreeTLiens;
		this.quandCreeTLiens = quandCreeTLiens;
		this.quiModifTLiens = quiModifTLiens;
		this.quandModifTLiens = quandModifTLiens;
		this.ipAcces = ipAcces;
		this.versionObj = versionObj;
		this.taLienses = taLienses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "GEN_T_LIENS")
	@Column(name = "ID_T_LIENS", unique = true, nullable = false)
	@LgrHibernateValidated(champEntite = "", champBd = "ID_T_LIENS",table = "TA_T_LIENS",clazz = TaTLiens.class)
	public int getIdTLiens() {
		return this.idTLiens;
	}

	public void setIdTLiens(int idTLiens) {
		this.idTLiens = idTLiens;
	}

	@Column(name = "VERSION", length = 20)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@Column(name = "CODE_T_LIENS", length = 20)
	@LgrHibernateValidated(champEntite = "", champBd = "CODE_T_LIENS",table = "TA_T_LIENS",clazz = TaTLiens.class)
	public String getCodeTLiens() {
		return this.codeTLiens;
	}

	public void setCodeTLiens(String codeTLiens) {
		this.codeTLiens = codeTLiens;
	}

	@Column(name = "LIBL_T_LIENS", length = 100)
	@LgrHibernateValidated(champEntite = "", champBd = "LIBL_T_LIENS",table = "TA_T_LIENS",clazz = TaTLiens.class)
	public String getLiblTLiens() {
		return this.liblTLiens;
	}

	public void setLiblTLiens(String liblTLiens) {
		this.liblTLiens = liblTLiens;
	}

	@Column(name = "QUI_CREE_T_LIENS", length = 50)
	public String getQuiCreeTLiens() {
		return this.quiCreeTLiens;
	}

	public void setQuiCreeTLiens(String quiCreeTLiens) {
		this.quiCreeTLiens = quiCreeTLiens;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "QUAND_CREE_T_LIENS", length = 19)
	public Date getQuandCreeTLiens() {
		return this.quandCreeTLiens;
	}

	public void setQuandCreeTLiens(Date quandCreeTLiens) {
		this.quandCreeTLiens = quandCreeTLiens;
	}

	@Column(name = "QUI_MODIF_T_LIENS", length = 50)
	public String getQuiModifTLiens() {
		return this.quiModifTLiens;
	}

	public void setQuiModifTLiens(String quiModifTLiens) {
		this.quiModifTLiens = quiModifTLiens;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "QUAND_MODIF_T_LIENS", length = 19)
	public Date getQuandModifTLiens() {
		return this.quandModifTLiens;
	}

	public void setQuandModifTLiens(Date quandModifTLiens) {
		this.quandModifTLiens = quandModifTLiens;
	}

	@Column(name = "IP_ACCES", length = 50)
	public String getIpAcces() {
		return this.ipAcces;
	}

	public void setIpAcces(String ipAcces) {
		this.ipAcces = ipAcces;
	}

	@Version
	@Column(name = "VERSION_OBJ")
	public Integer getVersionObj() {
		return this.versionObj;
	}

	public void setVersionObj(Integer versionObj) {
		this.versionObj = versionObj;
	}

	@OneToMany(cascade = {CascadeType.PERSIST, CascadeType.MERGE}, fetch = FetchType.LAZY, mappedBy = "taTLiens")
	public Set<TaLiens> getTaLienses() {
		return this.taLienses;
	}

	public void setTaLienses(Set<TaLiens> taLienses) {
		this.taLienses = taLienses;
	}


//	@PrePersist
//	@PreUpdate
	public void beforePost ()throws Exception{
		this.setCodeTLiens(codeTLiens.toUpperCase());
	}
}
