package fr.legrain.tiers.dao;

// Generated Mar 24, 2009 4:44:04 PM by Hibernate Tools 3.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import fr.legrain.validator.LgrHibernateValidated;

/**
 * TaTNote generated by hbm2java
 */
@Entity
//@Cache(usage=CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "TA_T_NOTE_TIERS")
@SequenceGenerator(name = "GEN_T_NOTE_TIERS", sequenceName = "NUM_ID_T_NOTE_TIERS", allocationSize = 1)
public class TaTNoteTiers implements java.io.Serializable {

	private int idTNoteTiers;
	private String version;
	private String codeTNoteTiers;
	private String liblTNoteTiers;
	private String quiCreeTNote;
	private Date quandCreeTNote;
	private String quiModifTNote;
	private Date quandModifTNote;
	private String ipAcces;
	private Integer versionObj;
	private Set<TaNoteTiers> taNotesTiers = new HashSet<TaNoteTiers>(0);

	public TaTNoteTiers() {
	}

	public TaTNoteTiers(int idTNote) {
		this.idTNoteTiers = idTNote;
	}

	public TaTNoteTiers(int idTNoteTiers, String codeTNoteTiers, String liblTNoteTiers,
			String quiCreeTNote, Date quandCreeTNote, String quiModifTNote,
			Date quandModifTNote, String ipAcces, Integer versionObj,
			Set<TaNoteTiers> taNotesTiers) {
		this.idTNoteTiers = idTNoteTiers;
		this.codeTNoteTiers = codeTNoteTiers;
		this.liblTNoteTiers = liblTNoteTiers;
		this.quiCreeTNote = quiCreeTNote;
		this.quandCreeTNote = quandCreeTNote;
		this.quiModifTNote = quiModifTNote;
		this.quandModifTNote = quandModifTNote;
		this.ipAcces = ipAcces;
		this.versionObj = versionObj;
		this.taNotesTiers = taNotesTiers;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "GEN_T_NOTE_TIERS")
	@Column(name = "ID_T_NOTE_TIERS", unique = true, nullable = false)
	@LgrHibernateValidated(champEntite = "", champBd = "ID_T_NOTE_TIERS",table = "TA_T_NOTE_TIERS",clazz = TaTNoteTiers.class)
	public int getIdTNoteTiers() {
		return this.idTNoteTiers;
	}

	public void setIdTNoteTiers(int idTNote) {
		this.idTNoteTiers = idTNote;
	}

	@Column(name = "VERSION", length = 20)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@Column(name = "CODE_T_NOTE_TIERS", length = 20)
	@LgrHibernateValidated(champEntite = "", champBd = "CODE_T_NOTE_TIERS",table = "TA_T_NOTE_TIERS",clazz = TaTNoteTiers.class)
	public String getCodeTNoteTiers() {
		return this.codeTNoteTiers;
	}

	public void setCodeTNoteTiers(String codeTNoteTiers) {
		this.codeTNoteTiers = codeTNoteTiers;
	}

	@Column(name = "LIBL_T_NOTE_TIERS", length = 100)
	@LgrHibernateValidated(champEntite = "", champBd = "LIBL_T_NOTE_TIERS",table = "TA_T_NOTE_TIERS",clazz = TaTNoteTiers.class)
	public String getLiblTNoteTiers() {
		return this.liblTNoteTiers;
	}

	public void setLiblTNoteTiers(String liblTNoteTiers) {
		this.liblTNoteTiers = liblTNoteTiers;
	}

	@Column(name = "QUI_CREE_T_NOTE", length = 50)
	public String getQuiCreeTNote() {
		return this.quiCreeTNote;
	}

	public void setQuiCreeTNote(String quiCreeTNote) {
		this.quiCreeTNote = quiCreeTNote;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "QUAND_CREE_T_NOTE", length = 19)
	public Date getQuandCreeTNote() {
		return this.quandCreeTNote;
	}

	public void setQuandCreeTNote(Date quandCreeTNote) {
		this.quandCreeTNote = quandCreeTNote;
	}

	@Column(name = "QUI_MODIF_T_NOTE", length = 50)
	public String getQuiModifTNote() {
		return this.quiModifTNote;
	}

	public void setQuiModifTNote(String quiModifTNote) {
		this.quiModifTNote = quiModifTNote;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "QUAND_MODIF_T_NOTE", length = 19)
	public Date getQuandModifTNote() {
		return this.quandModifTNote;
	}

	public void setQuandModifTNote(Date quandModifTNote) {
		this.quandModifTNote = quandModifTNote;
	}

	@Column(name = "IP_ACCES", length = 50)
	public String getIpAcces() {
		return this.ipAcces;
	}

	public void setIpAcces(String ipAcces) {
		this.ipAcces = ipAcces;
	}

	@Version
	@Column(name = "VERSION_OBJ")
	public Integer getVersionObj() {
		return this.versionObj;
	}

	public void setVersionObj(Integer versionObj) {
		this.versionObj = versionObj;
	}

	@OneToMany(cascade = {CascadeType.PERSIST, CascadeType.MERGE}, fetch = FetchType.LAZY, mappedBy = "taTNoteTiers")
	public Set<TaNoteTiers> getTaNotesTiers() {
		return this.taNotesTiers;
	}

	public void setTaNotesTiers(Set<TaNoteTiers> taNotes) {
		this.taNotesTiers = taNotes;
	}
	
//	@PrePersist
//	@PreUpdate
	public void beforePost ()throws Exception{
		this.setCodeTNoteTiers(codeTNoteTiers.toUpperCase());
	}
}
