package fr.legrain.tiers.dao;

// Generated Mar 24, 2009 4:44:04 PM by Hibernate Tools 3.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import fr.legrain.validator.LgrHibernateValidated;

/**
 * TaTTiers generated by hbm2java
 */
@Entity
//@Cache(usage=CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "TA_T_TIERS")
@SequenceGenerator(name = "GEN_T_TIERS", sequenceName = "NUM_ID_T_TIERS", allocationSize = 1)
public class TaTTiers implements java.io.Serializable {

	private int idTTiers;
	private String version;
	private String codeTTiers;
	private String libelleTTiers;
	private String compteTTiers;
	private String quiCreeTTiers;
	private Date quandCreeTTiers;
	private String quiModifTTiers;
	private Date quandModifTTiers;
	private String ipAcces;
	private Integer versionObj;
	private Set<TaTiers> taTierses = new HashSet<TaTiers>(0);

	public TaTTiers() {
	}

	public TaTTiers(int idTTiers) {
		this.idTTiers = idTTiers;
	}

	public TaTTiers(int idTTiers, String codeTTiers, String libelleTTiers,
			String compteTTiers, String quiCreeTTiers, Date quandCreeTTiers,
			String quiModifTTiers, Date quandModifTTiers, String ipAcces,
			Integer versionObj, Set<TaTiers> taTierses) {
		this.idTTiers = idTTiers;
		this.codeTTiers = codeTTiers;
		this.libelleTTiers = libelleTTiers;
		this.compteTTiers = compteTTiers;
		this.quiCreeTTiers = quiCreeTTiers;
		this.quandCreeTTiers = quandCreeTTiers;
		this.quiModifTTiers = quiModifTTiers;
		this.quandModifTTiers = quandModifTTiers;
		this.ipAcces = ipAcces;
		this.versionObj = versionObj;
		this.taTierses = taTierses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "GEN_T_TIERS")
	@Column(name = "ID_T_TIERS", unique = true, nullable = false)
	@LgrHibernateValidated(champEntite = "", champBd = "ID_T_TIERS",table = "TA_T_TIERS",clazz = TaTTiers.class)
	public int getIdTTiers() {
		return this.idTTiers;
	}

	public void setIdTTiers(int idTTiers) {
		this.idTTiers = idTTiers;
	}

	@Column(name = "VERSION", length = 20)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@Column(name = "CODE_T_TIERS", length = 20)
	@LgrHibernateValidated(champEntite = "", champBd = "CODE_T_TIERS",table = "TA_T_TIERS",clazz = TaTTiers.class)
	public String getCodeTTiers() {
		return this.codeTTiers;
	}

	public void setCodeTTiers(String codeTTiers) {
		this.codeTTiers = codeTTiers;
	}

	@Column(name = "LIBELLE_T_TIERS", length = 100)
	@LgrHibernateValidated(champEntite = "", champBd = "LIBELLE_T_TIERS",table = "TA_T_TIERS",clazz = TaTTiers.class)
	public String getLibelleTTiers() {
		return this.libelleTTiers;
	}

	public void setLibelleTTiers(String libelleTTiers) {
		this.libelleTTiers = libelleTTiers;
	}

	@Column(name = "COMPTE_T_TIERS", length = 8)
	@LgrHibernateValidated(champEntite = "", champBd = "COMPTE_T_TIERS",table = "TA_T_TIERS",clazz = TaTTiers.class)
	public String getCompteTTiers() {
		return this.compteTTiers;
	}

	public void setCompteTTiers(String compteTTiers) {
		this.compteTTiers = compteTTiers;
	}

	@Column(name = "QUI_CREE_T_TIERS", length = 50)
	public String getQuiCreeTTiers() {
		return this.quiCreeTTiers;
	}

	public void setQuiCreeTTiers(String quiCreeTTiers) {
		this.quiCreeTTiers = quiCreeTTiers;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "QUAND_CREE_T_TIERS", length = 19)
	public Date getQuandCreeTTiers() {
		return this.quandCreeTTiers;
	}

	public void setQuandCreeTTiers(Date quandCreeTTiers) {
		this.quandCreeTTiers = quandCreeTTiers;
	}

	@Column(name = "QUI_MODIF_T_TIERS", length = 50)
	public String getQuiModifTTiers() {
		return this.quiModifTTiers;
	}

	public void setQuiModifTTiers(String quiModifTTiers) {
		this.quiModifTTiers = quiModifTTiers;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "QUAND_MODIF_T_TIERS", length = 19)
	public Date getQuandModifTTiers() {
		return this.quandModifTTiers;
	}

	public void setQuandModifTTiers(Date quandModifTTiers) {
		this.quandModifTTiers = quandModifTTiers;
	}

	@Column(name = "IP_ACCES", length = 50)
	public String getIpAcces() {
		return this.ipAcces;
	}

	public void setIpAcces(String ipAcces) {
		this.ipAcces = ipAcces;
	}

	@Version
	@Column(name = "VERSION_OBJ")
	public Integer getVersionObj() {
		return this.versionObj;
	}

	public void setVersionObj(Integer versionObj) {
		this.versionObj = versionObj;
	}

	@OneToMany(cascade = {CascadeType.PERSIST, CascadeType.MERGE}, fetch = FetchType.LAZY, mappedBy = "taTTiers")
	public Set<TaTiers> getTaTierses() {
		return this.taTierses;
	}

	public void setTaTierses(Set<TaTiers> taTierses) {
		this.taTierses = taTierses;
	}

	

//	@PrePersist
//	@PreUpdate
	public void beforePost ()throws Exception{
		this.setCodeTTiers(codeTTiers.toUpperCase());
	}
}
