package fr.legrain.tiers.dao;

// Generated Mar 24, 2009 4:44:04 PM by Hibernate Tools 3.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import fr.legrain.validator.LgrHibernateValidated;

/**
 * TaTWeb generated by hbm2java
 */
@Entity
//@Cache(usage=CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "TA_T_WEB")
@SequenceGenerator(name = "GEN_T_WEB", sequenceName = "NUM_ID_T_WEB", allocationSize = 1)
public class TaTWeb implements java.io.Serializable {

	private int idTWeb;
	private String version;
	private String codeTWeb;
	private String liblTWeb;
	private String quiCreeTWeb;
	private Date quandCreeTWeb;
	private String quiModifTWeb;
	private Date quandModifTWeb;
	private String ipAcces;
	private Integer versionObj;
	private Set<TaWeb> taWebs = new HashSet<TaWeb>(0);

	public TaTWeb() {
	}

	public TaTWeb(int idTWeb) {
		this.idTWeb = idTWeb;
	}

	public TaTWeb(int idTWeb, String codeTWeb, String liblTWeb,
			String quiCreeTWeb, Date quandCreeTWeb, String quiModifTWeb,
			Date quandModifTWeb, String ipAcces, Integer versionObj,
			Set<TaWeb> taWebs) {
		this.idTWeb = idTWeb;
		this.codeTWeb = codeTWeb;
		this.liblTWeb = liblTWeb;
		this.quiCreeTWeb = quiCreeTWeb;
		this.quandCreeTWeb = quandCreeTWeb;
		this.quiModifTWeb = quiModifTWeb;
		this.quandModifTWeb = quandModifTWeb;
		this.ipAcces = ipAcces;
		this.versionObj = versionObj;
		this.taWebs = taWebs;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "GEN_T_WEB")
	@Column(name = "ID_T_WEB", unique = true, nullable = false)
	@LgrHibernateValidated(champEntite = "", champBd = "ID_T_WEB",table = "TA_T_WEB",clazz = TaTWeb.class)
	public int getIdTWeb() {
		return this.idTWeb;
	}

	public void setIdTWeb(int idTWeb) {
		this.idTWeb = idTWeb;
	}

	@Column(name = "VERSION", length = 20)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@Column(name = "CODE_T_WEB", length = 20)
	@LgrHibernateValidated(champEntite = "", champBd = "CODE_T_WEB",table = "TA_T_WEB",clazz = TaTWeb.class)
	public String getCodeTWeb() {
		return this.codeTWeb;
	}

	public void setCodeTWeb(String codeTWeb) {
		this.codeTWeb = codeTWeb;
	}

	@Column(name = "LIBL_T_WEB", length = 100)
	@LgrHibernateValidated(champEntite = "", champBd = "LIBL_T_WEB",table = "TA_T_WEB",clazz = TaTWeb.class)
	public String getLiblTWeb() {
		return this.liblTWeb;
	}

	public void setLiblTWeb(String liblTWeb) {
		this.liblTWeb = liblTWeb;
	}

	@Column(name = "QUI_CREE_T_WEB", length = 50)
	public String getQuiCreeTWeb() {
		return this.quiCreeTWeb;
	}

	public void setQuiCreeTWeb(String quiCreeTWeb) {
		this.quiCreeTWeb = quiCreeTWeb;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "QUAND_CREE_T_WEB", length = 19)
	public Date getQuandCreeTWeb() {
		return this.quandCreeTWeb;
	}

	public void setQuandCreeTWeb(Date quandCreeTWeb) {
		this.quandCreeTWeb = quandCreeTWeb;
	}

	@Column(name = "QUI_MODIF_T_WEB", length = 50)
	public String getQuiModifTWeb() {
		return this.quiModifTWeb;
	}

	public void setQuiModifTWeb(String quiModifTWeb) {
		this.quiModifTWeb = quiModifTWeb;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "QUAND_MODIF_T_WEB", length = 19)
	public Date getQuandModifTWeb() {
		return this.quandModifTWeb;
	}

	public void setQuandModifTWeb(Date quandModifTWeb) {
		this.quandModifTWeb = quandModifTWeb;
	}

	@Column(name = "IP_ACCES", length = 50)
	public String getIpAcces() {
		return this.ipAcces;
	}

	public void setIpAcces(String ipAcces) {
		this.ipAcces = ipAcces;
	}

	@Version
	@Column(name = "VERSION_OBJ")
	public Integer getVersionObj() {
		return this.versionObj;
	}

	public void setVersionObj(Integer versionObj) {
		this.versionObj = versionObj;
	}

	@OneToMany(cascade = {CascadeType.PERSIST, CascadeType.MERGE}, fetch = FetchType.LAZY, mappedBy = "taTWeb")
	public Set<TaWeb> getTaWebs() {
		return this.taWebs;
	}

	public void setTaWebs(Set<TaWeb> taWebs) {
		this.taWebs = taWebs;
	}


//	@PrePersist
//	@PreUpdate
	public void beforePost ()throws Exception{
		this.setCodeTWeb(codeTWeb.toUpperCase());
	}
}
