package fr.legrain.gestCom.Module_Tiers;

import fr.legrain.lib.data.ModelObject;

// Generated Mar 1, 2007 11:26:10 AM by Hibernate Tools 3.2.0.b9

/**
 * SWTCompl generated by hbm2java
 */
public class SWTCompl extends ModelObject {

	private Integer idCompl;
	private Integer idTiers;
	private String tvaIComCompl;
	private String siretCompl;
	private String codeTiers;
	private String nomTiers;
	private String prenomTiers;
	private String accise;

	public SWTCompl() {
	}

	public void setSWTCompl(SWTCompl swtCompl) {
		this.idCompl = swtCompl.idCompl;
		this.idTiers = swtCompl.idTiers;
		this.tvaIComCompl = swtCompl.tvaIComCompl;
		this.siretCompl = swtCompl.siretCompl;
		this.codeTiers = swtCompl.codeTiers;
		this.nomTiers = swtCompl.nomTiers;
		this.prenomTiers = swtCompl.prenomTiers;
		this.accise = swtCompl.accise;
	}

	public static SWTCompl copy(SWTCompl swtCompl){
		SWTCompl swtComplLoc = new SWTCompl();
		swtComplLoc.setIdTiers(swtCompl.getIdTiers());                //1
		swtComplLoc.setIdCompl(swtCompl.getIdCompl());                //1
		swtComplLoc.setTvaIComCompl(swtCompl.getTvaIComCompl());                //1
		swtComplLoc.setCodeTiers(swtCompl.getCodeTiers());                //1
		swtComplLoc.setNomTiers(swtCompl.getNomTiers());                //1
		swtComplLoc.setPrenomTiers(swtCompl.getPrenomTiers());                //1
		swtComplLoc.setSiretCompl(swtCompl.getSiretCompl()); 
		swtComplLoc.setAccise(swtCompl.getAccise());//1
		return swtComplLoc;
	}
	public Integer getIdCompl() {
		return this.idCompl;
	}

	public void setIdCompl(Integer ID_COMPL) {
		firePropertyChange("idCompl", this.idCompl, this.idCompl = ID_COMPL);
	}

	public Integer getIdTiers() {
		return this.idTiers;
	}

	public void setIdTiers(Integer ID_TIERS) {
		firePropertyChange("idTiers", this.idTiers, this.idTiers = ID_TIERS);
	}

	public String getTvaIComCompl() {
		return this.tvaIComCompl;
	}

	public void setTvaIComCompl(String TVA_I_COM_COMPL) {
		firePropertyChange("tvaIComCompl", this.tvaIComCompl, this.tvaIComCompl = TVA_I_COM_COMPL);
	}

	public String getSiretCompl() {
		return this.siretCompl;
	}

	public void setSiretCompl(String SIRET_COMPL) {
		firePropertyChange("siretCompl", this.siretCompl, this.siretCompl = SIRET_COMPL);
	}

	public String getCodeTiers() {
		return this.codeTiers;
	}

	public void setCodeTiers(String CODE_TIERS) {
		firePropertyChange("codeTiers", this.codeTiers, this.codeTiers = CODE_TIERS);
	}

	public String getNomTiers() {
		return this.nomTiers;
	}

	public void setNomTiers(String NOM_TIERS) {
		firePropertyChange("nomTiers", this.nomTiers, this.nomTiers = NOM_TIERS);
	}

	public String getPrenomTiers() {
		return this.prenomTiers;
	}

	public void setPrenomTiers(String PRENOM_TIERS) {
		firePropertyChange("prenomTiers", this.prenomTiers, this.prenomTiers = PRENOM_TIERS);
	}

	public String getAccise() {
		return accise;
	}

	public void setAccise(String accise) {
		firePropertyChange("accise", this.accise, this.accise = accise);
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((accise == null) ? 0 : accise.hashCode());
		result = prime * result
				+ ((codeTiers == null) ? 0 : codeTiers.hashCode());
		result = prime * result + ((idCompl == null) ? 0 : idCompl.hashCode());
		result = prime * result + ((idTiers == null) ? 0 : idTiers.hashCode());
		result = prime * result
				+ ((nomTiers == null) ? 0 : nomTiers.hashCode());
		result = prime * result
				+ ((prenomTiers == null) ? 0 : prenomTiers.hashCode());
		result = prime * result
				+ ((siretCompl == null) ? 0 : siretCompl.hashCode());
		result = prime * result
				+ ((tvaIComCompl == null) ? 0 : tvaIComCompl.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		SWTCompl other = (SWTCompl) obj;
		if (accise == null) {
			if (other.accise != null)
				return false;
		} else if (!accise.equals(other.accise))
			return false;
		if (codeTiers == null) {
			if (other.codeTiers != null)
				return false;
		} else if (!codeTiers.equals(other.codeTiers))
			return false;
		if (idCompl == null) {
			if (other.idCompl != null)
				return false;
		} else if (!idCompl.equals(other.idCompl))
			return false;
		if (idTiers == null) {
			if (other.idTiers != null)
				return false;
		} else if (!idTiers.equals(other.idTiers))
			return false;
		if (nomTiers == null) {
			if (other.nomTiers != null)
				return false;
		} else if (!nomTiers.equals(other.nomTiers))
			return false;
		if (prenomTiers == null) {
			if (other.prenomTiers != null)
				return false;
		} else if (!prenomTiers.equals(other.prenomTiers))
			return false;
		if (siretCompl == null) {
			if (other.siretCompl != null)
				return false;
		} else if (!siretCompl.equals(other.siretCompl))
			return false;
		if (tvaIComCompl == null) {
			if (other.tvaIComCompl != null)
				return false;
		} else if (!tvaIComCompl.equals(other.tvaIComCompl))
			return false;
		return true;
	}





}
