package fr.legrain.gestCom.Module_Tiers;

import fr.legrain.lib.data.ModelObject;

// Generated Mar 1, 2007 11:26:10 AM by Hibernate Tools 3.2.0.b9

/**
 * SWTFamille generated by hbm2java
 */
public class SWTFamille extends ModelObject {

	private Integer idFamille;
	private String codeFamille;
	private String libcFamille;
	private String liblFamille;

	public SWTFamille() {
	}

	public SWTFamille(Integer ID_FAMILLE, String CODE_FAMILLE,
			String LIBC_FAMILLE, String LIBL_FAMILLE) {
		this.idFamille = ID_FAMILLE;
		this.codeFamille = CODE_FAMILLE;
		this.libcFamille = LIBC_FAMILLE;
		this.liblFamille = LIBL_FAMILLE;
	}
	
	public void setSWTFamille(SWTFamille swtFamille) {
		this.idFamille = swtFamille.idFamille;
		this.codeFamille = swtFamille.codeFamille;
		this.libcFamille = swtFamille.libcFamille;
		this.liblFamille = swtFamille.liblFamille;
	}
	
	public static SWTFamille copy(SWTFamille swtFamille){
		SWTFamille swtFamilleLoc = new SWTFamille();
		swtFamilleLoc.setIdFamille(swtFamille.idFamille);
		swtFamilleLoc.setCodeFamille(swtFamille.codeFamille);
		swtFamilleLoc.setLibcFamille(swtFamille.libcFamille);
		swtFamilleLoc.setLiblFamille(swtFamille.liblFamille);
		return swtFamilleLoc;
	}

	public Integer getIdFamille() {
		return this.idFamille;
	}

	public void setIdFamille(Integer ID_FAMILLE) {
		firePropertyChange("idFamille", this.idFamille, this.idFamille = ID_FAMILLE);
	}

	public String getCodeFamille() {
		return this.codeFamille;
	}

	public void setCodeFamille(String CODE_FAMILLE) {
		firePropertyChange("codeFamille", this.codeFamille, this.codeFamille = CODE_FAMILLE);
	}

	public String getLibcFamille() {
		return this.libcFamille;
	}

	public void setLibcFamille(String LIBC_FAMILLE) {
		firePropertyChange("libcFamille", this.libcFamille, this.libcFamille = LIBC_FAMILLE);
	}

	public String getLiblFamille() {
		return this.liblFamille;
	}

	public void setLiblFamille(String LIBL_FAMILLE) {
		firePropertyChange("liblFamille", this.liblFamille, this.liblFamille = LIBL_FAMILLE);
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SWTFamille))
			return false;
		SWTFamille castOther = (SWTFamille) other;

		return ((this.getIdFamille() == castOther.getIdFamille()) || (this
				.getIdFamille() != null
				&& castOther.getIdFamille() != null && this.getIdFamille()
				.equals(castOther.getIdFamille())))
				&& ((this.getCodeFamille() == castOther.getCodeFamille()) || (this
						.getCodeFamille() != null
						&& castOther.getCodeFamille() != null && this
						.getCodeFamille().equals(castOther.getCodeFamille())))
				&& ((this.getLibcFamille() == castOther.getLibcFamille()) || (this
						.getLibcFamille() != null
						&& castOther.getLibcFamille() != null && this
						.getLibcFamille().equals(castOther.getLibcFamille())))
				&& ((this.getLiblFamille() == castOther.getLiblFamille()) || (this
						.getLiblFamille() != null
						&& castOther.getLiblFamille() != null && this
						.getLiblFamille().equals(castOther.getLiblFamille())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getIdFamille() == null ? 0 : this.getIdFamille()
						.hashCode());
		result = 37
				* result
				+ (getCodeFamille() == null ? 0 : this.getCodeFamille()
						.hashCode());
		result = 37
				* result
				+ (getLibcFamille() == null ? 0 : this.getLibcFamille()
						.hashCode());
		result = 37
				* result
				+ (getLiblFamille() == null ? 0 : this.getLiblFamille()
						.hashCode());
		return result;
	}

}
