package fr.legrain.tiers.dto;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

import fr.legrain.bdg.model.ModelObject;
import fr.legrain.validator.LgrHibernateValidated;

// Generated Mar 1, 2007 11:26:10 AM by Hibernate Tools 3.2.0.b9

/**
 * SWTEmail generated by hbm2java
 */
public class TaEmailDTO extends ModelObject implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1212163527328909180L;
	private Integer id;
	private String adresseEmail;
	private String codeTiers;
	private String nomTiers;
	private String prenomTiers;
	private String nomEntreprise;
	private String codeTEmail;
	private String liblTEmail;
	private Boolean commCommercialEmail;
	private Boolean commAdministratifEmail;
	private Integer idTiers;
	
	private Integer versionObj;
	
	private boolean defaut=false;

	public TaEmailDTO() {
	}

	public boolean estVide() {
		if(this.getAdresseEmail()!=null && !this.getAdresseEmail().isEmpty())return false;

		return true;
	}
	
	public TaEmailDTO(Integer id, String adresseEmail,
			String codeTiers, Integer idTiers) {
		this.id = id;
		this.adresseEmail = adresseEmail;
		this.codeTiers = codeTiers;
		this.idTiers = idTiers;
	}
	
	public void setSWTEmail(TaEmailDTO taEmailDTO) {
		this.id = taEmailDTO.id;
		this.adresseEmail = taEmailDTO.adresseEmail;
		this.codeTiers = taEmailDTO.codeTiers;
		this.idTiers = taEmailDTO.idTiers;
		this.codeTEmail = taEmailDTO.codeTEmail;
		this.commCommercialEmail = taEmailDTO.commCommercialEmail;
		this.commAdministratifEmail = taEmailDTO.commAdministratifEmail;
	}
	
	public TaEmailDTO(Integer id, String adresseEmail, String codeTiers, String nomTiers, String prenomTiers,
			String nomEntreprise, String codeTEmail, int commCommercialEmail, int commAdministratifEmail,
			Integer idTiers) {
		super();
		this.id = id;
		this.adresseEmail = adresseEmail;
		this.codeTiers = codeTiers;
		this.nomTiers = nomTiers;
		this.prenomTiers = prenomTiers;
		this.nomEntreprise = nomEntreprise;
		this.codeTEmail = codeTEmail;
		this.commAdministratifEmail = commAdministratifEmail==1?true:false;
		this.commCommercialEmail = commCommercialEmail==1?true:false;
		this.idTiers = idTiers;
	}


	
	public static TaEmailDTO copy(TaEmailDTO taEmailDTO) {
		TaEmailDTO taEmailDTOLoc = new TaEmailDTO();
		taEmailDTOLoc.setId(taEmailDTO.getId());
		taEmailDTOLoc.setAdresseEmail(taEmailDTO.getAdresseEmail());
		taEmailDTOLoc.setCodeTiers(taEmailDTO.getCodeTiers());
		taEmailDTOLoc.setIdTiers(taEmailDTO.getIdTiers());
		taEmailDTOLoc.setCodeTEmail(taEmailDTO.getCodeTEmail());
		taEmailDTOLoc.setCommCommercialEmail(taEmailDTO.commCommercialEmail); 
		taEmailDTOLoc.setCommAdministratifEmail(taEmailDTO.commAdministratifEmail); 
		return taEmailDTOLoc;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		firePropertyChange("id", this.id, this.id = id);
	}

	@NotNull
	@Size(min=0, max=255)
//	@Pattern(regexp="[a-zA-Z0-9\\+\\.\\_\\%\\-\\+]{1,256}\\@[a-zA-Z0-9][a-zA-Z0-9\\-]{0,64}" +
//            "( \\.[a-zA-Z0-9][a-zA-Z0-9\\-]{0,25})+")
	@LgrHibernateValidated(champBd = "adresse_email",table = "ta_email",champEntite="adresseEmail",clazz = TaEmailDTO.class)
	public String getAdresseEmail() {
		return this.adresseEmail;
	}

	public void setAdresseEmail(String adresseEmail) {
		firePropertyChange("adresseEmail", this.adresseEmail, this.adresseEmail = adresseEmail);
	}


	@Size(min=0, max=20)
	@LgrHibernateValidated(champBd = "code_tiers",table = "ta_tiers",champEntite="codeTiers",clazz = TaEmailDTO.class)
	public String getCodeTiers() {
		return this.codeTiers;
	}

	public void setCodeTiers(String codeTiers) {
		firePropertyChange("codeTiers", this.codeTiers, this.codeTiers = codeTiers);
	}

	public Integer getIdTiers() {
		return this.idTiers;
	}

	public void setIdTiers(Integer idTiers) {
		firePropertyChange("idTiers", this.idTiers, this.idTiers = idTiers);
	}
	
	@NotNull
	@Size(min=1, max=20)
	@LgrHibernateValidated(champBd = "code_t_email",table = "ta_t_email",champEntite="codeTEmail",clazz = TaEmailDTO.class)
	public String getCodeTEmail() {
		return codeTEmail;
	}

	public void setCodeTEmail(String codeTEmail) {
		firePropertyChange("codeTEmail", this.codeTEmail, this.codeTEmail = codeTEmail);
	}
	
	public Boolean getCommCommercialEmail() {
		return commCommercialEmail;
	}

	public void setCommCommercialEmail(Boolean commCommercialEmail) {
		firePropertyChange("commCommercialEmail", this.commCommercialEmail, this.commCommercialEmail = commCommercialEmail);
	}

	public Boolean getCommAdministratifEmail() {
		return commAdministratifEmail;
	}

	public void setCommAdministratifEmail(Boolean commAdministratifEmail) {
		firePropertyChange("commAdministratifEmail", this.commAdministratifEmail, this.commAdministratifEmail = commAdministratifEmail);
	}
	
	public Integer getVersionObj() {
		return this.versionObj;
	}

	public void setVersionObj(Integer versionObj) {
		this.versionObj = versionObj;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final TaEmailDTO other = (TaEmailDTO) obj;
		if (adresseEmail == null) {
			if (other.adresseEmail != null)
				return false;
		} else if (!adresseEmail.equals(other.adresseEmail))
			return false;
		if (codeTEmail == null) {
			if (other.codeTEmail != null)
				return false;
		} else if (!codeTEmail.equals(other.codeTEmail))
			return false;
		if (codeTiers == null) {
			if (other.codeTiers != null)
				return false;
		} else if (!codeTiers.equals(other.codeTiers))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (idTiers == null) {
			if (other.idTiers != null)
				return false;
		} else if (!idTiers.equals(other.idTiers))
			return false;
		return true;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((adresseEmail == null) ? 0 : adresseEmail.hashCode());
		result = prime * result
				+ ((codeTEmail == null) ? 0 : codeTEmail.hashCode());
		result = prime * result
				+ ((codeTiers == null) ? 0 : codeTiers.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((idTiers == null) ? 0 : idTiers.hashCode());
		return result;
	}

	public String getNomTiers() {
		return nomTiers;
	}

	public void setNomTiers(String nomTiers) {
		this.nomTiers = nomTiers;
	}

	public String getPrenomTiers() {
		return prenomTiers;
	}

	public void setPrenomTiers(String prenomTiers) {
		this.prenomTiers = prenomTiers;
	}

	public String getNomEntreprise() {
		return nomEntreprise;
	}

	public void setNomEntreprise(String nomEntreprise) {
		this.nomEntreprise = nomEntreprise;
	}

	public boolean isDefaut() {
		return defaut;
	}

	public void setDefaut(boolean defaut) {
		this.defaut = defaut;
	}

	public String getLiblTEmail() {
		return liblTEmail;
	}

	public void setLiblTEmail(String liblTEmail) {
		this.liblTEmail = liblTEmail;
	}

}
