package fr.legrain.tiers.dto;

import fr.legrain.bdg.model.ModelObject;
import fr.legrain.validator.LgrHibernateValidated;

// Generated Mar 1, 2007 11:26:10 AM by Hibernate Tools 3.2.0.b9

/**
 * SWTCPaiement generated by hbm2java
 */
public class TaTCPaiementDTO extends ModelObject implements java.io.Serializable {
//IHMInfosCPaiement

	/**
	 * 
	 */
	private static final long serialVersionUID = -1119579131097885829L;
	private Integer id;
	private String codeCPaiement;
	private String libCPaiement;
	private Integer reportCPaiement;
	private Integer finMoisCPaiement;
	private Integer versionObj;

	public TaTCPaiementDTO() {
	}

	public TaTCPaiementDTO(String CODE_C_PAIEMENT,
			String LIB_C_PAIEMENT, Integer REPORT_C_PAIEMENT,
			Integer FIN_MOIS_C_PAIEMENT) {
		this.codeCPaiement = CODE_C_PAIEMENT;
		this.libCPaiement = LIB_C_PAIEMENT;
		this.reportCPaiement = REPORT_C_PAIEMENT;
		this.finMoisCPaiement = FIN_MOIS_C_PAIEMENT;
	}
	
	public void setIHMInfosCPaiement(TaTCPaiementDTO swtCPaiement) {
		setCodeCPaiement(swtCPaiement.codeCPaiement);
		setLibCPaiement(swtCPaiement.libCPaiement);
		setReportCPaiement(swtCPaiement.reportCPaiement);
		setFinMoisCPaiement(swtCPaiement.finMoisCPaiement);
	}
	
	public void setSWTCPaiement(TaCPaiementDTO taTCPaiementDTO) {
		setCodeCPaiement(taTCPaiementDTO.getCodeCPaiement());
		setLibCPaiement(taTCPaiementDTO.getCodeCPaiement());
		setReportCPaiement(taTCPaiementDTO.getReportCPaiement());
		setFinMoisCPaiement(taTCPaiementDTO.getFinMoisCPaiement());
	}

	
	public static TaTCPaiementDTO copy(TaTCPaiementDTO taTCPaiementDTO){
		TaTCPaiementDTO ihmInfosCPaiement = new TaTCPaiementDTO();
		ihmInfosCPaiement.setCodeCPaiement(taTCPaiementDTO.getCodeCPaiement());
		ihmInfosCPaiement.setLibCPaiement(taTCPaiementDTO.getLibCPaiement());
		ihmInfosCPaiement.setReportCPaiement(taTCPaiementDTO.getReportCPaiement());
		ihmInfosCPaiement.setFinMoisCPaiement(taTCPaiementDTO.getFinMoisCPaiement());
		return ihmInfosCPaiement;
	}

	
	@LgrHibernateValidated(champBd = "code_t_c_paiement",table = "ta_t_c_paiement",champEntite="codeCPaiement",clazz = TaTCPaiementDTO.class)
	public String getCodeCPaiement() {
		return this.codeCPaiement;
	}

	public void setCodeCPaiement(String code_c_paiement) {
		firePropertyChange("codeCPaiement", this.codeCPaiement, this.codeCPaiement = code_c_paiement);
	}

	@LgrHibernateValidated(champBd = "libl_t_c_paiement",table = "ta_t_c_paiement",champEntite="libCPaiement",clazz = TaTCPaiementDTO.class)
	public String getLibCPaiement() {
		return this.libCPaiement;
	}

	public void setLibCPaiement(String lib_c_paiement) {
		firePropertyChange("libCPaiement", this.libCPaiement, this.libCPaiement = lib_c_paiement);
	}

	@LgrHibernateValidated(champBd = "report_c_paiement",table = "ta_t_c_paiement",champEntite="reportCPaiement",clazz = TaTCPaiementDTO.class)
	public Integer getReportCPaiement() {
		return this.reportCPaiement;
	}

	public void setReportCPaiement(Integer report_c_paiement) {
		firePropertyChange("reportCPaiement", this.reportCPaiement, this.reportCPaiement = report_c_paiement);
	}

	@LgrHibernateValidated(champBd = "fin_mois_c_paiement",table = "ta_t_c_paiement",champEntite="finMoisCPaiement",clazz = TaTCPaiementDTO.class)
	public Integer getFinMoisCPaiement() {
		return this.finMoisCPaiement;
	}

	public void setFinMoisCPaiement(Integer fin_mois_c_paiement) {
		firePropertyChange("finMoisCPaiement", this.finMoisCPaiement, this.finMoisCPaiement = fin_mois_c_paiement);
	}
	
	public Integer getVersionObj() {
		return this.versionObj;
	}

	public void setVersionObj(Integer versionObj) {
		this.versionObj = versionObj;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TaTCPaiementDTO))
			return false;
		TaTCPaiementDTO castOther = (TaTCPaiementDTO) other;

		return (((this.getCodeCPaiement() == castOther
						.getCodeCPaiement()) || (this.getCodeCPaiement() != null
						&& castOther.getCodeCPaiement() != null && this
						.getCodeCPaiement().equals(
								castOther.getCodeCPaiement())))
				&& ((this.getLibCPaiement() == castOther.getLibCPaiement()) || (this
						.getLibCPaiement() != null
						&& castOther.getLibCPaiement() != null && this
						.getLibCPaiement().equals(
								castOther.getLibCPaiement())))
				&& ((this.getReportCPaiement() == castOther
						.getReportCPaiement()) || (this
						.getReportCPaiement() != null
						&& castOther.getReportCPaiement() != null && this
						.getReportCPaiement().equals(
								castOther.getReportCPaiement())))
				&& ((this.getFinMoisCPaiement() == castOther
						.getFinMoisCPaiement()) || (this
						.getFinMoisCPaiement() != null
						&& castOther.getFinMoisCPaiement() != null && this
						.getFinMoisCPaiement().equals(
								castOther.getFinMoisCPaiement()))));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCodeCPaiement() == null ? 0 : this.getCodeCPaiement()
						.hashCode());
		result = 37
				* result
				+ (getLibCPaiement() == null ? 0 : this.getLibCPaiement()
						.hashCode());
		result = 37
				* result
				+ (getReportCPaiement() == null ? 0 : this
						.getReportCPaiement().hashCode());
		result = 37
				* result
				+ (getFinMoisCPaiement() == null ? 0 : this
						.getFinMoisCPaiement().hashCode());
		return result;
	}

	
	public boolean estVide(){
		return this.equals(new TaTCPaiementDTO());
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
}
