ALTER TABLE ta_l_apporteur  ALTER COLUMN id_lot DROP NOT NULL;
ALTER TABLE ta_l_avoir  ALTER COLUMN id_lot DROP NOT NULL;
ALTER TABLE ta_l_acompte  ALTER COLUMN id_lot DROP NOT NULL;
ALTER TABLE ta_l_facture  ALTER COLUMN id_lot DROP NOT NULL;
ALTER TABLE ta_l_bonliv  ALTER COLUMN id_lot DROP NOT NULL;
ALTER TABLE ta_l_boncde  ALTER COLUMN id_lot DROP NOT NULL;
ALTER TABLE ta_l_proforma  ALTER COLUMN id_lot DROP NOT NULL;
ALTER TABLE ta_l_prelevement  ALTER COLUMN id_lot DROP NOT NULL;