INSERT INTO TRAITEMENTS (TYPE_TRAITEMENT, LIBELLE_TYPE, SOUS_TYPE_TRAITEMENT, LIBELLE_SOUS_TYPE_TRAITEMENT, ORIGINES_DONNEES, ANNEE, REGIME) VALUES ('L', 'Liasse', 'balance', 'page 1 a 4', 'Bilan;', 2002, 'A');
INSERT INTO TRAITEMENTS (TYPE_TRAITEMENT, LIBELLE_TYPE, SOUS_TYPE_TRAITEMENT, LIBELLE_SOUS_TYPE_TRAITEMENT, ORIGINES_DONNEES, ANNEE, REGIME) VALUES ('L', 'Liasse', 'immo', 'page 5', 'Bilan;5A3;5B1;5B2;', 2002, 'A');
INSERT INTO TRAITEMENTS (TYPE_TRAITEMENT, LIBELLE_TYPE, SOUS_TYPE_TRAITEMENT, LIBELLE_SOUS_TYPE_TRAITEMENT, ORIGINES_DONNEES, ANNEE, REGIME) VALUES ('L', 'Liasse', 'ammort', 'page 6', 'Bilan;6B1;6B2;6A3;6C4;6C5;', 2002, 'A');
INSERT INTO TRAITEMENTS (TYPE_TRAITEMENT, LIBELLE_TYPE, SOUS_TYPE_TRAITEMENT, LIBELLE_SOUS_TYPE_TRAITEMENT, ORIGINES_DONNEES, ANNEE, REGIME) VALUES ('L', 'Liasse', '8', 'page 8', 'Bilan;8B1VS;8B1VT;8B2VC;8B2VD;8B3VC;8B3VD;8B4VC;8B4VD;', 2002, 'A');
INSERT INTO TRAITEMENTS (TYPE_TRAITEMENT, LIBELLE_TYPE, SOUS_TYPE_TRAITEMENT, LIBELLE_SOUS_TYPE_TRAITEMENT, ORIGINES_DONNEES, ANNEE, REGIME) VALUES ('L', 'Liasse', '9', 'page 9', 'Bilan;9WM;', 2002, 'A');
INSERT INTO TRAITEMENTS (TYPE_TRAITEMENT, LIBELLE_TYPE, SOUS_TYPE_TRAITEMENT, LIBELLE_SOUS_TYPE_TRAITEMENT, ORIGINES_DONNEES, ANNEE, REGIME) VALUES ('L', 'Liasse', '11', 'page 11', 'Bilan;', 2002, 'A');

INSERT INTO TRAITEMENTS (TYPE_TRAITEMENT, LIBELLE_TYPE, SOUS_TYPE_TRAITEMENT, LIBELLE_SOUS_TYPE_TRAITEMENT, ORIGINES_DONNEES, ANNEE, REGIME) VALUES ('L', 'Liasse', 'balance', 'page 1 a 4', 'Bilan;', 2002, 'I');
