/* GENERATOR */
CREATE GENERATOR NUM_ID_FINAL;
CREATE GENERATOR NUM_ID_FINAL_DETAIL;
CREATE GENERATOR NUM_ID_INITIAL;
CREATE GENERATOR NUM_ID_INITIAL_COMPL;
CREATE GENERATOR NUM_ID_REPART;
CREATE GENERATOR NUM_ID_TOTAUX;
CREATE GENERATOR NUM_ID_TRAITEMENTS;


/* TABLES PARAMETRES */

CREATE TABLE REPART (
	ID_REPART DID3 primary key,
    NUM_CPT        DIDLIB9,
    MT_DEBIT    DLIB50,
    MT_CREDIT    DLIB50,
    SOLDE DLIB50,
    MT_DEBIT_2    DLIB50,
    MT_CREDIT_2    DLIB50,
    SOLDE_2 DLIB50,
    MT_DEBIT_3    DLIB50,
    MT_CREDIT_3    DLIB50,
    SOLDE_3 DLIB50,
    REGIME        DLIB1,
    TYPE_TRAITEMENT   DLIB1,
    SOUS_TYPE_TRAITEMENT DLIB50,
	ORIGINE DLIB50,
    ANNEE INTEGER
);

CREATE TABLE TOTAUX (
	ID_TOTAUX DID3 primary key,
    CLE        DLIB255NN,
    LISTE_CLE    DLIB255,
    REGIME        DLIB1,
    TYPE_TRAITEMENT   DLIB1,
    SOUS_TYPE_TRAITEMENT DLIB50,
	CONDITION DLIB255,
    ORDRE   FLOAT,
    ANNEE INTEGER
);

CREATE TABLE TRAITEMENTS
(
  ID_TRAITEMENTS DID3 primary key,
  TYPE_TRAITEMENT DLIB50,
  LIBELLE_TYPE DLIB255,
  SOUS_TYPE_TRAITEMENT DLIB50,
  LIBELLE_SOUS_TYPE_TRAITEMENT DLIB255,
  ORIGINES_DONNEES DLIB255,
  ANNEE Integer,
  REGIME DLIB1
);

/* TABLES DE TRAVAIL */

CREATE TABLE INITIAL (
    ID_INITIAL  DID3 primary key,
    NUM_CPT        DIDLIB9,
    LIBELLE_CPT    DLIB255,
    
    MT_DEBIT    DID9,
    MT_CREDIT    DID9,
    SOLDE DID9,
    
    MT_DEBIT_2    DID9,
    MT_CREDIT_2    DID9,
    SOLDE_2 DID9,
    
    MT_DEBIT_3    DID9,
    MT_CREDIT_3    DID9,
    SOLDE_3 DID9
);

CREATE TABLE INITIAL_COMPL (
    ID_INITIAL_COMPL DID3 primary key,
    ID_COMPL    DID3,
    VALEUR        DLIB255,
    EMPLACEMENT    DLIB255
);

CREATE TABLE FINAL (
    ID_FINAL DID3 primary key,
    CLE        DID3,
    VALEUR        DLIB255,
    ID_DETAIL    DID3
);

CREATE TABLE FINAL_DETAIL (
	ID_FINAL_DETAIL     DID3 primary key,
    ID_DETAIL    DID3,
    NUM_CPT      DID3, 
    TYPE_TRAITEMENT    DLIB1
);
