/* Trigger: TBI_REPART */
CREATE TRIGGER TBI_REPART FOR REPART
ACTIVE BEFORE INSERT POSITION 0
as
begin
   If (New.ID_REPART is null) Then
      New.ID_REPART = GEN_ID(NUM_ID_REPART,1);
end
^

/* Trigger: TBI_TOTAUX */
CREATE TRIGGER TBI_TOTAUX FOR TOTAUX
ACTIVE BEFORE INSERT POSITION 0
as
begin
   If (New.ID_TOTAUX is null) Then
      New.ID_TOTAUX = GEN_ID(NUM_ID_TOTAUX,1);
end
^

CREATE TRIGGER TBI_TRAITEMENTS FOR TRAITEMENTS ACTIVE
BEFORE INSERT POSITION 0
as
begin
   If (New.ID_TRAITEMENTS is null) Then
      New.ID_TRAITEMENTS = GEN_ID(NUM_ID_TRAITEMENTS,1);
end
^