package fr.legrain.stock.dto;

// Generated Mar 1, 2007 11:26:10 AM by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import java.util.Date;

import fr.legrain.bdg.model.ModelObject;
import fr.legrain.stock.model.TaLInventaire;
import fr.legrain.validator.LgrHibernateValidated;


/**
 * SWTPrix generated by hbm2java
 */
public class LInventaireDTO extends ModelObject implements java.io.Serializable {




	private static final long serialVersionUID = -1106284744073630599L;


	private Integer id;	

	
	private Integer idInventaire;
	private String codeInventaire;
	private String libelleLInventaire;
	private BigDecimal qteReelle;
	private String un1Inventaire;
	private BigDecimal qteTheorique;
	private BigDecimal qte2LInventaire;
	private BigDecimal ecart;
	private String un2Inventaire;	
	private Integer idLot;
	private String numLot;
	private boolean lotTermine;
	private Date dluo;
	private Boolean ligneControlee = false;
	
	private Integer idArticle;
	private String codeArticle;
	

	private Integer idEntrepot;
	private String codeEntrepot;
	private String emplacement;

	private String codeFamille;
	
	private Integer versionObj;
	private boolean insereAuto=false;
	
	

	public LInventaireDTO() {	
	}

	public LInventaireDTO(Integer id, Integer idInventaire,
			String codeInventaire, String libelleLInventaire,
			BigDecimal qteReelle, String un1Inventaire,
			BigDecimal qteTheorique, BigDecimal qte2lInventaire,
			 String un2Inventaire, String numLot, boolean lotTermine,
			String codeArticle, String codeEntrepot, String emplacement,
			Integer versionObj) {
		super();
		this.id = id;
		this.idInventaire = idInventaire;
		this.codeInventaire = codeInventaire;
		this.libelleLInventaire = libelleLInventaire;
		this.qteReelle = qteReelle;
		this.un1Inventaire = un1Inventaire;
		this.qteTheorique = qteTheorique;
		this.qte2LInventaire = qte2lInventaire;
		this.un2Inventaire = un2Inventaire;
		this.numLot = numLot;
		this.lotTermine = lotTermine;
		this.codeArticle = codeArticle;
		this.codeEntrepot = codeEntrepot;
		this.emplacement = emplacement;
		this.versionObj = versionObj;
	}

	public LInventaireDTO(Integer id, Integer idInventaire,
			String codeInventaire, String libelleLInventaire,
			BigDecimal qteReelle, String un1Inventaire,
			BigDecimal qteTheorique, BigDecimal qte2lInventaire,
			 String un2Inventaire, String numLot, boolean lotTermine,
			String codeArticle, String codeEntrepot, String emplacement,
			Integer versionObj, String codeFamille) {
		super();
		this.id = id;
		this.idInventaire = idInventaire;
		this.codeInventaire = codeInventaire;
		this.libelleLInventaire = libelleLInventaire;
		this.qteReelle = qteReelle;
		this.un1Inventaire = un1Inventaire;
		this.qteTheorique = qteTheorique;
		this.qte2LInventaire = qte2lInventaire;
		this.un2Inventaire = un2Inventaire;
		this.numLot = numLot;
		this.lotTermine = lotTermine;
		this.codeArticle = codeArticle;
		this.codeEntrepot = codeEntrepot;
		this.emplacement = emplacement;
		this.versionObj = versionObj;
		this.codeFamille = codeFamille;
	}
	
	public LInventaireDTO(Integer id, Integer idInventaire,
			String codeInventaire, String libelleLInventaire,
			BigDecimal qteReelle, String un1Inventaire,
			BigDecimal qteTheorique, BigDecimal qte2lInventaire,
			 String un2Inventaire, String numLot, Date dluo, boolean lotTermine, //+ champ dluo
			String codeArticle, String codeEntrepot, String emplacement,
			Integer versionObj, String codeFamille, Boolean ligneControlee) {
		super();
		this.id = id;
		this.idInventaire = idInventaire;
		this.codeInventaire = codeInventaire;
		this.libelleLInventaire = libelleLInventaire;
		this.qteReelle = qteReelle;
		this.un1Inventaire = un1Inventaire;
		this.qteTheorique = qteTheorique;
		this.qte2LInventaire = qte2lInventaire;
		this.un2Inventaire = un2Inventaire;
		this.numLot = numLot;
		this.dluo = dluo;
		this.lotTermine = lotTermine;
		this.codeArticle = codeArticle;
		this.codeEntrepot = codeEntrepot;
		this.emplacement = emplacement;
		this.versionObj = versionObj;
		this.codeFamille = codeFamille;
		this.ligneControlee = ligneControlee;
	}
	
	public LInventaireDTO(Integer id, Integer idInventaire,
			String codeInventaire, String libelleLInventaire,
			BigDecimal qteReelle, String un1Inventaire,
			BigDecimal qteTheorique, BigDecimal qte2lInventaire,
			 String un2Inventaire, String numLot, boolean lotTermine,
			String codeArticle, String codeEntrepot, String emplacement,
			String codeFamille,
			Integer versionObj) {
		super();
		this.id = id;
		this.idInventaire = idInventaire;
		this.codeInventaire = codeInventaire;
		this.libelleLInventaire = libelleLInventaire;
		this.qteReelle = qteReelle;
		this.un1Inventaire = un1Inventaire;
		this.qteTheorique = qteTheorique;
		this.qte2LInventaire = qte2lInventaire;
		this.un2Inventaire = un2Inventaire;
		this.numLot = numLot;
		this.lotTermine = lotTermine;
		this.codeArticle = codeArticle;
		this.codeEntrepot = codeEntrepot;
		this.emplacement = emplacement;
		this.codeFamille = codeFamille;
		this.versionObj = versionObj;
	}
	public Integer getId() {
		return id;
	}

	public void setId(Integer idLInventaire) {
		firePropertyChange("idLInventaire", this.id, this.id = idLInventaire);
	}

	public Integer getIdInventaire() {
		return idInventaire;
	}


	public void setIdInventaire(Integer idInventaire) {
		firePropertyChange("idInventaire", this.idInventaire, this.idInventaire = idInventaire);
	}

	public String getCodeInventaire() {
		return codeInventaire;
	}


	public void setCodeInventaire(String codeInventaire) {
		firePropertyChange("codeInventaire", this.codeInventaire, this.codeInventaire = codeInventaire);
	}



	public Integer getIdEntrepot() {
		return idEntrepot;
	}


	public void setIdEntrepot(Integer idEntrepot) {
		firePropertyChange("idEntrepot", this.idEntrepot, this.idEntrepot = idEntrepot);
	}


	public String getCodeEntrepot() {
		return codeEntrepot;
	}


	public void setCodeEntrepot(String codeEntrepot) {
		firePropertyChange("codeEntrepot", this.codeEntrepot, this.codeEntrepot = codeEntrepot);
	}


	public String getEmplacement() {
		return emplacement;
	}


	public void setEmplacement(String emplacement) {
		firePropertyChange("emplacement", this.emplacement, this.emplacement = emplacement);
	}

//
//	public Integer getIdLot() {
//		return idLot;
//	}
//
//
//	public void setIdLot(Integer idLot) {
//		firePropertyChange("idLot", this.idLot, this.idLot = idLot);
//	}


	public String getNumLot() {
		return numLot;
	}


	public void setNumLot(String numLot) {
		firePropertyChange("numLot", this.numLot, this.numLot = numLot);
	}


	public String getLibelleLInventaire() {
		return libelleLInventaire;
	}


	public void setLibelleLInventaire(String libelleLInventaire) {
		firePropertyChange("libelleLInventaire", this.libelleLInventaire, this.libelleLInventaire = libelleLInventaire);
	}


	@LgrHibernateValidated(champBd = "qte_reelle",table = "ta_l_inventaire", champEntite="qteReelle", clazz = LInventaireDTO.class)
	public BigDecimal getQteReelle() {
		return qteReelle;
	}


	public void setQteReelle(BigDecimal qteReelle) {
		firePropertyChange("qteReelle", this.qteReelle, this.qteReelle = qteReelle);
	}


	public String getUn1Inventaire() {
		return un1Inventaire;
	}


	public void setUn1Inventaire(String un1Inventaire) {
		firePropertyChange("un1Inventaire", this.un1Inventaire, this.un1Inventaire = un1Inventaire);
	}


	public BigDecimal getQteTheorique() {
		return qteTheorique;
	}


	public void setQteTheorique(BigDecimal qteTheorique) {
		firePropertyChange("qteTheorique", this.qteTheorique, this.qteTheorique = qteTheorique);
	}


	
	public Integer getVersionObj() {
		return this.versionObj;
	}

	public void setVersionObj(Integer versionObj) {
		this.versionObj = versionObj;
	}


	public Integer getIdArticle() {
		return idArticle;
	}


	public void setIdArticle(Integer idArticle) {
		firePropertyChange("idArticle", this.idArticle, this.idArticle = idArticle);
	}


	public String getCodeArticle() {
		return codeArticle;
	}


	public void setCodeArticle(String codeArticle) {
		firePropertyChange("codeArticle", this.codeArticle, this.codeArticle = codeArticle);
	}


	public BigDecimal getEcart() {
		return ecart;
	}


	public void setEcart(BigDecimal ecart) {
		firePropertyChange("ecart", this.ecart, this.ecart = ecart);
	}


	public BigDecimal getQte2LInventaire() {
		return qte2LInventaire;
	}


	public void setQte2LInventaire(BigDecimal qte2LInventaire) {
		firePropertyChange("qte2LInventaire", this.qte2LInventaire, this.qte2LInventaire = qte2LInventaire);
	}


	public String getUn2Inventaire() {
		return un2Inventaire;
	}


	public void setUn2Inventaire(String un2Inventaire) {
		firePropertyChange("un2Inventaire", this.un2Inventaire, this.un2Inventaire = un2Inventaire);
	}


	public Integer getIdLot() {
		return idLot;
	}


	public void setIdLot(Integer idLot) {
		firePropertyChange("idLot", this.idLot, this.idLot = idLot);
	}

	public boolean isInsereAuto() {
		return insereAuto;
	}

	public void setInsereAuto(boolean insereAuto) {
		this.insereAuto = insereAuto;
	}

	public String getCodeFamille() {
		return codeFamille;
	}

	public void setCodeFamille(String codeFamille) {
		firePropertyChange("codeFamille", this.codeFamille, this.codeFamille = codeFamille);
	}

	public boolean isLotTermine() {
		return lotTermine;
	}

	public void setLotTermine(boolean lotTermine) {
		this.lotTermine = lotTermine;
	}

	public Date getDluo() {
		return dluo;
	}

	public void setDluo(Date dluo) {
		this.dluo = dluo;
	}

	public Boolean getLigneControlee() {
		return ligneControlee;
	}

	public void setLigneControlee(Boolean ligneControlee) {
		this.ligneControlee = ligneControlee;
	}


	
}
