package fr.legrain.document.model;

//Generated Apr 9, 2009 12:40:07 PM by Hibernate Tools 3.2.0.CR1

import java.beans.PropertyChangeEvent;
import java.math.BigDecimal;
import java.math.MathContext;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.OrderBy;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

import org.apache.log4j.Logger;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

import com.fasterxml.jackson.annotation.JsonIgnore;

import fr.legrain.document.dto.IDocumentCalcul;
import fr.legrain.document.dto.IDocumentTiers;
import fr.legrain.document.dto.IInfosDocumentTiers;
import fr.legrain.document.dto.ILigneDocumentTiers;
import fr.legrain.document.events.SWTModificationDocumentEvent;
import fr.legrain.lib.data.ChangeModeEvent;
import fr.legrain.lib.data.ChangeModeListener;
import fr.legrain.lib.data.EnumModeObjet;
import fr.legrain.lib.data.ExceptLgr;
import fr.legrain.lib.data.LibCalcul;
import fr.legrain.lib.data.LibConversion;
import fr.legrain.tiers.model.TaAdresse;
import fr.legrain.tiers.model.TaCPaiement;
import fr.legrain.tiers.model.TaTiers;
import fr.legrain.validator.LgrHibernateValidated;

/**
 * TaApporteur generated by hbm2java
 */
@Entity
@EntityListeners(SwtDocumentListener.class)
//@Cache(usage=CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "ta_apporteur", uniqueConstraints = @UniqueConstraint(columnNames = "code_document"))
//@SequenceGenerator(name = "gen_apporteur", sequenceName = "num_id_apporteur", allocationSize = 1)
@NamedQueries(value = { 
		@NamedQuery(name=TaApporteur.QN.FIND_BY_DATEEXPORT_LIGHT, query="select new fr.legrain.document.dto.TaApporteurDTO(f.idDocument, f.codeDocument, f.dateDocument, f.libelleDocument, tiers.codeTiers, infos.nomTiers,f.dateEchDocument,f.dateExport,f.netHtCalc,f.netTtcCalc) from TaApporteur f join f.taInfosDocument infos join f.taTiers tiers where f.taTiers.codeTiers like :codeTiers and  f.dateExport =:date order by f.dateDocument"),
		@NamedQuery(name=TaApporteur.QN.FIND_BY_TIERS_AND_DATE_LIGHT, query="select new fr.legrain.document.dto.TaApporteurDTO(f.idDocument, f.codeDocument, f.dateDocument, f.libelleDocument, tiers.codeTiers, infos.nomTiers,f.dateEchDocument,f.dateExport,f.netHtCalc,f.netTtcCalc) from TaApporteur f join f.taInfosDocument infos join f.taTiers tiers  where f.taTiers.codeTiers like :codeTiers and f.dateDocument between :dateDeb and :dateFin order by f.codeDocument"),
		@NamedQuery(name=TaApporteur.QN.FIND_BY_DATE_EXPORT_LIGHT, query="select new fr.legrain.document.dto.TaApporteurDTO(f.idDocument, f.codeDocument, f.dateDocument, f.libelleDocument, tiers.codeTiers, infos.nomTiers,f.dateEchDocument,f.dateExport,f.netHtCalc,f.netTtcCalc) from TaApporteur f join f.taInfosDocument infos join f.taTiers tiers  where f.taTiers.codeTiers like :codeTiers and f.dateDocument between :dateDeb and :dateFin  and f.dateExport is not null order by f.codeDocument"), 
		@NamedQuery(name=TaApporteur.QN.FIND_BY_DATE, query="select a from TaApporteur a where a.taTiers.codeTiers like :codeTiers and  a.dateDocument between :dateDeb and :dateFin order by a.codeDocument"),
		@NamedQuery(name=TaApporteur.QN.FIND_BY_TIERS_AND_CODE_LIGHT, query="select f.idDocument, f.codeDocument, f.dateDocument, f.libelleDocument, tiers.codeTiers, infos.nomTiers,f.dateEchDocument,f.dateExport,f.netHtCalc,f.netTtcCalc from TaApporteur f join f.taInfosDocument infos join f.taTiers tiers where tiers.codeTiers like :codeTiers and f.codeDocument like :codeDocument order by f.codeDocument"),
		@NamedQuery(name=TaApporteur.QN.FIND_BY_DATE_LIGHT, query="select f.idDocument, f.codeDocument, f.dateDocument, f.libelleDocument, tiers.codeTiers, infos.nomTiers,f.dateEchDocument,f.dateExport,f.netHtCalc,f.netTtcCalc from TaApporteur f join f.taInfosDocument infos join f.taTiers tiers where tiers.codeTiers like :codeTiers and f.dateDocument between :dateDeb and :dateFin order by f.codeDocument"),
		@NamedQuery(name=TaApporteur.QN.FIND_BY_DATE_PARDATE, query="select a from TaApporteur a where a.taTiers.codeTiers like :codeTiers and a.dateDocument between :dateDeb and :dateFin order by a.dateDocument"),
		@NamedQuery(name=TaApporteur.QN.FIND_BY_DATE_NON_EXPORT, query="select a from TaApporteur a where a.taTiers.codeTiers like :codeTiers and a.dateDocument between :dateDeb and :dateFin  and a.dateExport is null order by a.codeDocument"), 
		@NamedQuery(name=TaApporteur.QN.FIND_BY_CODE_NON_EXPORT, query="select a from TaApporteur a where a.taTiers.codeTiers like :codeTiers and a.codeDocument between :dateDeb and :dateFin and a.dateExport is null order by a.codeDocument"),
		@NamedQuery(name=TaApporteur.QN.FIND_BY_DATE_NON_EXPORT_PARDATE, query="select a from TaApporteur a where a.taTiers.codeTiers like :codeTiers and a.dateDocument between :dateDeb and :dateFin  and a.dateExport is null order by a.dateDocument"),
		@NamedQuery(name=TaApporteur.QN.FIND_BY_DATE_NON_EXPORT_LIGHT, query="select new fr.legrain.document.dto.TaApporteurDTO(f.idDocument, f.codeDocument, f.dateDocument, f.libelleDocument, tiers.codeTiers, infos.nomTiers,f.dateEchDocument,f.dateExport,f.netHtCalc,f.netTtcCalc) from TaApporteur f join f.taInfosDocument infos join f.taTiers tiers where f.taTiers.codeTiers like :codeTiers and f.dateDocument between :dateDeb and :dateFin  and f.dateExport is null order by f.codeDocument"), 
		@NamedQuery(name=TaApporteur.QN.FIND_BY_DATEEXPORT, query="select a from TaApporteur a where a.taTiers.codeTiers like :codeTiers and a.dateExport =:date order by a.codeDocument"), 
		@NamedQuery(name=TaApporteur.QN.FIND_BY_CODE_NON_EXPORT_LIGHT, query="select new fr.legrain.document.dto.TaApporteurDTO(f.idDocument, f.codeDocument, f.dateDocument, f.libelleDocument, tiers.codeTiers, infos.nomTiers,f.dateEchDocument,f.dateExport,f.netHtCalc,f.netTtcCalc) from TaApporteur f join f.taInfosDocument infos join f.taTiers tiers where f.taTiers.codeTiers like :codeTiers and f.codeDocument between :dateDeb and :dateFin and f.dateExport is null order by f.codeDocument"),
		@NamedQuery(name=TaApporteur.QN.FIND_BY_DATE_NON_EXPORT_PARDATE_LIGHT, query="select new fr.legrain.document.dto.TaApporteurDTO(f.idDocument, f.codeDocument, f.dateDocument, f.libelleDocument, tiers.codeTiers, infos.nomTiers,f.dateEchDocument,f.dateExport,f.netHtCalc,f.netTtcCalc) from TaApporteur f join f.taInfosDocument infos join f.taTiers tiers where f.taTiers.codeTiers like :codeTiers and f.dateDocument between :dateDeb and :dateFin  and f.dateExport is null order by f.dateDocument"),
		@NamedQuery(name=TaApporteur.QN.FIND_BY_DATE_EXPORT, query="select a from TaApporteur a where a.taTiers.codeTiers like :codeTiers and a.dateDocument between :dateDeb and :dateFin  and a.dateExport is not null order by a.codeDocument"), 
		@NamedQuery(name=TaApporteur.QN.FIND_BY_CODE_EXPORT, query="select a from TaApporteur a where a.taTiers.codeTiers like :codeTiers and a.codeDocument between :dateDeb and :dateFin and a.dateExport is not null order by a.codeDocument"),
		@NamedQuery(name=TaApporteur.QN.FIND_BY_TIERS_AND_CODE, query="select a from TaApporteur a where a.taTiers.codeTiers like :codeTiers and a.codeDocument between :dateDeb and :dateFin order by a.codeDocument"),
		@NamedQuery(name=TaApporteur.QN.FIND_BY_CODE, query="select a from TaApporteur a where a.taTiers.codeTiers like :codeTiers and  a.codeDocument between :dateDeb and :dateFin order by a.codeDocument"),
		@NamedQuery(name=TaApporteur.QN.FIND_ALL_LIGHT, query="select new fr.legrain.document.dto.TaApporteurDTO(f.idDocument, f.codeDocument, f.dateDocument, f.libelleDocument, tiers.codeTiers, infos.nomTiers,infos.prenomTiers, "
				+ " infos.nomEntreprise,f.dateEchDocument,f.netHtCalc,f.netTvaCalc,f.netTtcCalc,f.dateExport,f.dateVerrouillage, mad.accessibleSurCompteClient, mad.envoyeParEmail, mad.imprimePourClient) from TaApporteur f join f.taInfosDocument infos join f.taTiers tiers left join f.taMiseADisposition mad order by f.dateDocument DESC, f.codeDocument DESC"),		
		@NamedQuery(name=TaApporteur.QN.FIND_BY_TIERS_AND_DATE, query="select a from TaApporteur a where a.taTiers.codeTiers like :codeTiers and a.dateDocument between :dateDeb and :dateFin order by a.codeDocument")
})
public class TaApporteur extends SWTDocument implements ChangeModeListener, java.io.Serializable, 
IDocumentTiers, IDocumentCalcul {

	private static final long serialVersionUID = -7887237028022654107L;
	
	public static final String TYPE_DOC = "Apporteur";
	public static final String PATH_ICONE_COULEUR = "dashboard/fact-apporteur.svg";
	public static final String PATH_ICONE_BLANC = "";
	public static final String PATH_ICONE_GRIS = "";
	public static class QN {
		public static final String FIND_BY_DATE = "TaApporteur.findEntre2Date";
		public static final String FIND_BY_TIERS_AND_CODE_LIGHT = "TaApporteur.findEntre2CodeParCodeLight";
		public static final String FIND_BY_DATE_EXPORT_LIGHT = "TaApporteur.findEntre2DateExporteLight";
		public static final String FIND_BY_DATE_LIGHT = "TaApporteur.findEntre2DateLight";
		public static final String FIND_BY_DATE_NON_EXPORT = "TaApporteur.findEntre2DateNonExporte";
		public static final String FIND_BY_CODE_NON_EXPORT = "TaApporteur.findEntre2CodeNonExporte";
		public static final String FIND_BY_DATE_NON_EXPORT_PARDATE = "TaApporteur.findEntre2DateNonExporteParDate";
		public static final String FIND_BY_DATE_NON_EXPORT_LIGHT = "TaApporteur.findEntre2DateNonExporteLight";
		public static final String FIND_BY_CODE_NON_EXPORT_LIGHT = "TaApporteur.findEntre2CodeNonExporteLight";
		public static final String FIND_BY_DATE_NON_EXPORT_PARDATE_LIGHT = "TaApporteur.findEntre2DateNonExporteParDateLight";
		public static final String FIND_BY_DATE_EXPORT = "TaApporteur.findEntre2DateExporte";
		public static final String FIND_BY_CODE_EXPORT = "TaApporteur.findEntre2CodeExporte";
		public static final String FIND_BY_CODE = "TaApporteur.findEntre2Code";
		public static final String FIND_BY_TIERS_AND_CODE = "TaApporteur.findEntre2CodeParCode";
		public static final String FIND_BY_TIERS_AND_DATE = "TaApporteur.findTiersEntre2Date";
		public static final String FIND_BY_DATE_PARDATE = "TaApporteur.findEntre2DateParDate";
		public static final String FIND_BY_DATEEXPORT = "TaApporteur.findDateExporte";
		public static final String FIND_ALL_LIGHT = "TaApporteur.findAllLight";
		public static final String FIND_BY_DATEEXPORT_LIGHT = "TaApporteur.findDateExporteLight";     
		public static final String FIND_BY_TIERS_AND_DATE_LIGHT = "TaApporteur.findTiersEntre2DateLight";

	}

	//	private int idDocument;
	private String version;
	private TaTPaiement taTPaiement;
	private TaTiers taTiers;
	//private TaCPaiement taCPaiement;

	private String codeDocument;
	private Date dateDocument;
	private Date dateEchDocument;
	private Date dateLivDocument;
	private Date dateExport;
	private String libelleDocument;
	private BigDecimal regleDocument = new BigDecimal(0);
	private BigDecimal remHtDocument = new BigDecimal(0);
	private BigDecimal txRemHtDocument = new BigDecimal(0);
	private BigDecimal remTtcDocument = new BigDecimal(0);
	private BigDecimal txRemTtcDocument = new BigDecimal(0);
	private Integer nbEDocument = 0;
	private Integer ttc = 0;
//	private Integer export = 0;
	private String commentaire;
	private String ipAcces;
	private Boolean gestionLot = false;
	private Boolean mouvementerStock = true;
	private Date dateVerrouillage;
	
	protected Integer nbDecimalesPrix;
	protected Integer nbDecimalesQte;
	
	//	private Integer versionObj;
	private TaEtat taEtat;
	private TaInfosApporteur taInfosDocument;
	private TaMiseADisposition taMiseADisposition;
	private Set<TaRDocument> taRDocuments = new HashSet<TaRDocument>(0);
	private Set<TaRAcompte> taRAcomptes = new HashSet<TaRAcompte>(0);
	private Set<TaREtat> taREtats = new HashSet<TaREtat>(0);
	private Set<TaHistREtat> taHistREtats = new HashSet<TaHistREtat>(0);
	
	@Transient
	private ArrayList<LigneTva> lignesTVA = null; //ensemble des lignes de tva du document
	@Transient
	private boolean gestionTVA = true;
	@Transient
	static Logger logger = Logger.getLogger(TaApporteur.class.getName());

	//	@Transient
	private BigDecimal mtTtcCalc = new BigDecimal(0);
	//	@Transient
	private BigDecimal mtHtCalc = new BigDecimal(0);
	//	@Transient
	private BigDecimal mtTvaCalc = new BigDecimal(0);
	//	@Transient
	private BigDecimal netTtcCalc = new BigDecimal(0);
	//	@Transient
	private BigDecimal netHtCalc = new BigDecimal(0);
	//	@Transient
	private BigDecimal netTvaCalc = new BigDecimal(0);
	//	@Transient
	private BigDecimal netAPayer = new BigDecimal(0);
	//	@Transient
	private BigDecimal mtTtcAvantRemiseGlobaleCalc = new BigDecimal(0);

	@Transient
	private BigDecimal remTtcIntermediaireDocument = new BigDecimal(0);
	
	@Transient
	private boolean legrain = false;
	
	protected Boolean utiliseUniteSaisie = true;

	private Set<TaRReglementLiaison> taRReglementLiaisons = new HashSet<TaRReglementLiaison>(0);

	public TaApporteur(boolean legrain) {
		this.legrain = legrain;
		lignes = new ArrayList<TaLApporteur>(0);
		lignesTVA = new ArrayList<LigneTva>();
	}

	public TaApporteur() {
		lignes = new ArrayList<TaLApporteur>(0);
		lignesTVA = new ArrayList<LigneTva>();
	}

	public TaApporteur(int idApporteur) {
		this.idDocument = idApporteur;
		lignes = new ArrayList<TaLApporteur>(0);
		lignesTVA = new ArrayList<LigneTva>();
	}

	public TaApporteur(String oldCodeApporteur) {
		super(oldCodeApporteur);
		legrain = true;
		lignes = new ArrayList<TaLApporteur>(0);
		this.lignesTVA = new ArrayList<LigneTva>();
		//passage ejb
//		this.modeDocument = EnumModeObjet.C_MO_INSERTION;
	}

	public TaApporteur(int idApporteur, TaTPaiement taTPaiement, TaTiers taTiers,
			TaCPaiement taCPaiement, TaAdresse taAdresseByIdAdresse,
			TaAdresse taAdresseByIdAdresseLiv, String codeApporteur,
			Date dateApporteur, Date dateEchApporteur, Date dateLivApporteur,
			String libelleApporteur, BigDecimal regleApporteur,
			BigDecimal remHtApporteur, BigDecimal txRemHtApporteur,
			BigDecimal remTtcApporteur, BigDecimal txRemTtcApporteur,
			Integer nbEApporteur, Integer ttc, Integer export, String commentaire,
			String quiCreeApporteur, Date quandCreeApporteur,
			String quiModifApporteur, Date quandModifApporteur, String ipAcces,
			Integer versionObj, List<TaLApporteur> taLApporteurs,
			TaInfosApporteur taInfosApporteurs, Set<TaRDocument> taRDocuments) {
		this.idDocument = idApporteur;
		this.taTPaiement = taTPaiement;
		this.taTiers = taTiers;
		//this.taCPaiement = taCPaiement;
		this.codeDocument = codeApporteur;
		this.dateDocument = dateApporteur;
		this.dateEchDocument = dateEchApporteur;
		this.dateLivDocument = dateLivApporteur;
		this.libelleDocument = libelleApporteur;
		this.regleDocument = regleApporteur;
		this.remHtDocument = remHtApporteur;
		this.txRemHtDocument = txRemHtApporteur;
		this.remTtcDocument = remTtcApporteur;
		this.txRemTtcDocument = txRemTtcApporteur;
		this.nbEDocument = nbEApporteur;
		this.ttc = ttc;
//		this.export = export;
		this.commentaire = commentaire;
		this.quiCree = quiCreeApporteur;
		this.quandCree = quandCreeApporteur;
		this.quiModif = quiModifApporteur;
		this.quandModif = quandModifApporteur;
		this.ipAcces = ipAcces;
		this.versionObj = versionObj;
		this.lignes = taLApporteurs;
		this.taInfosDocument = taInfosApporteurs;
		this.taRDocuments = taRDocuments;
	}

	//	@Id
	//	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "gen_apporteur")
	//	@Column(name = "id_document", unique = true, nullable = false)
	//	@LgrHibernateValidated(champ = "id_document",table = "ta_apporteur",clazz = TaApporteur.class)
	//	public int getIdDocument() {
	//		return this.idDocument;
	//	}
	//
	//	public void setIdDocument(int idApporteur) {
	//		this.idDocument = idApporteur;
	//	}

	@Column(name = "version", length = 20)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_t_paiement")
	@LgrHibernateValidated(champBd = "id_t_paiement",table = "ta_t_paiement",champEntite="TaTPaiement.idTPaiement",clazz = TaTPaiement.class)
	public TaTPaiement getTaTPaiement() {
		return this.taTPaiement;
	}

	public void setTaTPaiement(TaTPaiement taTPaiement) {
		this.taTPaiement = taTPaiement;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_tiers")
	@LgrHibernateValidated(champBd = "id_tiers",table = "ta_tiers",champEntite="TaTiers.idTiers",clazz = TaTiers.class)
	public TaTiers getTaTiers() {
		return this.taTiers;
	}

	public void setTaTiers(TaTiers taTiers) {
		if(taRAcomptes.size()==0 || rechercheSiMemeTiers(taTiers))
			this.taTiers = taTiers;
	}

	public boolean rechercheSiMemeTiers(TaTiers taTiers){
		for (TaRAcompte acompte : taRAcomptes) {
			if(acompte.getTaAcompte().getTaTiers()!=null)
				if (!acompte.getTaAcompte().getTaTiers().equals(taTiers))
					return false;
		}
		return true;
	}

	//	@ManyToOne(fetch = FetchType.LAZY)
	//	@JoinColumn(name = "id_c_paiement")
	//	@LgrHibernateValidated(champ = "id_c_paiement",table = "ta_c_paiement",clazz = TaCPaiement.class)
	//	public TaCPaiement getTaCPaiement() {
	//		return this.taCPaiement;
	//	}
	//
	//	public void setTaCPaiement(TaCPaiement taCPaiement) {
	//		this.taCPaiement = taCPaiement;
	//	}



	@Column(name = "code_document", unique = true, length = 20)
	@LgrHibernateValidated(champBd = "code_document",table = "ta_apporteur",champEntite="codeDocument",clazz = TaApporteur.class)
	public String getCodeDocument() {
		return this.codeDocument;
	}

	public void setCodeDocument(String codeApporteur) {
		this.codeDocument = codeApporteur;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_document", length = 19)
	@LgrHibernateValidated(champBd = "date_document",table = "ta_apporteur",champEntite="dateDocument",clazz = TaApporteur.class)
	public Date getDateDocument() {
		return this.dateDocument;
	}

	public void setDateDocument(Date dateFacture) {
		if(this.oldDate==null)this.oldDate=dateFacture;
		else
		if(this.dateDocument==null||
				this.dateDocument.compareTo(dateFacture)!=0)
			this.oldDate=this.dateDocument;
		this.dateDocument = dateFacture;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_ech_document", length = 19)
	@LgrHibernateValidated(champBd = "date_ech_document",table = "ta_apporteur",champEntite="dateEchDocument",clazz = TaApporteur.class)
	public Date getDateEchDocument() {
		return this.dateEchDocument;
	}

	public void setDateEchDocument(Date dateEchApporteur) {
		this.dateEchDocument = dateEchApporteur;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_liv_document", length = 19)
	@LgrHibernateValidated(champBd = "date_liv_document",table = "ta_apporteur",champEntite="dateLivDocument",clazz = TaApporteur.class)
	public Date getDateLivDocument() {
		return this.dateLivDocument;
	}

	public void setDateLivDocument(Date dateLivApporteur) {
		this.dateLivDocument = dateLivApporteur;
	}

	@Column(name = "libelle_document")
	@LgrHibernateValidated(champBd = "libelle_document",table = "ta_apporteur",champEntite="libelleDocument",clazz = TaApporteur.class)
	public String getLibelleDocument() {
		return this.libelleDocument;
	}

	public void setLibelleDocument(String libelleApporteur) {
		this.libelleDocument = libelleApporteur;
	}

	@Column(name = "regle_document", precision = 15)
	@LgrHibernateValidated(champBd = "regle_document",table = "ta_apporteur",champEntite="regleDocument",clazz = TaApporteur.class)
	public BigDecimal getRegleDocument() {
		return this.regleDocument;
	}

	public void setRegleDocument(BigDecimal regleApporteur) {
		if(regleDocument==null)regleDocument=new BigDecimal(0);
		if(this.regleDocument!=null && this.regleDocument.compareTo(regleDocument)!=0){	
			this.regleDocument = regleApporteur;		
			if(legrain) {
				System.out.println("===****=== Transfert de code metier des entites vers les services, à bien vérifier");
				//passage ejb => dans TaApporteurService
//				calculTotaux();
				try {
					fireModificationDocument(new SWTModificationDocumentEvent(this));
				} catch (Exception e) {
					logger.error("",e);
				}
			}
		}
	}	

	@Column(name = "rem_ht_document", precision = 15)
	@LgrHibernateValidated(champBd = "rem_ht_document",table = "ta_apporteur",champEntite="remHtDocument",clazz = TaApporteur.class)
	public BigDecimal getRemHtDocument() {
		return this.remHtDocument;
	}

	public void setRemHtDocument(BigDecimal remHtApporteur) {
		this.remHtDocument = remHtApporteur;
	}

	@Column(name = "tx_rem_ht_document", precision = 15)
	@LgrHibernateValidated(champBd = "tx_rem_ht_document",table = "ta_apporteur",champEntite="txRemHtDocument",clazz = TaApporteur.class)
	public BigDecimal getTxRemHtDocument() {
		return this.txRemHtDocument;
	}

	public void setTxRemHtDocument(BigDecimal txRemHtApporteur) {
		if(txRemHtApporteur==null)txRemHtApporteur=new BigDecimal(0);
		if(this.txRemHtDocument!=null && this.txRemHtDocument.compareTo(txRemHtApporteur)!=0){	
			this.txRemHtDocument = txRemHtApporteur;
			if(legrain) {
				System.out.println("===****=== Transfert de code metier des entites vers les services, à bien vérifier");
				//passage ejb => dans TaApporteurService
				calculeTvaEtTotaux();
				try {
					fireModificationDocument(new SWTModificationDocumentEvent(this));
				} catch (Exception e) {
					logger.error("",e);
				}
			}
		}
	}

	@Column(name = "rem_ttc_document", precision = 15)
	@LgrHibernateValidated(champBd = "rem_ttc_document",table = "ta_apporteur",champEntite="remTtcDocument",clazz = TaApporteur.class)
	public BigDecimal getRemTtcDocument() {
		return this.remTtcDocument;
	}

	public void setRemTtcDocument(BigDecimal remTtcApporteur) {
		this.remTtcDocument = remTtcApporteur;
	}

	@Column(name = "tx_rem_ttc_document", precision = 15)
	@LgrHibernateValidated(champBd = "tx_rem_ttc_document",table = "ta_apporteur",champEntite="txRemTtcDocument",clazz = TaApporteur.class)
	public BigDecimal getTxRemTtcDocument() {
		return this.txRemTtcDocument;
	}

	public void setTxRemTtcDocument(BigDecimal txRemTtcApporteur) {
		if(txRemTtcApporteur==null)txRemTtcApporteur=new BigDecimal(0);
		if(this.txRemTtcDocument!=null && this.txRemTtcDocument.compareTo(txRemTtcApporteur)!=0){	
			this.txRemTtcDocument = txRemTtcApporteur;
			if(legrain) {
				System.out.println("===****=== Transfert de code metier des entites vers les services, à bien vérifier");
				//passage ejb => dans TaApporteurService
				calculeTvaEtTotaux();
				try {
					fireModificationDocument(new SWTModificationDocumentEvent(this,"txRemTtcDocument"));
				} catch (Exception e) {
					logger.error("",e);
				}
			}
		}
	}

	@Column(name = "nb_e_document")
	@LgrHibernateValidated(champBd = "nb_e_document",table = "ta_apporteur",champEntite="nbEDocument",clazz = TaApporteur.class)
	public Integer getNbEDocument() {
		return this.nbEDocument;
	}

	public void setNbEDocument(Integer nbEApporteur) {
		this.nbEDocument = nbEApporteur;
	}

	@Column(name = "ttc")
	@LgrHibernateValidated(champBd = "ttc",table = "ta_apporteur",champEntite="ttc",clazz = TaApporteur.class)
	public Integer getTtc() {
		return this.ttc;
	}

	public void setTtc(Integer ttc) {
		this.ttc = ttc;
	}

//	@Column(name = "export")
//	@LgrHibernateValidated(champBd = "export",table = "ta_apporteur",champEntite="export",clazz = TaApporteur.class)
//	public Integer getExport() {
//		return this.export;
//	}
//
//	public void setExport(Integer export) {
//		this.export = export;
//	}

	@Column(name = "commentaire", length = 2000)
	@LgrHibernateValidated(champBd = "commentaire",table = "ta_apporteur",champEntite="commentaire",clazz = TaApporteur.class)
	public String getCommentaire() {
		return this.commentaire;
	}

	public void setCommentaire(String commentaire) {
		if(this.commentaire==null||(commentaire!=null &&
				this.commentaire.compareTo(commentaire)!=0)){
			this.commentaire = commentaire;		
			if(legrain) {
				try {
					fireModificationDocument(new SWTModificationDocumentEvent(this));
				} catch (Exception e) {
					logger.error("",e);
				}
			}
		}
	}

	@Column(name = "qui_cree", length = 50)
	public String getQuiCree() {
		return this.quiCree;
	}

	public void setQuiCree(String quiCreeApporteur) {
		this.quiCree = quiCreeApporteur;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "quand_cree", length = 19)
	public Date getQuandCree() {
		return this.quandCree;
	}

	public void setQuandCree(Date quandCreeApporteur) {
		this.quandCree = quandCreeApporteur;
	}

	@Column(name = "qui_modif", length = 50)
	public String getQuiModif() {
		return this.quiModif;
	}

	public void setQuiModif(String quiModifApporteur) {
		this.quiModif = quiModifApporteur;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "quand_modif", length = 19)
	public Date getQuandModif() {
		return this.quandModif;
	}

	public void setQuandModif(Date quandModifApporteur) {
		this.quandModif = quandModifApporteur;
	}

	@Column(name = "ip_acces", length = 50)
	public String getIpAcces() {
		return this.ipAcces;
	}

	public void setIpAcces(String ipAcces) {
		this.ipAcces = ipAcces;
	}

	//	@Version
	//	@Column(name = "version_obj")
	//	public Integer getVersionObj() {
	//		return this.versionObj;
	//	}
	//
	//	public void setVersionObj(Integer versionObj) {
	//		this.versionObj = versionObj;
	//	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER, mappedBy = "taDocument", orphanRemoval=true)
	@OrderBy("numLigneLDocument")
	@Fetch(FetchMode.SUBSELECT)
	public List<TaLApporteur> getLignes() {
		return this.lignes;
	}

	public void setLignes(List<TaLApporteur> taLApporteurs) {
		this.lignes = taLApporteurs;
	}

//	@javax.persistence.OneToOne(cascade = CascadeType.ALL, fetch = FetchType.EAGER, mappedBy = "taDocument")
	@OneToOne(fetch = FetchType.EAGER, cascade = CascadeType.ALL , orphanRemoval=true, optional=false)
	@JoinColumn(name = "id_infos_document")
	public TaInfosApporteur getTaInfosDocument() {
		return this.taInfosDocument;
	}

	public void setTaInfosDocument(TaInfosApporteur taInfosApporteurs) {
		this.taInfosDocument = taInfosApporteurs;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "taApporteur", orphanRemoval=true)
	public Set<TaRDocument> getTaRDocuments() {
		return this.taRDocuments;
	}

	public void setTaRDocuments(Set<TaRDocument> taRDocuments) {
		this.taRDocuments = taRDocuments;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "taApporteur", orphanRemoval=true)
	public Set<TaRAcompte> getTaRAcomptes(){
		return this.taRAcomptes;
	}

	public void setTaRAcomptes(Set<TaRAcompte> taRAcomptes) {
		this.taRAcomptes = taRAcomptes;
	}
	/**
	 * Initialisation des propriétés de la facture en fonction du tiers
	 */
	public void changementDeTiers() {
//		if(this.taTiers!=null && this.taTiers.getTaTTvaDoc()!=null && 
//				this.taTiers.getTaTTvaDoc().getCodeTTvaDoc()!=null){
//			if(!this.taTiers.getTaTTvaDoc().getCodeTTvaDoc().equals("F")
//					//				||this.taTiers.getTaTTvaDoc().getCodeTTvaDoc().equals("UE")
//					//				||this.taTiers.getTaTTvaDoc().getCodeTTvaDoc().equals("HUE")
//			)
//				setGestionTVA(false);
//			else setGestionTVA(true);
//		}else
//			setGestionTVA(true);
	}

	/*
	 * *********************************************************************************************************************************
	 * *********************************************************************************************************************************
	 * *********************************************************************************************************************************
	 * *********************************************************************************************************************************
	 * *********************************************************************************************************************************
	 * *********************************************************************************************************************************
	 * *********************************************************************************************************************************
	 */
	//	public Integer typeLigne(String CodeTypeLigne) throws SQLException{		
	//		Integer idTLigne;
	//		return  idTLigne =LibConversion.stringToInteger(ibApplication.selectCleEtrangere(Const.C_NOM_TA_T_LIGNE,
	//				Const.C_ID_T_LIGNE, Variant.STRING, Const.C_CODE_T_LIGNE, CodeTypeLigne));		
	//	}

	@Override
	protected boolean beforeAjoutLigne(SWTLigneDocument ligne) {
		// TODO Raccord de méthode auto-généré
		return true;
	}

	@Override
	protected void afterAjoutLigne(SWTLigneDocument ligne) throws ExceptLgr {
		System.out.println("===****=== Transfert de code metier des entites vers les services, à bien vérifier");
		//passage ejb => dans TaApporteurService
		calculeTvaEtTotaux();
		reinitialiseNumLignes();
	}

	@Override
	protected boolean beforeRemoveLigne(SWTLigneDocument ligne) {
		// TODO Raccord de méthode auto-généré
		return true;
	}

	@Override
	protected void afterRemoveLigne(SWTLigneDocument ligne) throws ExceptLgr {
		System.out.println("===****=== Transfert de code metier des entites vers les services, à bien vérifier");
		//passage ejb => dans TaApporteurService
		calculeTvaEtTotaux();
		reinitialiseNumLignes();
	}

	@Transient
	public boolean isGestionTVA() {
		return gestionTVA;
	}

	public void setGestionTVA(boolean gestionTVA) {
		this.gestionTVA = gestionTVA;
	}

	@Transient
	public ArrayList<LigneTva> getLignesTVA() {
		return lignesTVA;
	}

	public void setLignesTVA(ArrayList<LigneTva> lignesTVA) {
		this.lignesTVA = lignesTVA;
	}

	@Override
	protected boolean beforeEnregistrerEntete() {
		// TODO Raccord de méthode auto-généré
		return false;
	}

	@Override
	protected void afterEnregistrerEntete() throws ExceptLgr {
		// TODO Raccord de méthode auto-généré

	}

	@Override
	protected boolean beforeModifierEntete() {
		// TODO Raccord de méthode auto-généré
		return false;
	}

	@Override
	protected void afterModifierEntete() throws ExceptLgr {
		// TODO Raccord de méthode auto-généré

	}

	@Override
	protected boolean beforeSupprimerEntete() {
		// TODO Raccord de méthode auto-généré
		return false;
	}

	@Override
	protected void afterSupprimerEntete() throws ExceptLgr {
		// TODO Raccord de méthode auto-généré

	}



	public void changementMode(ChangeModeEvent evt) {
		// TODO Raccord de méthode auto-généré
		switch (evt.getNouveauMode()) {
		case C_MO_CONSULTATION:
			break;
		case C_MO_EDITION:
			//S'il n'existe pas déjà, charger un objet swtArticle pour la ligne
			break;
		case C_MO_INSERTION:
			//			S'il n'existe pas déjà, charger un objet swtArticle pour la ligne
			break;
		case C_MO_SUPPRESSION:
			break;
		}

	}

	//@Transient
	@Column(name = "mt_ttc_calc", precision = 15)
	@LgrHibernateValidated(champBd = "mt_ttc_calc",table = "ta_apporteur",champEntite="mtTtcCalc",clazz = TaApporteur.class)
	public BigDecimal getMtTtcCalc() {
		return mtTtcCalc;
	}

	public void setMtTtcCalc(BigDecimal mtTtcCalc) {
		this.mtTtcCalc = LibCalcul.arrondi(mtTtcCalc);
	}

	//@Transient
	@Column(name = "mt_ht_calc", precision = 15)
	@LgrHibernateValidated(champBd = "mt_ht_calc",table = "ta_apporteur",champEntite="getMtHtCalc",clazz = TaApporteur.class)
	public BigDecimal getMtHtCalc() {
		return mtHtCalc;
	}

	public void setMtHtCalc(BigDecimal mtHtCalc) {
		this.mtHtCalc = LibCalcul.arrondi(mtHtCalc);
	}

	//@Transient
	@Column(name = "mt_tva_calc", precision = 15)
	@LgrHibernateValidated(champBd = "mt_tva_calc",table = "ta_apporteur",champEntite="mtTvaCalc",clazz = TaApporteur.class)
	public BigDecimal getMtTvaCalc() {
		return mtTvaCalc;
	}

	public void setMtTvaCalc(BigDecimal mtTvaCalc) {
		this.mtTvaCalc = LibCalcul.arrondi(mtTvaCalc);
	}

	//@Transient
	@Column(name = "net_ttc_calc", precision = 15)
	@LgrHibernateValidated(champBd = "net_ttc_calc",table = "ta_apporteur",champEntite="netTtcCalc",clazz = TaApporteur.class)
	public BigDecimal getNetTtcCalc() {
		return netTtcCalc;
	}

	public void setNetTtcCalc(BigDecimal netTtcCalc) {
		this.netTtcCalc = LibCalcul.arrondi(netTtcCalc);
	}

	//@Transient
	@Column(name = "net_ht_calc", precision = 15)
	@LgrHibernateValidated(champBd = "net_ht_calc",table = "ta_apporteur",champEntite="netHtCalc", clazz = TaApporteur.class)
	public BigDecimal getNetHtCalc() {
		return netHtCalc;
	}

	public void setNetHtCalc(BigDecimal netHtCalc) {
		this.netHtCalc = LibCalcul.arrondi(netHtCalc);
	}

	//@Transient
	@Column(name = "net_tva_calc", precision = 15)
	@LgrHibernateValidated(champBd = "net_tva_calc",table = "ta_apporteur",champEntite="netTvaCalc", clazz = TaApporteur.class)
	public BigDecimal getNetTvaCalc() {
		return netTvaCalc;
	}

	public void setNetTvaCalc(BigDecimal netTvaCalc) {
		this.netTvaCalc = LibCalcul.arrondi(netTvaCalc);
	}

	//@Transient
	@Column(name = "net_a_payer", precision = 15)
	@LgrHibernateValidated(champBd = "net_a_payer",table = "ta_apporteur",champEntite="netAPayer",clazz = TaApporteur.class)
	public BigDecimal getNetAPayer() {
		return netAPayer;
	}

	public void setNetAPayer(BigDecimal netAPayer) {
		this.netAPayer = LibCalcul.arrondi(netAPayer);
	}

	//	public void addLigne(TaLApporteur taLApporteur) {
	//		this.getLignes().add(taLApporteur);
	//	}

	//	public void removeLigne(TaLApporteur taLApporteur){
	//		this.getLignes().remove(taLApporteur);
	//	}
	
//passage ejb => dans TaApporteurService

	/**
	 * Reparti le total chaque code TVA sur l'ensemble des lignes concernées par ce code. 
	 */
	public void dispatcherTva() {

		BigDecimal tvaLigne = new BigDecimal(0);
		BigDecimal totalTemp = new BigDecimal(0);

		for (Object ligne : lignes) {
			if(((TaLApporteur)ligne).getMtHtLDocument()!=null)
				totalTemp = totalTemp.add(((TaLApporteur)ligne).getMtHtLDocument());
		}
		if(totalTemp!=null && txRemHtDocument!=null)
			setRemHtDocument(totalTemp.multiply(txRemHtDocument.divide(new BigDecimal(100))).setScale(2,BigDecimal.ROUND_HALF_UP));	
		
		for (TaLApporteur ligne : getLignes()) {
			if(txRemHtDocument!=null && txRemHtDocument.signum()>0 && ligne.getMtHtLDocument()!=null  && ligne.getMtTtcLDocument()!=null) {
				if(ttc==1){
					((TaLApporteur)ligne).setMtTtcLApresRemiseGlobaleDocument(((TaLApporteur)ligne).getMtTtcLDocument().subtract(((TaLApporteur)ligne).getMtTtcLDocument()
							.multiply(txRemHtDocument).divide(new BigDecimal(100),MathContext.DECIMAL128).setScale(2,BigDecimal.ROUND_HALF_UP)));
					((TaLApporteur)ligne).setMtHtLApresRemiseGlobaleDocument(((TaLApporteur)ligne).getMtTtcLApresRemiseGlobaleDocument());
					
				}else{
					((TaLApporteur)ligne).setMtHtLApresRemiseGlobaleDocument(((TaLApporteur)ligne).getMtHtLDocument().subtract(((TaLApporteur)ligne).getMtHtLDocument()
							.multiply(txRemHtDocument).divide(new BigDecimal(100),MathContext.DECIMAL128).setScale(2,BigDecimal.ROUND_HALF_UP)));
					((TaLApporteur)ligne).setMtTtcLApresRemiseGlobaleDocument(((TaLApporteur)ligne).getMtHtLApresRemiseGlobaleDocument());	
				}
			}
		}
		
		for (LigneTva ligneTva : lignesTVA) {

			if (ligneTva.getMtTva()!=null) {
				int lignepasse=1;
				BigDecimal tvaTmp = ligneTva.getMtTva();
				BigDecimal ttcTmp = LibCalcul.arrondi(ligneTva.getMontantTotalTtcAvecRemise());
				BigDecimal htTmp = LibCalcul.arrondi(ligneTva.getMontantTotalHtAvecRemise());

				for (Object ligne : lignes) {
					if(((TaLApporteur)ligne).getTaTLigne().getCodeTLigne().equals(C_CODE_T_LIGNE_H)) {
						if(((TaLApporteur)ligne).getCodeTvaLDocument()!=null &&
								((TaLApporteur)ligne).getCodeTvaLDocument().equals(ligneTva.getCodeTva())){
							if (ligneTva.getMontantTotalHt().signum()==0) 
								tvaLigne = ((TaLApporteur)ligne).getMtHtLDocument().multiply(ligneTva.getTauxTva()).divide(new BigDecimal(100));
							else {
								if  (lignepasse>= ligneTva.getNbLigneDocument()) 
									tvaLigne = tvaTmp;
								else {
									if(ttc==1){
										if(LibCalcul.arrondi(ligneTva.getMontantTotalTtcAvecRemise()).signum()<=0)
											tvaLigne=BigDecimal.valueOf(0);
										else
											tvaLigne = (ligneTva.getMtTva().multiply(((TaLApporteur)ligne).getMtTtcLDocument())).divide(LibCalcul.arrondi(ligneTva.getMontantTotalTtcAvecRemise()),MathContext.DECIMAL128).setScale(2,BigDecimal.ROUND_HALF_UP);
									}
									else{
										if(LibCalcul.arrondi(ligneTva.getMontantTotalHtAvecRemise()).signum()<=0)
											tvaLigne =BigDecimal.valueOf(0);
										else
											tvaLigne = (ligneTva.getMtTva().multiply(((TaLApporteur)ligne).getMtHtLDocument())).divide(LibCalcul.arrondi(ligneTva.getMontantTotalHtAvecRemise()),MathContext.DECIMAL128).setScale(2,BigDecimal.ROUND_HALF_UP);
									}
								}
							}
							tvaTmp =  tvaTmp.subtract(tvaLigne);
							totalTemp = totalTemp.add(((TaLApporteur)ligne).getMtHtLDocument());

							if(txRemHtDocument!=null && txRemHtDocument.signum()>0) {
								if  (lignepasse>= ligneTva.getNbLigneDocument()) {
									((TaLApporteur)ligne).setMtHtLApresRemiseGlobaleDocument(htTmp);
									((TaLApporteur)ligne).setMtTtcLApresRemiseGlobaleDocument(ttcTmp);
								} else {
									((TaLApporteur)ligne).setMtHtLApresRemiseGlobaleDocument(((TaLApporteur)ligne).getMtHtLDocument().subtract(((TaLApporteur)ligne).getMtHtLDocument().multiply(txRemHtDocument).divide(new BigDecimal(100),MathContext.DECIMAL128).setScale(2,BigDecimal.ROUND_HALF_UP)));
									((TaLApporteur)ligne).setMtTtcLApresRemiseGlobaleDocument(((TaLApporteur)ligne).getMtTtcLDocument().subtract(((TaLApporteur)ligne).getMtTtcLDocument().multiply(txRemHtDocument).divide(new BigDecimal(100),MathContext.DECIMAL128).setScale(2,BigDecimal.ROUND_HALF_UP)));
								}
								//								ttcTmp =  ttcTmp.subtract(((TaLApporteur)ligne).getMtTtcLFacture());
								//								htTmp =  htTmp.subtract(((TaLApporteur)ligne).getMtHtLFacture());
							} else {
								if(ttc==1)
									if  (lignepasse>= ligneTva.getNbLigneDocument()) {
										((TaLApporteur)ligne).setMtHtLApresRemiseGlobaleDocument(htTmp);
									}else{
										((TaLApporteur)ligne).setMtHtLApresRemiseGlobaleDocument(((TaLApporteur)ligne).getMtTtcLDocument().subtract(tvaLigne));
									}
								else
									if  (lignepasse>= ligneTva.getNbLigneDocument()) {
										((TaLApporteur)ligne).setMtTtcLApresRemiseGlobaleDocument(ttcTmp);
									}else {
										((TaLApporteur)ligne).setMtTtcLApresRemiseGlobaleDocument(((TaLApporteur)ligne).getMtHtLDocument().add(tvaLigne));
									}

							}
//							ttcTmp =  ttcTmp.subtract(((TaLApporteur)ligne).getMtTtcLApresRemiseGlobaleDocument());
//							htTmp =  htTmp.subtract(((TaLApporteur)ligne).getMtHtLApresRemiseGlobaleDocument());
							if(((TaLApporteur)ligne).getMtTtcLApresRemiseGlobaleDocument()!=null)
								ttcTmp =  ttcTmp.subtract(((TaLApporteur)ligne).getMtTtcLApresRemiseGlobaleDocument());

							if(((TaLApporteur)ligne).getMtHtLApresRemiseGlobaleDocument()!=null)
								htTmp =  htTmp.subtract(((TaLApporteur)ligne).getMtHtLApresRemiseGlobaleDocument());
							lignepasse++;
						}
					}
					setRemHtDocument(totalTemp.multiply(txRemHtDocument.divide(new BigDecimal(100))));						

					//					setRemHtDocument(getRemHtDocument().add(totalTemp.multiply(txRemHtDocument.divide(new BigDecimal(100)))));						

				}
			}
		}
		//		}

	}

	/**
	 * Lance la fonction de calcul du montant sur chacunes des lignes du document.
	 */
	public void calculMontantLigneDocument() {
		for (Object ligne : lignes) {
			((TaLApporteur)ligne).calculMontant();
		}
	}

	/**
	 * Calcul de la grille de TVA en fonction de lignes du document et du taux de remise HT global.
	 * Mise à jour de la propriété <code>lignesTVA</code>
	 * et mise à jour du montant de la TVA dans les lignes du document
	 */
	public void calculTvaTotal() {
		calculMontantLigneDocument();
		calculLignesTva();
		dispatcherTva();
	}

//	/**
//	 * Calcul de la grille de TVA en fonction de lignes du document et du taux de remise HT global.
//	 * Mise à jour de la propriété <code>lignesTVA</code>
//	 */
//	public void calculLignesTva() {
//
//		Map<String,BigDecimal> montantTotalHt = new HashMap<String,BigDecimal>();
//		Map<String,BigDecimal> montantTotalTtc = new HashMap<String,BigDecimal>();
//		Map<String,BigDecimal> montantTotalHtAvecRemise = new HashMap<String,BigDecimal>();
//		Map<String,BigDecimal> montantTotalTtcAvecRemise = new HashMap<String,BigDecimal>();
//		Map<String,BigDecimal> mtTVA = new HashMap<String,BigDecimal>();
//		Map<String,BigDecimal> tauxTVA = new HashMap<String,BigDecimal>();
//		Map<String,Integer> nbLigne = new HashMap<String,Integer>();
//		Map<String,String> libelleLignesTVA = new HashMap<String,String>();
//		String codeTVA = null;
////		TaTvaDAO taTvaDAO = new TaTvaDAO();
//
//		/*
//		 * calcul de la TVA different en fonction de la propriete TTC
//		 */
//		BigDecimal ttcLigne = null;
//		BigDecimal htLigne = null;
//		for (Object ligne : lignes) {
//			//en commentaire pour ne pas refaire les calculs pendants les editions, 
//			//((TaLApporteur)ligne).calculMontant();
//			codeTVA = ((TaLApporteur)ligne).getCodeTvaLDocument();
//			if(codeTVA!=null && !codeTVA.equals("")) {
//				ttcLigne = ((TaLApporteur)ligne).getMtTtcLDocument();
//				htLigne = ((TaLApporteur)ligne).getMtHtLDocument();
//				if(montantTotalHt.containsKey(codeTVA)) {
//					montantTotalTtc.put(codeTVA,montantTotalTtc.get(codeTVA).add(ttcLigne));
//					montantTotalHt.put(codeTVA,montantTotalHt.get(codeTVA).add(htLigne));
//					montantTotalTtcAvecRemise.put(codeTVA,montantTotalTtcAvecRemise.get(codeTVA).add(ttcLigne));
//					montantTotalHtAvecRemise.put(codeTVA,montantTotalHtAvecRemise.get(codeTVA).add(htLigne));
//					nbLigne.put(codeTVA,nbLigne.get(codeTVA)+1);
//				} else {
//					montantTotalTtc.put(codeTVA,ttcLigne);
//					montantTotalHt.put(codeTVA,htLigne);
//					montantTotalTtcAvecRemise.put(codeTVA,ttcLigne);
//					montantTotalHtAvecRemise.put(codeTVA,htLigne);
//					tauxTVA.put(codeTVA,((TaLApporteur)ligne).getTauxTvaLDocument());
//					libelleLignesTVA.put(codeTVA, ((TaLApporteur)ligne).getLibTvaLDocument());
//					nbLigne.put(codeTVA,1);
//				}
//			}
//		}
//
//		for (String codeTva : montantTotalTtc.keySet()) {
//			//les 2 maps ont les meme cles
//			BigDecimal mtTtcTotal = montantTotalTtc.get(codeTva);
//			BigDecimal mtHtTotal = montantTotalHt.get(codeTva);
//			BigDecimal tva =null;
//			if(txRemHtDocument!=null && txRemHtDocument.signum()>0) {
////				mtTtcTotal =LibCalcul.arrondi(mtTtcTotal.subtract(     mtTtcTotal.multiply(   txRemHtDocument.divide(new BigDecimal(100))  )       ));
////				mtHtTotal = LibCalcul.arrondi(mtHtTotal.subtract(    mtHtTotal.multiply( (txRemHtDocument.divide(new BigDecimal(100))))     ) ) ;
//				BigDecimal valeurInterTTC=mtTtcTotal.multiply(   txRemHtDocument.divide(new BigDecimal(100)),MathContext.DECIMAL128).setScale(2,BigDecimal.ROUND_HALF_UP);
//				mtTtcTotal =LibCalcul.arrondi(mtTtcTotal.subtract(valeurInterTTC )) ;
//				BigDecimal valeurInterHT=mtHtTotal.multiply( txRemHtDocument.divide(new BigDecimal(100)),MathContext.DECIMAL128).setScale(2,BigDecimal.ROUND_HALF_UP);
//				mtHtTotal = LibCalcul.arrondi(mtHtTotal.subtract( valeurInterHT )) ;
//				montantTotalTtcAvecRemise.put(codeTva, mtTtcTotal);
//				montantTotalHtAvecRemise.put(codeTva, mtHtTotal);
//			} 
//
//			if (ttc==1) {
//				tva=mtTtcTotal.subtract((mtTtcTotal.multiply(BigDecimal.valueOf(100))) .divide((BigDecimal.valueOf(100).add(tauxTVA.get(codeTva))) ,MathContext.DECIMAL128).setScale(2,BigDecimal.ROUND_HALF_UP)     ) ;
//				mtTVA.put(codeTva, tva);
//				montantTotalHtAvecRemise.put(codeTva, mtTtcTotal.subtract(tva));
//			} else {
//				tva=mtHtTotal.multiply(   (tauxTVA.get(codeTva).divide(new BigDecimal(100)))) ;
//				mtTVA.put(codeTva, tva );
//				montantTotalTtcAvecRemise.put(codeTva, mtHtTotal.add(tva));
//			}
//		}
//
//		lignesTVA.clear();
//		for (String codeTva : mtTVA.keySet()) {
//			LigneTva ligneTva = new LigneTva();
//			ligneTva.setCodeTva(codeTva);
//			ligneTva.setTauxTva(tauxTVA.get(codeTva));
//			ligneTva.setMtTva(mtTVA.get(codeTva));
//			ligneTva.setMontantTotalHt(montantTotalHt.get(codeTva));
//			ligneTva.setMontantTotalTtc(montantTotalTtc.get(codeTva));
//			ligneTva.setMontantTotalHtAvecRemise(montantTotalHtAvecRemise.get(codeTva));
//			ligneTva.setMontantTotalTtcAvecRemise(montantTotalTtcAvecRemise.get(codeTva));
////			ligneTva.setLibelle(taTvaDAO.findByCode(codeTva).getLibelleTva());
//			ligneTva.setLibelle(libelleLignesTVA.get(codeTva));
//			ligneTva.setNbLigneDocument(nbLigne.get(codeTva));
//			lignesTVA.add(ligneTva);
//		}
//
//		//dispatcherTva();
//	}

	/**
	 * Calcul de la grille de TVA en fonction de lignes du document et du taux de remise HT global.
	 * Mise à jour de la propriété <code>lignesTVA</code>
	 */
	public void calculLignesTva() {
		Map<String,BigDecimal> montantTotalHt = new HashMap<String,BigDecimal>();
		Map<String,BigDecimal> montantTotalTtc = new HashMap<String,BigDecimal>();
		Map<String,BigDecimal> montantTotalHtAvecRemise = new HashMap<String,BigDecimal>();
		Map<String,BigDecimal> montantTotalTtcAvecRemise = new HashMap<String,BigDecimal>();
		Map<String,BigDecimal> mtTVA = new HashMap<String,BigDecimal>();
		Map<String,BigDecimal> mtTVAAvantRemise = new HashMap<String,BigDecimal>();
		Map<String,BigDecimal> tauxTVA = new HashMap<String,BigDecimal>();
		Map<String,Integer> nbLigne = new HashMap<String,Integer>();
		Map<String,String> libelleLignesTVA = new HashMap<String,String>();
		String codeTVA = null;
//		TaTvaDAO taTvaDAO = new TaTvaDAO();
		
		/*
		 * calcul de la TVA different en fonction de la propriete TTC
		 */
		BigDecimal ttcLigne = null;
		BigDecimal htLigne = null;
		for (Object ligne : lignes) {
			//en commentaire pour ne pas refaire les calculs pendants les editions, 
			//((TaLApporteur)ligne).calculMontant();
			codeTVA = ((TaLApporteur)ligne).getCodeTvaLDocument();
			if(codeTVA!=null && !codeTVA.equals("")) {
				ttcLigne = ((TaLApporteur)ligne).getMtTtcLDocument();
				htLigne = ((TaLApporteur)ligne).getMtHtLDocument();
				if(montantTotalHt.containsKey(codeTVA)) {
					montantTotalTtc.put(codeTVA,montantTotalTtc.get(codeTVA).add(ttcLigne));
					montantTotalHt.put(codeTVA,montantTotalHt.get(codeTVA).add(htLigne));
					montantTotalTtcAvecRemise.put(codeTVA,montantTotalTtcAvecRemise.get(codeTVA).add(ttcLigne));
					montantTotalHtAvecRemise.put(codeTVA,montantTotalHtAvecRemise.get(codeTVA).add(htLigne));
					nbLigne.put(codeTVA,nbLigne.get(codeTVA)+1);
				} else {
					montantTotalTtc.put(codeTVA,ttcLigne);
					montantTotalHt.put(codeTVA,htLigne);
					montantTotalTtcAvecRemise.put(codeTVA,ttcLigne);
					montantTotalHtAvecRemise.put(codeTVA,htLigne);
					tauxTVA.put(codeTVA,((TaLApporteur)ligne).getTauxTvaLDocument());
					nbLigne.put(codeTVA,1);
					libelleLignesTVA.put(codeTVA, ((TaLApporteur)ligne).getLibTvaLDocument());
//					libelleLignesTVA.put(codeTVA, ((TaLApporteur)ligne).getLibLDocument());
				}
			}
		}

		for (String codeTva : montantTotalTtc.keySet()) {
			//les 2 maps ont les meme cles
			BigDecimal mtTtcTotal = montantTotalTtc.get(codeTva);
			BigDecimal mtHtTotal = montantTotalHt.get(codeTva);
			BigDecimal tva =null;
			//traitement tva avant remise
			if (ttc==1) {
				tva=mtTtcTotal.subtract((mtTtcTotal.multiply(BigDecimal.valueOf(100))) .divide((BigDecimal.valueOf(100).add(tauxTVA.get(codeTva))) ,MathContext.DECIMAL128).setScale(2,BigDecimal.ROUND_HALF_UP)     ) ;
				mtTVAAvantRemise.put(codeTva, tva);
			} else {
				tva=mtHtTotal.multiply(   (tauxTVA.get(codeTva).divide(new BigDecimal(100)))) ;
				mtTVAAvantRemise.put(codeTva, tva );
			}
			//traitement remise
			if(txRemHtDocument!=null && txRemHtDocument.signum()>0) {
//				mtTtcTotal =LibCalcul.arrondi(mtTtcTotal.subtract(     mtTtcTotal.multiply(   txRemHtDocument.divide(new BigDecimal(100))  )       ));
//				mtHtTotal = LibCalcul.arrondi(mtHtTotal.subtract(    mtHtTotal.multiply( (txRemHtDocument.divide(new BigDecimal(100))))     ) ) ;
				BigDecimal valeurInterTTC=mtTtcTotal.multiply(   txRemHtDocument.divide(new BigDecimal(100)),MathContext.DECIMAL128).setScale(2,BigDecimal.ROUND_HALF_UP);
				mtTtcTotal =LibCalcul.arrondi(mtTtcTotal.subtract(valeurInterTTC )) ;
				BigDecimal valeurInterHT=mtHtTotal.multiply( txRemHtDocument.divide(new BigDecimal(100)),MathContext.DECIMAL128).setScale(2,BigDecimal.ROUND_HALF_UP);
				mtHtTotal = LibCalcul.arrondi(mtHtTotal.subtract( valeurInterHT )) ;
				montantTotalTtcAvecRemise.put(codeTva, mtTtcTotal);
				montantTotalHtAvecRemise.put(codeTva, mtHtTotal);
			} 
			//traitement tva après remise
			if (ttc==1) {
				tva=mtTtcTotal.subtract((mtTtcTotal.multiply(BigDecimal.valueOf(100))) .divide((BigDecimal.valueOf(100).add(tauxTVA.get(codeTva))) ,MathContext.DECIMAL128).setScale(2,BigDecimal.ROUND_HALF_UP)     ) ;
				mtTVA.put(codeTva, tva);
				montantTotalHtAvecRemise.put(codeTva, mtTtcTotal.subtract(tva));
			} else {
				tva=mtHtTotal.multiply(   (tauxTVA.get(codeTva).divide(new BigDecimal(100)))) ;
				mtTVA.put(codeTva, tva );
				montantTotalTtcAvecRemise.put(codeTva, mtHtTotal.add(tva));
			}
		}

		lignesTVA.clear();
		for (String codeTva : mtTVA.keySet()) {
			LigneTva ligneTva = new LigneTva();
			ligneTva.setCodeTva(codeTva);
			ligneTva.setTauxTva(tauxTVA.get(codeTva));
			ligneTva.setMtTva(mtTVA.get(codeTva));
			ligneTva.setMtTvaAvantRemise(mtTVAAvantRemise.get(codeTva));
			ligneTva.setMontantTotalHt(montantTotalHt.get(codeTva));
			ligneTva.setMontantTotalTtc(montantTotalTtc.get(codeTva));
			ligneTva.setMontantTotalHtAvecRemise(montantTotalHtAvecRemise.get(codeTva));
			ligneTva.setMontantTotalTtcAvecRemise(montantTotalTtcAvecRemise.get(codeTva));
//			ligneTva.setLibelle(taTvaDAO.findByCode(codeTva).getLibelleTva());
			ligneTva.setLibelle(libelleLignesTVA.get(codeTva));
			ligneTva.setNbLigneDocument(nbLigne.get(codeTva));
			lignesTVA.add(ligneTva);
		}
		
		//dispatcherTva();
	}

	/**
	 * Calcul des totaux de la facture
	 */
	public void calculTotaux() {

		//			    MT_TVA Numeric(15,2),
		setMtHtCalc(new BigDecimal(0));
		setNetHtCalc(new BigDecimal(0));
		setMtTtcCalc(new BigDecimal(0));
		setMtTtcAvantRemiseGlobaleCalc(new BigDecimal(0));
		for (Object ligne : lignes) {
			if(((TaLApporteur)ligne).getTaTLigne().getCodeTLigne().equals(C_CODE_T_LIGNE_H) && ((TaLApporteur)ligne).getTaArticle()!=null) {
				if(((TaLApporteur)ligne).getMtHtLApresRemiseGlobaleDocument()!=null)
					setNetHtCalc(getNetHtCalc().add(((TaLApporteur)ligne).getMtHtLApresRemiseGlobaleDocument()));
				if(((TaLApporteur)ligne).getMtTtcLApresRemiseGlobaleDocument()!=null)
					setMtTtcCalc(getMtTtcCalc().add(((TaLApporteur)ligne).getMtTtcLApresRemiseGlobaleDocument()));
				if(((TaLApporteur)ligne).getMtHtLDocument()!=null)
					setMtHtCalc(getMtHtCalc().add(((TaLApporteur)ligne).getMtHtLDocument()));
				if(((TaLApporteur)ligne).getMtTtcLDocument()!=null)
					setMtTtcAvantRemiseGlobaleCalc(getMtTtcAvantRemiseGlobaleCalc().add(((TaLApporteur)ligne).getMtTtcLDocument()));
			}

		}
		setRemHtDocument(getMtHtCalc().subtract(getNetHtCalc())); // passage ejb 3/8/2016
		setNetTvaCalc(getMtTtcCalc().subtract(getNetHtCalc()));
		BigDecimal tva = new BigDecimal(0);
		for (LigneTva ligneTva : lignesTVA) {
			tva = tva.add(ligneTva.getMtTva());
		}
		if(tva.compareTo(getNetTvaCalc())!=0) {
			logger.error("Montant de la TVA incorrect : "+getNetTvaCalc()+" ** "+tva);
		}
		BigDecimal tvaAvantRemise = new BigDecimal(0);
		for (LigneTva ligneTva : lignesTVA) {
			tvaAvantRemise = tvaAvantRemise.add(ligneTva.getMtTvaAvantRemise());
		}
		setMtTvaCalc(tvaAvantRemise);
		setNetTtcCalc(getMtTtcCalc().subtract(getMtTtcCalc().multiply(getTxRemTtcDocument().divide(new BigDecimal(100))).setScale(2,BigDecimal.ROUND_HALF_UP)));
		/*
		 * remise HT déjà calculée dans dispatcherTva()
		 */
		setRemTtcDocument(getMtTtcCalc().subtract(getNetTtcCalc()).setScale(2,BigDecimal.ROUND_HALF_UP));
		setNetAPayer(getNetTtcCalc().subtract(getRegleDocument()));
	}

	public void calculeTvaEtTotaux(){
		calculTvaTotal();
		calculTotaux();
	}

	public void propertyChange(PropertyChangeEvent evt) {
		if(evt.getPropertyName().equals("qteLApporteur")
				|| evt.getPropertyName().equals("qte2LApporteur")
				|| evt.getPropertyName().equals("prixULApporteur")
				|| evt.getPropertyName().equals("remTxLApporteur")
		){
			//passage ejb => dans TaApporteurService
			System.out.println("===****=== Transfert de code metier des entites vers les services, à bien vérifier");
			System.err.println("modification du recalcul pour ejb");
			calculeTvaEtTotaux();
			try {
				fireModificationDocument(new SWTModificationDocumentEvent(this));
			} catch (Exception e) {
				logger.error("",e);
			}
		}
	}


	public void setLegrain(boolean legrain) {
		this.legrain = legrain;
		for (TaLApporteur ligne : getLignes()) {
			ligne.setLegrain(legrain);
		}		
	}

	@Override
	protected void reinitialiseNumLignes() {
		//		for (Object ligne : lignes) {
		//			((TaLApporteur)ligne).setNumLigneLDocument(
		//					((TaLApporteur) ligne).getNUM_LIGNE());
		//		}

	}

	//@Transient
	@Column(name = "mt_ttc_avt_rem_globale_calc", precision = 15)
	@LgrHibernateValidated(champBd = "mt_ttc_avt_rem_globale_calc",table = "ta_apporteur",champEntite="mtTtcAvantRemiseGlobaleCalc", clazz = TaApporteur.class)
	public BigDecimal getMtTtcAvantRemiseGlobaleCalc() {
		return mtTtcAvantRemiseGlobaleCalc;
	}

	public void setMtTtcAvantRemiseGlobaleCalc(
			BigDecimal mtTtcAvantRemiseGlobaleCalc) {
		this.mtTtcAvantRemiseGlobaleCalc = mtTtcAvantRemiseGlobaleCalc;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
		+ ((codeDocument == null) ? 0 : codeDocument.hashCode());
		return result;
	}
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		TaApporteur other = (TaApporteur) obj;
		if (codeDocument == null) {
			if (other.codeDocument != null)
				return false;
		} else if (!codeDocument.equals(other.codeDocument))
			return false;
		if (commentaire == null) {
			if (other.commentaire != null)
				return false;
		} else if (!commentaire.equals(other.commentaire))
			return false;
		if (dateDocument == null) {
			if (other.dateDocument != null)
				return false;
		} else if (!dateDocument.equals(other.dateDocument))
			return false;
		if (dateEchDocument == null) {
			if (other.dateEchDocument != null)
				return false;
		} else if (!dateEchDocument.equals(other.dateEchDocument))
			return false;
		if (dateLivDocument == null) {
			if (other.dateLivDocument != null)
				return false;
		} else if (!dateLivDocument.equals(other.dateLivDocument))
			return false;
		if (dateExport == null) {
			if (other.dateExport != null)
				return false;
		} else if (!dateExport.equals(other.dateExport))
			return false;
		if (gestionTVA != other.gestionTVA)
			return false;
		if (ipAcces == null) {
			if (other.ipAcces != null)
				return false;
		} else if (!ipAcces.equals(other.ipAcces))
			return false;
		if (legrain != other.legrain)
			return false;
		if (libelleDocument == null) {
			if (other.libelleDocument != null)
				return false;
		} else if (!libelleDocument.equals(other.libelleDocument))
			return false;
		if (lignesTVA == null) {
			if (other.lignesTVA != null)
				return false;
		} else if (!lignesTVA.equals(other.lignesTVA))
			return false;
		if (mtHtCalc == null) {
			if (other.mtHtCalc != null)
				return false;
		} else if (!mtHtCalc.equals(other.mtHtCalc))
			return false;
		if (mtTtcAvantRemiseGlobaleCalc == null) {
			if (other.mtTtcAvantRemiseGlobaleCalc != null)
				return false;
		} else if (!mtTtcAvantRemiseGlobaleCalc
				.equals(other.mtTtcAvantRemiseGlobaleCalc))
			return false;
		if (mtTtcCalc == null) {
			if (other.mtTtcCalc != null)
				return false;
		} else if (!mtTtcCalc.equals(other.mtTtcCalc))
			return false;
		if (mtTvaCalc == null) {
			if (other.mtTvaCalc != null)
				return false;
		} else if (!mtTvaCalc.equals(other.mtTvaCalc))
			return false;
		if (nbEDocument == null) {
			if (other.nbEDocument != null)
				return false;
		} else if (!nbEDocument.equals(other.nbEDocument))
			return false;
		if (netAPayer == null) {
			if (other.netAPayer != null)
				return false;
		} else if (!netAPayer.equals(other.netAPayer))
			return false;
		if (netHtCalc == null) {
			if (other.netHtCalc != null)
				return false;
		} else if (!netHtCalc.equals(other.netHtCalc))
			return false;
		if (netTtcCalc == null) {
			if (other.netTtcCalc != null)
				return false;
		} else if (!netTtcCalc.equals(other.netTtcCalc))
			return false;
		if (netTvaCalc == null) {
			if (other.netTvaCalc != null)
				return false;
		} else if (!netTvaCalc.equals(other.netTvaCalc))
			return false;
		if (quandCree == null) {
			if (other.quandCree != null)
				return false;
		} else if (!quandCree.equals(other.quandCree))
			return false;
		if (quandModif == null) {
			if (other.quandModif != null)
				return false;
		} else if (!quandModif.equals(other.quandModif))
			return false;
		if (quiCree == null) {
			if (other.quiCree != null)
				return false;
		} else if (!quiCree.equals(other.quiCree))
			return false;
		if (quiModif == null) {
			if (other.quiModif != null)
				return false;
		} else if (!quiModif.equals(other.quiModif))
			return false;
		if (regleDocument == null) {
			if (other.regleDocument != null)
				return false;
		} else if (!regleDocument.equals(other.regleDocument))
			return false;
		if (remHtDocument == null) {
			if (other.remHtDocument != null)
				return false;
		} else if (!remHtDocument.equals(other.remHtDocument))
			return false;
		if (remTtcDocument == null) {
			if (other.remTtcDocument != null)
				return false;
		} else if (!remTtcDocument.equals(other.remTtcDocument))
			return false;
		if (taInfosDocument == null) {
			if (other.taInfosDocument != null)
				return false;
		} else if (!taInfosDocument.equals(other.taInfosDocument))
			return false;
		if (taRDocuments == null) {
			if (other.taRDocuments != null)
				return false;
		} else if (!taRDocuments.equals(other.taRDocuments))
			return false;
		if (taTPaiement == null) {
			if (other.taTPaiement != null)
				return false;
		} else if (!taTPaiement.equals(other.taTPaiement))
			return false;
		if (taTiers == null) {
			if (other.taTiers != null)
				return false;
		} else if (!taTiers.equals(other.taTiers))
			return false;
		if (ttc == null) {
			if (other.ttc != null)
				return false;
		} else if (!ttc.equals(other.ttc))
			return false;
		if (txRemHtDocument == null) {
			if (other.txRemHtDocument != null)
				return false;
		} else if (!txRemHtDocument.equals(other.txRemHtDocument))
			return false;
		if (txRemTtcDocument == null) {
			if (other.txRemTtcDocument != null)
				return false;
		} else if (!txRemTtcDocument.equals(other.txRemTtcDocument))
			return false;
		if (version == null) {
			if (other.version != null)
				return false;
		} else if (!version.equals(other.version))
			return false;
		return true;
	}

	@Override
	@Transient
	public String getTypeDocument() {
		// TODO Auto-generated method stub
		return TYPE_DOC;
	}
	@Transient
	public BigDecimal getRemTtcIntermediaireDocument() {
		return mtTtcAvantRemiseGlobaleCalc.subtract(mtTtcCalc);
	}
	
//passage ejb => dans TaApporteurService
	
//	public void calculDateEcheanceAbstract(Integer report, Integer finDeMois){
//		calculDateEcheance(report,finDeMois);
//	}
//	public Date calculDateEcheance(Integer report, Integer finDeMois) {
//		TaTCPaiementDAO taTCPaiementDAO = new TaTCPaiementDAO();
//		TaTCPaiement typeCP = taTCPaiementDAO.findByCode(TaTCPaiement.C_CODE_TYPE_APORTEUR);
//		TaCPaiement conditionDoc = null;
//		TaCPaiement conditionTiers = null;
//		TaCPaiement conditionSaisie = null;
//		
//		if(typeCP!=null) conditionDoc = typeCP.getTaCPaiement();
//		if(getTaTiers()!=null) conditionTiers = getTaTiers().getTaCPaiement();
//
//		if(report!=null || finDeMois!=null) { 
//			conditionSaisie = new TaCPaiement();
//			if(report!=null)
//				conditionSaisie.setReportCPaiement(report);
//			if(finDeMois!=null)
//				conditionSaisie.setFinMoisCPaiement(finDeMois);
//		}
//		
//		//on applique toute les conditions par ordre décroissant de priorité, la derniere valide est conservée
//		Date nouvelleDate = getDateDocument();
//		if(conditionDoc!=null) {
//			nouvelleDate = conditionDoc.calculeNouvelleDate(getDateDocument());
//		}
//		if(conditionTiers!=null) {
//			nouvelleDate = conditionTiers.calculeNouvelleDate(getDateDocument());
//		}
//		if(conditionSaisie!=null) {
//			nouvelleDate = conditionSaisie.calculeNouvelleDate(getDateDocument());
//		}
//		setDateEchDocument(nouvelleDate);
//		return nouvelleDate;
//	}
	
	
	@Transient
	public List<ILigneDocumentTiers> getLignesGeneral(){
		return this.lignes;
	}

	@Transient
	public BigDecimal getRegleCompletDocument() {
		// TODO Auto-generated method stub
		return null;
	}
	@Transient
	public BigDecimal getResteAReglerComplet() {
		// TODO Auto-generated method stub
		return null;
	}	
	@Transient
	public boolean isLegrain() {
		// TODO Auto-generated method stub
		return legrain;
	}
	
	@Override
	@JsonIgnore
	public void setTaInfosDocument(IInfosDocumentTiers infosDocumentTiers) {
		this.taInfosDocument =  (TaInfosApporteur) infosDocumentTiers;
		
	}

	public Object cloneCentralisation() throws CloneNotSupportedException {
		TaApporteur doc = new TaApporteur(false);
		try {
			doc.setIdDocument(0);
			doc.setVersion(version);
			//doc.setTaTPaiement(taTPaiement);
			doc.setTaTiers(taTiers);
			//doc.setTaCPaiement(taCPaiement);
			doc.setCodeDocument("");
			doc.setDateDocument(dateDocument);
			doc.setDateEchDocument(dateEchDocument);
			doc.setDateLivDocument(dateLivDocument);
			doc.setLibelleDocument("");

			doc.setRemHtDocument(remHtDocument);
			doc.setTxRemHtDocument(txRemHtDocument);
			doc.setRemTtcDocument(remTtcDocument);
			doc.setTxRemTtcDocument(txRemTtcDocument);
			doc.setNbEDocument(nbEDocument);
			doc.setTtc(ttc);
			doc.setDateExport(dateExport);
			doc.setCommentaire(commentaire);
			doc.setQuiCree(quiCree);
			doc.setQuandCree(quandCree);
			doc.setQuiModif(quiModif);
			doc.setQuandModif(quandModif);
			doc.setIpAcces(ipAcces);
			doc.setVersionObj(versionObj);
			
			doc.setNbDecimalesPrix(nbDecimalesPrix);
			doc.setNbDecimalesQte(nbDecimalesQte);
			
			TaInfosApporteur infos = getTaInfosDocument().clone();
			infos.setTaDocument(doc);
			doc.setTaInfosDocument(infos);
		} catch(Exception cnse) {
			logger.error("",cnse);
		}
		// on renvoie le clone
		return doc;
	}

	public TaLApporteur contientMemeParametreCompte(TaLApporteur ligneCompare){
		for (TaLApporteur obj : getLignes()) {
			if(obj.getCompteLDocument()!=null && obj.getCodeTvaLDocument()!=null
					&& obj.getCompteLDocument().equals(ligneCompare.getCompteLDocument())
					&& obj.getCodeTvaLDocument().equals(ligneCompare.getCodeTvaLDocument())
					&& LibConversion.bigDecimalToString(obj.getTauxTvaLDocument()).equals(LibConversion.bigDecimalToString(ligneCompare.getTauxTvaLDocument()))
					&& obj.getCodeTTvaLDocument().equals(ligneCompare.getCodeTTvaLDocument()))
			{
				return obj;	
			}
		}
		return null;
	}
	
	@OneToOne(fetch = FetchType.EAGER, cascade = {CascadeType.ALL} , orphanRemoval=true )
	@JoinColumn(name = "id_mise_a_disposition")
	public TaMiseADisposition getTaMiseADisposition() {
		return taMiseADisposition;
	}

	public void setTaMiseADisposition(TaMiseADisposition taMiseADisposition) {
		this.taMiseADisposition = taMiseADisposition;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_export")
	@LgrHibernateValidated(champBd = "date_export",table = "ta_apporteur",champEntite="dateExport", clazz = TaApporteur.class)
	public Date getDateExport() {
		return dateExport;
	}

	public void setDateExport(Date dateExport) {
		this.dateExport = dateExport;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_etat")
	@LgrHibernateValidated(champBd = "id_etat",table = "ta_etat",champEntite="TaEtat.idEtat", clazz = TaEtat.class)
	public TaEtat getTaEtat() {
		return this.taEtat;
	}

	public void setTaEtat(TaEtat taEtat) {
//		this.taEtat = taEtat;
	}

	
	@Column(name = "date_verrouillage")
	public Date getDateVerrouillage() {
		return dateVerrouillage;
	}

	public void setDateVerrouillage(Date dateVerrouillage) {
		this.dateVerrouillage=dateVerrouillage;
	}
	
	@Column(name = "gestion_lot")
	public Boolean getGestionLot() {
		return gestionLot;
	}

	public void setGestionLot(Boolean gestionLot) {
		this.gestionLot = gestionLot;
	}
	
	@Column(name = "mouvementer_stock")
	public Boolean getMouvementerStock() {
		return mouvementerStock;
	}

	public void setMouvementerStock(Boolean mouvementerStock) {
		this.mouvementerStock = mouvementerStock;
	}
	


	
	
	@Column(name = "nb_decimales_qte")
	public Integer getNbDecimalesQte() {
		return nbDecimalesQte;
	}

	public void setNbDecimalesQte(Integer nbDecimalesQte) {
		this.nbDecimalesQte = nbDecimalesQte;
	}

	@Column(name = "nb_decimales_prix")
	public Integer getNbDecimalesPrix() {
		return nbDecimalesPrix;
	}

	public void setNbDecimalesPrix(Integer nbDecimalesPrix) {
		this.nbDecimalesPrix = nbDecimalesPrix;
	}

	@PrePersist
	public void PrePersist() throws Exception{
		verifInfoDocument();
	}
	
	@PreUpdate
	public void PreUpdate() throws Exception{
		verifInfoDocument();
	}

	
	
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "taApporteur", orphanRemoval = true)
	public Set<TaREtat> getTaREtats() {
		return this.taREtats;
	}

	public void setTaREtats(Set<TaREtat> taREtats) {
		this.taREtats = taREtats;
	}
	

	
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "taApporteur", orphanRemoval = true)
	public Set<TaHistREtat> getTaHistREtats() {
		return this.taHistREtats;
	}

	public void setTaHistREtats(Set<TaHistREtat> taHistREtats) {
		this.taHistREtats = taHistREtats;
	}

	public void addREtat(TaEtat taEtat) {
		TaHistREtat hist=new TaHistREtat();
		TaREtat rEtat=getTaREtat();
		if(rEtat!=null) {
			hist.setTaEtat(getTaREtat().getTaEtat());
			hist.setTaApporteur(this);
			this.getTaHistREtats().add(hist);
		}else rEtat=new TaREtat();
		
		rEtat.setTaEtat(taEtat);
		rEtat.setTaApporteur(this);
		this.setTaREtat(rEtat);
		this.getTaREtats().add(rEtat);
	}

	@Override
	public Boolean gereStock() {
		// TODO Auto-generated method stub
		return false;
	}

	
	
	@OneToMany(cascade = CascadeType.ALL,fetch = FetchType.LAZY, mappedBy = "taApporteur", orphanRemoval=true)
	public Set<TaRReglementLiaison> getTaRReglementLiaisons() {
		return taRReglementLiaisons;
	}

	public void setTaRReglementLiaisons(Set<TaRReglementLiaison> taRReglementLiaisons) {
		this.taRReglementLiaisons = taRReglementLiaisons;
	}

	
	public void addRReglementLiaison(TaRReglementLiaison taReglementLiaison){
		if(!this.getTaRReglementLiaisons().contains(taReglementLiaison)){
			taReglementLiaison.setTaApporteur(this);
			this.getTaRReglementLiaisons().add(taReglementLiaison);	
		}
	}
	public void removeReglementLiaison(TaRReglementLiaison taRReglementLiaison){
		this.getTaRReglementLiaisons().remove(taRReglementLiaison);
	}

	@Transient
	public String getNumeroCommandeFournisseur() {
		// TODO Auto-generated method stub
		return null;
	}
	
	@Column(name = "utilise_unite_saisie")
	public Boolean getUtiliseUniteSaisie() {
		return utiliseUniteSaisie;
	}

	public void setUtiliseUniteSaisie(Boolean utiliseUniteSaisie) {
		this.utiliseUniteSaisie = utiliseUniteSaisie;
	}
}

