package fr.legrain.document.model;

// Generated Apr 7, 2009 3:27:23 PM by Hibernate Tools 3.2.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import fr.legrain.general.model.TaObjetLgr;
import fr.legrain.validator.LgrHibernateValidated;

/**
 * TaHistREtat generated by hbm2java
 */
@Entity
//@Cache(usage=CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "ta_hist_r_etat_ligne_doc")
public class TaHistREtatLigneDocument extends TaObjetLgr  implements java.io.Serializable {
	

	
	/**
	 * 
	 */
	private static final long serialVersionUID = 6503611145304200153L;
	
	
	private int idHistREtatLigneDoc;
//	private String version;
	private TaEtat taEtat;
	private TaLFacture taLFacture;
	private TaLTicketDeCaisse taLTicketDeCaisse;
	private TaLBoncde taLBoncde;
	private TaLBoncdeAchat taLBoncdeAchat;
	private TaLProforma taLProforma;
	private TaLBonliv taLBonliv;
	private TaLAvoir taLAvoir;
	private TaLApporteur taLApporteur;
	private TaLDevis taLDevis;
	private TaLAcompte taLAcompte;
	private TaLPrelevement taLPrelevement;
	private TaLAvisEcheance taLAvisEcheance;
	private TaLBonReception taLBonReception;
	private TaLFlash taLFlash;
	private TaRReglement taRReglement;
	private Date dateEtat;
	private String commentaire;
	private TaLPreparation taLPreparation;
	
	//rajout yann 
	private TaLEcheance taLEcheance;
	private TaLAbonnement taLAbonnement;
	private TaLPanier taLPanier;
	
//	private String quiCree;
//	private Date quandCree;
//	private String quiModif;
//	private Date quandModif;
//	private String ipAcces;
	private Integer versionObj;

	public TaHistREtatLigneDocument() {
	}

	public TaHistREtatLigneDocument(int idHistREtatLigneDoc) {
		this.idHistREtatLigneDoc = idHistREtatLigneDoc;
	}





	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id_hist_r_etat_ligne_doc", unique = true, nullable = false)
	public int getIdHistREtatLigneDoc() {
		return this.idHistREtatLigneDoc;
	}

	public void setIdHistREtatLigneDoc(int idHistREtatLigneDoc) {
		this.idHistREtatLigneDoc = idHistREtatLigneDoc;
	}

//	@Column(name = "version", length = 20)
//	public String getVersion() {
//		return this.version;
//	}
//
//	public void setVersion(String version) {
//		this.version = version;
//	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_L_facture")
	public TaLFacture getTaLFacture() {
		return this.taLFacture;
	}

	public void setTaLFacture(TaLFacture taLFacture) {
		this.taLFacture = taLFacture;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_L_prelevement")
	public TaLPrelevement getTaLPrelevement() {
		return taLPrelevement;
	}

	public void setTaLPrelevement(TaLPrelevement taLPrelevement) {
		this.taLPrelevement = taLPrelevement;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_L_avis_echeance")
	public TaLAvisEcheance getTaLAvisEcheance() {
		return taLAvisEcheance;
	}

	public void setTaLAvisEcheance(TaLAvisEcheance taLAvisEcheance) {
		this.taLAvisEcheance = taLAvisEcheance;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_L_boncde")
	public TaLBoncde getTaLBoncde() {
		return this.taLBoncde;
	}

	public void setTaLBoncde(TaLBoncde taLBoncde) {
		this.taLBoncde = taLBoncde;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_L_boncde_achat")
	public TaLBoncdeAchat getTaLBoncdeAchat() {
		return this.taLBoncdeAchat;
	}

	public void setTaLBoncdeAchat(TaLBoncdeAchat taLBoncdeAchat) {
		this.taLBoncdeAchat = taLBoncdeAchat;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_L_bon_reception")
	public TaLBonReception getTaLBonReception() {
		return this.taLBonReception;
	}

	public void setTaLBonReception(TaLBonReception taLBonReception) {
		this.taLBonReception = taLBonReception;
	}
	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_L_proforma")
	public TaLProforma getTaLProforma() {
		return this.taLProforma;
	}

	public void setTaLProforma(TaLProforma taLProforma) {
		this.taLProforma = taLProforma;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_L_bonliv")
	public TaLBonliv getTaLBonliv() {
		return this.taLBonliv;
	}

	public void setTaLBonliv(TaLBonliv taLBonliv) {
		this.taLBonliv = taLBonliv;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_L_avoir")
	public TaLAvoir getTaLAvoir() {
		return this.taLAvoir;
	}

	public void setTaLAvoir(TaLAvoir taLAvoir) {
		this.taLAvoir = taLAvoir;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_L_apporteur")
	public TaLApporteur getTaLApporteur() {
		return this.taLApporteur;
	}

	public void setTaLApporteur(TaLApporteur taLApporteur) {
		this.taLApporteur = taLApporteur;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_L_devis")
	public TaLDevis getTaLDevis() {
		return this.taLDevis;
	}

	public void setTaLDevis(TaLDevis idLDevis) {
		this.taLDevis = idLDevis;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_L_acompte")
	public TaLAcompte getTaLAcompte() {
		return taLAcompte;
	}

	public void setTaLAcompte(TaLAcompte taLAcompte) {
		this.taLAcompte = taLAcompte;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_L_ticket_caisse")
	public TaLTicketDeCaisse getTaLTicketDeCaisse() {
		return taLTicketDeCaisse;
	}

	public void setTaLTicketDeCaisse(TaLTicketDeCaisse taLTicketDeCaisse) {
		this.taLTicketDeCaisse = taLTicketDeCaisse;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_r_reglement")
	public TaRReglement getTaRReglement() {
		return taRReglement;
	}

	public void setTaRReglement(TaRReglement taRReglement) {
		this.taRReglement = taRReglement;
	}
	
	
//	@Column(name = "qui_cree", length = 50)
//	public String getQuiCree() {
//		return this.quiCree;
//	}
//
//	public void setQuiCree(String quiCreeHistREtat) {
//		this.quiCree = quiCreeHistREtat;
//	}
//
//	@Temporal(TemporalType.TIMESTAMP)
//	@Column(name = "quand_cree", length = 19)
//	public Date getQuandCree() {
//		return this.quandCree;
//	}
//
//	public void setQuandCree(Date quandCreeHistREtat) {
//		this.quandCree = quandCreeHistREtat;
//	}
//
//	@Column(name = "qui_modif", length = 50)
//	public String getQuiModif() {
//		return this.quiModif;
//	}
//
//	public void setQuiModif(String quiModifHistREtat) {
//		this.quiModif = quiModifHistREtat;
//	}
//
//	@Temporal(TemporalType.TIMESTAMP)
//	@Column(name = "quand_modif", length = 19)
//	public Date getQuandModif() {
//		return this.quandModif;
//	}
//
//	public void setQuandModif(Date quandModifHistREtat) {
//		this.quandModif = quandModifHistREtat;
//	}
//
//	@Column(name = "ip_acces", length = 50)
//	public String getIpAcces() {
//		return this.ipAcces;
//	}
//
//	public void setIpAcces(String ipAcces) {
//		this.ipAcces = ipAcces;
//	}

	@Version
	@Column(name = "version_obj")
	public Integer getVersionObj() {
		return this.versionObj;
	}

	public void setVersionObj(Integer versionObj) {
		this.versionObj = versionObj;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_etat", length = 19)
	public Date getDateEtat() {
		return dateEtat;
	}

	public void setDateEtat(Date dateEtat) {
		this.dateEtat = dateEtat;
	}

	@Column(name = "commentaire")
	public String getCommentaire() {
		return commentaire;
	}

	public void setCommentaire(String commentaire) {
		this.commentaire = commentaire;
	}


	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_etat")
	@LgrHibernateValidated(champBd = "id_etat",table = "ta_etat",champEntite="TaEtat.idEtat", clazz = TaEtat.class)
	public TaEtat getTaEtat() {
		return this.taEtat;
	}

	public void setTaEtat(TaEtat taEtat) {
		this.taEtat = taEtat;
	}

	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_L_flash")
	public TaLFlash getTaLFlash() {
		return this.taLFlash;
	}

	public void setTaLFlash(TaLFlash taLflash) {
		this.taLFlash = taLflash;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_L_preparation")
	public TaLPreparation getTaLPreparation() {
		return this.taLPreparation;
	}

	public void setTaLPreparation(TaLPreparation taLpreparation) {
		this.taLPreparation = taLpreparation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_L_echeance")
	public TaLEcheance getTaLEcheance() {
		return taLEcheance;
	}

	public void setTaLEcheance(TaLEcheance taLEcheance) {
		this.taLEcheance = taLEcheance;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_L_abonnement")
	public TaLAbonnement getTaLAbonnement() {
		return taLAbonnement;
	}

	public void setTaLAbonnement(TaLAbonnement taLAbonnement) {
		this.taLAbonnement = taLAbonnement;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_L_panier")
	public TaLPanier getTaLPanier() {
		return taLPanier;
	}

	public void setTaLPanier(TaLPanier taLPanier) {
		this.taLPanier = taLPanier;
	}
}
