package fr.legrain.document.model;

// Generated Apr 7, 2009 3:27:23 PM by Hibernate Tools 3.2.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import fr.legrain.general.model.TaObjetLgr;
import fr.legrain.validator.LgrHibernateValidated;

/**
 * TaREtat generated by hbm2java
 */
@Entity
//@Cache(usage=CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "ta_r_etat")
public class TaREtat extends TaObjetLgr  implements java.io.Serializable {
	

	
	/**
	 * 
	 */
	private static final long serialVersionUID = 6503611145304200153L;
	
	
	private int idREtat;
//	private String version;
	private TaEtat taEtat;
	private TaFacture taFacture;
	private TaTicketDeCaisse taTicketDeCaisse;
	private TaBoncde taBoncde;
	private TaBoncdeAchat taBoncdeAchat;
	private TaProforma taProforma;
	private TaBonliv taBonliv;
	private TaAvoir taAvoir;
	private TaApporteur taApporteur;
	private TaDevis taDevis;
	private TaAcompte taAcompte;
	private TaPrelevement taPrelevement;
	private TaAvisEcheance taAvisEcheance;
	private TaBonReception taBonReception;
	private TaReglement taReglement;
	private Date dateEtat;
	private String commentaire;
	private TaFlash taFlash;
	private TaPreparation taPreparation;
	private TaPanier taPanier;
	
//	private String quiCree;
//	private Date quandCree;
//	private String quiModif;
//	private Date quandModif;
//	private String ipAcces;
	private Integer versionObj;

	public TaREtat() {
	}

	public TaREtat(int idREtat) {
		this.idREtat = idREtat;
	}





	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id_r_etat", unique = true, nullable = false)
	@LgrHibernateValidated(champBd = "id_r_etat",table = "ta_r_etat", champEntite="idREtat", clazz = TaREtat.class)
	public int getIdREtat() {
		return this.idREtat;
	}

	public void setIdREtat(int idREtat) {
		this.idREtat = idREtat;
	}

//	@Column(name = "version", length = 20)
//	public String getVersion() {
//		return this.version;
//	}
//
//	public void setVersion(String version) {
//		this.version = version;
//	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_facture")
	@LgrHibernateValidated(champBd = "id_document",table = "ta_facture", champEntite="taFacture.idDocument", clazz = TaFacture.class)
	public TaFacture getTaFacture() {
		return this.taFacture;
	}

	public void setTaFacture(TaFacture taFacture) {
		this.taFacture = taFacture;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_prelevement")
	@LgrHibernateValidated(champBd = "id_document",table = "ta_prelevement", champEntite="taPrelevement.idDocument", clazz = TaPrelevement.class)
	public TaPrelevement getTaPrelevement() {
		return taPrelevement;
	}

	public void setTaPrelevement(TaPrelevement taPrelevement) {
		this.taPrelevement = taPrelevement;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_avis_echeance")
	@LgrHibernateValidated(champBd = "id_document",table = "ta_avis_echeance", champEntite="taAvisEcheance.idDocument", clazz = TaAvisEcheance.class)
	public TaAvisEcheance getTaAvisEcheance() {
		return taAvisEcheance;
	}

	public void setTaAvisEcheance(TaAvisEcheance taAvisEcheance) {
		this.taAvisEcheance = taAvisEcheance;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_boncde")
	@LgrHibernateValidated(champBd = "id_document",table = "ta_boncde", champEntite="taBoncde.idDocument", clazz = TaBoncde.class)
	public TaBoncde getTaBoncde() {
		return this.taBoncde;
	}

	public void setTaBoncde(TaBoncde taBoncde) {
		this.taBoncde = taBoncde;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_boncde_achat")
	@LgrHibernateValidated(champBd = "id_document",table = "ta_boncde_achat", champEntite="taBoncde.idDocument", clazz = TaBoncdeAchat.class)
	public TaBoncdeAchat getTaBoncdeAchat() {
		return this.taBoncdeAchat;
	}

	public void setTaBoncdeAchat(TaBoncdeAchat taBoncdeAchat) {
		this.taBoncdeAchat = taBoncdeAchat;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_bon_reception")
	@LgrHibernateValidated(champBd = "id_document",table = "ta_bon_reception", champEntite="taBonReception.idDocument", clazz = TaBonReception.class)
	public TaBonReception getTaBonReception() {
		return this.taBonReception;
	}

	public void setTaBonReception(TaBonReception taBonReception) {
		this.taBonReception = taBonReception;
	}
	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_proforma")
	@LgrHibernateValidated(champBd = "id_document",table = "ta_proforma", champEntite="taProforma.idDocument", clazz = TaProforma.class)
	public TaProforma getTaProforma() {
		return this.taProforma;
	}

	public void setTaProforma(TaProforma taProforma) {
		this.taProforma = taProforma;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_bonliv")
	@LgrHibernateValidated(champBd = "id_document",table = "ta_bonliv", champEntite="taBonliv.idDocument", clazz = TaBonliv.class)
	public TaBonliv getTaBonliv() {
		return this.taBonliv;
	}

	public void setTaBonliv(TaBonliv taBonliv) {
		this.taBonliv = taBonliv;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_avoir")
	@LgrHibernateValidated(champBd = "id_document",table = "ta_avoir", champEntite="taAvoir.idDocument", clazz = TaAvoir.class)
	public TaAvoir getTaAvoir() {
		return this.taAvoir;
	}

	public void setTaAvoir(TaAvoir taAvoir) {
		this.taAvoir = taAvoir;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_apporteur")
	@LgrHibernateValidated(champBd = "id_document",table = "ta_apporteur", champEntite="taApporteur.idDocument", clazz = TaApporteur.class)
	public TaApporteur getTaApporteur() {
		return this.taApporteur;
	}

	public void setTaApporteur(TaApporteur taApporteur) {
		this.taApporteur = taApporteur;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_devis")
	@LgrHibernateValidated(champBd = "id_document",table = "ta_devis", champEntite="taDevis.idDocument", clazz = TaApporteur.class)
	public TaDevis getTaDevis() {
		return this.taDevis;
	}

	public void setTaDevis(TaDevis idDevis) {
		this.taDevis = idDevis;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_acompte")
	@LgrHibernateValidated(champBd = "id_document",table = "ta_acompte", champEntite="taAcompte.idDocument", clazz = TaAcompte.class)
	public TaAcompte getTaAcompte() {
		return taAcompte;
	}

	public void setTaAcompte(TaAcompte taAcompte) {
		this.taAcompte = taAcompte;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_ticket_caisse")
	@LgrHibernateValidated(champBd = "id_document",table = "ta_ticket_caisse", champEntite="taTicketDeCaisse.idDocument", clazz = TaTicketDeCaisse.class)
	public TaTicketDeCaisse getTaTicketDeCaisse() {
		return taTicketDeCaisse;
	}

	public void setTaTicketDeCaisse(TaTicketDeCaisse taTicketDeCaisse) {
		this.taTicketDeCaisse = taTicketDeCaisse;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_reglement")
	@LgrHibernateValidated(champBd = "id_document",table = "ta_reglement", champEntite="taReglement.idDocument", clazz = TaReglement.class)
	public TaReglement getTaReglement() {
		return taReglement;
	}

	public void setTaReglement(TaReglement taReglement) {
		this.taReglement = taReglement;
	}
	
	
//	@Column(name = "qui_cree", length = 50)
//	public String getQuiCree() {
//		return this.quiCree;
//	}
//
//	public void setQuiCree(String quiCreeREtat) {
//		this.quiCree = quiCreeREtat;
//	}
//
//	@Temporal(TemporalType.TIMESTAMP)
//	@Column(name = "quand_cree", length = 19)
//	public Date getQuandCree() {
//		return this.quandCree;
//	}
//
//	public void setQuandCree(Date quandCreeREtat) {
//		this.quandCree = quandCreeREtat;
//	}
//
//	@Column(name = "qui_modif", length = 50)
//	public String getQuiModif() {
//		return this.quiModif;
//	}
//
//	public void setQuiModif(String quiModifREtat) {
//		this.quiModif = quiModifREtat;
//	}
//
//	@Temporal(TemporalType.TIMESTAMP)
//	@Column(name = "quand_modif", length = 19)
//	public Date getQuandModif() {
//		return this.quandModif;
//	}
//
//	public void setQuandModif(Date quandModifREtat) {
//		this.quandModif = quandModifREtat;
//	}
//
//	@Column(name = "ip_acces", length = 50)
//	public String getIpAcces() {
//		return this.ipAcces;
//	}
//
//	public void setIpAcces(String ipAcces) {
//		this.ipAcces = ipAcces;
//	}

	@Version
	@Column(name = "version_obj")
	public Integer getVersionObj() {
		return this.versionObj;
	}

	public void setVersionObj(Integer versionObj) {
		this.versionObj = versionObj;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_etat", length = 19)
	public Date getDateEtat() {
		return dateEtat;
	}

	public void setDateEtat(Date dateEtat) {
		this.dateEtat = dateEtat;
	}

	@Column(name = "commentaire")
	public String getCommentaire() {
		return commentaire;
	}

	public void setCommentaire(String commentaire) {
		this.commentaire = commentaire;
	}



	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_etat")
	@LgrHibernateValidated(champBd = "id_etat",table = "ta_etat",champEntite="TaEtat.idEtat", clazz = TaEtat.class)
	public TaEtat getTaEtat() {
		return this.taEtat;
	}

	public void setTaEtat(TaEtat taEtat) {
		this.taEtat = taEtat;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_flash")
	@LgrHibernateValidated(champBd = "id_document",table = "ta_flash", champEntite="taFlashn.idDocument", clazz = TaFlash.class)
	public TaFlash getTaFlash() {
		return taFlash;
	}

	public void setTaFlash(TaFlash taFlash) {
		this.taFlash = taFlash;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_preparation")
	@LgrHibernateValidated(champBd = "id_document",table = "ta_preparation", champEntite="taPreparation.idDocument", clazz = TaPreparation.class)
	public TaPreparation getTaPreparation() {
		return taPreparation;
	}

	public void setTaPreparation(TaPreparation taPreparation) {
		this.taPreparation = taPreparation;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_panier")
	@LgrHibernateValidated(champBd = "id_document",table = "ta_panier", champEntite="taPanier.idDocument", clazz = TaPanier.class)
	public TaPanier getTaPanier() {
		return taPanier;
	}

	public void setTaPanier(TaPanier taPanier) {
		this.taPanier = taPanier;
	}

	
}
