package fr.legrain.dossierIntelligent.dao;

// Generated Mar 24, 2009 4:44:04 PM by Hibernate Tools 3.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import fr.legrain.validator.LgrHibernateValidated;


/**
 * TaAdresse generated by hbm2java
 */
@Entity
//@Cache(usage=CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "TA_PARAM_DOSSIER_INTELLIGENT")
@SequenceGenerator(name = "GEN_PARAM_DOSSIER_INTELLIGENT", sequenceName = "NUM_ID_PARAM_DOSS_INTEL", allocationSize = 1)
public class TaParamDossierIntel implements java.io.Serializable {

	private int id;
	private String mot;
	private String sql;
	private int nbZones;
	private String quiCree;
	private Date quandCree;
	private String quiModif;
	private Date quandModif;
	private String ipAcces;
	private Integer versionObj;
	private String version;
	private Set<TaRParamDossierIntel> taRParamDossierIntel = new HashSet<TaRParamDossierIntel>(0);

	public TaParamDossierIntel() {
	}

	public TaParamDossierIntel(int id) {
		this.id = id;
	}


	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "GEN_PARAM_DOSSIER_INTELLIGENT")
	@Column(name = "ID", unique = true, nullable = false)
	@LgrHibernateValidated(champEntite = "", champBd = "ID",table = "TA_PARAM_DOSSIER_INTELLIGENT",clazz = TaTypeDonnee.class)
	public int getId() {
		return this.id;
	}

	public void setId(int idTiersPoint) {
		this.id = idTiersPoint;
	}

	@Column(name = "VERSION", length = 20)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}



	@Column(name = "MOT", length = 50)
	@LgrHibernateValidated(champEntite = "", champBd = "MOT",table = "TA_PARAM_DOSSIER_INTELLIGENT",clazz = TaTypeDonnee.class)
	public String getMot() {
		return this.mot;
	}

	public void setMot(String mot) {
		this.mot = mot;
	}

	@Column(name = "SQL", length = 50)
	@LgrHibernateValidated(champEntite = "", champBd = "SQL",table = "TA_PARAM_DOSSIER_INTELLIGENT",clazz = TaTypeDonnee.class)
	public String getSql() {
		return this.sql;
	}

	public void setSql(String sql) {
		this.sql = sql;
	}
	
	@Column(name = "NB_ZONES" )
	@LgrHibernateValidated(champEntite = "", champBd = "NB_ZONES",table = "TA_PARAM_DOSSIER_INTELLIGENT",clazz = TaTypeDonnee.class)
	public int getNbZones() {
		return this.nbZones;
	}

	public void setNbZones(int nbZones) {
		this.nbZones = nbZones;
	}
	
	@Column(name = "QUI_CREE", length = 50)
	public String getQuiCree() {
		return this.quiCree;
	}

	public void setQuiCree(String quiCree) {
		this.quiCree = quiCree;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "QUAND_CREE", length = 19)
	public Date getQuandCree() {
		return this.quandCree;
	}

	public void setQuandCree(Date quandCree) {
		this.quandCree = quandCree;
	}

	@Column(name = "QUI_MODIF", length = 50)
	public String getQuiModif() {
		return this.quiModif;
	}

	public void setQuiModif(String quiModif) {
		this.quiModif = quiModif;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "QUAND_MODIF", length = 19)
	public Date getQuandModif() {
		return this.quandModif;
	}

	public void setQuandModif(Date quandModif) {
		this.quandModif = quandModif;
	}

	@Column(name = "IP_ACCES", length = 50)
	public String getIpAcces() {
		return this.ipAcces;
	}

	public void setIpAcces(String ipAcces) {
		this.ipAcces = ipAcces;
	}

	@Version
	@Column(name = "VERSION_OBJ")
	public Integer getVersionObj() {
		return this.versionObj;
	}

	public void setVersionObj(Integer versionObj) {
		this.versionObj = versionObj;
	}

	@OneToMany(cascade = {CascadeType.PERSIST, CascadeType.MERGE}, fetch = FetchType.LAZY, mappedBy = "taParamDossierIntel")
	public Set<TaRParamDossierIntel> getTaRParamDossierIntel() {
		return this.taRParamDossierIntel;
	}

	public void setTaRParamDossierIntel(Set<TaRParamDossierIntel> taRParamDossierIntel) {
		this.taRParamDossierIntel = taRParamDossierIntel;
	}

}
