package fr.legrain.gestCom.Module_Document;

// Generated 20 mars 2007 09:51:19 by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import java.util.Date;

import fr.legrain.lib.data.ModelObject;

/**
 * IHMEnteteFacture generated by hbm2java
 */
public class IHMAideDocument extends ModelObject {

	private Integer idDocument=0;
	private String codeDocument;
	private Date dateDocument=new Date();
	private Date dateEchDocument=new Date();
	private Date dateLivDocument=new Date();
	private String libelleDocument;
	private String codeTiers;
	private String nomTiers;
	private String codeCompta;
	private String compte;
	private BigDecimal regleDocument=new BigDecimal(0);
	private BigDecimal netTtcCalc=new BigDecimal(0);
	private String commentaire;
	private BigDecimal resteARegler=new BigDecimal(0);
	private BigDecimal regleCompletDocument=new BigDecimal(0);
	private BigDecimal resteAReglerComplet=new BigDecimal(0);
	private Boolean export=false;
	
	public IHMAideDocument() {
	}

	public IHMAideDocument(Integer ID_FACTURE, String CODE_FACTURE,
			Date DATE_FACTURE, Date DATE_ECH_FACTURE, Date DATE_LIV_FACTURE,
			String LIBELLE_FACTURE, String CODE_TIERS, String NOM_TIERS,
			String CODE_COMPTA, String COMPTE, BigDecimal REGLE_FACTURE,
			String COMMENTAIRE,BigDecimal netTtcCalc,BigDecimal ResteARegler) {
		this.idDocument = ID_FACTURE;
		this.codeDocument = CODE_FACTURE;
		this.dateDocument = DATE_FACTURE;
		this.dateEchDocument = DATE_ECH_FACTURE;
		this.dateLivDocument = DATE_LIV_FACTURE;
		this.libelleDocument = LIBELLE_FACTURE;
		this.codeTiers = CODE_TIERS;
		this.nomTiers = NOM_TIERS;
		this.codeCompta = CODE_COMPTA;
		this.compte = COMPTE;
		this.regleDocument = REGLE_FACTURE;
		this.commentaire = COMMENTAIRE;
		this.netTtcCalc = netTtcCalc;
		this.resteARegler = ResteARegler;
	}

	public void setIHMEnteteFacture(IHMAideDocument ihmEnteteFacture){
		setIdDocument(ihmEnteteFacture.idDocument);
		setCodeDocument(ihmEnteteFacture.codeDocument);
		setDateDocument(ihmEnteteFacture.dateDocument);
		setDateEchDocument(ihmEnteteFacture.dateEchDocument);
		setDateLivDocument(ihmEnteteFacture.dateLivDocument);
		setLibelleDocument(ihmEnteteFacture.libelleDocument);
		setCodeTiers(ihmEnteteFacture.codeTiers);
		setNomTiers(ihmEnteteFacture.nomTiers);
		setCodeCompta(ihmEnteteFacture.codeCompta);
		setCompte(ihmEnteteFacture.compte);
		setRegleDocument(ihmEnteteFacture.regleDocument);
		setCommentaire(ihmEnteteFacture.commentaire);
		setNetTtcCalc(ihmEnteteFacture.netTtcCalc);
		setResteARegler(ihmEnteteFacture.resteARegler);
	}
	
	
	public static IHMAideDocument copy(IHMAideDocument ihmEnteteFacture){
		IHMAideDocument ihmEnteteFactureLoc = new IHMAideDocument();
		ihmEnteteFactureLoc.setIdDocument(ihmEnteteFacture.idDocument);
		ihmEnteteFactureLoc.setCodeDocument(ihmEnteteFacture.codeDocument);
		ihmEnteteFactureLoc.setDateDocument(ihmEnteteFacture.dateDocument);
		ihmEnteteFactureLoc.setDateEchDocument(ihmEnteteFacture.dateEchDocument);
		ihmEnteteFactureLoc.setDateLivDocument(ihmEnteteFacture.dateLivDocument);
		ihmEnteteFactureLoc.setLibelleDocument(ihmEnteteFacture.libelleDocument);
		ihmEnteteFactureLoc.setCodeTiers(ihmEnteteFacture.codeTiers);
		ihmEnteteFactureLoc.setNomTiers(ihmEnteteFacture.nomTiers);
		ihmEnteteFactureLoc.setCodeCompta(ihmEnteteFacture.codeCompta);
		ihmEnteteFactureLoc.setCompte(ihmEnteteFacture.compte);
		ihmEnteteFactureLoc.setRegleDocument(ihmEnteteFacture.regleDocument);
		ihmEnteteFactureLoc.setCommentaire(ihmEnteteFacture.commentaire);
		ihmEnteteFactureLoc.setNetTtcCalc(ihmEnteteFacture.netTtcCalc);
		ihmEnteteFactureLoc.setResteARegler(ihmEnteteFacture.resteARegler);
		return ihmEnteteFactureLoc;
	}
	
	
	public Integer getIdDocument() {
		return this.idDocument;
	}

	public void setIdDocument(Integer ID_FACTURE) {
		firePropertyChange("idDocument", this.idDocument, this.idDocument = ID_FACTURE);
	}

	public String getCodeDocument() {
		return this.codeDocument;
	}

	public void setCodeDocument(String CODE_FACTURE) {
		firePropertyChange("codeDocument", this.codeDocument, this.codeDocument = CODE_FACTURE);
	}

	public Date getDateDocument() {
		return this.dateDocument;
	}

	public void setDateDocument(Date DATE_FACTURE) {
		firePropertyChange("dateDocument", this.dateDocument, this.dateDocument = DATE_FACTURE);
	}

	
	public Date getDateEchDocument() {
		return this.dateEchDocument;
	}

	public void setDateEchDocument(Date DATE_ECH_FACTURE) {
		firePropertyChange("dateEchDocument", this.dateEchDocument, this.dateEchDocument = DATE_ECH_FACTURE);
	}

	public Date getDateLivDocument() {
		return this.dateLivDocument;
	}

	public void setDateLivDocument(Date DATE_LIV_FACTURE) {
		firePropertyChange("dateLivDocument", this.dateLivDocument, this.dateLivDocument = DATE_LIV_FACTURE);
	}

	public String getLibelleDocument() {
		return this.libelleDocument;
	}

	public void setLibelleDocument(String LIBELLE_FACTURE) {
		firePropertyChange("libelleDocument", this.libelleDocument, this.libelleDocument = LIBELLE_FACTURE);
	}

	public String getCodeTiers() {
		return this.codeTiers;
	}

	public void setCodeTiers(String CODE_TIERS) {
		firePropertyChange("codeTiers", this.codeTiers, this.codeTiers = CODE_TIERS);
	}

	public String getNomTiers() {
		return this.nomTiers;
	}

	public void setNomTiers(String NOM_TIERS) {
		firePropertyChange("nomTiers", this.nomTiers, this.nomTiers = NOM_TIERS);
	}

	public String getCodeCompta() {
		return this.codeCompta;
	}

	public void setCodeCompta(String CODE_COMPTA) {
		firePropertyChange("codeCompta", this.codeCompta, this.codeCompta = CODE_COMPTA);
	}

	public String getCompte() {
		return this.compte;
	}

	public void setCompte(String COMPTE) {
		firePropertyChange("compte", this.compte, this.compte = COMPTE);
	}

	public BigDecimal getRegleDocument() {
		return this.regleDocument;
	}

	public void setRegleDocument(BigDecimal REGLE_FACTURE) {
		firePropertyChange("regleDocument", this.regleDocument, this.regleDocument = REGLE_FACTURE);
	}




	public String getCommentaire() {
		return commentaire;
	}

	public void setCommentaire(String COMMENTAIRE) {
		firePropertyChange("commentaire", this.commentaire, this.commentaire = COMMENTAIRE);
	}

	public BigDecimal getNetTtcCalc() {
		return netTtcCalc;
	}

	public void setNetTtcCalc(BigDecimal netTtcCalc) {
		firePropertyChange("netTtcCalc", this.netTtcCalc, this.netTtcCalc = netTtcCalc);
	}

	public BigDecimal getResteARegler() {
		return resteARegler;
	}

	public void setResteARegler(BigDecimal resteARegler) {
		firePropertyChange("ResteARegler", this.resteARegler, this.resteARegler = resteARegler);
	}

	public BigDecimal getRegleCompletDocument() {
		return regleCompletDocument;
	}

	public void setRegleCompletDocument(BigDecimal regleCompletDocument) {
		firePropertyChange("regleCompletDocument", this.regleCompletDocument, this.regleCompletDocument = regleCompletDocument);
	}

	public BigDecimal getResteAReglerComplet() {
		return resteAReglerComplet;
	}

	public void setResteAReglerComplet(BigDecimal resteAReglerComplet) {
		firePropertyChange("resteAReglerComplet", this.resteAReglerComplet, this.resteAReglerComplet = resteAReglerComplet);
	}
	
	public Boolean getExport() {
		return this.export;
	}

	public void setExport(Boolean EXPORT) {
		firePropertyChange("export", this.export, this.export = EXPORT);
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((codeCompta == null) ? 0 : codeCompta.hashCode());
		result = prime * result
				+ ((codeDocument == null) ? 0 : codeDocument.hashCode());
		result = prime * result
				+ ((codeTiers == null) ? 0 : codeTiers.hashCode());
		result = prime * result
				+ ((commentaire == null) ? 0 : commentaire.hashCode());
		result = prime * result + ((compte == null) ? 0 : compte.hashCode());
		result = prime * result
				+ ((dateDocument == null) ? 0 : dateDocument.hashCode());
		result = prime * result
				+ ((dateEchDocument == null) ? 0 : dateEchDocument.hashCode());
		result = prime * result
				+ ((dateLivDocument == null) ? 0 : dateLivDocument.hashCode());
		result = prime * result + ((export == null) ? 0 : export.hashCode());
		result = prime * result
				+ ((idDocument == null) ? 0 : idDocument.hashCode());
		result = prime * result
				+ ((libelleDocument == null) ? 0 : libelleDocument.hashCode());
		result = prime * result
				+ ((netTtcCalc == null) ? 0 : netTtcCalc.hashCode());
		result = prime * result
				+ ((nomTiers == null) ? 0 : nomTiers.hashCode());
		result = prime
				* result
				+ ((regleCompletDocument == null) ? 0 : regleCompletDocument
						.hashCode());
		result = prime * result
				+ ((regleDocument == null) ? 0 : regleDocument.hashCode());
		result = prime * result
				+ ((resteARegler == null) ? 0 : resteARegler.hashCode());
		result = prime
				* result
				+ ((resteAReglerComplet == null) ? 0 : resteAReglerComplet
						.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		IHMAideDocument other = (IHMAideDocument) obj;
		if (codeCompta == null) {
			if (other.codeCompta != null)
				return false;
		} else if (!codeCompta.equals(other.codeCompta))
			return false;
		if (codeDocument == null) {
			if (other.codeDocument != null)
				return false;
		} else if (!codeDocument.equals(other.codeDocument))
			return false;
		if (codeTiers == null) {
			if (other.codeTiers != null)
				return false;
		} else if (!codeTiers.equals(other.codeTiers))
			return false;
		if (commentaire == null) {
			if (other.commentaire != null)
				return false;
		} else if (!commentaire.equals(other.commentaire))
			return false;
		if (compte == null) {
			if (other.compte != null)
				return false;
		} else if (!compte.equals(other.compte))
			return false;
		if (dateDocument == null) {
			if (other.dateDocument != null)
				return false;
		} else if (!dateDocument.equals(other.dateDocument))
			return false;
		if (dateEchDocument == null) {
			if (other.dateEchDocument != null)
				return false;
		} else if (!dateEchDocument.equals(other.dateEchDocument))
			return false;
		if (dateLivDocument == null) {
			if (other.dateLivDocument != null)
				return false;
		} else if (!dateLivDocument.equals(other.dateLivDocument))
			return false;
		if (export == null) {
			if (other.export != null)
				return false;
		} else if (!export.equals(other.export))
			return false;
		if (idDocument == null) {
			if (other.idDocument != null)
				return false;
		} else if (!idDocument.equals(other.idDocument))
			return false;
		if (libelleDocument == null) {
			if (other.libelleDocument != null)
				return false;
		} else if (!libelleDocument.equals(other.libelleDocument))
			return false;
		if (netTtcCalc == null) {
			if (other.netTtcCalc != null)
				return false;
		} else if (!netTtcCalc.equals(other.netTtcCalc))
			return false;
		if (nomTiers == null) {
			if (other.nomTiers != null)
				return false;
		} else if (!nomTiers.equals(other.nomTiers))
			return false;
		if (regleCompletDocument == null) {
			if (other.regleCompletDocument != null)
				return false;
		} else if (!regleCompletDocument.equals(other.regleCompletDocument))
			return false;
		if (regleDocument == null) {
			if (other.regleDocument != null)
				return false;
		} else if (!regleDocument.equals(other.regleDocument))
			return false;
		if (resteARegler == null) {
			if (other.resteARegler != null)
				return false;
		} else if (!resteARegler.equals(other.resteARegler))
			return false;
		if (resteAReglerComplet == null) {
			if (other.resteAReglerComplet != null)
				return false;
		} else if (!resteAReglerComplet.equals(other.resteAReglerComplet))
			return false;
		return true;
	}
	
	







	

}
