package fr.legrain.documents.dao;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import fr.legrain.validator.LgrHibernateValidated;

/**
 * TaTRelance generated by hbm2java
 */
@Entity
//@Cache(usage=CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "TA_DOCUMENT_DOC")
@SequenceGenerator(name = "GEN_DOCUMENT_DOC", sequenceName = "NUM_ID_DOCUMENT_DOC", allocationSize = 1)
public class TaDocumentEditable implements java.io.Serializable {

	private int idDocumentDoc;
	private String version;
	private String codeDocumentDoc;
	private String libelleDocumentDoc;
	private String cheminModelDocumentDoc;
	private String cheminCorrespDocumentDoc;
	private String quiCreeDocumentDoc;
	private Date quandCreeDocumentDoc;
	private String quiModifDocumentDoc;
	private Date quandModifDocumentDoc;
	private String ipAcces;
	private Integer versionObj;
	private Integer actif=1;
	private Integer defaut=0;
	private String typeLogiciel;
	private Set<TaTDoc> taTDoc = new HashSet<TaTDoc>(0);

	public TaDocumentEditable() {
	}

	public TaDocumentEditable(int idDocumentDoc) {
		this.idDocumentDoc = idDocumentDoc;
	}

	
	public TaDocumentEditable(int idDocumentDoc, String version, String codeDocumentDoc,
			String libelleDocumentDoc, String cheminModelDocumentDoc,
			String cheminCorrespDocumentDoc, 
			String quiCreeDocumentDoc, Date quandCreeDocumentDoc,
			String quiModifDocumentDoc, Date quandModifDocumentDoc, String ipAcces,
			Integer versionObj, Integer actif, Integer defaut,
			String typeLogiciel) {
		this.idDocumentDoc = idDocumentDoc;
		this.version = version;
		this.codeDocumentDoc = codeDocumentDoc;
		this.libelleDocumentDoc = libelleDocumentDoc;
		this.cheminModelDocumentDoc = cheminModelDocumentDoc;
		this.cheminCorrespDocumentDoc = cheminCorrespDocumentDoc;
		this.quiCreeDocumentDoc = quiCreeDocumentDoc;
		this.quandCreeDocumentDoc = quandCreeDocumentDoc;
		this.quiModifDocumentDoc = quiModifDocumentDoc;
		this.quandModifDocumentDoc = quandModifDocumentDoc;
		this.ipAcces = ipAcces;
		this.versionObj = versionObj;
		this.actif = actif;
		this.defaut = defaut;
		this.typeLogiciel = typeLogiciel;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "GEN_DOCUMENT_DOC")
	@Column(name = "ID_DOCUMENT_DOC", unique = true, nullable = false)
	@LgrHibernateValidated(champEntite = "", champBd = "ID_DOCUMENT_DOC",table = "TA_DOCUMENT_DOC",clazz = TaDocumentEditable.class)
	public int getIdDocumentDoc() {
		return this.idDocumentDoc;
	}

	public void setIdDocumentDoc(int idDocumentDoc) {
		this.idDocumentDoc = idDocumentDoc;
	}

	@Column(name = "VERSION", length = 20)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@Column(name = "CODE_DOCUMENT_DOC", length = 20)
	@LgrHibernateValidated(champEntite = "", champBd = "CODE_DOCUMENT_DOC",table = "TA_DOCUMENT_DOC",clazz = TaDocumentEditable.class)
	public String getCodeDocumentDoc() {
		return this.codeDocumentDoc;
	}

	public void setCodeDocumentDoc(String codeDocumentDoc) {
		this.codeDocumentDoc = codeDocumentDoc;
	}

	@Column(name = "LIBELLE_DOCUMENT_DOC", length = 100)
	@LgrHibernateValidated(champEntite = "", champBd = "LIBELLE_DOCUMENT_DOC",table = "TA_DOCUMENT_DOC",clazz = TaDocumentEditable.class)
	public String getLibelleDocumentDoc() {
		return libelleDocumentDoc;
	}

	public void setLibelleDocumentDoc(String libelleDocumentDoc) {
		this.libelleDocumentDoc = libelleDocumentDoc;
	}
	
	@Column(name = "CHEMIN_MODEL_DOCUMENT_DOC", length = 255)
	@LgrHibernateValidated(champEntite = "", champBd = "CHEMIN_MODEL_DOCUMENT_DOC",table = "TA_DOCUMENT_DOC",clazz = TaDocumentEditable.class)
	public String getCheminModelDocumentDoc() {
		return this.cheminModelDocumentDoc;
	}

	public void setCheminModelDocumentDoc(String cheminModelDocumentDoc) {
		this.cheminModelDocumentDoc = cheminModelDocumentDoc;
	}
	
	@Column(name = "CHEMIN_CORRESP_DOCUMENT_DOC", length = 255)
	@LgrHibernateValidated(champEntite = "", champBd = "CHEMIN_CORRESP_DOCUMENT_DOC",table = "TA_DOCUMENT_DOC",clazz = TaDocumentEditable.class)
	public String getCheminCorrespDocumentDoc() {
		return cheminCorrespDocumentDoc;
	}

	public void setCheminCorrespDocumentDoc(String cheminCorrespDocumentDoc) {
		this.cheminCorrespDocumentDoc = cheminCorrespDocumentDoc;
	}
	
	@Column(name = "ACTIF" )
	@LgrHibernateValidated(champEntite = "", champBd = "ACTIF",table = "TA_DOCUMENT_DOC",clazz = TaDocumentEditable.class)
	public Integer getActif() {
		return actif;
	}

	public void setActif(Integer actif) {
		this.actif = actif;
	}

	@Column(name = "DEFAUT")
	@LgrHibernateValidated(champEntite = "", champBd = "DEFAUT",table = "TA_DOCUMENT_DOC",clazz = TaDocumentEditable.class)
	public Integer getDefaut() {
		return defaut;
	}

	public void setDefaut(Integer defaut) {
		this.defaut = defaut;
	}
	
	@Column(name = "TYPE_LOGICIEL", length = 20)
	@LgrHibernateValidated(champEntite = "", champBd = "TYPE_LOGICIEL",table = "TA_DOCUMENT_DOC",clazz = TaDocumentEditable.class)
	public String getTypeLogiciel() {
		return typeLogiciel;
	}

	public void setTypeLogiciel(String typeLogiciel) {
		this.typeLogiciel = typeLogiciel;
	}
	
	@ManyToMany(/*cascade = CascadeType.ALL,*/ fetch = FetchType.LAZY)
	@JoinTable(name = "TA_R_DOCUMENT_DOC",
			joinColumns = {@JoinColumn(name = "ID_DOCUMENT_DOC")},inverseJoinColumns = {@JoinColumn(name = "ID_T_DOC")})
	public Set<TaTDoc> getTaTDoc(){
		return this.taTDoc;
	}

	public void setTaTDoc(Set<TaTDoc> taTDoc) {
		this.taTDoc = taTDoc;
	}

	@Column(name = "QUI_CREE_DOCUMENT_DOC ", length = 50)
	public String getQuiCreeDocumentDoc() {
		return this.quiCreeDocumentDoc;
	}

	public void setQuiCreeDocumentDoc(String quiCreeDocumentDoc) {
		this.quiCreeDocumentDoc = quiCreeDocumentDoc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "QUAND_CREE_DOCUMENT_DOC", length = 19)
	public Date getQuandCreeDocumentDoc() {
		return this.quandCreeDocumentDoc;
	}

	public void setQuandCreeDocumentDoc(Date quandCreeDocumentDoc) {
		this.quandCreeDocumentDoc = quandCreeDocumentDoc;
	}

	@Column(name = "QUI_MODIF_DOCUMENT_DOC", length = 50)
	public String getQuiModifDocumentDoc() {
		return this.quiModifDocumentDoc;
	}

	public void setQuiModifDocumentDoc(String quiModifDocumentDoc) {
		this.quiModifDocumentDoc = quiModifDocumentDoc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "QUAND_MODIF_DOCUMENT_DOC", length = 19)
	public Date getQuandModifDocumentDoc() {
		return this.quandModifDocumentDoc;
	}

	public void setQuandModifDocumentDoc(Date quandModifDocumentDoc) {
		this.quandModifDocumentDoc = quandModifDocumentDoc;
	}

	@Column(name = "IP_ACCES", length = 50)
	public String getIpAcces() {
		return this.ipAcces;
	}

	public void setIpAcces(String ipAcces) {
		this.ipAcces = ipAcces;
	}

	@Version
	@Column(name = "VERSION_OBJ")
	public Integer getVersionObj() {
		return this.versionObj;
	}

	public void setVersionObj(Integer versionObj) {
		this.versionObj = versionObj;
	}
	
	public void addTaTDoc(TaTDoc taTDoc){
		if(!this.getTaTDoc().contains(taTDoc))
			this.getTaTDoc().add(taTDoc);
	}
	public void removeTaTDoc(TaTDoc taTDoc){
		this.getTaTDoc().remove(taTDoc);
	}

}
