package fr.legrain.documents.dao;

// Generated Apr 9, 2009 12:40:07 PM by Hibernate Tools 3.2.0.CR1

import java.beans.PropertyChangeEvent;
import java.math.BigDecimal;
import java.math.MathContext;
import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.apache.log4j.Logger;

import fr.legrain.articles.dao.TaArticle;
import fr.legrain.articles.dao.TaPrix;
import fr.legrain.gestCom.Appli.Const;
import fr.legrain.gestCom.Module_Document.ILigneDocumentTiers;
import fr.legrain.gestCom.Module_Document.SWTLigneDocument;
import fr.legrain.lib.data.LibCalcul;
import fr.legrain.validator.LgrHibernateValidated;

/**
 * TaLFacture generated by hbm2java
 */
@Entity
//@Cache(usage=CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "TA_L_FACTURE")
//@SequenceGenerator(name = "GEN_L_FACTURE", sequenceName = "NUM_ID_L_FACTURE", allocationSize = 1)
public class TaLFacture extends SWTLigneDocument implements java.io.Serializable, ILigneDocumentTiers,Cloneable {

//	private int idLDocument;
	private String version;
	private TaTLigne taTLigne;
	private TaFacture taDocument;
	private TaArticle taArticle;
	private Integer numLigneLDocument;
	private String libLDocument;
	private BigDecimal qteLDocument;
	private BigDecimal qte2LDocument;
	private String u1LDocument;
	private String u2LDocument;
	private BigDecimal prixULDocument;
	private BigDecimal tauxTvaLDocument;
	private String compteLDocument;
	private String codeTvaLDocument;
	private String codeTTvaLDocument;
	private BigDecimal mtHtLDocument;
	private BigDecimal mtTtcLDocument;
	private BigDecimal remTxLDocument;
	private BigDecimal remHtLDocument;
	private String codeTitreTransport;
	private BigDecimal qteTitreTransport;
	private String quiCreeLDocument;
	private Date quandCreeLDocument;
	private String quiModifLDocument;
	private Date quandModifLDocument;
//	private Integer versionObj;
	private String ipAcces;
	
	@Transient
	private boolean gestionTVA = true;

	/**
	 * Les annotations JPA étant définies sur les méthodes getXXX(), hibernate les utilises pour accéder ou affecter les valeurs des propriétés.<br>
	 * A l'initialisation des objets certaines valeur peuvent être nulles. La présence de code dans les get/set peu dans cas provoquer des erreurs.<br>
	 * JPA utlise toujours le constructeur par defaut (sans argument) pour créer un objet.<br>
	 * En ayant cette variable (<code>legrain</code>) initialisé à false par défaut et en "protégeant" le code présent dans les méthodes get/set par <br>
	 * cette variable, on empeche JPA d'executer cette partie de code.<br>
	 * Dans le cas ou un objet a été créé par JPA (résultat d'une requette JPA) mais que l'on souhaite que ces parties du code s'excute,<br>
	 *  il faut penser à changer cette variable.<br>
	 * Il est possible de faire en sorte que le framework JPA n'utilise pas les methodes get/set pour accéder aux valeurs en mettant les annotations<br>
	 * directement sur les propriétés ou avec des annotations spéciales mais cela pose d'autres problème dans le bureau de gestion.
	 */
	@Transient
	private boolean legrain = false;
	@Transient
	private BigDecimal txRemHtDocument;
	//@Transient
	private BigDecimal mtHtLApresRemiseGlobaleDocument;
	//@Transient
	private BigDecimal mtTtcLApresRemiseGlobaleDocument;
	@Transient
	static Logger logger = Logger.getLogger(TaLFacture.class.getName());
	

	public TaLFacture() {
	}

	public TaLFacture(boolean legrain) {
		this.legrain = legrain;
	}
	
	public TaLFacture(int idLFacture) {
		this.idLDocument = idLFacture;
	}

	public TaLFacture(int idLFacture, TaTLigne taTLigne, TaFacture taFacture,
			TaArticle taArticle, Integer numLigneLFacture, String libLFacture,
			BigDecimal qteLFacture, BigDecimal qte2LFacture, String u1LFacture,
			String u2LFacture, BigDecimal prixULFacture,
			BigDecimal tauxTvaLFacture, String compteLFacture,
			String codeTvaLFacture, String codeTTvaLFacture,
			BigDecimal mtHtLFacture, BigDecimal mtTtcLFacture,
			BigDecimal remTxLFacture, BigDecimal remHtLFacture,
			String quiCreeLFacture, Date quandCreeLFacture,
			String quiModifLFacture, Date quandModifLFacture, String ipAcces,
			Integer versionObj) {
		this.idLDocument = idLFacture;
		this.taTLigne = taTLigne;
		this.taDocument = taFacture;
		this.taArticle = taArticle;
		this.numLigneLDocument = numLigneLFacture;
		this.libLDocument = libLFacture;
		this.qteLDocument = qteLFacture;
		this.qte2LDocument = qte2LFacture;
		this.u1LDocument = u1LFacture;
		this.u2LDocument = u2LFacture;
		this.prixULDocument = prixULFacture;
		this.tauxTvaLDocument = tauxTvaLFacture;
		this.compteLDocument = compteLFacture;
		this.codeTvaLDocument = codeTvaLFacture;
		this.codeTTvaLDocument = codeTTvaLFacture;
		this.mtHtLDocument = mtHtLFacture;
		this.mtTtcLDocument = mtTtcLFacture;
		this.remTxLDocument = remTxLFacture;
		this.remHtLDocument = remHtLFacture;
		this.quiCreeLDocument = quiCreeLFacture;
		this.quandCreeLDocument = quandCreeLFacture;
		this.quiModifLDocument = quiModifLFacture;
		this.quandModifLDocument = quandModifLFacture;
		this.ipAcces = ipAcces;
		this.versionObj = versionObj;
	}

//	@Id
//	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "GEN_L_FACTURE")
//	@Column(name = "ID_L_DOCUMENT", unique = true, nullable = false)
//	@LgrHibernateValidated(champEntite = "", champ = "ID_L_DOCUMENT",table = "TA_L_FACTURE",clazz = TaLFacture.class)
//	public int getIdLDocument() {
//		return this.idLDocument;
//	}
//
//	public void setIdLDocument(int idLFacture) {
//		this.idLDocument = idLFacture;
//	}

	@Column(name = "VERSION", length = 20)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.REFRESH)
	@JoinColumn(name = "ID_T_LIGNE")
	@LgrHibernateValidated(champEntite = "", champBd = "ID_T_LIGNE",table = "TA_T_LIGNE",clazz = TaTLigne.class)
	public TaTLigne getTaTLigne() {
		return this.taTLigne;
	}

	public void setTaTLigne(TaTLigne taTLigne) {
		this.taTLigne = taTLigne;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_DOCUMENT")
	@LgrHibernateValidated(champEntite = "", champBd = "ID_DOCUMENT",table = "TA_FACTURE",clazz = TaFacture.class)
	public TaFacture getTaDocument() {
		return this.taDocument;
	}

	public void setTaDocument(TaFacture taFacture) {
		this.taDocument = taFacture;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.REFRESH)
	@JoinColumn(name = "ID_ARTICLE")
	@LgrHibernateValidated(champEntite = "", champBd = "ID_ARTICLE",table = "TA_ARTICLE",clazz = TaArticle.class)
	public TaArticle getTaArticle() {
		return this.taArticle;
	}

	public void setTaArticle(TaArticle taArticle) {
		this.taArticle = taArticle;

		if(legrain) {
			if(taArticle!=null) {
				if(getTaTLigne()==null || getTaTLigne().getCodeTLigne()==null)
					setTaTLigne(new TaTLigneDAO().findByCode(Const.C_CODE_T_LIGNE_H));
				else
					if(!getTaTLigne().getCodeTLigne().equals(Const.C_CODE_T_LIGNE_H))
						setTaTLigne(new TaTLigneDAO().findByCode(Const.C_CODE_T_LIGNE_H));
				boolean commentaire=false;
				commentaire=taArticle.getTaFamille()!=null && taArticle.getTaFamille().getCodeFamille().equals("&&&");
				if(!commentaire){
					TaPrix prix = taArticle.chercheTarif(taDocument.getTaTiers());
					if(prix!=null) {
						if(taDocument!=null) { //#JPA
							if(taDocument.getTtc()==1)
								setPrixULDocument(prix.getPrixttcPrix());
							else
								setPrixULDocument(prix.getPrixPrix());
						}

						if(prix.getTaUnite()!=null) {
							setU1LDocument(prix.getTaUnite().getCodeUnite());
						}
					}else{
						setPrixULDocument(BigDecimal.valueOf(0));
						setU1LDocument("");
					}

					if(taArticle.getTaTva()!=null && taDocument.isGestionTVA()) {
						setCodeTvaLDocument(taArticle.getTaTva().getCodeTva());
						setTauxTvaLDocument(taArticle.getTaTva().getTauxTva());
					}else{
						setCodeTvaLDocument("");
						setTauxTvaLDocument(BigDecimal.valueOf(0));
					}
					setQteLDocument(new BigDecimal(1));
					setCompteLDocument(taArticle.getNumcptArticle());
//					if(taArticle.getTaTitreTransport()!=null) {
//						setCodeTitreTransport(taArticle.getTaTitreTransport().getCodeTitreTransport());
//					}
					if(taArticle.getTaRTaTitreTransport()!=null) {
						//if(taArticle.getTaRTaTitreTransport().getTaUnite()!=null && getU1LDocument().equals(taArticle.getTaRTaTitreTransport().getTaUnite().getCodeUnite())) {
							setCodeTitreTransport(taArticle.getTaRTaTitreTransport().getTaTitreTransport().getCodeTitreTransport());
							setQteTitreTransport(taArticle.getTaRTaTitreTransport().getQteTitreTransport());
						//}
					} else {
						setCodeTitreTransport("");
						setQteTitreTransport(BigDecimal.valueOf(0));
					}
					calculMontant();
					setLibLDocument(taArticle.getLibellecArticle());
				}
				else {
				setLibLDocument(taArticle.getLibellecArticle());
				setTaArticle(null);
				}
			}
		}
	}

	@Column(name = "NUM_LIGNE_L_DOCUMENT")
	@LgrHibernateValidated(champEntite = "", champBd = "NUM_LIGNE_L_DOCUMENT",table = "TA_L_FACTURE",clazz = TaLFacture.class)
	public Integer getNumLigneLDocument() {
		return this.numLigneLDocument;
	}

	public void setNumLigneLDocument(Integer numLigneLFacture) {
		this.numLigneLDocument = numLigneLFacture;
	}

	@Column(name = "LIB_L_DOCUMENT")
	@LgrHibernateValidated(champEntite = "", champBd = "LIB_L_DOCUMENT",table = "TA_L_FACTURE",clazz = TaLFacture.class)
	public String getLibLDocument() {
		return this.libLDocument;
	}

	public void setLibLDocument(String libLFacture) {
		this.libLDocument = libLFacture;
	}

	@Column(name = "QTE_L_DOCUMENT", precision = 15)
	@LgrHibernateValidated(champEntite = "", champBd = "QTE_L_DOCUMENT",table = "TA_L_FACTURE",clazz = TaLFacture.class)
	public BigDecimal getQteLDocument() {
		return this.qteLDocument;
	}

	public void setQteLDocument(BigDecimal qteLFacture) {
		BigDecimal qteLFactureOld = this.qteLDocument;
		this.qteLDocument = qteLFacture;
		if(legrain) {
			calculMontant();
			if(getCodeTitreTransport()!=null && !getCodeTitreTransport().equals("") //il y a un code CRD
					&& (
							(getQteTitreTransport()==null || getQteTitreTransport().equals("")) //il n'il y a pas de qte CRD
							|| (
									taArticle!=null && taArticle.getTaRTaTitreTransport()!=null //il y a une qte CRD qui correspond au rapport normal (qte CRD de l'aticle * qte de l'article)
									&& taArticle.getTaRTaTitreTransport().getQteTitreTransport()!=null && getQteTitreTransport()!=null 
									&& taArticle.getTaRTaTitreTransport().getQteTitreTransport().multiply(qteLFactureOld).compareTo(getQteTitreTransport())==0
									)
						)
					) { //CRD et pas de quantité saisie par l'utilisateur
				if(taArticle.getTaRTaTitreTransport()!=null && taArticle.getTaRTaTitreTransport().getQteTitreTransport()!=null) {
					setQteTitreTransport(taArticle.getTaRTaTitreTransport().getQteTitreTransport().multiply(getQteLDocument()));
				}
			} else {
				if(getCodeTitreTransport()==null || getCodeTitreTransport().equals(""))
					setQteTitreTransport(null);
			}
			firePropertyChange(new PropertyChangeEvent(this,"qteLDocument",qteLFactureOld,qteLFacture));
		}
	}

	@Column(name = "QTE2_L_DOCUMENT", precision = 15)
	@LgrHibernateValidated(champEntite = "", champBd = "QTE2_L_DOCUMENT",table = "TA_L_FACTURE",clazz = TaLFacture.class)
	public BigDecimal getQte2LDocument() {
		return this.qte2LDocument;
	}

	public void setQte2LDocument(BigDecimal qte2LFacture) {
		this.qte2LDocument = qte2LFacture;
	}

	@Column(name = "U1_L_DOCUMENT", length = 20)
	@LgrHibernateValidated(champEntite = "", champBd = "U1_L_DOCUMENT",table = "TA_L_FACTURE",clazz = TaLFacture.class)
	public String getU1LDocument() {
		return this.u1LDocument;
	}

	public void setU1LDocument(String u1LFacture) {
		this.u1LDocument = u1LFacture;
	}

	@Column(name = "U2_L_DOCUMENT", length = 20)
	@LgrHibernateValidated(champEntite = "", champBd = "U2_L_DOCUMENT",table = "TA_L_FACTURE",clazz = TaLFacture.class)
	public String getU2LDocument() {
		return this.u2LDocument;
	}

	public void setU2LDocument(String u2LFacture) {
		this.u2LDocument = u2LFacture;
	}

	@Column(name = "PRIX_U_L_DOCUMENT", precision = 15)
	@LgrHibernateValidated(champEntite = "", champBd = "PRIX_U_L_DOCUMENT",table = "TA_L_FACTURE",clazz = TaLFacture.class)
	public BigDecimal getPrixULDocument() {
		return this.prixULDocument;
	}

	public void setPrixULDocument(BigDecimal prixULFacture) {
		this.prixULDocument = prixULFacture;
		if(legrain) {
			calculMontant();
		}
	}

	@Column(name = "TAUX_TVA_L_DOCUMENT", precision = 15, scale = 4)
	@LgrHibernateValidated(champEntite = "", champBd = "TAUX_TVA_L_DOCUMENT",table = "TA_L_FACTURE",clazz = TaLFacture.class)
	public BigDecimal getTauxTvaLDocument() {
		return this.tauxTvaLDocument;
	}

	public void setTauxTvaLDocument(BigDecimal tauxTvaLFacture) {
		this.tauxTvaLDocument = tauxTvaLFacture;
	}

	@Column(name = "COMPTE_L_DOCUMENT", length = 8)
	@LgrHibernateValidated(champEntite = "", champBd = "COMPTE_L_DOCUMENT",table = "TA_L_FACTURE",clazz = TaLFacture.class)
	public String getCompteLDocument() {
		return this.compteLDocument;
	}

	public void setCompteLDocument(String compteLFacture) {
		this.compteLDocument = compteLFacture;
	}

	@Column(name = "CODE_TVA_L_DOCUMENT", length = 20)
	@LgrHibernateValidated(champEntite = "", champBd = "CODE_TVA_L_DOCUMENT",table = "TA_L_FACTURE",clazz = TaLFacture.class)
	public String getCodeTvaLDocument() {
		return this.codeTvaLDocument;
	}

	public void setCodeTvaLDocument(String codeTvaLFacture) {
		this.codeTvaLDocument = codeTvaLFacture;
	}

	@Column(name = "CODE_T_TVA_L_DOCUMENT", length = 1)
	@LgrHibernateValidated(champEntite = "", champBd = "CODE_T_TVA_L_DOCUMENT",table = "TA_L_FACTURE",clazz = TaLFacture.class)
	public String getCodeTTvaLDocument() {
		return this.codeTTvaLDocument;
	}

	public void setCodeTTvaLDocument(String codeTTvaLFacture) {
		this.codeTTvaLDocument = codeTTvaLFacture;
	}

	@Column(name = "MT_HT_L_DOCUMENT", precision = 15)
	@LgrHibernateValidated(champEntite = "", champBd = "MT_HT_L_DOCUMENT",table = "TA_L_FACTURE",clazz = TaLFacture.class)
	public BigDecimal getMtHtLDocument() {
		return this.mtHtLDocument;
	}

	public void setMtHtLDocument(BigDecimal mtHtLFacture) {
		this.mtHtLDocument = LibCalcul.arrondi(mtHtLFacture);
	}

	@Column(name = "MT_TTC_L_DOCUMENT", precision = 15)
	@LgrHibernateValidated(champEntite = "", champBd = "MT_TTC_L_DOCUMENT",table = "TA_L_FACTURE",clazz = TaLFacture.class)
	public BigDecimal getMtTtcLDocument() {
		return this.mtTtcLDocument;
	}

	public void setMtTtcLDocument(BigDecimal mtTtcLFacture) {
		this.mtTtcLDocument = LibCalcul.arrondi(mtTtcLFacture);
	}

	@Column(name = "REM_TX_L_DOCUMENT", precision = 15)
	@LgrHibernateValidated(champEntite = "", champBd = "REM_TX_L_DOCUMENT",table = "TA_L_FACTURE",clazz = TaLFacture.class)
	public BigDecimal getRemTxLDocument() {
		return this.remTxLDocument;
	}

	public void setRemTxLDocument(BigDecimal remTxLFacture) {
		this.remTxLDocument = remTxLFacture;
		if(legrain) {
			//calculMontant();
			taDocument.calculeTvaEtTotaux();
		}
		
	}

	@Column(name = "REM_HT_L_DOCUMENT", precision = 15)
	@LgrHibernateValidated(champEntite = "", champBd = "REM_HT_L_DOCUMENT",table = "TA_L_FACTURE",clazz = TaLFacture.class)
	public BigDecimal getRemHtLDocument() {
		return this.remHtLDocument;
	}

	public void setRemHtLDocument(BigDecimal remHtLFacture) {
		this.remHtLDocument = LibCalcul.arrondi(remHtLFacture);
	}
	
	@Column(name = "TITRE_TRANSPORT_L_DOCUMENT", length = 20)
	@LgrHibernateValidated(champEntite = "", champBd = "TITRE_TRANSPORT_L_DOCUMENT",table = "TA_L_FACTURE",clazz = TaLFacture.class)
	public String getCodeTitreTransport() {
		return this.codeTitreTransport;
	}

	public void setCodeTitreTransport(String titreTransport) {
		this.codeTitreTransport = titreTransport;
	}
	
	@Column(name = "QTE_TITRE_TRANSPORT_L_DOCUMENT", precision = 15)
	@LgrHibernateValidated(champEntite = "", champBd = "QTE_TITRE_TRANSPORT_L_DOCUMENT",table = "TA_L_FACTURE",clazz = TaLFacture.class)
	public BigDecimal getQteTitreTransport() {
		return this.qteTitreTransport;
	}

	public void setQteTitreTransport(BigDecimal qteTitreTransport) {
		this.qteTitreTransport = qteTitreTransport;
	}

	@Column(name = "QUI_CREE_L_DOCUMENT", length = 50)
	public String getQuiCreeLDocument() {
		return this.quiCreeLDocument;
	}

	public void setQuiCreeLDocument(String quiCreeLFacture) {
		this.quiCreeLDocument = quiCreeLFacture;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "QUAND_CREE_L_DOCUMENT", length = 19)
	public Date getQuandCreeLDocument() {
		return this.quandCreeLDocument;
	}

	public void setQuandCreeLDocument(Date quandCreeLFacture) {
		this.quandCreeLDocument = quandCreeLFacture;
	}

	@Column(name = "QUI_MODIF_L_DOCUMENT", length = 50)
	public String getQuiModifLDocument() {
		return this.quiModifLDocument;
	}

	public void setQuiModifLDocument(String quiModifLFacture) {
		this.quiModifLDocument = quiModifLFacture;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "QUAND_MODIF_L_DOCUMENT", length = 19)
	public Date getQuandModifLDocument() {
		return this.quandModifLDocument;
	}

	public void setQuandModifLDocument(Date quandModifLFacture) {
		this.quandModifLDocument = quandModifLFacture;
	}

	@Column(name = "IP_ACCES", length = 50)
	public String getIpAcces() {
		return this.ipAcces;
	}

	public void setIpAcces(String ipAcces) {
		this.ipAcces = ipAcces;
	}

//	@Version
//	@Column(name = "VERSION_OBJ")
//	public Integer getVersionObj() {
//		return this.versionObj;
//	}
//
//	public void setVersionObj(Integer versionObj) {
//		this.versionObj = versionObj;
//	}

//	public void initialiseLigne(boolean reset){
//		if (reset){
//			setLibLDocument("");
//			setQteLDocument(null);
//			setQte2LDocument(null);
//			setU1LDocument("") ;
//			setU2LDocument("") ;
//			setPrixULDocument(null);
//			setTauxTvaLDocument(null);
//			setCodeTvaLDocument("");
//			setCodeTTvaLDocument("");
//			setMtHtLDocument(null);
//			setMtTtcLDocument(null);
//			setRemTxLDocument(null);
//			setRemHtLDocument(null);
//		}else {
//			setLibLDocument("");
//			setQteLDocument(new BigDecimal(0));
//			setQte2LDocument(new BigDecimal(0));
//			setU1LDocument("");
//			setU2LDocument("");
//			setPrixULDocument(new BigDecimal(0)) ;
//			setTauxTvaLDocument(new BigDecimal(0));
//			setCodeTvaLDocument("");
//			setCodeTTvaLDocument("");
//			setMtHtLDocument(new BigDecimal(0));
//			setMtTtcLDocument(new BigDecimal(0));
//			setRemTxLDocument(new BigDecimal(0));
//			setRemHtLDocument(new BigDecimal(0)) ;
//		}
//		setTaArticle(null);	
//	}

	//@Override
	public boolean ligneEstVide() {
		if (taArticle!=null)return false;
		if (!libLDocument.equals(""))return false;		
		return true;
	}
	
	public void calculMontant() {
		if(qteLDocument!=null && prixULDocument!=null) {
			if(taDocument!=null) {//#JPA
				setTxRemHtDocument(taDocument.getTxRemHtDocument());
				if(taDocument.getTtc()==1) {
					setMtTtcLDocument(qteLDocument.multiply(prixULDocument));
					if(remTxLDocument!=null && remTxLDocument.signum()!=0){
						setMtTtcLDocument(getMtTtcLDocument().subtract(getMtTtcLDocument().multiply(remTxLDocument.divide(new BigDecimal(100)))));
					}
					if( tauxTvaLDocument!=null && tauxTvaLDocument.signum()!=0){
						//precision du diviseur = 3, car sinon pour un taux de 19,60% il arrondi a 1.20  au lieu de 1.196
						setMtHtLDocument(mtTtcLDocument.divide(BigDecimal.valueOf(1).add(
								 (tauxTvaLDocument.divide(new BigDecimal(100),MathContext.DECIMAL128).setScale(3,BigDecimal.ROUND_HALF_UP)
							)),MathContext.DECIMAL128).setScale(2,BigDecimal.ROUND_HALF_UP));					
					} else {
						setMtHtLDocument(mtTtcLDocument);
					}
					
				} else {
					setMtHtLDocument(qteLDocument.multiply(prixULDocument));
					if(remTxLDocument!=null && remTxLDocument.signum()!=0){
						setMtHtLDocument(getMtHtLDocument().subtract(getMtHtLDocument().multiply(remTxLDocument.divide(new BigDecimal(100)))));
					}
					if( tauxTvaLDocument!=null && tauxTvaLDocument.signum()!=0){
						setMtTtcLDocument(mtHtLDocument.add((mtHtLDocument.multiply(tauxTvaLDocument.divide(new BigDecimal(100))))));
					} else {
						setMtTtcLDocument(mtHtLDocument);
					}
				
				}
				setMtTtcLApresRemiseGlobaleDocument(getMtTtcLDocument());
				setMtHtLApresRemiseGlobaleDocument(getMtHtLDocument());
			}
		}
	}

	@Transient
	public BigDecimal getTxRemHtDocument() {
		return txRemHtDocument;
	}

	public void setTxRemHtDocument(BigDecimal txRemHtFacture) {
		this.txRemHtDocument = txRemHtFacture;
	}

	public void setLegrain(boolean legrain) {
		this.legrain = legrain;
	}

	public TaLFacture clone() {
		TaLFacture ligne = new TaLFacture();
		try {
			//ligne = (TaLFacture)super.clone();
			ligne.setIdLDocument(0);
			ligne.setVersion(version);
			ligne.setTaTLigne(taTLigne);
			ligne.setTaDocument(taDocument);
			ligne.setTaArticle(taArticle);
			ligne.setNumLigneLDocument(numLigneLDocument);
			ligne.setLibLDocument(libLDocument);
			ligne.setQteLDocument(qteLDocument);
			ligne.setQte2LDocument(qte2LDocument);
			ligne.setU1LDocument(u1LDocument);
			ligne.setU2LDocument(u2LDocument);
			ligne.setPrixULDocument(prixULDocument);
			ligne.setTauxTvaLDocument(tauxTvaLDocument);
			ligne.setTxRemHtDocument(txRemHtDocument);
			ligne.setCompteLDocument(compteLDocument);
			ligne.setCodeTvaLDocument(codeTvaLDocument);
			ligne.setCodeTTvaLDocument(codeTTvaLDocument);
			ligne.setMtHtLDocument(mtHtLDocument);
			ligne.setMtTtcLDocument(mtTtcLDocument);
			ligne.setMtHtLApresRemiseGlobaleDocument(mtHtLApresRemiseGlobaleDocument);
			ligne.setMtTtcLApresRemiseGlobaleDocument(mtTtcLApresRemiseGlobaleDocument);
			ligne.setRemTxLDocument(remTxLDocument);
			ligne.setRemHtLDocument(remHtLDocument);
			ligne.setQuiCreeLDocument(quiCreeLDocument);
			ligne.setQuandCreeLDocument(quandCreeLDocument);
			ligne.setQuiModifLDocument(quiModifLDocument);
			ligne.setQuandModifLDocument(quandModifLDocument);
			ligne.setIpAcces(ipAcces);
			ligne.setVersionObj(versionObj);			
		} catch(Exception cnse) {
			logger.error("",cnse);
		}
		// on renvoie le clone
		return ligne;
	}

	//@Transient
	@Column(name = "MT_HT_APR_REM_GLOBALE", precision = 15)
	@LgrHibernateValidated(champEntite = "", champBd = "MT_APR_REM_GLOBALE",table = "TA_L_FACTURE",clazz = TaLFacture.class)
	public BigDecimal getMtHtLApresRemiseGlobaleDocument() {
		return mtHtLApresRemiseGlobaleDocument;
	}

	public void setMtHtLApresRemiseGlobaleDocument(
			BigDecimal mtHtLApresRemiseGlobaleDocument) {
		this.mtHtLApresRemiseGlobaleDocument = mtHtLApresRemiseGlobaleDocument;
	}
	
	//@Transient
	@Column(name = "MT_TTC_APR_REM_GLOBALE", precision = 15)
	@LgrHibernateValidated(champEntite = "", champBd = "MT_TTC_APR_REM_GLOBALE",table = "TA_L_FACTURE",clazz = TaLFacture.class)
	public BigDecimal getMtTtcLApresRemiseGlobaleDocument() {
		return mtTtcLApresRemiseGlobaleDocument;
	}

	public void setMtTtcLApresRemiseGlobaleDocument(
			BigDecimal mtTtcLApresRemiseGlobaleDocument) {
		this.mtTtcLApresRemiseGlobaleDocument = mtTtcLApresRemiseGlobaleDocument;
	}




//	@Transient
//	public LinkedList<TaLFacture> creeLigneImpression_indirect(int coupure, int rangImpression){
//		LinkedList<TaLFacture> listeNewLigne=new LinkedList<TaLFacture>();
//		try {
//
//			ArrayList<String> listPhrases =new ArrayList<String>();
//			String phrase="";
//			String ligneAParcourir=this.getLibLDocument();
//			String lettre="";
//			int nbMinus=0;
//			int nbMaj=0;
//			int nbDemisMinus=0;
//			int rang=0;
//			int j=0;
//			String ligneParcourue="";
//			String ligneDejaParcourue="";
//			String[]mots=ligneAParcourir.split(" ");
//
//			while(rang<=ligneAParcourir.length()-1){
//				lettre=ligneAParcourir.substring(rang, rang+1);
//				ligneParcourue+=lettre;
//				if (LibChaine.formatDemisMinus(lettre))nbDemisMinus++;
//				else
//				if (LibChaine.formatChiffre(lettre))nbMinus++;
//			else{
//				if(lettre.equals(lettre.toUpperCase()))
//					nbMaj++;
//				else
//					nbMinus++;
//			}
//				boolean trouve=true;
//				String ligneAEcrire="";
//				if((nbMaj*1.3)+nbMinus+(nbDemisMinus*0.7)>=coupure){
//					j=0;
//					//on récupère tous les mots qui sont contenus dans la ligneParcourue
//					//jusqu'à l'avant dernier
//					j=ligneParcourue.lastIndexOf(" ");
//					if(j>0)ligneAEcrire=ligneParcourue.substring(0, j);
//					else ligneAEcrire=ligneParcourue;
//					ligneDejaParcourue+=ligneAEcrire;
//					listPhrases.add(ligneAEcrire);
//					rang=ligneDejaParcourue.length();
//					ligneParcourue="";
//					ligneAEcrire="";
//					nbMaj=0;
//					nbMinus=0;
//					nbDemisMinus=0;
//				}
//
//				rang++;
//			}
//			if(!ligneParcourue.equals(""))listPhrases.add(ligneParcourue);		
//			rang=0;
//			for (String phrases : listPhrases) {
//				if(rang==0){//on traite la ligne initiale
//					TaLFacture lf=new TaLFacture();
//					lf=this.clone();
//					lf.setLibLDocument(phrases);
//					lf.setNumLigneImpression(rangImpression);
//					listeNewLigne.add(lf);
//				}
//				else{
//					//création de la nouvelle ligne
//					TaLFacture newLigne=new TaLFacture();
//					newLigne.initialiseLigne(true);
//					newLigne.setTaTLigne(getTaTLigne());
//					newLigne.setLibLDocument(phrases);
//					newLigne.setTaDocument(taDocument);
//					newLigne.setNumLigneImpression(rangImpression);
//					listeNewLigne.add(newLigne);
//					//taDocument.insertLigne(newLigne, numLigneLDocument+rang);
//				}
//				rang++;
//			}
//		} catch (Exception e) {
//			return null;
//		}
//		return listeNewLigne;
//	}
	
//	@Transient
//	public LinkedList<TaLFacture> creeLigneImpression_indirect(int coupure, int rangImpression){
//		LinkedList<TaLFacture> listeNewLigne=new LinkedList<TaLFacture>();
//		try {
//			String lettre ="";
//			ArrayList<String> listPhrases =new ArrayList<String>();
//			String phrase="";
//			int nbLigne=1;
//			int rang=0;
//			int rangSortie=0;
//			Float nbMaj=new Float(0);
//			int nbMinus=0;
//			int demiMinus=0;
//			String ligneEnCours="";
//			String motSuivant="";
//			int resteMot=0;
//			
//			String[] motsInitials=libLDocument.split(" ");
//			ArrayList<String> mots=new ArrayList<String>();
//			for (int i = 0; i < motsInitials.length; i++) {
//				mots.add(motsInitials[i]);
//			}
//			String ligneParcourue="";
////			rang=0;
////			for (int i = 0; i < motsInitials.length; i++) {
////				while(rang<=mots.get(i).length()-1){
////					lettre=motsInitials[i].substring(rang, rang+1);
////					ligneParcourue+=lettre;
////					if (LibChaine.formatChiffre(lettre))nbMinus++;
////					else{
////						if(lettre.equals(lettre.toUpperCase()))
////							nbMaj++;
////						else
////							nbMinus++;
////					}
////					if((nbMaj*1.5)+nbMinus-demiMinus>=coupure){
////						mots.add(i, ligneParcourue);
////						ligneParcourue="";
////					}
////					rang++;
////				}
////				rang=0;
////				nbMaj=new Float(0);
////				nbMinus=0;
////				demiMinus=0;
////				ligneParcourue="";
////			}
//			for (int i = 0; i < mots.size(); i++) {
//				if(i+1<mots.size())motSuivant=mots.get(i+1);
//				else motSuivant="";
//				nbMinus++;
//				rang=0;
//				rangSortie=i;
//				ligneEnCours="";
//				while(rang<=mots.get(i).length()-1){
//					lettre=mots.get(i).substring(rang, rang+1);
//					ligneParcourue+=lettre;
//					ligneEnCours+=lettre;
//					if (LibChaine.formatChiffre(lettre))nbMinus++;
//					else{
//						if(lettre.equals(lettre.toUpperCase()))
//							nbMaj++;
//						else
//							nbMinus++;
//					}
//					resteMot=mots.get(i).length()-ligneEnCours.length();
//					//on multiplie les majuscules par 1.5, on rajoute les minuscules, on enlève 
//					//les minuscules plus petites 
//					if(((nbMaj*1.5)+nbMinus-demiMinus>=coupure) ||
//							((nbMaj*1.5)+nbMinus-demiMinus+resteMot-coupure<motSuivant.length()) ||
//							(rang>=mots.get(i).length()-1 && i >= mots.size())){
//									//&& i >= mots.size())){
//						nbLigne++;
//						nbMaj=new Float(0); 
//						nbMinus=0;
//						if (rang<mots.get(i).length()-1){
//							phrase=phrase+" "+ligneEnCours;
//							String ligne=mots.get(i);
//							//mots.remove(i);
//							
//							ligne=ligne.replace(ligneEnCours, "");
//							mots.set(i,ligne);
//							rang=0;
//						}
//						else phrase=phrase+" "+mots.get(i);
//						listPhrases.add(phrase);
//						phrase="";
//						ligneParcourue="";
//
//					}else 
//						if (rang==mots.get(i).length()-1)
//							phrase=phrase+" "+mots.get(i);
//					rang++;
//				}				
//			}
//			if (rang==mots.get(rangSortie).length()-1)phrase=phrase+" "+mots.get(rangSortie);
//			if(listPhrases.add(phrase));
//			rang=0;
//			for (String phrases : listPhrases) {
//				if(rang==0){//on traite la ligne initiale
//					TaLFacture lf=new TaLFacture();
//					lf=this.clone();
//					lf.setLibLDocument(phrases);
//					lf.setNumLigneImpression(rangImpression);
//					listeNewLigne.add(lf);
//				}
//				else{
//					//création de la nouvelle ligne
//					TaLFacture newLigne=new TaLFacture();
//					newLigne.initialiseLigne(true);
//					newLigne.setTaTLigne(getTaTLigne());
//					newLigne.setLibLDocument(phrases);
//					newLigne.setTaDocument(taDocument);
//					newLigne.setNumLigneImpression(rangImpression);
//					listeNewLigne.add(newLigne);
//					//taDocument.insertLigne(newLigne, numLigneLDocument+rang);
//				}
//				rang++;
//			}
//		} catch (Exception e) {
//			return null;
//		}
//		return listeNewLigne;
//	}
	
	
	



}
