package fr.legrain.document.dashboard.dto;

// Generated 20 mars 2007 09:51:19 by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import java.util.Date;

import fr.legrain.bdg.lib.osgi.Const;
import fr.legrain.bdg.model.ModelObject;
import fr.legrain.document.dto.IDocumentDTO;
import fr.legrain.lib.data.LgrConstantes;

/**
 * IHMEnteteFacture generated by hbm2java
 */
public class CountDocumentParTypeRegrouptement extends ModelObject implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3841248268187900819L;
		
	/**
	 * 
	 */
	private long count;
	private String valeurRegroupement;
	private String typeRegroupement;
	
	
	
	public CountDocumentParTypeRegrouptement() {

	}
	
	
	
	
	public CountDocumentParTypeRegrouptement(			
			long count,
			String typeRegroupement, 
			String valeurRegroupement) {
		this.count = count;
		this.valeurRegroupement = valeurRegroupement;
		this.typeRegroupement = typeRegroupement;
	}




	public long getCount() {
		return count;
	}
	public void setCount(long count) {
		this.count = count;
	}
	public String getValeurRegroupement() {
		return valeurRegroupement;
	}
	public void setValeurRegroupement(String valeurRegroupement) {
		this.valeurRegroupement = valeurRegroupement;
	}
	public String getTypeRegroupement() {
		return typeRegroupement;
	}
	public void setTypeRegroupement(String typeRegroupement) {
		this.typeRegroupement = typeRegroupement;
	}
	

	
	
	
}
