package fr.legrain.document.dashboard.dto;

// Generated 20 mars 2007 09:51:19 by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import fr.legrain.bdg.lib.osgi.Const;
import fr.legrain.document.dto.DocumentChiffreAffaireDTO;
import fr.legrain.document.dto.IDocumentDTO;
import fr.legrain.document.dto.TaTDocDTO;
import fr.legrain.general.dto.AbstractDTO;
import fr.legrain.lib.data.LgrConstantes;

/**
 * IHMEnteteFacture generated by hbm2java
 */
public class TaArticlesParTiersDTO extends AbstractDTO implements java.io.Serializable, IDocumentDTO {
		
	/**
	 * 
	 */
	private static final long serialVersionUID = -7778752491740942727L;
	
	
	///// décrire chaque champ en constante	
	
	public static final String f_codeDocument="codeDocument";
	public static final String f_dateDocument="dateDocument";
	public static final String f_dateEchDocument="dateEchDocument";
	public static final String f_libelleDocument="libelleDocument";
	public static final String f_codeTiers="codeTiers";
	public static final String f_nomTiers="nomTiers";
	public static final String f_nomEntreprise="nomEntreprise";
	public static final String f_mtHtLDocument="mtHtLDocument";
	public static final String f_mtTtcLDocument="mtTtcLDocument";
	public static final String f_prixPrix="prixPrix";
	public static final String f_prixttcPrix="prixttcPrix";
	public static final String f_netTvaCalc="netTvaCalc";
	public static final String f_libellecArticle="libellecArticle";
	public static final String f_codeArticle="codeArticle";
	public static final String f_codeFamille="codeFamille";
	
	//champs rajouté par yann le 25/07/18
	public static final String f_libcFamille="libcFamille";
	
	public static final String f_codeFamilleTiers="codeFamilleTiers";
	public static final String f_tauxTvaLDocument="tauxTvaLDocument";
	public static final String f_codeTPaiement="codeTPaiement";
	
	//champs rajouté par yann le 13/02/19
	//Voir l'interet de cette classe
	public static final String f_qteLDocument="qteLDocument";
	public static final String f_u1LDocument="u1LDocument";
	
	public static final String f_identifiantEtat="identifiant";
	public static final String f_relancer="relancer";

	
	/////////////// Fin décrire chaque champ en constante pour requete dynamique	
	
	private List<DocumentChiffreAffaireDTO> listeDetail = new ArrayList<DocumentChiffreAffaireDTO>();
	
	
	private String codeDocument=LgrConstantes.C_STR_VIDE;
	private Date dateDocument=new Date();
	private Date dateEchDocument=new Date();
	private String libelleDocument=LgrConstantes.C_STR_VIDE;
	
	private String codeTiers=LgrConstantes.C_STR_VIDE;
	

	private String nomTiers=LgrConstantes.C_STR_VIDE;
	private String nomEntreprise=LgrConstantes.C_STR_VIDE;
	

	
	private BigDecimal mtHtLDocument=new BigDecimal(0);
	private BigDecimal mtTtcLDocument=new BigDecimal(0);
	private BigDecimal prixPrix=new BigDecimal(0);
	private BigDecimal prixttcPrix=new BigDecimal(0);
	private BigDecimal netTvaCalc=new BigDecimal(0);
	private String libellecArticle=LgrConstantes.C_STR_VIDE;
	private String codeArticle=LgrConstantes.C_STR_VIDE;
	
	private String libcFamille = LgrConstantes.C_STR_VIDE;
	//pour regroupement dans requete
	private String codeFamille=LgrConstantes.C_STR_VIDE;
	private BigDecimal tauxTvaLDocument=new BigDecimal(0);
	private String codeTPaiement=LgrConstantes.C_STR_VIDE;
	//rajout yann
	private BigDecimal qteLDocument = new BigDecimal(0);
	private String u1LDocument = LgrConstantes.C_STR_VIDE;
	
	private String identifiant = LgrConstantes.C_STR_VIDE;
	private Boolean relancer = false;
	

	public TaArticlesParTiersDTO() {
		initMapDTO();
	}

	
	public TaArticlesParTiersDTO(
			String type,
			BigDecimal valeurRegroupement,
			String codeTiers,
			String nomTiers,
			String nomEntreprise,
			String codeDocument,
			Date dateDocument, 
			String codeArticle,
			String libellecArticle,
			BigDecimal mtHtLDocument,
			BigDecimal mtTtcLDocument) {
		if(type.equals(Const.PAR_TAUX_TVA))this.tauxTvaLDocument = valeurRegroupement;
		this.codeDocument = codeDocument;
		this.dateDocument = dateDocument;
		this.codeArticle = codeArticle;
		this.libellecArticle = libellecArticle;
		this.nomTiers = nomTiers;
		this.codeTiers = codeTiers;
		this.nomEntreprise = nomEntreprise;
		this.mtHtLDocument = mtHtLDocument;
		this.mtTtcLDocument = mtTtcLDocument;
	}
	
	public TaArticlesParTiersDTO(
			String type,
			String valeurRegroupement,
			String codeTiers,
			String nomTiers,
			String nomEntreprise,
			String codeDocument,
			Date dateDocument, 
			String codeArticle,
			String libellecArticle,
			BigDecimal mtHtLDocument,
			BigDecimal mtTtcLDocument) {
		if(type.equals(Const.PAR_FAMILLE_ARTICLE))this.codeFamille = valeurRegroupement;
		if(type.equals(Const.PAR_TYPE_PAIEMENT))this.codeTPaiement = valeurRegroupement;
		this.codeDocument = codeDocument;
		this.dateDocument = dateDocument;
		this.codeArticle = codeArticle;
		this.libellecArticle = libellecArticle;
		this.nomTiers = nomTiers;
		this.codeTiers = codeTiers;
		this.nomEntreprise = nomEntreprise;
		this.mtHtLDocument = mtHtLDocument;
		this.mtTtcLDocument = mtTtcLDocument;
	}
	
	public TaArticlesParTiersDTO(String codeTiers,
			String nomTiers,
			String nomEntreprise,
			String codeDocument,
			Date dateDocument, 
			String codeArticle,
			String libellecArticle,
			BigDecimal mtHtLDocument,
			BigDecimal mtTtcLDocument) {
		
		this.codeDocument = codeDocument;
		this.dateDocument = dateDocument;
		this.codeArticle = codeArticle;
		this.libellecArticle = libellecArticle;
		this.nomTiers = nomTiers;
		this.codeTiers = codeTiers;
		this.nomEntreprise = nomEntreprise;
		this.mtHtLDocument = mtHtLDocument;
		this.mtTtcLDocument = mtTtcLDocument;
	}
	
	public TaArticlesParTiersDTO(String codeTiers,
			String nomTiers,
			String nomEntreprise,
			String codeDocument,
			Date dateDocument, 
			String codeArticle,
			String libellecArticle,
			BigDecimal mtHtLDocument,
			BigDecimal mtTtcLDocument,
			Date dateEchDocument) {
		
		this.codeDocument = codeDocument;
		this.dateDocument = dateDocument;
		this.codeArticle = codeArticle;
		this.libellecArticle = libellecArticle;
		this.nomTiers = nomTiers;
		this.codeTiers = codeTiers;
		this.nomEntreprise = nomEntreprise;
		this.mtHtLDocument = mtHtLDocument;
		this.mtTtcLDocument = mtTtcLDocument;
		this.dateEchDocument = dateEchDocument;
		
		
	}
	
	public String getLibelleDocument() {
		return libelleDocument;
	}

	public void setLibelleDocument(String libelleDocument) {
		this.libelleDocument = libelleDocument;
	}
	
	public String getCodeDocument() {
		return codeDocument;
	}

	public void setCodeDocument(String codeDocument) {
		this.codeDocument = codeDocument;
	}

	public Date getDateDocument() {
		return dateDocument;
	}

	public void setDateDocument(Date dateDocument) {
		this.dateDocument = dateDocument;
	}

	public String getLibellecDocument() {
		return libelleDocument;
	}

	public void setLibellecDocument(String libelleDocument) {
		this.libelleDocument = libelleDocument;
	}

	public String getNomTiers() {
		return nomTiers;
	}

	public void setNomTiers(String nomTiers) {
		this.nomTiers = nomTiers;
	}

	public String getNomEntreprise() {
		return nomEntreprise;
	}

	public void setNomEntreprise(String nomEntreprise) {
		this.nomEntreprise = nomEntreprise;
	}

	public BigDecimal getNetTvaCalc() {
		return netTvaCalc;
	}

	public void setNetTvaCalc(BigDecimal netTvaCalc) {
		this.netTvaCalc = netTvaCalc;
	}

	public String getLibellecArticle() {
		return libellecArticle;
	}

	public void setLibellecArticle(String libellecArticle) {
		this.libellecArticle = libellecArticle;
	}
	
	public String getCodeTiers() {
		return codeTiers;
	}

	public void setCodeTiers(String codeTiers) {
		this.codeTiers = codeTiers;
	}
	
	@Override
	public Integer getId() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setId(Integer id) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public Integer getIdTiers() {
		// TODO Auto-generated method stub
		return null;
	}

	

	@Override
	public String getCodeTTvaDoc() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public String getCodeTPaiement() {
		// TODO Auto-generated method stub
		return codeTPaiement;
	}

	

	@Override
	public void setCodeTTvaDoc(String codeTTvaDoc) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void setCodeTPaiement(String codeTPaiement) {
		// TODO Auto-generated method stub
		this.codeTPaiement=codeTPaiement;
	}

	@Override
	public Boolean getTtc() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setTtc(Boolean ttc) {
		// TODO Auto-generated method stub
		
	}

	public BigDecimal getPrixPrix() {
		return prixPrix;
	}

	public void setPrixPrix(BigDecimal prixPrix) {
		this.prixPrix = prixPrix;
	}

	public BigDecimal getPrixttcPrix() {
		return prixttcPrix;
	}

	public void setPrixttcPrix(BigDecimal prixttcPrix) {
		this.prixttcPrix = prixttcPrix;
	}

	public BigDecimal getMtHtLDocument() {
		return mtHtLDocument;
	}

	public void setMtHtLDocument(BigDecimal mtHtLDocument) {
		this.mtHtLDocument = mtHtLDocument;
	}

	public BigDecimal getMtTtcLDocument() {
		return mtTtcLDocument;
	}

	public void setMtTtcLDocument(BigDecimal mtTtcLDocument) {
		this.mtTtcLDocument = mtTtcLDocument;
	}

	public Date getDateEchDocument() {
		return dateEchDocument;
	}

	public void setDateEchDocument(Date dateEchDocument) {
		this.dateEchDocument = dateEchDocument;
	}

	@Override
	public String getCodeEtat() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setCodeEtat(String taEtat) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public String getLiblEtat() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setLiblEtat(String taEtat) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public Date getDateExport() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public Date getDateVerrouillage() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public boolean getEstMisADisposition() {
		// TODO Auto-generated method stub
		return false;
	}



	@Override
	public boolean setEstMisADisposition(boolean mad) {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public Date getDateLivDocument() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setDateLivDocument(Date dateLivDocument) {
		// TODO Auto-generated method stub
		
	}

	public String getCodeArticle() {
		return codeArticle;
	}

	public void setCodeArticle(String codeArticle) {
		this.codeArticle = codeArticle;
	}

	public String getCodeFamille() {
		return codeFamille;
	}

	public void setCodeFamille(String codeFamille) {
		this.codeFamille = codeFamille;
	}

	public BigDecimal getTauxTvaLDocument() {
		return tauxTvaLDocument;
	}

	public void setTauxTvaLDocument(BigDecimal tauxTvaLDocument) {
		this.tauxTvaLDocument = tauxTvaLDocument;
	}


	@Override
	public String getPrenomTiers() {
		// TODO Auto-generated method stub
		return null;
	}


	@Override
	public BigDecimal getNetHtCalc() {
		// TODO Auto-generated method stub
		return null;
	}


	@Override
	public BigDecimal getNetTtcCalc() {
		// TODO Auto-generated method stub
		return null;
	}


	@Override
	protected void initMapDTO() {
//		public static final String f_codeDocument="codeDocument";
//		public static final String f_dateDocument="dateDocument";
//		public static final String f_dateEchDocument="dateEchDocument";
//		public static final String f_libelleDocument="libelleDocument";
//		public static final String f_codeTiers="codeTiers";
//		public static final String f_nomTiers="nomTiers";
//		public static final String f_nomEntreprise="nomEntreprise";
//		public static final String f_mtHtLDocument="mtHtLDocument";
//		public static final String f_mtTtcLDocument="mtTtcLDocument";
//		public static final String f_prixPrix="prixPrix";
//		public static final String f_prixttcPrix="prixttcPrix";
//		public static final String f_netTvaCalc="netTvaCalc";
//		public static final String f_libellecArticle="libellecArticle";
//		public static final String f_codeArticle="codeArticle";
//		public static final String f_codeFamille="codeFamille";
//		public static final String f_tauxTvaLDocument="tauxTvaLDocument";
//		public static final String f_codeTPaiement="codeTPaiement";

		mapAliasDTO.put("tiers.codeTiers", f_codeTiers);	
		mapAliasDTO.put("infos.nomTiers", f_nomTiers);
		mapAliasDTO.put("ent.nomEntreprise", f_nomEntreprise);
		mapAliasDTO.put("doc.codeDocument", f_codeDocument);
		mapAliasDTO.put("doc.dateDocument", f_dateDocument);
		mapAliasDTO.put("art.codeArticle", f_codeArticle);
		mapAliasDTO.put("art.libellecArticle", f_libellecArticle);
		mapAliasDTO.put("ldoc.mtHtLDocument", f_mtHtLDocument);
		mapAliasDTO.put("ldoc.mtTtcLDocument", f_mtTtcLDocument);
		mapAliasDTO.put("fam.codeFamille", f_codeFamille);
		mapAliasDTO.put("fam.libcFamille", f_libcFamille);
		mapAliasDTO.put("famTiers.codeFamille", f_codeFamilleTiers);
		mapAliasDTO.put("ldoc.qteLDocument",f_qteLDocument);
		mapAliasDTO.put("ldoc.u1LDocument",f_u1LDocument);
		
		mapAliasDTO.put("et.identifiant",f_identifiantEtat);
		mapAliasDTO.put("relancer",f_relancer);
	}


	public String getLibcFamille() {
		return libcFamille;
	}


	public void setLibcFamille(String libcFamille) {
		this.libcFamille = libcFamille;
	}


	public BigDecimal getQteLDocument() {
		return qteLDocument;
	}


	public void setQteLDocument(BigDecimal qteLDocument) {
		this.qteLDocument = qteLDocument;
	}


	public String getU1LDocument() {
		return u1LDocument;
	}


	public void setU1LDocument(String u1lDocument) {
		u1LDocument = u1lDocument;
	}


	@Override
	public String getTypeDocument() {
		// TODO Auto-generated method stub
		return null;
	}


	public List<DocumentChiffreAffaireDTO> getListeDetail() {
		return listeDetail;
	}


	public void setListeDetail(List<DocumentChiffreAffaireDTO> listeDetail) {
		this.listeDetail = listeDetail;
	}


	public String getIdentifiant() {
		return identifiant;
	}

	public void setIdentifiant(String identifiant) {
		this.identifiant = identifiant;
	}

	public Boolean getRelancer() {
		return relancer;
	}

	public void setRelancer(Boolean relancer) {
		this.relancer = relancer;
	}
	
	
	
}
