//package fr.legrain.article.dto;
//
//import java.util.Date;
//import java.util.List;
//
//import fr.legrain.article.model.TaArticle;
//import fr.legrain.article.model.TaTypeMouvement;
//import fr.legrain.bdg.model.ModelObject;
//
//
//
//// Generated Mar 1, 2007 11:26:10 AM by Hibernate Tools 3.2.0.b9
//
///**
// * TaBaremeDTO generated by hbm2java
// */
//public class TaMatierePremiereDTO extends ModelObject implements java.io.Serializable {
//	
//	/**
//	 * 
//	 */
//	private static final long serialVersionUID = 656467988688867937L;
//																	
//									
//					
//	// ta fabrication
//	private Integer idFabrication;
//	//ta mouvement
//	private TaMouvementDTO mouvement;
//	//matiere premiere
//	private Integer id;
//	private Integer versionObj;
//	
//	public TaMatierePremiereDTO() {
//		mouvement = new TaMouvementDTO();
//	}
//	
//	public TaMatierePremiereDTO(Integer id) {
//		this.id = id;
//	}
//	
//	public Integer getId() {
//		return this.id;
//	}
//	
//	public void setId(Integer id) {
//		firePropertyChange("id", this.id, this.id = id);
//	}
//	
//	public Integer getVersionObj() {
//		return this.versionObj;
//	}
//
//	public void setVersionObj(Integer versionObj) {
//		this.versionObj = versionObj;
//	}
//
//	public Integer getIdFabrication() {
//		return idFabrication;
//	}
//
//	public void setIdFabrication(Integer idFabrication) {
//		this.idFabrication = idFabrication;
//	}
//
//	
//
//
//
//	public TaMouvementDTO getMouvement() {
//		return mouvement;
//	}
//
//	public void setMouvement(TaMouvementDTO mouvement) {
//		this.mouvement = mouvement;
//	}
//
//}
