package fr.legrain.article.dto;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import java.util.Map;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import fr.legrain.article.model.TaFabrication;
import fr.legrain.bdg.model.ModelObject;
import fr.legrain.lib.data.LgrConstantes;
import fr.legrain.validator.LgrHibernateValidated;



// Generated Mar 1, 2007 11:26:10 AM by Hibernate Tools 3.2.0.b9

/**
 * TaBaremeDTO generated by hbm2java
 */
public class TaModeleFabricationDTO extends ModelObject implements java.io.Serializable {
	
	private static final long serialVersionUID = -4425732529899621121L;
	private Integer id=0;
	private String codeDocument;
	private Date dateDebT;
	private Date dateFinT;
	private Date dateDebR;
	private Date dateFinR;
	private String description;
	
	//private String codeDocument=LgrConstantes.C_STR_VIDE;
	private Date dateDocument=new Date();
	private Date dateEchDocument=new Date();
	private Date dateLivDocument=new Date();
	private Integer numLigneLDocument;
	private String libelleDocument=LgrConstantes.C_STR_VIDE;
	private Integer idAdresse=0;
	private Integer idAdresseLiv=0;
	private Integer idTiers=0;
	private String codeTiers=LgrConstantes.C_STR_VIDE;
	private String nomTiers=LgrConstantes.C_STR_VIDE;
	private String prenomTiers=LgrConstantes.C_STR_VIDE;
	private String surnomTiers=LgrConstantes.C_STR_VIDE;
	private String codeCompta=LgrConstantes.C_STR_VIDE;
	private String compte=LgrConstantes.C_STR_VIDE;
	private Integer idTPaiement=0;
	private String codeTPaiement=LgrConstantes.C_STR_VIDE;
	private Integer idCPaiement=0;
	//private BigDecimal REGLE_BONLIV=new BigDecimal(0);
	private BigDecimal remHtDocument=new BigDecimal(0);
	private BigDecimal txRemHtDocument=new BigDecimal(0);
	private BigDecimal remTtcDocument=new BigDecimal(0);
	private BigDecimal txRemTtcDocument=new BigDecimal(0);
	private Integer nbEDocument=0;
	private BigDecimal mtTtcCalc=new BigDecimal(0);
	private BigDecimal mtHtCalc=new BigDecimal(0);
	private BigDecimal mtTvaCalc=new BigDecimal(0);
	private BigDecimal netTtcCalc=new BigDecimal(0);
	private BigDecimal netHtCalc=new BigDecimal(0);
	private BigDecimal netTvaCalc=new BigDecimal(0);
	private String ipAcces=LgrConstantes.C_STR_VIDE;
	private Boolean ttc=false;
	private Boolean export=false;
	private String commentaire = "";
	private Boolean accepte=true;
	private Integer idTFabrication=0;
	private String codeTFabrication=LgrConstantes.C_STR_VIDE;
	private String liblTFabrication=LgrConstantes.C_STR_VIDE;
	
	
	
	
	//topEffacable
	
	private Integer versionObj;
	
	public TaModeleFabricationDTO() {
	}
	
	
	public static TaModeleFabricationDTO copy(TaModeleFabricationDTO taFabrication){
		TaModeleFabricationDTO taFabricationLoc = new TaModeleFabricationDTO();
		
		taFabricationLoc.setCodeDocument(taFabrication.codeDocument);
		taFabricationLoc.setCommentaire(taFabrication.commentaire);
		taFabricationLoc.setDescription(taFabrication.description);
		taFabricationLoc.setDateFinR(taFabrication.dateFinR);
		taFabricationLoc.setDateDebR(taFabrication.dateDebR);
		taFabricationLoc.setDateFinT(taFabrication.dateFinT);
		taFabricationLoc.setDateDebT(taFabrication.dateDebT);
		taFabricationLoc.setId(taFabrication.id);
		
		return taFabricationLoc;
	}
	
	public void setTaFabricationDTO(TaModeleFabricationDTO dto){
		this.id = dto.id;
		this.codeDocument = dto.codeDocument;
		this.commentaire = dto.commentaire;
		this.dateDebR = dto.dateDebR;
		this.dateDebT = dto.dateDebT;
		this.dateFinR = dto.dateFinR;
		this.dateFinT = dto.dateFinT;
		this.description = dto.description;
	}
	
	
	public TaModeleFabricationDTO(Integer id, String commentaire, Date dateDebR, Date dateDebT, Date dateFinR, Date dateFinT, String description)
	{
		this.commentaire = commentaire;
		this.dateDebR = dateDebR;
		this.dateDebT = dateDebT;
		this.dateFinR = dateFinR;
		this.dateFinT = dateFinT;
		this.description = description;
		this.id = id;
		
		
	}
	public Integer getId() {
		return this.id;
	}
	
	public void  setId(Integer idFabrication) {
		firePropertyChange("id", this.id, this.id = idFabrication);
	}
	
	
	
	public Integer getVersionObj() {
		return this.versionObj;
	}

	public void setVersionObj(Integer versionObj) {
		this.versionObj = versionObj;
	}
//
//	this.commentaire = commentaire;
//	this.dateDebR = dateDebR;
//	this.dateDebT = dateDebT;
//	this.dateFinR = dateFinR;
//	this.dateFinT = dateFinT;
//	this.description = description;
//	this.id = id;

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		TaModeleFabricationDTO other = (TaModeleFabricationDTO) obj;
		if (commentaire == null) {
			if (other.commentaire != null){
				return false;
			}
		} 
		else if (!commentaire.equals(other.commentaire)){
			return false;
		}
		if (dateDebR == null) {
			if (other.dateDebR != null){
				return false;
			}
		} 
		else if (!dateDebR.equals(other.dateDebR)){
			return false;
		}
		if (dateDebT == null) {
			if (other.dateDebT != null){
				return false;
			}
		} 
		else if (!dateDebT.equals(other.dateDebT)){
			return false;
		}
		
		
		if (dateFinR == null) {
			if (other.dateFinR != null){
				return false;
			}
		} 
		else if (!dateFinR.equals(other.dateFinR)){
			return false;
		}
		if (dateFinT == null) {
			if (other.dateFinT != null){
				return false;
			}
		} 
		else if (!dateFinT.equals(other.dateFinT)){
			return false;
		}
		if (description == null) {
			if (other.description != null){
				return false;
			}
		} 
		else if (!description.equals(other.description)){
			return false;
		}		
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		
		return true;
	}

	@LgrHibernateValidated(champBd = "date_deb_t",table = "ta_fabrication", champEntite="dateDebT", clazz = TaFabricationDTO.class)
	public Date getDateDebT() {
		return dateDebT;
	}


	public void setDateDebT(Date dateDebT) {
		this.dateDebT = dateDebT;
	}

	@LgrHibernateValidated(champBd = "date_fin_t",table = "ta_fabrication", champEntite="dateFinT", clazz = TaFabricationDTO.class)
	public Date getDateFinT() {
		return dateFinT;
	}


	public void setDateFinT(Date dateFinT) {
		this.dateFinT = dateFinT;
	}

	@LgrHibernateValidated(champBd = "date_deb_r",table = "ta_fabrication", champEntite="dateDebR", clazz = TaFabricationDTO.class)
	public Date getDateDebR() {
		return dateDebR;
	}


	public void setDateDebR(Date dateDebR) {
		this.dateDebR = dateDebR;
	}

	@LgrHibernateValidated(champBd = "date_fin_r",table = "ta_fabrication", champEntite="dateFinR", clazz = TaFabricationDTO.class)
	public Date getDateFinR() {
		return dateFinR;
	}


	public void setDateFinR(Date dateFinR) {
		this.dateFinR = dateFinR;
	}


	public String getDescription() {
		return description;
	}


	public void setDescription(String description) {
		this.description = description;
	}

	@LgrHibernateValidated(champBd = "commentaire",table = "ta_fabrication", champEntite="commentaire", clazz = TaFabricationDTO.class)
	public String getCommentaire() {
		return commentaire;
	}


	public void setCommentaire(String commentaire) {
		this.commentaire = commentaire;
	}

	@NotNull
	@Size(min=1, max=20)
	@LgrHibernateValidated(champBd = "code_document",table = "ta_fabrication", champEntite="codeDocument", clazz = TaFabricationDTO.class)
	public String getCodeDocument() {
		return codeDocument;
	}


	public void setCodeDocument(String code) {
		this.codeDocument = code;
	}


	public Integer getNumLigneLDocument() {
		return numLigneLDocument;
	}


	public void setNumLigneLDocument(Integer numLigneLDocument) {
		this.numLigneLDocument = numLigneLDocument;
	}

	@LgrHibernateValidated(champBd = "libelle_document",table = "ta_fabrication", champEntite="", clazz = TaFabricationDTO.class)
	public String getLibelleDocument() {
		return libelleDocument;
	}


	public void setLibelleDocument(String libelleDocument) {
		this.libelleDocument = libelleDocument;
	}


	public Integer getIdTFabrication() {
		return idTFabrication;
	}


	public void setIdTFabrication(Integer idTFabrication) {
		this.idTFabrication = idTFabrication;
	}


	public String getCodeTFabrication() {
		return codeTFabrication;
	}


	public void setCodeTFabrication(String codeTFabrication) {
		this.codeTFabrication = codeTFabrication;
	}


	public String getLiblTFabrication() {
		return liblTFabrication;
	}


	public void setLiblTFabrication(String liblTFabrication) {
		this.liblTFabrication = liblTFabrication;
	}


	



	





}
