package fr.legrain.article.dto;

// Generated Mar 1, 2007 11:26:10 AM by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import fr.legrain.article.model.TaArticle;
import fr.legrain.article.model.TaPrix;
import fr.legrain.article.model.TaUnite;
import fr.legrain.bdg.model.ModelObject;
import fr.legrain.validator.LgrHibernateValidated;


/**
 * SWTPrix generated by hbm2java
 */
public class TaPrixDTO extends ModelObject implements java.io.Serializable {

	private static final long serialVersionUID = -5449939652076235529L;
	
	private Integer id;
	private BigDecimal prixPrix;
	private BigDecimal prixttcPrix;
	private Integer idArticle;
	private String codeArticle;
	private String libellecArticle;
	private BigDecimal tauxTva;
//	private Integer idUnite;
//	private String codeUnite;
//	private String liblUnite;
	private Boolean idRefPrix;
	
	private BigDecimal prixPrixCalc;
	private BigDecimal prixttcPrixCalc;
	private BigDecimal coef;
	private Integer idTTarif;
	private String codeTTarif;
	private String codeTiers;
	private boolean diff=false;
	
	private BigDecimal mtTva;
	
	private Integer versionObj;
	private Boolean accepte;

	public Integer getVersionObj() {
		return versionObj;
	}

	public void setVersionObj(Integer versionObj) {
		this.versionObj = versionObj;
	}

	public TaPrixDTO() {
	}

	public TaPrixDTO(Integer ID_PRIX, BigDecimal PRIX_PRIX,
			BigDecimal PRIXTTC_PRIX, Integer ID_ARTICLE, String CODE_ARTICLE,
			String LIBELLEC_ARTICLE, BigDecimal TAUX_TVA, Integer ID_UNITE,
			String CODE_UNITE, String LIBL_UNITE, Boolean ID_REF_PRIX) {
		this.id = ID_PRIX;
		this.prixPrix = PRIX_PRIX;
		this.prixttcPrix = PRIXTTC_PRIX;
		this.idArticle = ID_ARTICLE;
		this.codeArticle = CODE_ARTICLE;
		this.libellecArticle = LIBELLEC_ARTICLE;
		this.tauxTva = TAUX_TVA;
//		this.idUnite = ID_UNITE;
//		this.codeUnite = CODE_UNITE;
//		this.liblUnite = LIBL_UNITE;
		this.idRefPrix = ID_REF_PRIX;
	}
	
	public void setSWTPrix(TaPrixDTO swtPrix) {
		this.id = swtPrix.id;
		this.prixPrix = swtPrix.prixPrix;
		this.prixttcPrix = swtPrix.prixttcPrix;
		this.idArticle = swtPrix.idArticle;
		this.codeArticle = swtPrix.codeArticle;
		this.libellecArticle = swtPrix.libellecArticle;
		this.tauxTva = swtPrix.tauxTva;
//		this.idUnite = swtPrix.idUnite;
//		this.codeUnite = swtPrix.codeUnite;
//		this.liblUnite = swtPrix.liblUnite;
		this.idRefPrix = swtPrix.idRefPrix;

	}
	
	public static TaPrixDTO copy(TaPrixDTO swtPrix){
		TaPrixDTO swtPrixLoc = new TaPrixDTO();
		swtPrixLoc.setId(swtPrix.id);
		swtPrixLoc.setPrixPrix(swtPrix.prixPrix);
		swtPrixLoc.setPrixttcPrix(swtPrix.prixttcPrix);
		swtPrixLoc.setIdArticle(swtPrix.idArticle);
		swtPrixLoc.setCodeArticle(swtPrix.codeArticle);
		swtPrixLoc.setLibellecArticle(swtPrix.libellecArticle);
		swtPrixLoc.setTauxTva(swtPrix.tauxTva);
//		swtPrixLoc.setIdUnite(swtPrix.idUnite);
//		swtPrixLoc.setCodeUnite(swtPrix.codeUnite);
//		swtPrixLoc.setLiblUnite(swtPrix.liblUnite);
		swtPrixLoc.setIdRefPrix(swtPrix.idRefPrix);
		return swtPrixLoc;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer ID_PRIX) {
		firePropertyChange("id", this.id, this.id = ID_PRIX);
	}

	@LgrHibernateValidated(champBd = "prix_prix",table = "ta_prix", champEntite="prixPrix" ,clazz = TaPrixDTO.class)
	public BigDecimal getPrixPrix() {
		return this.prixPrix;
	}

	public void setPrixPrix(BigDecimal PRIX_PRIX) {
		firePropertyChange("prixPrix", this.prixPrix, this.prixPrix = PRIX_PRIX);
	}

	@LgrHibernateValidated(champBd = "prixttc_prix",table = "ta_prix", champEntite="prixttcPrix" ,clazz = TaPrixDTO.class)
	public BigDecimal getPrixttcPrix() {
		return this.prixttcPrix;
	}

	public void setPrixttcPrix(BigDecimal PRIXTTC_PRIX) {
		firePropertyChange("prixttcPrix", this.prixttcPrix, this.prixttcPrix = PRIXTTC_PRIX);
	}

	public Integer getIdArticle() {
		return this.idArticle;
	}

	public void setIdArticle(Integer ID_ARTICLE) {
		firePropertyChange("idArticle", this.idArticle, this.idArticle = ID_ARTICLE);
	}

	@NotNull
	@Size(min=1, max=20)
	@LgrHibernateValidated(champBd = "code_article",table = "ta_article", champEntite="codeArticle" ,clazz = TaPrixDTO.class)
	public String getCodeArticle() {
		return this.codeArticle;
	}

	public void setCodeArticle(String CODE_ARTICLE) {
		firePropertyChange("codeArticle", this.codeArticle, this.codeArticle = CODE_ARTICLE);
	}

	public String getLibellecArticle() {
		return this.libellecArticle;
	}

	public void setLibellecArticle(String LIBELLEC_ARTICLE) {
		firePropertyChange("libellecArticle", this.libellecArticle, this.libellecArticle = LIBELLEC_ARTICLE);
	}

	public BigDecimal getTauxTva() {
		return this.tauxTva;
	}

	public void setTauxTva(BigDecimal TAUX_TVA) {
		firePropertyChange("tauxTva", this.tauxTva, this.tauxTva = TAUX_TVA);
	}

//	public Integer getIdUnite() {
//		return this.idUnite;
//	}
//
//	public void setIdUnite(Integer ID_UNITE) {
//		firePropertyChange("idUnite", this.idUnite, this.idUnite = ID_UNITE);
//	}
//
//	@Size(min=0, max=20)
//	@LgrHibernateValidated(champBd = "code_unite",table = "ta_unite", champEntite="codeUnite" ,clazz = TaPrixDTO.class)
//	public String getCodeUnite() {
//		return this.codeUnite;
//	}
//
//	public void setCodeUnite(String CODE_UNITE) {
//		firePropertyChange("codeUnite", this.codeUnite, this.codeUnite = CODE_UNITE);
//	}
//
//	public String getLiblUnite() {
//		return this.liblUnite;
//	}
//
//	public void setLiblUnite(String LIBL_UNITE) {
//		firePropertyChange("liblUnite", this.liblUnite, this.liblUnite = LIBL_UNITE);
//	}

	public Boolean getIdRefPrix() {
		return this.idRefPrix;
	}

	public void setIdRefPrix(Boolean ID_REF_PRIX) {
		firePropertyChange("idRefPrix", this.idRefPrix, this.idRefPrix = ID_REF_PRIX);
	}

	public BigDecimal getPrixPrixCalc() {
		return prixPrixCalc;
	}

	public void setPrixPrixCalc(BigDecimal prixPrixCalc) {
		this.prixPrixCalc = prixPrixCalc;
	}

	public BigDecimal getPrixttcPrixCalc() {
		return prixttcPrixCalc;
	}

	public void setPrixttcPrixCalc(BigDecimal prixttcPrixCalc) {
		this.prixttcPrixCalc = prixttcPrixCalc;
	}

	public BigDecimal getCoef() {
		return coef;
	}

	public void setCoef(BigDecimal coef) {
		this.coef = coef;
	}

	public Boolean getAccepte() {
		return accepte;
	}

	public void setAccepte(Boolean accepte) {
		this.accepte = accepte;
	}

	public Integer getIdTTarif() {
		return idTTarif;
	}

	public void setIdTTarif(Integer idTTarif) {
		this.idTTarif = idTTarif;
	}

	public String getCodeTTarif() {
		return codeTTarif;
	}

	public void setCodeTTarif(String codeTTarif) {
		this.codeTTarif = codeTTarif;
	}

	public BigDecimal getMtTva() {
		return mtTva;
	}

	public void setMtTva(BigDecimal mtTva) {
		this.mtTva = mtTva;
	}

	public String getCodeTiers() {
		return codeTiers;
	}

	public void setCodeTiers(String codeTiers) {
		this.codeTiers = codeTiers;
	}

	public boolean isDiff() {
		return diff;
	}

	public void setDiff(boolean diff) {
		this.diff = diff;
	}



}
