package fr.legrain.article.dto;

import java.math.BigDecimal;
import java.util.Date;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import fr.legrain.article.model.TaArticle;
import fr.legrain.article.model.TaUnite;
import fr.legrain.article.titretransport.model.TaTitreTransport;
import fr.legrain.bdg.model.ModelObject;
import fr.legrain.validator.LgrHibernateValidated;


// Generated Mar 1, 2007 11:26:10 AM by Hibernate Tools 3.2.0.b9

/**
 * SWTFamille generated by hbm2java
 */
public class TaRTitreTransportDTO extends ModelObject implements java.io.Serializable {

/**
	 * 
	 */
	private static final long serialVersionUID = 510798466783668850L;
	
	private Integer id;
	private String codeArticle;
	private String codeUnite;
	private String codeTitreTransport;
	private BigDecimal qteTitreTransport;

	
	private Integer versionObj;

	public Integer getVersionObj() {
		return versionObj;
	}

	public void setVersionObj(Integer versionObj) {
		this.versionObj = versionObj;
	}

	public TaRTitreTransportDTO() {
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		firePropertyChange("id", this.id, this.id = id);
	}

	@NotNull
	@Size(min=1, max=20)
	@LgrHibernateValidated(champBd = "code_article",table = "ta_article", champEntite="codeArticle" ,clazz = TaRTitreTransportDTO.class)
	public String getCodeArticle() {
		return codeArticle;
	}

	public void setCodeArticle(String codeArticle) {
		firePropertyChange("codeArticle", this.codeArticle, this.codeArticle = codeArticle);
	}

	@Size(min=0, max=20)
	@LgrHibernateValidated(champBd = "code_unite",table = "ta_unite", champEntite="codeUnite" ,clazz = TaRTitreTransportDTO.class)
	public String getCodeUnite() {
		return codeUnite;
	}

	public void setCodeUnite(String codeUnite) {
		firePropertyChange("codeUnite", this.codeUnite, this.codeUnite = codeUnite);
	}

	@NotNull
	@Size(min=1, max=20)
	@LgrHibernateValidated(champBd = "code_titre_transport",table = "ta_titre_transport", champEntite="codeTitreTransport" ,clazz = TaRTitreTransportDTO.class)
	public String getCodeTitreTransport() {
		return codeTitreTransport;
	}

	public void setCodeTitreTransport(String codeTitreTransport) {
		firePropertyChange("codeTitreTransport", this.codeTitreTransport, this.codeTitreTransport = codeTitreTransport);
	}

	@LgrHibernateValidated(champBd = "qte_min_titre_transport",table = "ta_titre_transport", champEntite="qteTitreTransport" ,clazz = TaRTitreTransportDTO.class)
	public BigDecimal getQteTitreTransport() {
		return qteTitreTransport;
	}

	public void setQteTitreTransport(BigDecimal qteTitreTransport) {
		firePropertyChange("qteTitreTransport", this.qteTitreTransport, this.qteTitreTransport = qteTitreTransport);
	}


	public static TaRTitreTransportDTO copy(TaRTitreTransportDTO swtRapportUnite){
		TaRTitreTransportDTO swtRapportUniteLoc = new TaRTitreTransportDTO();
		swtRapportUniteLoc.codeArticle = swtRapportUnite.codeArticle;
		swtRapportUniteLoc.codeUnite = swtRapportUnite.codeUnite;
		
		return swtRapportUniteLoc;
		
	}

	public TaRTitreTransportDTO(Integer id, String codeArticle,
			String codeUnite, String codeTitreTransport,
			BigDecimal qteTitreTransport, Integer versionObj) {
		super();
		this.id = id;
		this.codeArticle = codeArticle;
		this.codeUnite = codeUnite;
		this.codeTitreTransport = codeTitreTransport;
		this.qteTitreTransport = qteTitreTransport;
		this.versionObj = versionObj;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((codeArticle == null) ? 0 : codeArticle.hashCode());
		result = prime
				* result
				+ ((codeTitreTransport == null) ? 0 : codeTitreTransport
						.hashCode());
		result = prime * result
				+ ((codeUnite == null) ? 0 : codeUnite.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime
				* result
				+ ((qteTitreTransport == null) ? 0 : qteTitreTransport
						.hashCode());
		result = prime * result
				+ ((versionObj == null) ? 0 : versionObj.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		TaRTitreTransportDTO other = (TaRTitreTransportDTO) obj;
		if (codeArticle == null) {
			if (other.codeArticle != null)
				return false;
		} else if (!codeArticle.equals(other.codeArticle))
			return false;
		if (codeTitreTransport == null) {
			if (other.codeTitreTransport != null)
				return false;
		} else if (!codeTitreTransport.equals(other.codeTitreTransport))
			return false;
		if (codeUnite == null) {
			if (other.codeUnite != null)
				return false;
		} else if (!codeUnite.equals(other.codeUnite))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (qteTitreTransport == null) {
			if (other.qteTitreTransport != null)
				return false;
		} else if (!qteTitreTransport.equals(other.qteTitreTransport))
			return false;
		if (versionObj == null) {
			if (other.versionObj != null)
				return false;
		} else if (!versionObj.equals(other.versionObj))
			return false;
		return true;
	}


	
}
