package fr.legrain.article.dto;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import fr.legrain.article.model.TaTFabrication;
import fr.legrain.bdg.model.ModelObject;
import fr.legrain.validator.LgrHibernateValidated;

// Generated Mar 1, 2007 11:26:10 AM by Hibernate Tools 3.2.0.b9

/**
 * SWTTFabrication generated by hbm2java
 */
public class TaTFabricationDTO extends ModelObject implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6872976469850948430L;
	private Integer id;
	private String codeTFabrication;
	private String liblTFabrication;
	private Integer versionObj;

	public TaTFabricationDTO() {
	}
	
	public TaTFabricationDTO(Integer id,String codeTFabrication,String liblTFabrication) {
		this.id = id;
		this.codeTFabrication = codeTFabrication;
		this.liblTFabrication = liblTFabrication;
	}

	public void setTaTFabricationDTO(TaTFabricationDTO taTFabricationDTO) {
		this.id = taTFabricationDTO.id;
		this.codeTFabrication = taTFabricationDTO.codeTFabrication;
		this.liblTFabrication = taTFabricationDTO.liblTFabrication;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		firePropertyChange("id", this.id, this.id = id);
	}

	@NotNull
	@Size(min=1, max=20)
	@LgrHibernateValidated(champBd = "code_t_fabrication",table = "ta_t_fabrication", champEntite="codeTFabrication", clazz = TaTFabricationDTO.class)
	public String getCodeTFabrication() {
		return this.codeTFabrication;
	}

	public void setCodeTFabrication(String codeTFabrication) {
		firePropertyChange("codeTFabrication", this.codeTFabrication, this.codeTFabrication = codeTFabrication);
	}

	@LgrHibernateValidated(champBd = "libl_t_fabrication",table = "ta_t_fabrication", champEntite="liblTFabrication", clazz = TaTFabricationDTO.class)
	public String getLiblTFabrication() {
		return this.liblTFabrication;
	}

	public void setLiblTFabrication(String liblTFabrication) {
		firePropertyChange("liblTFabrication", this.liblTFabrication, this.liblTFabrication = liblTFabrication);
	}
	
	public Integer getVersionObj() {
		return this.versionObj;
	}

	public void setVersionObj(Integer versionObj) {
		this.versionObj = versionObj;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TaTFabricationDTO))
			return false;
		TaTFabricationDTO castOther = (TaTFabricationDTO) other;

		return ((this.getId() == castOther.getId()) || (this
				.getId() != null
				&& castOther.getId() != null && this.getId()
				.equals(castOther.getId())))
				&& ((this.getCodeTFabrication() == castOther.getCodeTFabrication()) || (this
						.getCodeTFabrication() != null
						&& castOther.getCodeTFabrication() != null && this
						.getCodeTFabrication().equals(castOther.getCodeTFabrication())))
				&& ((this.getLiblTFabrication() == castOther.getLiblTFabrication()) || (this
						.getLiblTFabrication() != null
						&& castOther.getLiblTFabrication() != null && this
						.getLiblTFabrication().equals(castOther.getLiblTFabrication())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getId() == null ? 0 : this.getId().hashCode());
		result = 37
				* result
				+ (getCodeTFabrication() == null ? 0 : this.getCodeTFabrication()
						.hashCode());
		result = 37
				* result
				+ (getLiblTFabrication() == null ? 0 : this.getLiblTFabrication()
						.hashCode());
		return result;
	}

	
	public static TaTFabricationDTO copy(TaTFabricationDTO taTFabricationDTO){
		TaTFabricationDTO taTFabricationDTOLoc = new TaTFabricationDTO();
		taTFabricationDTOLoc.setId(taTFabricationDTO.getId());                //1
		taTFabricationDTOLoc.setCodeTFabrication(taTFabricationDTO.getCodeTFabrication());        //2
		taTFabricationDTOLoc.setLiblTFabrication(taTFabricationDTO.getLiblTFabrication());            //3
		return taTFabricationDTOLoc;
	}
}
