package fr.legrain.article.dto;

// Generated Mar 1, 2007 11:26:10 AM by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import fr.legrain.article.model.TaTva;
import fr.legrain.bdg.model.ModelObject;
import fr.legrain.validator.LgrHibernateValidated;


/**
 * SWTTva generated by hbm2java
 */
public class TaTvaDTO extends ModelObject implements java.io.Serializable {

	private static final long serialVersionUID = -185018220795513601L;
	
	private Integer id;
	private String codeTva;
	private String libelleTva;
	private BigDecimal tauxTva;
	private String numcptTva;
	
	private Integer versionObj;
	               
	public Integer getVersionObj() {
		return versionObj;
	}

	public void setVersionObj(Integer versionObj) {
		this.versionObj = versionObj;
	}

	public TaTvaDTO() {
	}

	public TaTvaDTO(Integer ID_TVA, String CODE_TVA, String LIBELLE_TVA,
			BigDecimal TAUX_TVA, String NUMCPT_TVA) {
		this.id = ID_TVA;
		this.codeTva = CODE_TVA;
		this.libelleTva = LIBELLE_TVA;
		this.tauxTva = TAUX_TVA;
		this.numcptTva = NUMCPT_TVA;
	}
	
	public void setSWTTva(TaTvaDTO swtTva) {
		this.id = swtTva.id;
		this.codeTva = swtTva.codeTva;
		this.libelleTva = swtTva.libelleTva;
		this.tauxTva = swtTva.tauxTva;
		this.numcptTva = swtTva.numcptTva;
	}
	
	public static TaTvaDTO copy(TaTvaDTO swtTva){
		TaTvaDTO swtTvaLoc = new TaTvaDTO();
		swtTvaLoc.setId(swtTva.id);
		swtTvaLoc.setCodeTva(swtTva.codeTva);
		swtTvaLoc.setLibelleTva(swtTva.libelleTva);
		swtTvaLoc.setTauxTva(swtTva.tauxTva);
		swtTvaLoc.setNumcptTva(swtTva.numcptTva);
		return swtTvaLoc;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer ID_TVA) {
		firePropertyChange("id", this.id, this.id = ID_TVA);
	}

	@NotNull
	@Size(min=1, max=20)
	@LgrHibernateValidated(champBd = "code_tva",table = "ta_tva", champEntite="codeTva", clazz = TaTvaDTO.class)
	public String getCodeTva() {
		return this.codeTva;
	}

	public void setCodeTva(String CODE_TVA) {
		firePropertyChange("codeTva", this.codeTva, this.codeTva = CODE_TVA);
	}

	@LgrHibernateValidated(champBd = "libelle_tva",table = "ta_tva", champEntite="libelleTva", clazz = TaTvaDTO.class)
	public String getLibelleTva() {
		return this.libelleTva;
	}

	public void setLibelleTva(String LIBELLE_TVA) {
		firePropertyChange("libelleTva", this.libelleTva, this.libelleTva = LIBELLE_TVA);
	}

	@LgrHibernateValidated(champBd = "taux_tva",table = "ta_tva", champEntite="tauxTva", clazz = TaTvaDTO.class)
	public BigDecimal getTauxTva() {
		return this.tauxTva;
	}

	public void setTauxTva(BigDecimal TAUX_TVA) {
		firePropertyChange("tauxTva", this.tauxTva, this.tauxTva = TAUX_TVA);
	}

	@Size(min=0, max=8)
	@LgrHibernateValidated(champBd = "numcpt_tva",table = "ta_tva", champEntite="numcptTva", clazz = TaTvaDTO.class)
	public String getNumcptTva() {
		return this.numcptTva;
	}

	public void setNumcptTva(String NUMCPT_TVA) {
		firePropertyChange("numcptTva", this.numcptTva, this.numcptTva = NUMCPT_TVA);
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TaTvaDTO))
			return false;
		TaTvaDTO castOther = (TaTvaDTO) other;

		return ((this.getId() == castOther.getId()) || (this
				.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getCodeTva() == castOther.getCodeTva()) || (this
						.getCodeTva() != null
						&& castOther.getCodeTva() != null && this
						.getCodeTva().equals(castOther.getCodeTva())))
				&& ((this.getLibelleTva() == castOther.getLibelleTva()) || (this
						.getLibelleTva() != null
						&& castOther.getLibelleTva() != null && this
						.getLibelleTva().equals(castOther.getLibelleTva())))
				&& ((this.getTauxTva() == castOther.getTauxTva()) || (this
						.getTauxTva() != null
						&& castOther.getTauxTva() != null && this
						.getTauxTva().equals(castOther.getTauxTva())))
				&& ((this.getNumcptTva() == castOther.getNumcptTva()) || (this
						.getNumcptTva() != null
						&& castOther.getNumcptTva() != null && this
						.getNumcptTva().equals(castOther.getNumcptTva())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getCodeTva() == null ? 0 : this.getCodeTva().hashCode());
		result = 37
				* result
				+ (getLibelleTva() == null ? 0 : this.getLibelleTva()
						.hashCode());
		result = 37 * result
				+ (getTauxTva() == null ? 0 : this.getTauxTva().hashCode());
		result = 37
				* result
				+ (getNumcptTva() == null ? 0 : this.getNumcptTva()
						.hashCode());
		return result;
	}

}
