package fr.legrain.tiers.model;

// Generated Mar 25, 2009 10:06:49 AM by Hibernate Tools 3.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.Version;

import org.apache.log4j.Logger;

import fr.legrain.general.model.TaObjetLgr;
import fr.legrain.validator.LgrHibernateValidated;

/**
 * TaCompl generated by hbm2java
 */
@Entity
//@Cache(usage=CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "ta_compl")
//@SequenceGenerator(name = "gen_compl", sequenceName = "num_id_compl", allocationSize = 1)
public class TaCompl extends TaObjetLgr   implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8154816637024392434L;
	@Transient
	static Logger logger = Logger.getLogger(TaCompl.class.getName());
	
	private int idCompl;
//	private String version;
	private String tvaIComCompl;
	private String siretCompl;
	private String accise;
	private String numAgrementSanitaire;
	private String ics;
//	private String quiCree;
//	private Date quandCree;
//	private String quiModif;
//	private Date quandModif;
//	private String ipAcces;
	private Integer versionObj;
//	private Set<TaTiers> taTierses = new HashSet<TaTiers>(0);

	public TaCompl() {
	}

	public TaCompl(int idCompl) {
		this.idCompl = idCompl;
	}

	public TaCompl(int idCompl, String tvaIComCompl, String siretCompl,String accise, String ics,
			String quiCreeCompl, Date quandCreeCompl, String quiModifCompl,
			Date quandModifCompl, String ipAcces, Integer versionObj,
			Set<TaTiers> taTierses) {
		this.idCompl = idCompl;
		this.tvaIComCompl = tvaIComCompl;
		this.siretCompl = siretCompl;
		this.accise = accise;
		this.ics = ics;
		this.quiCree = quiCreeCompl;
		this.quandCree = quandCreeCompl;
		this.quiModif = quiModifCompl;
		this.quandModif = quandModifCompl;
		this.ipAcces = ipAcces;
		this.versionObj = versionObj;
//		this.taTierses = taTierses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id_compl", unique = true, nullable = false)
	@LgrHibernateValidated(champBd = "id_compl",table = "ta_compl",champEntite="idCompl", clazz = TaCompl.class)
	public int getIdCompl() {
		return this.idCompl;
	}

	public void setIdCompl(int idCompl) {
		this.idCompl = idCompl;
	}

	
//	@Column(name = "version", length = 20)
//	public String getVersion() {
//		return this.version;
//	}
//
//	public void setVersion(String version) {
//		this.version = version;
//	}

	@Column(name = "tva_i_com_compl", length = 50)
	@LgrHibernateValidated(champBd = "tva_i_com_compl",table = "ta_compl",champEntite="tvaIComCompl", clazz = TaCompl.class)
	public String getTvaIComCompl() {
		return this.tvaIComCompl;
	}

	public void setTvaIComCompl(String tvaIComCompl) {
		this.tvaIComCompl = tvaIComCompl;
	}

	@Column(name = "siret_compl", length = 50)
	@LgrHibernateValidated(champBd = "siret_compl",table = "ta_compl",champEntite="siretCompl", clazz = TaCompl.class)
	public String getSiretCompl() {
		return this.siretCompl;
	}

	public void setSiretCompl(String siretCompl) {
		this.siretCompl = siretCompl;
	}

	@Column(name = "accise", length = 13)
	@LgrHibernateValidated(champBd = "accise",table = "ta_compl",champEntite="accise", clazz = TaCompl.class)
	public String getAccise() {
		return this.accise;
	}

	public void setAccise(String accise) {
		this.accise = accise;
	}
	
//	@Column(name = "qui_cree", length = 50)
//	public String getQuiCree() {
//		return this.quiCree;
//	}
//
//	public void setQuiCree(String quiCreeCompl) {
//		this.quiCree = quiCreeCompl;
//	}
//
//	@Temporal(TemporalType.TIMESTAMP)
//	@Column(name = "quand_cree", length = 19)
//	public Date getQuandCree() {
//		return this.quandCree;
//	}
//
//	public void setQuandCree(Date quandCreeCompl) {
//		this.quandCree = quandCreeCompl;
//	}
//
//	@Column(name = "qui_modif", length = 50)
//	public String getQuiModif() {
//		return this.quiModif;
//	}
//
//	public void setQuiModif(String quiModifCompl) {
//		this.quiModif = quiModifCompl;
//	}
//
//	@Temporal(TemporalType.TIMESTAMP)
//	@Column(name = "quand_modif", length = 19)
//	public Date getQuandModif() {
//		return this.quandModif;
//	}
//
//	public void setQuandModif(Date quandModifCompl) {
//		this.quandModif = quandModifCompl;
//	}
//
//	@Column(name = "ip_acces", length = 50)
//	public String getIpAcces() {
//		return this.ipAcces;
//	}
//
//	public void setIpAcces(String ipAcces) {
//		this.ipAcces = ipAcces;
//	}

	@Version
	@Column(name = "version_obj")
	public Integer getVersionObj() {
		return this.versionObj;
	}

	public void setVersionObj(Integer versionObj) {
		this.versionObj = versionObj;
	}

//	@OneToMany(cascade = {CascadeType.PERSIST, CascadeType.MERGE}, fetch = FetchType.LAZY, mappedBy = "taCompl")
//	public Set<TaTiers> getTaTierses() {
//		return this.taTierses;
//	}
//
//	public void setTaTierses(Set<TaTiers> taTierses) {
//		this.taTierses = taTierses;
//	}

	@Column(name = "ics", length = 50)
	@LgrHibernateValidated(champBd = "ics",table = "ta_compl",champEntite="ics", clazz = TaCompl.class)
	public String getIcs() {
		return ics;
	}

	public void setIcs(String ics) {
		this.ics = ics;
	}

	@Column(name = "num_agrement_sanitaire")
	public String getNumAgrementSanitaire() {
		return numAgrementSanitaire;
	}

	public void setNumAgrementSanitaire(String numAgrementSanitaire) {
		this.numAgrementSanitaire = numAgrementSanitaire;
	}

	@Override
	public Object clone() throws CloneNotSupportedException {
		TaCompl objet = new TaCompl();
		try {
			objet.setAccise(accise);
			objet.setIcs(ics);
			objet.setNumAgrementSanitaire(numAgrementSanitaire);
			objet.setSiretCompl(siretCompl);
			objet.setTvaIComCompl(tvaIComCompl);
		} catch (Exception e) {
			logger.error("", e);
		}
		// on renvoie le clone
		return objet;
	}
	
	
	
}
