package fr.legrain.tiers.model;

// Generated Mar 24, 2009 4:44:04 PM by Hibernate Tools 3.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import fr.legrain.general.model.TaObjetLgr;
import fr.legrain.validator.LgrHibernateValidated;

/**
 * TaTEmail generated by hbm2java
 */
@Entity
//@Cache(usage=CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "ta_t_email")
//@SequenceGenerator(name = "gen_t_email", sequenceName = "num_id_t_email", allocationSize = 1)
public class TaTEmail extends TaObjetLgr   implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2943628540588168602L;
	private int idTEmail;
//	private String version;
	private String codeTEmail;
	private String liblTEmail;
//	private String quiCree;
//	private Date quandCree;
//	private String quiModif;
//	private Date quandModif;
//	private String ipAcces;
	private Integer versionObj;
//	private Set<TaEmail> taEmails = new HashSet<TaEmail>(0);

	public TaTEmail() {
	}

	public TaTEmail(int idTEmail) {
		this.idTEmail = idTEmail;
	}

	public TaTEmail(int idTEmail, String codeTEmail, String liblTEmail,
			String quiCreeTEmail, Date quandCreeTEmail, String quiModifTEmail,
			Date quandModifTEmail, String ipAcces, Integer versionObj/*,
			Set<TaEmail> taEmails*/) {
		this.idTEmail = idTEmail;
		this.codeTEmail = codeTEmail;
		this.liblTEmail = liblTEmail;
		this.quiCree = quiCreeTEmail;
		this.quandCree = quandCreeTEmail;
		this.quiModif = quiModifTEmail;
		this.quandModif = quandModifTEmail;
		this.ipAcces = ipAcces;
		this.versionObj = versionObj;
//		this.taEmails = taEmails;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id_t_email", unique = true, nullable = false)
	@LgrHibernateValidated(champBd = "id_t_email",table = "ta_t_email",champEntite="idTEmail", clazz = TaTEmail.class)
	public int getIdTEmail() {
		return this.idTEmail;
	}

	public void setIdTEmail(int idTEmail) {
		this.idTEmail = idTEmail;
	}

	
//	@Column(name = "version", length = 20)
//	public String getVersion() {
//		return this.version;
//	}
//
//	public void setVersion(String version) {
//		this.version = version;
//	}

	@Column(name = "code_t_email", length = 20)
	@LgrHibernateValidated(champBd = "code_t_email",table = "ta_t_email",champEntite="codeTEmail",clazz = TaTEmail.class)
	public String getCodeTEmail() {
		return this.codeTEmail;
	}

	public void setCodeTEmail(String codeTEmail) {
		this.codeTEmail = codeTEmail;
	}

	@Column(name = "libl_t_email", length = 100)
	@LgrHibernateValidated(champBd = "libl_t_email",table = "ta_t_email",champEntite="liblTEmail",clazz = TaTEmail.class)
	public String getLiblTEmail() {
		return this.liblTEmail;
	}

	public void setLiblTEmail(String liblTEmail) {
		this.liblTEmail = liblTEmail;
	}

//	@Column(name = "qui_cree", length = 50)
//	public String getQuiCree() {
//		return this.quiCree;
//	}
//
//	public void setQuiCree(String quiCreeTEmail) {
//		this.quiCree = quiCreeTEmail;
//	}
//
//	@Temporal(TemporalType.TIMESTAMP)
//	@Column(name = "quand_cree", length = 19)
//	public Date getQuandCree() {
//		return this.quandCree;
//	}
//
//	public void setQuandCree(Date quandCreeTEmail) {
//		this.quandCree = quandCreeTEmail;
//	}
//
//	@Column(name = "qui_modif", length = 50)
//	public String getQuiModif() {
//		return this.quiModif;
//	}
//
//	public void setQuiModif(String quiModifTEmail) {
//		this.quiModif = quiModifTEmail;
//	}
//
//	@Temporal(TemporalType.TIMESTAMP)
//	@Column(name = "quand_modif", length = 19)
//	public Date getQuandModif() {
//		return this.quandModif;
//	}
//
//	public void setQuandModif(Date quandModifTEmail) {
//		this.quandModif = quandModifTEmail;
//	}
//
//	@Column(name = "ip_acces", length = 50)
//	public String getIpAcces() {
//		return this.ipAcces;
//	}
//
//	public void setIpAcces(String ipAcces) {
//		this.ipAcces = ipAcces;
//	}

	@Version
	@Column(name = "version_obj")
	public Integer getVersionObj() {
		return this.versionObj;
	}

	public void setVersionObj(Integer versionObj) {
		this.versionObj = versionObj;
	}

//	@OneToMany(cascade = {CascadeType.PERSIST, CascadeType.MERGE}, fetch = FetchType.LAZY, mappedBy = "taTEmail")
//	public Set<TaEmail> getTaEmails() {
//		return this.taEmails;
//	}
//
//	public void setTaEmails(Set<TaEmail> taEmails) {
//		this.taEmails = taEmails;
//	}


//	@PrePersist
//	@PreUpdate
	public void beforePost ()throws Exception{
		this.setCodeTEmail(codeTEmail.toUpperCase());
	}
}
