package fr.legrain.tiers.model;


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import fr.legrain.general.model.TaObjetLgr;

//import org.hibernate.annotations.Cache;
//import org.hibernate.annotations.CacheConcurrencyStrategy;

import fr.legrain.validator.LgrHibernateValidated;

/**
 * TaTTiers generated by hbm2java
 */
@Entity
//@Cache(usage=CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "ta_t_tiers")
//@SequenceGenerator(name = "gen_t_tiers", sequenceName = "num_id_t_tiers", allocationSize = 1)
public class TaTTiers extends TaObjetLgr   implements java.io.Serializable {
	
	public static final String CLIENT = "C";
	public static final String VISITEUR_BOUTIQUE = "VISIT";
	

	private static final long serialVersionUID = 809845643793842501L;
	
	private int idTTiers;
//	private String version;
	private String codeTTiers;
	private String libelleTTiers;
	private String compteTTiers;
//	private String quiCree;
//	private Date quandCree;
//	private String quiModif;
//	private Date quandModif;
//	private String ipAcces;
	private Integer versionObj;
//	private Set<TaTiers> taTierses = new HashSet<TaTiers>(0);

	public TaTTiers() {
	}

	public TaTTiers(int idTTiers) {
		this.idTTiers = idTTiers;
	}

	public TaTTiers(int idTTiers, String codeTTiers, String libelleTTiers,
			String compteTTiers, String quiCreeTTiers, Date quandCreeTTiers,
			String quiModifTTiers, Date quandModifTTiers, String ipAcces,
			Integer versionObj/*, Set<TaTiers> taTierses*/) {
		this.idTTiers = idTTiers;
		this.codeTTiers = codeTTiers;
		this.libelleTTiers = libelleTTiers;
		this.compteTTiers = compteTTiers;
		this.quiCree = quiCreeTTiers;
		this.quandCree = quandCreeTTiers;
		this.quiModif = quiModifTTiers;
		this.quandModif = quandModifTTiers;
		this.ipAcces = ipAcces;
		this.versionObj = versionObj;
//		this.taTierses = taTierses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id_t_tiers", unique = true, nullable = false)
	@LgrHibernateValidated(champBd = "id_t_tiers",table = "ta_t_tiers",champEntite="idTTiers", clazz = TaTTiers.class)
	public int getIdTTiers() {
		return this.idTTiers;
	}

	public void setIdTTiers(int idTTiers) {
		this.idTTiers = idTTiers;
	}

//	@Column(name = "version", length = 20)
//	public String getVersion() {
//		return this.version;
//	}
//
//	public void setVersion(String version) {
//		this.version = version;
//	}

	@Column(name = "code_t_tiers", length = 20)
	@LgrHibernateValidated(champBd = "code_t_tiers",table = "ta_t_tiers",champEntite="codeTTiers",clazz = TaTTiers.class)
	public String getCodeTTiers() {
		return this.codeTTiers;
	}

	public void setCodeTTiers(String codeTTiers) {
		this.codeTTiers = codeTTiers;
	}

	@Column(name = "libelle_t_tiers", length = 100)
	@LgrHibernateValidated(champBd = "libelle_t_tiers",table = "ta_t_tiers",champEntite="libelleTTiers",clazz = TaTTiers.class)
	public String getLibelleTTiers() {
		return this.libelleTTiers;
	}

	public void setLibelleTTiers(String libelleTTiers) {
		this.libelleTTiers = libelleTTiers;
	}

	@Column(name = "compte_t_tiers", length = 8)
	@LgrHibernateValidated(champBd = "compte_t_tiers",table = "ta_t_tiers",champEntite="compteTTiers",clazz = TaTTiers.class)
	public String getCompteTTiers() {
		return this.compteTTiers;
	}

	public void setCompteTTiers(String compteTTiers) {
		this.compteTTiers = compteTTiers;
	}

//	@Column(name = "qui_cree", length = 50)
//	public String getQuiCree() {
//		return this.quiCree;
//	}
//
//	public void setQuiCree(String quiCreeTTiers) {
//		this.quiCree = quiCreeTTiers;
//	}
//
//	@Temporal(TemporalType.TIMESTAMP)
//	@Column(name = "quand_cree", length = 19)
//	public Date getQuandCree() {
//		return this.quandCree;
//	}
//
//	public void setQuandCree(Date quandCreeTTiers) {
//		this.quandCree = quandCreeTTiers;
//	}
//
//	@Column(name = "qui_modif", length = 50)
//	public String getQuiModif() {
//		return this.quiModif;
//	}
//
//	public void setQuiModif(String quiModifTTiers) {
//		this.quiModif = quiModifTTiers;
//	}
//
//	@Temporal(TemporalType.TIMESTAMP)
//	@Column(name = "quand_modif", length = 19)
//	public Date getQuandModif() {
//		return this.quandModif;
//	}
//
//	public void setQuandModif(Date quandModifTTiers) {
//		this.quandModif = quandModifTTiers;
//	}
//
//	@Column(name = "ip_acces", length = 50)
//	public String getIpAcces() {
//		return this.ipAcces;
//	}
//
//	public void setIpAcces(String ipAcces) {
//		this.ipAcces = ipAcces;
//	}

	@Version
	@Column(name = "version_obj")
	public Integer getVersionObj() {
		return this.versionObj;
	}

	public void setVersionObj(Integer versionObj) {
		this.versionObj = versionObj;
	}

//	@OneToMany(cascade = {CascadeType.PERSIST, CascadeType.MERGE}, fetch = FetchType.LAZY, mappedBy = "taTTiers")
//	public Set<TaTiers> getTaTierses() {
//		return this.taTierses;
//	}
//
//	public void setTaTierses(Set<TaTiers> taTierses) {
//		this.taTierses = taTierses;
//	}

	

//	@PrePersist
//	@PreUpdate
	public void beforePost ()throws Exception{
		this.setCodeTTiers(codeTTiers.toUpperCase());
	}
}
