package fr.legrain.tiers.model;

// Generated Mar 24, 2009 4:44:04 PM by Hibernate Tools 3.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import fr.legrain.general.model.TaObjetLgr;
import fr.legrain.validator.LgrHibernateValidated;

/**
 * TaTTiers generated by hbm2java
 */
@Entity
//@Cache(usage=CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "ta_t_tva_doc")
//@SequenceGenerator(name = "gen_t_tva_doc", sequenceName = "num_id_t_tva_doc", allocationSize = 1)
public class TaTTvaDoc extends TaObjetLgr   implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3002679836761424739L;
	private int idTTvaDoc;
//	private String version;
	private String codeTTvaDoc;
	private String libelleTTvaDoc;
	private String journalTTvaDoc;
	private String libelleEdition;
//	private String quiCree;
//	private Date quandCree;
//	private String quiModif;
//	private Date quandModif;
//	private String ipAcces;
	private Integer versionObj;
//	private Set<TaTiers> taTierses = new HashSet<TaTiers>(0);

	public TaTTvaDoc() {
	}

	public TaTTvaDoc(int idTTvaDoc) {
		this.idTTvaDoc = idTTvaDoc;
	}

	public TaTTvaDoc(int idTTvaDoc, String codeTTvaDoc, String libelleTTvaDoc,
			String compteTTvaDoc, String quiCreeTTvaDoc, Date quandCreeTTvaDoc,
			String quiModifTTvaDoc, Date quandModifTTvaDoc, String ipAcces,
			Integer versionObj, Set<TaTiers> taTierses,String libelleEdition) {
		this.idTTvaDoc = idTTvaDoc;
		this.codeTTvaDoc = codeTTvaDoc;
		this.libelleTTvaDoc = libelleTTvaDoc;
		this.journalTTvaDoc = compteTTvaDoc;
		this.libelleEdition = libelleEdition;
		this.quiCree = quiCreeTTvaDoc;
		this.quandCree = quandCreeTTvaDoc;
		this.quiModif = quiModifTTvaDoc;
		this.quandModif = quandModifTTvaDoc;
		this.ipAcces = ipAcces;
		this.versionObj = versionObj;
//		this.taTierses = taTierses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id_t_tva_doc", unique = true, nullable = false)
	@LgrHibernateValidated(champBd = "id_t_tva_doc",table = "ta_t_tva_doc",champEntite="idTTvaDoc", clazz = TaTTvaDoc.class)
	public int getIdTTvaDoc() {
		return this.idTTvaDoc;
	}

	public void setIdTTvaDoc(int idTTvaDoc) {
		this.idTTvaDoc = idTTvaDoc;
	}

//	@Column(name = "version", length = 20)
//	public String getVersion() {
//		return this.version;
//	}
//
//	public void setVersion(String version) {
//		this.version = version;
//	}

	@Column(name = "code_t_tva_doc", length = 20)
	@LgrHibernateValidated(champBd = "code_t_tva_doc",table = "ta_t_tva_doc",champEntite="codeTTvaDoc",clazz = TaTTvaDoc.class)
	public String getCodeTTvaDoc() {
		return this.codeTTvaDoc;
	}

	public void setCodeTTvaDoc(String codeTTvaDoc) {
		this.codeTTvaDoc = codeTTvaDoc;
	}

	@Column(name = "libelle_t_tva_doc", length = 100)
	@LgrHibernateValidated(champBd = "libelle_t_tva_doc",table = "ta_t_tva_doc",champEntite="libelleTTvaDoc",clazz = TaTTvaDoc.class)
	public String getLibelleTTvaDoc() {
		return this.libelleTTvaDoc;
	}

	public void setLibelleTTvaDoc(String libelleTTvaDoc) {
		this.libelleTTvaDoc = libelleTTvaDoc;
	}

	@Column(name = "journal_t_tva_doc", length = 8)
	@LgrHibernateValidated(champBd = "journal_t_tva_doc",table = "ta_t_tva_doc",champEntite="journalTTvaDoc",clazz = TaTTvaDoc.class)
	public String getJournalTTvaDoc() {
		return this.journalTTvaDoc;
	}

	public void setJournalTTvaDoc(String compteTTvaDoc) {
		this.journalTTvaDoc = compteTTvaDoc;
	}


	@Column(name = "libelle_edition", length = 255)
	@LgrHibernateValidated(champBd = "libelle_edition",table = "ta_t_tva_doc",champEntite="libelleEdition",clazz = TaTTvaDoc.class)
	public String getLibelleEdition() {
		return libelleEdition;
	}

	public void setLibelleEdition(String libelleEdition) {
		this.libelleEdition = libelleEdition;
	}
	
//	@Column(name = "qui_cree", length = 50)
//	public String getQuiCree() {
//		return this.quiCree;
//	}
//
//	public void setQuiCree(String quiCreeTTvaDoc) {
//		this.quiCree = quiCreeTTvaDoc;
//	}
//
//	@Temporal(TemporalType.TIMESTAMP)
//	@Column(name = "quand_cree", length = 19)
//	public Date getQuandCree() {
//		return this.quandCree;
//	}
//
//	public void setQuandCree(Date quandCreeTTvaDoc) {
//		this.quandCree = quandCreeTTvaDoc;
//	}
//
//	@Column(name = "qui_modif", length = 50)
//	public String getQuiModif() {
//		return this.quiModif;
//	}
//
//	public void setQuiModif(String quiModifTTvaDoc) {
//		this.quiModif = quiModifTTvaDoc;
//	}
//
//	@Temporal(TemporalType.TIMESTAMP)
//	@Column(name = "quand_modif", length = 19)
//	public Date getQuandModif() {
//		return this.quandModif;
//	}
//
//	public void setQuandModif(Date quandModifTTvaDoc) {
//		this.quandModif = quandModifTTvaDoc;
//	}
//
//	@Column(name = "ip_acces", length = 50)
//	public String getIpAcces() {
//		return this.ipAcces;
//	}
//
//	public void setIpAcces(String ipAcces) {
//		this.ipAcces = ipAcces;
//	}

	@Version
	@Column(name = "version_obj")
	public Integer getVersionObj() {
		return this.versionObj;
	}

	public void setVersionObj(Integer versionObj) {
		this.versionObj = versionObj;
	}

//	@OneToMany(cascade = {CascadeType.PERSIST, CascadeType.MERGE}, fetch = FetchType.LAZY, mappedBy = "taTTiers")
//	public Set<TaTiers> getTaTierses() {
//		return this.taTierses;
//	}
//
//	public void setTaTierses(Set<TaTiers> taTierses) {
//		this.taTierses = taTierses;
//	}

	
	
//	@PrePersist
//	@PreUpdate
	public void beforePost ()throws Exception{
		this.setCodeTTvaDoc(codeTTvaDoc.toUpperCase());
	}


}
