package fr.legrain.tiers.model;

// Generated Mar 24, 2009 4:44:04 PM by Hibernate Tools 3.2.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import fr.legrain.general.model.TaObjetLgr;
import fr.legrain.validator.LgrHibernateValidated;

/**
 * TaTTel generated by hbm2java
 */
@Entity
//@Cache(usage=CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "ta_t_tel")
//@SequenceGenerator(name = "gen_t_tel", sequenceName = "num_id_t_tel", allocationSize = 1)
public class TaTTel extends TaObjetLgr   implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6834589698008225639L;
	private int idTTel;
//	private String version;
	private String codeTTel;
	private String liblTTel;
//	private String quiCree;
//	private Date quandCree;
//	private String quiModif;
//	private Date quandModif;
//	private String ipAcces;
	private Integer versionObj;
	//private Set<TaTelephone> taTelephones = new HashSet<TaTelephone>(0);

	public TaTTel() {
	}

	public TaTTel(int idTTel) {
		this.idTTel = idTTel;
	}

	public TaTTel(int idTTel, String codeTTel, String liblTTel,
			String quiCreeTTel, Date quandCreeTTel, String quiModifTTel,
			Date quandModifTTel, String ipAcces, Integer versionObj/*,
			Set<TaTelephone> taTelephones*/) {
		this.idTTel = idTTel;
		this.codeTTel = codeTTel;
		this.liblTTel = liblTTel;
		this.quiCree = quiCreeTTel;
		this.quandCree = quandCreeTTel;
		this.quiModif = quiModifTTel;
		this.quandModif = quandModifTTel;
		this.ipAcces = ipAcces;
		this.versionObj = versionObj;
		//this.taTelephones = taTelephones;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id_t_tel", unique = true, nullable = false)
	@LgrHibernateValidated(champBd = "id_t_tel",table = "ta_t_tel",champEntite="idTTel", clazz = TaTTel.class)
	public int getIdTTel() {
		return this.idTTel;
	}

	public void setIdTTel(int idTTel) {
		this.idTTel = idTTel;
	}

//	@Column(name = "version", length = 20)
//	public String getVersion() {
//		return this.version;
//	}
//
//	public void setVersion(String version) {
//		this.version = version;
//	}

	@Column(name = "code_t_tel", unique = true, length = 20)
	@LgrHibernateValidated(champBd = "code_t_tel",table = "ta_t_tel",champEntite="codeTTel",clazz = TaTTel.class)
	public String getCodeTTel() {
		return this.codeTTel;
	}

	public void setCodeTTel(String codeTTel) {
		this.codeTTel = codeTTel;
	}

	@Column(name = "libl_t_tel", length = 100)
	@LgrHibernateValidated(champBd = "libl_t_tel",table = "ta_t_tel",champEntite="liblTTel",clazz = TaTTel.class)
	public String getLiblTTel() {
		return this.liblTTel;
	}

	public void setLiblTTel(String liblTTel) {
		this.liblTTel = liblTTel;
	}

//	@Column(name = "qui_cree", length = 50)
//	public String getQuiCree() {
//		return this.quiCree;
//	}
//
//	public void setQuiCree(String quiCreeTTel) {
//		this.quiCree = quiCreeTTel;
//	}
//
//	@Temporal(TemporalType.TIMESTAMP)
//	@Column(name = "quand_cree", length = 19)
//	public Date getQuandCree() {
//		return this.quandCree;
//	}
//
//	public void setQuandCree(Date quandCreeTTel) {
//		this.quandCree = quandCreeTTel;
//	}
//
//	@Column(name = "qui_modif", length = 50)
//	public String getQuiModif() {
//		return this.quiModif;
//	}
//
//	public void setQuiModif(String quiModifTTel) {
//		this.quiModif = quiModifTTel;
//	}
//
//	@Temporal(TemporalType.TIMESTAMP)
//	@Column(name = "quand_modif", length = 19)
//	public Date getQuandModif() {
//		return this.quandModif;
//	}
//
//	public void setQuandModif(Date quandModifTTel) {
//		this.quandModif = quandModifTTel;
//	}
//
//	@Column(name = "ip_acces", length = 50)
//	public String getIpAcces() {
//		return this.ipAcces;
//	}
//
//	public void setIpAcces(String ipAcces) {
//		this.ipAcces = ipAcces;
//	}

	@Version
	@Column(name = "version_obj")
	public Integer getVersionObj() {
		return this.versionObj;
	}

	public void setVersionObj(Integer versionObj) {
		this.versionObj = versionObj;
	}

//	@OneToMany(cascade = {CascadeType.PERSIST, CascadeType.MERGE}, fetch = FetchType.LAZY, mappedBy = "taTTel")
//	public Set<TaTelephone> getTaTelephones() {
//		return this.taTelephones;
//	}
//
//	public void setTaTelephones(Set<TaTelephone> taTelephones) {
//		this.taTelephones = taTelephones;
//	}


//	@PrePersist
//	@PreUpdate
	public void beforePost ()throws Exception{
		this.setCodeTTel(codeTTel.toUpperCase());
	}
}
