package fr.legrain.tiers.model;

// Generated Mar 24, 2009 4:44:04 PM by Hibernate Tools 3.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.Version;
import javax.xml.bind.annotation.XmlElement;

import org.apache.log4j.Logger;
import org.eclipse.persistence.oxm.annotations.XmlInverseReference;

import fr.legrain.general.model.TaObjetLgr;
import fr.legrain.tiers.model.TaTWeb;
import fr.legrain.validator.LgrHibernateValidated;

/**
 * TaWeb generated by hbm2java
 */
@Entity
//@Cache(usage=CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "ta_web")
//@SequenceGenerator(name = "gen_web", sequenceName = "num_id_web", allocationSize = 1)
public class TaWeb extends TaObjetLgr   implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4580547959298491745L;
	
	@Transient
	static Logger logger = Logger.getLogger(TaWeb.class.getName());
	
	private int idWeb;
//	private String version;
	private TaTWeb taTWeb;
	private TaTiers taTiers;
	private String adresseWeb;
//	private String quiCree;
//	private Date quandCree;
//	private String quiModif;
//	private Date quandModif;
//	private String ipAcces;
	private Integer versionObj;
//	private Set<TaTiers> taTierses = new HashSet<TaTiers>(0);

	public TaWeb() {
	}

	public TaWeb(int idWeb) {
		this.idWeb = idWeb;
	}

	public TaWeb(int idWeb, TaTWeb taTWeb, TaTiers taTiers, String adresseWeb,
			String quiCreeWeb, Date quandCreeWeb, String quiModifWeb,
			Date quandModifWeb, String ipAcces, Integer versionObj,
			Set<TaTiers> taTierses) {
		this.idWeb = idWeb;
		this.taTWeb = taTWeb;
		this.taTiers = taTiers;
		this.adresseWeb = adresseWeb;
		this.quiCree = quiCreeWeb;
		this.quandCree = quandCreeWeb;
		this.quiModif = quiModifWeb;
		this.quandModif = quandModifWeb;
		this.ipAcces = ipAcces;
		this.versionObj = versionObj;
//		this.taTierses = taTierses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id_web", unique = true, nullable = false)
	@LgrHibernateValidated(champBd = "id_web",table = "ta_web",champEntite="idWeb", clazz = TaWeb.class)
	public int getIdWeb() {
		return this.idWeb;
	}

	public void setIdWeb(int idWeb) {
		this.idWeb = idWeb;
	}

//	@Column(name = "version", length = 20)
//	public String getVersion() {
//		return this.version;
//	}
//
//	public void setVersion(String version) {
//		this.version = version;
//	}

	@ManyToOne(fetch = FetchType.EAGER, cascade = {CascadeType.PERSIST, CascadeType.MERGE, CascadeType.REFRESH})
	@JoinColumn(name = "id_t_web")
	@LgrHibernateValidated(champBd = "id_t_web",table = "ta_t_web",champEntite="idTWeb",clazz = TaTWeb.class)
	public TaTWeb getTaTWeb() {
		return this.taTWeb;
	}

	public void setTaTWeb(TaTWeb taTWeb) {
		this.taTWeb = taTWeb;
	}

	@ManyToOne(fetch = FetchType.EAGER, cascade = {CascadeType.PERSIST, CascadeType.MERGE})
	@JoinColumn(name = "id_tiers")
	@LgrHibernateValidated(champBd = "id_tiers",table = "ta_tiers",champEntite="idTiers",clazz = TaTiers.class)
	@XmlElement
	@XmlInverseReference(mappedBy="taWebs")
	public TaTiers getTaTiers() {
		return this.taTiers;
	}

	public void setTaTiers(TaTiers taTiers) {
		this.taTiers = taTiers;
	}

	@Column(name = "adresse_web")
	@LgrHibernateValidated(champBd = "adresse_web",table = "ta_web",champEntite="adresseWeb",clazz = TaWeb.class)
	public String getAdresseWeb() {
		return this.adresseWeb;
	}

	public void setAdresseWeb(String adresseWeb) {
		this.adresseWeb = adresseWeb;
	}

//	@Column(name = "qui_cree", length = 50)
//	public String getQuiCree() {
//		return this.quiCree;
//	}
//
//	public void setQuiCree(String quiCreeWeb) {
//		this.quiCree = quiCreeWeb;
//	}
//
//	@Temporal(TemporalType.TIMESTAMP)
//	@Column(name = "quand_cree", length = 19)
//	public Date getQuandCree() {
//		return this.quandCree;
//	}
//
//	public void setQuandCree(Date quandCreeWeb) {
//		this.quandCree = quandCreeWeb;
//	}
//
//	@Column(name = "qui_modif", length = 50)
//	public String getQuiModif() {
//		return this.quiModif;
//	}
//
//	public void setQuiModif(String quiModifWeb) {
//		this.quiModif = quiModifWeb;
//	}
//
//	@Temporal(TemporalType.TIMESTAMP)
//	@Column(name = "quand_modif", length = 19)
//	public Date getQuandModif() {
//		return this.quandModif;
//	}
//
//	public void setQuandModif(Date quandModifWeb) {
//		this.quandModif = quandModifWeb;
//	}
//
//	@Column(name = "ip_acces", length = 50)
//	public String getIpAcces() {
//		return this.ipAcces;
//	}
//
//	public void setIpAcces(String ipAcces) {
//		this.ipAcces = ipAcces;
//	}

	@Version
	@Column(name = "version_obj")
	public Integer getVersionObj() {
		return this.versionObj;
	}

	public void setVersionObj(Integer versionObj) {
		this.versionObj = versionObj;
	}

	
	@Override
	public Object clone() throws CloneNotSupportedException {
		TaWeb objet = new TaWeb();
		try {
			objet.setAdresseWeb(adresseWeb);
			objet.setTaTWeb(taTWeb);
		} catch (Exception e) {
			logger.error("", e);
		}
		// on renvoie le clone
		return objet;
	}
//	@OneToMany(cascade = {CascadeType.PERSIST, CascadeType.MERGE}, fetch = FetchType.LAZY, mappedBy = "taWeb")
//	public Set<TaTiers> getTaTierses() {
//		return this.taTierses;
//	}
//
//	public void setTaTierses(Set<TaTiers> taTierses) {
//		this.taTierses = taTierses;
//	}

}
