package fr.legrain.moncompte.dto;

// Generated Mar 1, 2007 11:26:10 AM by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import java.util.Date;

import fr.legrain.moncompte.commun.model.ModelObject;


/**
 * SWTInfoEntreprise generated by hbm2java
 */
public class TaSetupDTO extends ModelObject implements java.io.Serializable {


	private static final long serialVersionUID = -6758316344488284429L;
	
	private Integer id;
	private String code;
	private String libelle;
	private String description;
	private String fichierSetup;
	private Boolean actif;
	private Boolean maj;
	private String versionProduit;
	private Date dateSetup;
	private String idProduit;
	private String codeProduit;

	
	private Integer versionObj;

	public TaSetupDTO() {
	}


	public TaSetupDTO(Integer id, String code, String libelle,
			String description, String fichierSetup, Boolean actif,
			Boolean maj, String versionProduit, Date dateSetup,
			String idProduit, String codeProduit, Integer versionObj) {
		super();
		this.id = id;
		this.code = code;
		this.libelle = libelle;
		this.description = description;
		this.fichierSetup = fichierSetup;
		this.actif = actif;
		this.maj = maj;
		this.versionProduit = versionProduit;
		this.dateSetup = dateSetup;
		this.idProduit = idProduit;
		this.codeProduit = codeProduit;
		this.versionObj = versionObj;
	}


	public void setSWTInfoEntreprise(TaSetupDTO taSetupDTO) {
		this.id = taSetupDTO.id;
		this.code = taSetupDTO.code;
		this.libelle = taSetupDTO.libelle;
		this.description = taSetupDTO.description;
		this.actif = taSetupDTO.actif;
		this.codeProduit = taSetupDTO.codeProduit;
		this.versionProduit = taSetupDTO.versionProduit;
		this.dateSetup = taSetupDTO.dateSetup;
		this.fichierSetup = taSetupDTO.fichierSetup;
		this.idProduit = taSetupDTO.idProduit;
		this.maj = taSetupDTO.maj;
		this.versionObj = taSetupDTO.versionObj;
	}
	
	public static TaSetupDTO copy(TaSetupDTO taSetupDTO){
		TaSetupDTO taSetupDTOLoc = new TaSetupDTO();
		taSetupDTOLoc.setId(taSetupDTO.id);
		taSetupDTOLoc.setCode(taSetupDTO.code);
		taSetupDTOLoc.setLibelle(taSetupDTO.libelle);
		taSetupDTOLoc.setDescription(taSetupDTO.description);
		taSetupDTOLoc.setActif(taSetupDTO.actif);
		taSetupDTOLoc.setCodeProduit(taSetupDTO.codeProduit);
		taSetupDTOLoc.setVersionProduit(taSetupDTO.versionProduit);
		taSetupDTOLoc.setDateSetup(taSetupDTO.dateSetup);
		taSetupDTOLoc.setFichierSetup(taSetupDTO.fichierSetup);
		taSetupDTOLoc.setIdProduit(taSetupDTO.idProduit);
		taSetupDTOLoc.setMaj(taSetupDTO.maj);
		taSetupDTOLoc.setVersionObj(taSetupDTO.versionObj);
		return taSetupDTOLoc;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		firePropertyChange("id", this.id, this.id = id);
	}

	public String getCode() {
		return code;
	}


	public void setCode(String code) {
		firePropertyChange("code", this.code, this.code = code);
	}


	public String getLibelle() {
		return libelle;
	}


	public void setLibelle(String libelle) {
		firePropertyChange("libelle", this.libelle, this.libelle = libelle);
	}


	public String getDescription() {
		return description;
	}


	public void setDescription(String description) {
		firePropertyChange("description", this.description, this.description = description);
	}

	
	public Integer getVersionObj() {
		return this.versionObj;
	}

	public void setVersionObj(Integer versionObj) {
		this.versionObj = versionObj;
	}


	public String getFichierSetup() {
		return fichierSetup;
	}


	public void setFichierSetup(String fichierSetup) {
		this.fichierSetup = fichierSetup;
	}


	public Boolean getActif() {
		return actif;
	}


	public void setActif(Boolean actif) {
		this.actif = actif;
	}


	public Boolean getMaj() {
		return maj;
	}


	public void setMaj(Boolean maj) {
		this.maj = maj;
	}


	public String getVersionProduit() {
		return versionProduit;
	}


	public void setVersionProduit(String versionProduit) {
		this.versionProduit = versionProduit;
	}


	public Date getDateSetup() {
		return dateSetup;
	}


	public void setDateSetup(Date dateSetup) {
		this.dateSetup = dateSetup;
	}


	public String getIdProduit() {
		return idProduit;
	}


	public void setIdProduit(String idProduit) {
		this.idProduit = idProduit;
	}


	public String getCodeProduit() {
		return codeProduit;
	}


	public void setCodeProduit(String codeProduit) {
		this.codeProduit = codeProduit;
	}


	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((actif == null) ? 0 : actif.hashCode());
		result = prime * result + ((code == null) ? 0 : code.hashCode());
		result = prime * result
				+ ((codeProduit == null) ? 0 : codeProduit.hashCode());
		result = prime * result
				+ ((dateSetup == null) ? 0 : dateSetup.hashCode());
		result = prime * result
				+ ((description == null) ? 0 : description.hashCode());
		result = prime * result
				+ ((fichierSetup == null) ? 0 : fichierSetup.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result
				+ ((idProduit == null) ? 0 : idProduit.hashCode());
		result = prime * result + ((libelle == null) ? 0 : libelle.hashCode());
		result = prime * result + ((maj == null) ? 0 : maj.hashCode());
		result = prime * result
				+ ((versionObj == null) ? 0 : versionObj.hashCode());
		result = prime * result
				+ ((versionProduit == null) ? 0 : versionProduit.hashCode());
		return result;
	}


	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		TaSetupDTO other = (TaSetupDTO) obj;
		if (actif == null) {
			if (other.actif != null)
				return false;
		} else if (!actif.equals(other.actif))
			return false;
		if (code == null) {
			if (other.code != null)
				return false;
		} else if (!code.equals(other.code))
			return false;
		if (codeProduit == null) {
			if (other.codeProduit != null)
				return false;
		} else if (!codeProduit.equals(other.codeProduit))
			return false;
		if (dateSetup == null) {
			if (other.dateSetup != null)
				return false;
		} else if (!dateSetup.equals(other.dateSetup))
			return false;
		if (description == null) {
			if (other.description != null)
				return false;
		} else if (!description.equals(other.description))
			return false;
		if (fichierSetup == null) {
			if (other.fichierSetup != null)
				return false;
		} else if (!fichierSetup.equals(other.fichierSetup))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (idProduit == null) {
			if (other.idProduit != null)
				return false;
		} else if (!idProduit.equals(other.idProduit))
			return false;
		if (libelle == null) {
			if (other.libelle != null)
				return false;
		} else if (!libelle.equals(other.libelle))
			return false;
		if (maj == null) {
			if (other.maj != null)
				return false;
		} else if (!maj.equals(other.maj))
			return false;
		if (versionObj == null) {
			if (other.versionObj != null)
				return false;
		} else if (!versionObj.equals(other.versionObj))
			return false;
		if (versionProduit == null) {
			if (other.versionProduit != null)
				return false;
		} else if (!versionProduit.equals(other.versionProduit))
			return false;
		return true;
	}

	
}
