//package fr.legrain.pointLgr.dao;
//
//// Generated Mar 24, 2009 4:44:04 PM by Hibernate Tools 3.2.0.CR1
//
//import java.math.BigDecimal;
//import java.util.Date;
//
//import javax.persistence.CascadeType;
//import javax.persistence.Column;
//import javax.persistence.Entity;
//import javax.persistence.FetchType;
//import javax.persistence.GeneratedValue;
//import javax.persistence.GenerationType;
//import javax.persistence.Id;
//import javax.persistence.JoinColumn;
//import javax.persistence.ManyToOne;
//import fr.legrain.validator.LgrHibernateValidated;
//import javax.persistence.Table;
//import javax.persistence.Temporal;
//import javax.persistence.TemporalType;
//import javax.persistence.Version;
//
//import fr.legrain.tiers.dao.TaTiers;
//import fr.legrain.validator.LgrHibernateValidated;
//
//
///**
// * TaAdresse generated by hbm2java
// */
//@Entity
////@Cache(usage=CacheConcurrencyStrategy.READ_WRITE)
//@Table(name = "TA_TIERS_POINT")
//@SequenceGenerator(name = "GEN_TIERS_POINT", sequenceName = "NUM_ID_TIERS_POINT", allocationSize = 1)
//public class TaTiersPoint implements java.io.Serializable {
//
//	private int idTiersPoint;
//	private BigDecimal points;
//	private Date dateValidite;
//	private String version;
//	private TaTiers taTiers;
//	private String quiCree;
//	private Date quandCree;
//	private String quiModif;
//	private Date quandModif;
//	private String ipAcces;
//	private Integer versionObj;
//
//	public TaTiersPoint() {
//	}
//
//	public TaTiersPoint(int idTiersPoint) {
//		this.idTiersPoint = idTiersPoint;
//	}
//
//
//	@Id
//	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "GEN_TIERS_POINT")
//	@Column(name = "ID_TIERS_POINT", unique = true, nullable = false)
//	@LgrHibernateValidated(champEntite = "", champ = "ID_TIERS_POINT",table = "TA_TIERS_POINT",clazz = TaTiersPoint.class)
//	public int getIdTiersPoint() {
//		return this.idTiersPoint;
//	}
//
//	public void setIdTiersPoint(int idTiersPoint) {
//		this.idTiersPoint = idTiersPoint;
//	}
//
//	@Column(name = "VERSION", length = 20)
//	public String getVersion() {
//		return this.version;
//	}
//
//	public void setVersion(String version) {
//		this.version = version;
//	}
//
//	@ManyToOne(fetch = FetchType.LAZY, cascade = {CascadeType.PERSIST, CascadeType.MERGE})
//	@JoinColumn(name = "ID_TIERS")
//	@LgrHibernateValidated(champEntite = "", champ = "ID_TIERS",table = "TA_TIERS",clazz = TaTiers.class)
//	public TaTiers getTaTiers() {
//		return this.taTiers;
//	}
//
//	public void setTaTiers(TaTiers taTiers) {
//		this.taTiers = taTiers;
//	}
//
//
//	@Column(name = "POINTS", precision = 15)
//	@LgrHibernateValidated(champEntite = "", champ = "POINTS",table = "TA_TIERS_POINT",clazz = TaTiersPoint.class)
//	public BigDecimal getPoints() {
//		return this.points;
//	}
//
//	public void setPoints(BigDecimal points) {
//		this.points = points;
//	}
//
//	@Temporal(TemporalType.DATE)
//	@Column(name = "DATE_VALIDITE", length = 19)
//	@LgrHibernateValidated(champEntite = "", champ = "DATE_VALIDITE",table = "TA_TIERS_POINT",clazz = TaTiersPoint.class)
//	public Date getDateValidite() {
//		return this.dateValidite;
//	}
//
//	public void setDateValidite(Date dateValidite) {
//		this.dateValidite = dateValidite;
//	}
//	
//	@Column(name = "QUI_CREE", length = 50)
//	public String getQuiCree() {
//		return this.quiCree;
//	}
//
//	public void setQuiCree(String quiCree) {
//		this.quiCree = quiCree;
//	}
//
//	@Temporal(TemporalType.TIMESTAMP)
//	@Column(name = "QUAND_CREE", length = 19)
//	public Date getQuandCree() {
//		return this.quandCree;
//	}
//
//	public void setQuandCree(Date quandCree) {
//		this.quandCree = quandCree;
//	}
//
//	@Column(name = "QUI_MODIF", length = 50)
//	public String getQuiModif() {
//		return this.quiModif;
//	}
//
//	public void setQuiModif(String quiModif) {
//		this.quiModif = quiModif;
//	}
//
//	@Temporal(TemporalType.TIMESTAMP)
//	@Column(name = "QUAND_MODIF", length = 19)
//	public Date getQuandModif() {
//		return this.quandModif;
//	}
//
//	public void setQuandModif(Date quandModif) {
//		this.quandModif = quandModif;
//	}
//
//	@Column(name = "IP_ACCES", length = 50)
//	public String getIpAcces() {
//		return this.ipAcces;
//	}
//
//	public void setIpAcces(String ipAcces) {
//		this.ipAcces = ipAcces;
//	}
//
//	@Version
//	@Column(name = "VERSION_OBJ")
//	public Integer getVersionObj() {
//		return this.versionObj;
//	}
//
//	public void setVersionObj(Integer versionObj) {
//		this.versionObj = versionObj;
//	}
//
//
//
//}
