package fr.legrain.SupportAbonLegrain.dao;

// Generated 11 août 2009 15:52:23 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Version;

import fr.legrain.validator.LgrHibernateValidated;


/**
 * TaWlgr generated by hbm2java
 */
@Entity
//@Cache(usage=CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "ta_utilisateur")

public class TaUtilisateur implements java.io.Serializable {
    
	private Integer idUtilisateur;
	private String nom;
    private String prenom;
    private String tel;
    private String email;
	private Integer versionObj;
//    private Set<TaLicence> taLicences = new HashSet<TaLicence>(0);

	
	public TaUtilisateur() {
	}

	public TaUtilisateur(Integer idUtilisateur) {
		this.idUtilisateur = idUtilisateur;
	}


	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id_utilisateur", unique = true)
	public Integer getIdUtilisateur() {
		return this.idUtilisateur;
	}

	public void setIdUtilisateur(Integer idUtilisateur) {
		this.idUtilisateur = idUtilisateur;
	}

	@Column(name = "nom")
	@LgrHibernateValidated(champEntite = "", champBd = "nom",table = "ta_utilisateur",clazz = TaUtilisateur.class)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}
	@Column(name = "prenom")
	@LgrHibernateValidated(champEntite = "", champBd = "prenom",table = "ta_utilisateur",clazz = TaUtilisateur.class)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}
	
	@Column(name = "tel")
	@LgrHibernateValidated(champEntite = "", champBd = "tel",table = "ta_utilisateur",clazz = TaUtilisateur.class)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}
	
	@Column(name = "email")
	@LgrHibernateValidated(champEntite = "", champBd = "email",table = "ta_utilisateur",clazz = TaUtilisateur.class)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
	
	@Version
	@Column(name = "version_obj", precision = 15)
	public Integer getVersionObj() {
		return this.versionObj;
	}

	public void setVersionObj(Integer versionObj) {
		this.versionObj = versionObj;
	}	
}
